### ISSUE TITLE
dont hardcode URNs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#10]
URNs are hardcoded in a few spots.

Don't do that.

 _Imported from trac ticket [#10](http://trac.gpolab.bbn.com/proto-ch/ticket/10),  created by ahelsing on 04-24-2012 at 16:30, last modified: 02-04-2014 at 16:50_

**Comment by tcmitchell** [comment]
Looking for hardcoded URNs:
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
reveals occurrences in:
 * `lib/php/am_client.php`
 * `portal/gcf.d/gcf.ini`
 * `portal/www/portal/db-util.php`
 * `portal/www/portal/flack.php`
 * `sa/php/sa_db.php`


_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2012 at 08:38_

**Comment by tcmitchell** [comment]
Looking again for hardcoded URNs:
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
reveals occurrences in:
 * `lib/php/am_client.php`
 * `portal/gcf.d/gcf.ini`
 * `portal/gcf.d/omni.ini`
 * `portal/www/portal/db-util.php`
 * `portal/www/portal/flack.php`
 * `sa/php/sa_db.php`


_Trac comment by tmitchel (github user: tcmitchell) on 08-20-2012 at 17:09_

**Comment by tcmitchell** [comment]
Looking again for hardcoded URNs:
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
reveals occurrences in:
 * lib/php/am_client.php (4)
 * ~~portal/gcf.d/gcf.ini~~ (3: 2 commented out, one appropriate a reference gcf AM on localhost)
 * portal/gcf.d/omni.ini (2)
 * portal/www/portal/db-util.php (1)
 * portal/www/portal/flack.php (1)
 * ~~sa/php/sa_db.php~~ (1, commented out)


_Trac comment by tmitchel (github user: tcmitchell) on 04-04-2013 at 15:37_

**Comment by tcmitchell** [comment]
GeniUser->urn() should return the urn from the MA (which appears to be dropped on the floor) instead of inventing one.

_Trac comment by tmitchel (github user: tcmitchell) on 04-05-2013 at 16:15_

**Comment by ahelsing** [comment]
This ticket is a dependency for the migration to ch.geni.net.

_Trac comment by chaos on 05-22-2013 at 14:46_

**Comment by ahelsing** [comment]
This is not a dependency for ch.geni.net --- i misunderstood what this ticket was about.

_Trac comment by chaos on 05-22-2013 at 15:54_

**Comment by tcmitchell** [comment]
I fixed some of the hardcoded URNs. Again, using the same command to locate these:
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
I see:
 * portal/gcf.d/gcf.ini (3 occurrences)
  * 2 commented out
  * 1 appropriate (a reference gcf AM on localhost)
 * portal/gcf.d/omni.ini (2 occurrences)
  * Is this file used for anything at this point?
 * portal/www/portal/flack.php (1 occurrence)
  * A hardcoded SA URN
  * Not fixable at this time, but it is possible to improve it by deriving the SA URN from the slice URN.
  * A better fix will be available thanks to #354; we can get the SA URN out of the service registry.

_Trac comment by tmitchel (github user: tcmitchell) on 05-22-2013 at 17:21_

**Comment by tcmitchell** [comment]
#354 does not install URNs in the service registry. Looking up in the service registry won't work when there is more than one SA in the service registry. I don't think there is a general way to deduce the SA URN from a slice URN. I'm not sure how to eradicate the hardcoded SA URN from `portal/www/portal/flack.php` at this time.

_Trac comment by tmitchel (github user: tcmitchell) on 08-05-2013 at 14:18_

**Comment by tcmitchell** [comment]
The SA URN is in the service registry courtesy of the switch to chapi.

Running the find command again
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
I see:
 * portal/gcf.d/gcf.ini (3 occurrences)
  * 2 commented out
  * 1 appropriate (a reference gcf AM on localhost)
 * portal/gcf.d/omni.ini (2 occurrences)
  * Is this file used for anything at this point?


_Trac comment by tmitchel (github user: tcmitchell) on 02-04-2014 at 16:46_

**Comment by tcmitchell** [comment]
I find no references in the code to `portal/gcf.d/omni.ini`. It is not installed on `make install`, and no file references it.

That's it for this one. The hardcoded URNs are gone.

_Trac comment by tmitchel (github user: tcmitchell) on 02-04-2014 at 16:50_
