### ISSUE TITLE
auto add project lead to all slices

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#100]
The project lead / admin should be automatically added to all slices in their project, so they can deal with things they are responsible for

 _Imported from trac ticket [#100](http://trac.gpolab.bbn.com/proto-ch/ticket/100),  created by ahelsing on 06-05-2012 at 14:18, last modified: 09-07-2012 at 11:22_

**Comment by MarshallBrinn** [comment]
This is fixed - a new slice automatically has the project lead (if a different person) added as a new member with 'admin' privileges. In fixing this, needed to also change the semantics of list_slices (to get for all slices for which you are a member, not merely owner)

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-07-2012 at 11:22_
