### ISSUE TITLE
Use style sheet on openid/server.php

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1007]
Max says the portal openid server.php page that asks "Do you trust http.." ...  "Send my information" should have a consistent look and feel with the portal which is sending the information. So use the portal CSS probably.

 _Imported from trac ticket [#1007](http://trac.gpolab.bbn.com/proto-ch/ticket/1007),  created by ahelsing on 05-02-2014 at 11:31, last modified: 08-08-2014 at 11:54_

**Comment by tcmitchell** [comment]
The portal style has been applied to the OpenID trust page.

_Trac comment by tmitchel (github user: tcmitchell) on 08-08-2014 at 11:54_
