### ISSUE TITLE
Wording modifications for the Join a project page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1023]
Wording modifications that might reduce the number of doorknob rattlers for the 
Join a project page. It is slide number 3 on this word document:
https://docs.google.com/presentation/d/1ougMS3Xbn6W3CCSVMLGY9EtxkbaME6gOaI0Z3YVdVOc/edit?usp=sharing

 _Imported from trac ticket [#1023](http://trac.gpolab.bbn.com/proto-ch/ticket/1023),  created by nriga on 05-16-2014 at 12:19, last modified: 05-20-2014 at 12:15_

**Comment by tcmitchell** [comment]
See https://portal-tm.gpolab.bbn.com/secure/join-project.php for a mockup.

_Trac comment by tmitchel (github user: tcmitchell) on 05-16-2014 at 13:04_

**Comment by tcmitchell** [comment]
Got the thumbs up from Niky. Done.

_Trac comment by tmitchel (github user: tcmitchell) on 05-20-2014 at 12:15_
