### ISSUE TITLE
Wording modifications for ssh generation page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1024]
Wording modifications that warn people during key generation can be found in this document (the first two slides):
https://docs.google.com/presentation/d/1ougMS3Xbn6W3CCSVMLGY9EtxkbaME6gOaI0Z3YVdVOc/edit?usp=sharing

Slide 1: depicts current status
Slide 2: depicts suggested changes (phrases in bold represent buttons)

 _Imported from trac ticket [#1024](http://trac.gpolab.bbn.com/proto-ch/ticket/1024),  created by nriga on 05-16-2014 at 12:23, last modified: 05-20-2014 at 12:15_

**Comment by innnkkki** [comment]
Just a note, things that are red are just to emphasize what has changed, no text should be in red at the portal (at least from our point of view). 

_Trac comment by nriga (github user: innnkkki) on 05-16-2014 at 13:02_

**Comment by tcmitchell** [comment]
See https://portal-tm.gpolab.bbn.com/secure/profile.php#ssh for a mockup.

_Trac comment by tmitchel (github user: tcmitchell) on 05-16-2014 at 13:05_

**Comment by ahelsing** [comment]
I suggest a newline between the button and the new text. Perhaps preface the text with "Note: "

_Trac comment by ahelsing on 05-16-2014 at 14:13_

**Comment by tcmitchell** [comment]
Got the thumbs up from Niky. Done.

_Trac comment by tmitchel (github user: tcmitchell) on 05-20-2014 at 12:15_
