### ISSUE TITLE
Pick your IdP page uses http

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1025]
The pick your IdP page loads the nsf logo over http, so your browser warns. Load it over https to avoid that warning.

 _Imported from trac ticket [#1025](http://trac.gpolab.bbn.com/proto-ch/ticket/1025),  created by ahelsing on 05-20-2014 at 15:45, last modified: 06-12-2014 at 13:27_

**Comment by tcmitchell** [comment]
This is causing problems for an internal demo today. The NSF web site is out and the demonstration tool is waiting interminably for the logo gif.

_Trac comment by tmitchel (github user: tcmitchell) on 06-12-2014 at 13:21_

**Comment by tcmitchell** [comment]
Fixed in shib/sp/eds (shib repository) and on portal.geni.net.

_Trac comment by tmitchel (github user: tcmitchell) on 06-12-2014 at 13:21_
