### ISSUE TITLE
Profile page uses http for an icon

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1026]
The profile page uses http to get an icon from the wiki. Copy that icon into our source to avoid that error.

http://groups.geni.net/geni/attachment/wiki/GENIExperimenter/Tutorials/Graphics/Symbols-Tips-icon-clear.png?format=raw

 _Imported from trac ticket [#1026](http://trac.gpolab.bbn.com/proto-ch/ticket/1026),  created by ahelsing on 05-20-2014 at 15:47, last modified: 05-30-2014 at 09:44_

**Comment by tcmitchell** [comment]
Done.

_Trac comment by tmitchel (github user: tcmitchell) on 05-30-2014 at 09:44_
