### ISSUE TITLE
Allow multiple Jacks windows on listresources

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1027]
Give each Jacks container a unique ID to prevent multiple Jacks windows from colliding

 _Imported from trac ticket [#1027](http://trac.gpolab.bbn.com/proto-ch/ticket/1027),  created by kdownie on 05-20-2014 at 15:55, last modified: 05-21-2014 at 16:16_

**Comment by tcmitchell** [comment]
This is complete.

_Trac comment by tmitchel (github user: tcmitchell) on 05-21-2014 at 16:16_
