### ISSUE TITLE
Labwiki kmactivate.php redirect fails

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1029]
I ran into a bit of a corner case yesterday with Labwiki's OpenID authentication.
I tried using one of my new scale testing accounts to authenticate with Labwiki.
This particular account had not been activated yet, therefore, it was redirected to
the activation page.  However, I ended up getting a 404 error.

After doing a quick comparison using the same account with GENI Desktop (which successfully
gets to the activation page), it looks like it has a different URL than in the Labwiki case.

For GENI Desktop:
https://portal.geni.net/secure/kmactivate.php

For Labwiki:
https://portal.geni.net/secure/openid/kmactivate.php

 _Imported from trac ticket [#1029](http://trac.gpolab.bbn.com/proto-ch/ticket/1029),  created by johren on 05-20-2014 at 16:17, last modified: 05-22-2014 at 15:29_

**Comment by tcmitchell** [comment]
A quick and dirty fix: create openid/kmactivate.php and have it redirect to kmactivate. Jeanne tested it out and thinks it's ok.

_Trac comment by tmitchel (github user: tcmitchell) on 05-22-2014 at 15:29_
