### ISSUE TITLE
Aggregate specific Jacks instances on "Details" pages contains nodes from multiple aggregates

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1034]
If I click on the "Details" page for a multi-AM slice, I get login info for each AM separated by a Jacks instance.

In this case, I seem to get the same nodes drawn in each Jacks instance.

I think this is because some AMs (in this case IG AMs) copy any XML not ingested by that AM into their manifest.  So I think when this happens, Jacks is drawing the whole topology.

Anyways this is confusing for a couple of reasons:
 * same nodes appear in multiple pictures
 * the nodes aren't labeled to represent the AM they are from

I've attached a couple of screenshots.

In the multi-AM screenshot you can see that each picture has the same nodes.  In the single AM screenshot you can see that the AMs only have one node, but the picture includes more.

 _Imported from trac ticket [#1034](http://trac.gpolab.bbn.com/proto-ch/ticket/1034),  created by sedwards on 05-21-2014 at 14:09, last modified: 02-09-2015 at 13:15_
   CCing: kdownie@...

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [multiAM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1034/multiAM.png) on 05-21-2014 at 14:10_

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [singleAM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1034/singleAM.png) on 05-21-2014 at 14:10_

**Comment by ahelsing** [comment]
This is an issue that will be fixed with the release of a multi-aggregate supporting version of Jacks. 

The Portal implementation will need to change when this is released. Currently, the Details page will create a new Jacks instance for each manifest that it gets from the slice. In the future, the page will need to create only one Jacks instance and pass each manifest to that instance to be compiled into a single multi-aggregate topology.

_Trac comment by kdownie on 08-08-2014 at 12:12_

**Comment by ahelsing** [comment]
This new Jacks instance will have to be able to deconflict nodes and take the manifest from the AM whose node this is.

_Trac comment by ahelsing on 09-30-2014 at 15:47_

**Comment by tcmitchell** [comment]
This one is tied up with [combining the status and details pages](1043).

_Trac comment by tmitchel (github user: tcmitchell) on 01-20-2015 at 13:29_

**Comment by tcmitchell** [comment]
This is OBE. The [combined status and details page](1043) does not include a Jacks view.

_Trac comment by tmitchel (github user: tcmitchell) on 02-09-2015 at 13:15_
