### ISSUE TITLE
Jacks misparses gemini extensions

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1036]
Jacks misparses the gemini extensions in GENI RSpecs.

The general structure of a gemini extension to a node in a manifest looks like:
```xml
  <node>
    <color:resource_color>
      <color:xmlblob>
        <color:blob>
          <gemini:node type="global_node">
            <gemini:monitor_urn name="URN ELIDED"/>
          </gemini:node>
        </color:blob>
      </color:xmlblob>
    </color:resource_color>
  </node>
```
Jacks parses this into:
```xml
  <node>
    <color:resource_color>
      <color:xmlblob>
        <color:blob>
        </color:blob>
      </color:xmlblob>
    </color:resource_color>
  </node>
  <gemini:node type="global_node">
    <gemini:monitor_urn name="URN ELIDED"/>
  </gemini:node>
```

Jacks also adds additional nodes (computer icons) to the canvas, presumably representing these gemini:nodes.

A example screenshot and matching manifest rspec are attached.

 _Imported from trac ticket [#1036](http://trac.gpolab.bbn.com/proto-ch/ticket/1036),  created by tmitchel on 05-22-2014 at 11:42, last modified: 06-30-2014 at 15:37_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [joGEM0520.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1036/joGEM0520.png) on 05-22-2014 at 11:45_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [joGEM0520.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1036/joGEM0520.rspec) on 05-22-2014 at 11:43_

**Comment by tcmitchell** [comment]
Posted to http://gitlab.flux.utah.edu/duerig/jacks/issues/1

_Trac comment by tmitchel (github user: tcmitchell) on 05-22-2014 at 12:50_

**Comment by ahelsing** [comment]
Jon fixed this.

_Trac comment by ahelsing on 06-30-2014 at 15:37_
