### ISSUE TITLE
geni-ops-report doesn't handle disabled users

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1037]
geni-ops-report doesn't know if users are disabled. So it complains if someone is listed as a lead or operator in the DB who does not have that permission in the infra accounting of expected permissions.

Exclude disabled users from the report altogether? List if users are disabled in the chart and avoid complaining if a disabled user has a permission not expected?

 _Imported from trac ticket [#1037](http://trac.gpolab.bbn.com/proto-ch/ticket/1037),  created by ahelsing on 05-23-2014 at 10:44, last modified: 05-23-2014 at 15:40_

**Comment by ahelsing** [comment]
Probably it should pretend disabled users dont exist.

_Trac comment by ahelsing on 05-23-2014 at 12:37_

**Comment by MarshallBrinn** [comment]
Excluded all disabled users from load_members and conditioned calls to Member.find to the member already existing. The report now excludes disabled users.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-23-2014 at 15:40_
