### ISSUE TITLE
Allow seeing/downloading request RSpecs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#104]
You should be able to see the canned RSpec you are about to submit, if you select one of those.

Maybe you should be able to see any request RSpec you submit via the portal?

 _Imported from trac ticket [#104](http://trac.gpolab.bbn.com/proto-ch/ticket/104),  created by ahelsing on 06-06-2012 at 10:07, last modified: 02-15-2013 at 09:34_

**Comment by MarshallBrinn** [comment]
Per discussions 8/20/2012, need to upload, download, paste, name, search and share (these last two are optional).

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 07:38_

**Comment by ahelsing** [comment]
See ticket #164

_Trac comment by ahelsing on 09-21-2012 at 11:07_

**Comment by ahelsing** [comment]
and #165

_Trac comment by ahelsing on 09-21-2012 at 11:08_

**Comment by tcmitchell** [comment]
This is effectively done, and the rest is on #230.

_Trac comment by tmitchel (github user: tcmitchell) on 02-12-2013 at 15:14_
