### ISSUE TITLE
Combine the Status and Details pages

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1043]
Combine the status and details pages, so that 'Details' tells you what resources you have, and also if they are ready.

Keep the links to show raw status and manifest.

 _Imported from trac ticket [#1043](http://trac.gpolab.bbn.com/proto-ch/ticket/1043),  created by ahelsing on 05-29-2014 at 14:50, last modified: 01-22-2015 at 13:03_

**Comment by MarshallBrinn** [comment]
As part of this, remove the jacks viewers between every aggregate section.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 15:22_

**Comment by MarshallBrinn** [comment]
Have a prototype of this checked into branch tkt1043_status_details. Once we get (and incorporate) some feedback from experimenter-support, we'll merge this and remove the separate buttons to get at both status and details. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-20-2015 at 14:59_

**Comment by MarshallBrinn** [comment]
This is implemented and demo'ed to Sarah and Vic. Eliminated 'status' buttons, there are only 'details' buttons to get to the combo view. Also added in sliver expiration times into this view.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-22-2015 at 13:03_
