### ISSUE TITLE
Clarify slice page wording about user keys being loaded on nodes

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1050]
We currently say:
"Slice members will be able to login to resources reserved in the future if:

	• The resources were reserved directly through the portal (by clicking Add Resources on the slice page), and
	• The slice member has uploaded an ssh public key."

However this is no longer accurate.

It should now say something like:
"Slice members will be able to login to resources reserved in the future if:

	• The resources were reserved directly through the portal (by clicking Add Resources on the slice page) or using omni 2.5 or newer, and
	• The slice member has uploaded an ssh public key."

 _Imported from trac ticket [#1050](http://trac.gpolab.bbn.com/proto-ch/ticket/1050),  created by sedwards on 06-02-2014 at 13:08, last modified: 06-02-2014 at 14:04_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Updated the text to that in the ticket.

_Trac comment by kdownie on 06-02-2014 at 14:04_
