### ISSUE TITLE
Add privilege check when requesting to view private RSpecs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1054]
It's possible to view other users' private RSpecs by knowing the URL of where they are located (e.g. https://portal-bu.gpolab.bbn.com/secure/rspecview.php?id=524 goes to a private RSpec). Add some mechanism to verify if the user should be allowed to access the RSpec.

 _Imported from trac ticket [#1054](http://trac.gpolab.bbn.com/proto-ch/ticket/1054),  created by bujcich on 06-03-2014 at 11:08, last modified: 08-08-2014 at 17:11_

**Comment by tcmitchell** [comment]
Added a check for owner on private rspecs. Also returned 404 when the rspec does not exist since the ajax doesn't respond to a redirect to the home page.

_Trac comment by tmitchel (github user: tcmitchell) on 08-08-2014 at 17:11_
