### ISSUE TITLE
Update link to password reset page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1056]
Once [idp-tools 95](http://trac.gpolab.bbn.com/idp-tools/ticket/95) is deployed on production, we should update the link to the password reset page on the GPO IdP login page.

 _Imported from trac ticket [#1056](http://trac.gpolab.bbn.com/proto-ch/ticket/1056),  created by sedwards on 06-03-2014 at 12:03, last modified: 07-15-2014 at 16:10_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
This is queued up. Also fixing link on login-help page.

_Trac comment by ahelsing on 07-15-2014 at 16:10_
