### ISSUE TITLE
Portal hangs indefinitely when getting sliverstatus on large slivers

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1060]
I used the nifty-difty new "select your aggregates" tool on the slice page and selected my aggregates (for bss-sw-test:vts-stage) and hit the button that says "Resource Status" and the portal got really unhappy and never loaded a page for me again.  (I had to launch a new browser to even get the portal login to load again, and I can always hang the portal by asking for resource status on that slice at any of those aggregates).

The problem is likely related to the fact that the sliverstatus result for these slivers is around 17MB.

 _Imported from trac ticket [#1060](http://trac.gpolab.bbn.com/proto-ch/ticket/1060),  created by nick.bastin on 06-04-2014 at 13:39, last modified: 01-23-2015 at 14:08_

**Comment by ahelsing** [comment]
_nick.bastin attached [vts-stage-sliverstatus-utahddc-geniracks-net.json](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1060/vts-stage-sliverstatus-utahddc-geniracks-net.json) on 06-04-2014 at 13:45_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [pwe-build.xml](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1060/pwe-build.xml) on 06-04-2014 at 22:40_

**Comment by ahelsing** [comment]
Just as an FYI it takes my omni about 65 seconds to download and write sliverstatus to a file:

real	1m5.372s
user	0m8.393s
sys	0m0.490s

(My internet is also not awesome)

_Trac comment by nick.bastin on 06-04-2014 at 13:54_

**Comment by tcmitchell** [comment]
The logs indicate that the calls to the AMs went out at 13:12:31 and were timed out (i.e. the portal gave up) at 13:24:31 which is exactly our 12 minute limit on child omni processes.

There are a few problems:
 * why doesn't omni return within 12 minutes when Nick gets the status in 65 seconds?
 * the SESSION is held open while omni is running so no other page can be displayed
 * does the error ("Operation timed out") ever make it back to the page for display?


_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2014 at 14:21_

**Comment by tcmitchell** [comment]
Given an appropriate rspec (thanks, Nick) I can repeat part of the reported problem. It does take 12 minutes and after 12 minutes the portal reports "failed". The failure does get reported back to the portal at the end of the 12 minutes though.

I cannot replicate the "unhappy" or frozen portal. I was able to open other portal pages without a problem during that 12 minute period where the portal was collecting status. The SESSION is not held open during the sliver status call.

We have some ideas about the 12 minutes.

_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2014 at 17:30_

**Comment by ahelsing** [comment]
So I suspect you may be able to interact with the Portal while I can't simply because of the number of concurrent operations you are attempting.  Typically a browser has a maximum number of connections it will make to the same domain, and since I'm trying to get sliverstatus on many aggregates I have hit that limit (since apparently there is one connection per sliverstatus call?), while you do not hit the limit because you're only trying one aggregate.

_Trac comment by nick.bastin on 06-04-2014 at 17:33_

**Comment by tcmitchell** [comment]
A fix is in place on portal.geni.net, please try it out. For me it changes from a 12 minute timeout to results in 35 seconds at Utah DDC for the rspec you gave me. There's not much I can do about hitting the maximum connections if that's the issue with the unresponsive portal. See if the reduced time for status alleviates the problem enough to make things workable for you.

_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2014 at 20:37_

**Comment by ahelsing** [comment]
When querying 3 aggregates there's no change in either Chrome or Safari.

_Trac comment by nick.bastin on 06-04-2014 at 20:50_

**Comment by tcmitchell** [comment]
No visible change to you, but changes internally. Now it is a PHP max execution time exceeded error instead of a process timeout. Also a max memory exceeded. Handling large sliver status will require some deeper changes. Very sorry for the inconvenience.


_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2014 at 22:39_

**Comment by tcmitchell** [comment]
The sample rspec is attached. Not sure what the best approach is on this. Longer sleep while waiting and a larger read buffer to fix the max execution time?  But max memory exceeded? That pushes towards leveraging the SESSION to force fetching status serially which is undesirable for the dominant case of small sliver status.

We also need to handle the max execution time failure in javascript with a ".fail" handler so the user knows it's over.

_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2014 at 22:45_

**Comment by ahelsing** [comment]
FWIW, I left safari open for 2 hours and the page never returned and said anything other than querying resources.

_Trac comment by nick.bastin on 06-05-2014 at 00:52_

**Comment by tcmitchell** [comment]
Replying to [nick.bastin](comment:9):
> FWIW, I left safari open for 2 hours and the page never returned and said anything other than querying resources.

Yes, given the errors I see in the logs that's the behavior I expect you'll see. That's because of [the omission of a .fail handler in the ajax call](1000). If you look in your javascript console I think you'll see the ajax call failing with an error return that our javascript code does not catch. Bug.


_Trac comment by tmitchel (github user: tcmitchell) on 06-05-2014 at 07:59_

**Comment by MarshallBrinn** [comment]
I'm going to try to recreate this by setting up 4 (hacked) GCF AM's that return this content from their sliver status calls.

Clearly there is some limit to how much data the portal should be able to ingest as a response from an omni call, but I'm not sure what the gating factors are. But it is possible  that the portal may not be a tool that can handle topologies of the scale that Nick is testing on. But if so it should hand back a nice error and let you move on….

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-05-2014 at 08:43_

**Comment by MarshallBrinn** [comment]
I notice that the sliver status response has a large number of repeated references to:

http://www.geni.net/resources/rspec/ext/shared-vlan/1 http://www.geni.net/resources/rspec/ext/shared-vlan/1/request.xsd

in the xsi:schemaLocation. But this is a small issue, when you edit them out to only one occurrence, the file only shrinks from 17MB to 15MB.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-05-2014 at 09:00_

**Comment by ahelsing** [comment]
Well right, there's an entirely separate problem with the fact that sliverstatus shouldn't be 20MB in the first place...

_Trac comment by nick.bastin on 06-05-2014 at 11:51_

**Comment by tcmitchell** [comment]
I added a band-aid to catch the server-side error in javascript and close out the querying properly, with an error message in the aggregate table.

_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2014 at 15:21_

**Comment by tcmitchell** [comment]
This will be fixed when the manifest is dropped from the sliver status response from instageni. That is waiting on a new release of omni containing a reworked ready-to-login script that no longer relies on the manifest embedded in the sliver status response.

_Trac comment by tmitchel (github user: tcmitchell) on 08-08-2014 at 15:59_

**Comment by tcmitchell** [comment]
This is waiting on omni [2.7](http://trac.gpolab.bbn.com/gcf/milestone/2.7), which is in late stage testing. Once that has sufficient uptake we can ask ProtoGENI/InstaGENI to remove the manifest from the sliver status.

Bumping back to the GEC 22 milestone since omni 2.7 is unlikely to have sufficient uptake until after GEC 21 at this point.

_Trac comment by tmitchel (github user: tcmitchell) on 10-08-2014 at 11:51_

**Comment by ahelsing** [comment]
See http://trac.gpolab.bbn.com/gcf/ticket/674

_Trac comment by ahelsing on 10-29-2014 at 15:41_

**Comment by ahelsing** [comment]
Leigh is dropping the manifest from sliverstatus in the upgrade next week (11/21)

_Trac comment by ahelsing on 11-14-2014 at 16:45_

**Comment by tcmitchell** [comment]
Nick, can you test this and see if it is fixed for you?

_Trac comment by tmitchel (github user: tcmitchell) on 01-20-2015 at 13:26_

**Comment by ahelsing** [comment]
It's better, for sure.  It still takes long enough that maybe it'd be nice if there was some kind of spinner or something that made me feel it was doing something.. :-)

_Trac comment by nick.bastin on 01-21-2015 at 12:20_

**Comment by tcmitchell** [comment]
Completed via the modification in ProtoGENI / InstaGENI code.

_Trac comment by tmitchel (github user: tcmitchell) on 01-23-2015 at 14:08_
