### ISSUE TITLE
Expiration of ION AM does not show at the portal

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1065]
I tried to get the expiration for an ION sliver but the portal says "expiration not retrieved"
See screenshot here:
http://grab.by/xxtQ

 _Imported from trac ticket [#1065](http://trac.gpolab.bbn.com/proto-ch/ticket/1065),  created by nriga on 06-06-2014 at 08:45, last modified: 06-06-2014 at 11:20_

**Comment by ahelsing** [comment]
My guess is that the portal code is failing to parse the expiration properly. Sample sliverstatus:
```
{
  "https:\/\/geni-am.net.internet2.edu:12346":{
    "geni_resources":[
      {
        "geni_urn":"urn:publicid:IDN+ch.geni.net:ahscaletest+slice+ahtest_vlan_ion.internet2.edu-95781",
        "geni_error":"",
        "geni_status":"ready"
      }
    ],
    "geni_expires":"2014-06-07T13:32:10.000Z",
    "geni_urn":"urn:publicid:IDN+ch.geni.net:ahscaletest+slice+ahtest",
    "geni_status":"ready"
  }
```}


_Trac comment by ahelsing on 06-06-2014 at 09:55_

**Comment by ahelsing** [comment]
Just for documentation purposes 

php function, date_parse, for this string, "2014-06-07T13:32:10.000Z", will return values with keys defined by the array below.   amstatus.php had previously looked for a key that is not in this array.   Added zone as the correct key to be looking for in amstatus.php.  Previously fixed for GRAM.
Array
(
    [0] => year
    [1] => month
    [2] => day
    [3] => hour
    [4] => minute
    [5] => second
    [6] => fraction
    [7] => warning_count
    [8] => warnings
    [9] => error_count
    [10] => errors
    [11] => is_localtime
    [12] => zone_type
    [13] => zone
    [14] => is_dst
    [15] => tz_abbr
)


_Trac comment by rrhain on 06-06-2014 at 11:20_
