### ISSUE TITLE
Slice page does not switch to "This Slice" on Safari

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1067]
On safari when the slice page loads the page does not switch over to "This Slice" the way it does on Chrome and Firefox. This leaves all the aggregates selected by default.

 _Imported from trac ticket [#1067](http://trac.gpolab.bbn.com/proto-ch/ticket/1067),  created by tmitchel on 06-06-2014 at 15:54, last modified: 06-09-2014 at 12:00_

**Comment by ahelsing** [comment]
Safari didn't like the jQuery using .attr('selected','selected') to set the selected option when the document was ready. Switched it to .prop('selected',true) and all browsers appear happy.

_Trac comment by kdownie on 06-06-2014 at 16:29_

**Comment by tcmitchell** [comment]
Fixed in tag `v2.16.6`

_Trac comment by tmitchel (github user: tcmitchell) on 06-09-2014 at 12:00_
