### ISSUE TITLE
Support Unicode strings in Portal

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1069]
Need to support names, emails, logging messages that contain unicode (non-ASCII) messages.

Some specific tasks:

kmhome.php
 * "Tool 'portal' has been authorized for user NAME" is garbled
  - recreate by deauthorizing and then authorizing the portal
 * Still uses NSF logo from nsf web site, which is still down

RSpec uploading
 * UTF-8 encode appropriate fields from RSpec upload form for database
 * Probably UTF-8 decode fields as they come in from the form
   submittal
 * UTF-8 decode fields for display when querying database

Modify Your Account
 * UTF-8 encode values for display
 * handle UTF-8 strings on input, maybe database writes

 _Imported from trac ticket [#1069](http://trac.gpolab.bbn.com/proto-ch/ticket/1069),  created by mbrinn on 06-12-2014 at 09:32, last modified: 09-08-2014 at 13:37_

**Comment by MarshallBrinn** [comment]
This ticket is a partner of CHAPI ticket 310 http://trac.gpolab.bbn.com/chapi/ticket/310.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-12-2014 at 09:34_

**Comment by MarshallBrinn** [comment]
Tested and checked in for CHAPI and PROTO-CH.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-12-2014 at 06:05_

**Comment by ahelsing** [comment]
Some tests:
 - enter international characters in RSpec name
 - enter such characters in modify your account
 - enter such characters in the field with reason for denying a project join request or the field for a project join request
 - manually get some international characters in a person's name, see that appear OK

_Trac comment by ahelsing on 09-08-2014 at 13:37_
