### ISSUE TITLE
Project Join Request email subject is grammatically incorrect

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1083]
The subject of Project Join Request emails is currently:
```
Join GENI Project XXX?
```

Change it to something grammatically correct like:
```
May I join GENI Project XXX?
```
Or
```
Request to join GENI Project XXX
```

 _Imported from trac ticket [#1083](http://trac.gpolab.bbn.com/proto-ch/ticket/1083),  created by sedwards on 07-10-2014 at 14:32, last modified: 07-22-2014 at 15:17_
   CCing: nick.bastin@...

**Comment by ahelsing** [comment]
I also strongly dislike how the form email puts words in the experimenters mouth (or keyboard, as it were):

```
To handle my request, go to the GENI Portal here:
https://portal.geni.net/secure/handle-project-request.php?project_id=5f5fbc4a-f5e4-4688-8901-07109f60f151&member_id=242d561f-9b11-48e4-88eb-ab04c8c8fd8c&request_id=2185
```

This entire email reads (by default) like a pleading child begging to join my project, not a process email sent by a computer informing me of a request.  Even if the user changes the default "I think I need to do research in your project", it's still going to say "To handle my request".

It would be great if the email was clearly generated by the portal, and perhaps just had an (optional) "Requestor Notes" or "Comment" section at the end where user-supplied text could go, *but was not required*.

_Trac comment by nick.bastin on 07-10-2014 at 14:42_

**Comment by ahelsing** [comment]
For now lets make it 'Request to join ....' and leave more substantial changes for later.



_Trac comment by ahelsing on 07-14-2014 at 12:08_

**Comment by ahelsing** [comment]
Changed the subject. Refactoring the email is on ticket http://trac.gpolab.bbn.com/proto-ch/ticket/1112

_Trac comment by ahelsing on 07-22-2014 at 15:17_
