### ISSUE TITLE
Restore client_id to status page

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1085]
On the slice status page for instageni and protogeni aggregates the client_id is no longer available (see issue #1084). Restore client_id to this page by retrieving the manifest rspec via list resources and matching up the URN in sliver status with the URN in the manifest to locate the correct client id.

(Or are we getting rid of this page altogether?)

 _Imported from trac ticket [#1085](http://trac.gpolab.bbn.com/proto-ch/ticket/1085),  created by tmitchel on 07-11-2014 at 15:45, last modified: 02-23-2015 at 10:51_

**Comment by ahelsing** [comment]
Leigh has added geni_client_id. This is deployed at PG Utah so far.


_Trac comment by ahelsing on 07-17-2014 at 14:45_

**Comment by ahelsing** [comment]
On the details page, I see the client_id for nodes. The status page shows the URN for resources. Is that what this ticket is really about? Or is this fixed?

_Trac comment by ahelsing on 09-30-2014 at 16:03_

**Comment by ahelsing** [comment]
May be made OBE for #1043

_Trac comment by ahelsing on 10-30-2014 at 14:28_

**Comment by ahelsing** [comment]
This seems to now work with combined status/details page.

_Trac comment by ahelsing on 02-23-2015 at 10:51_
