### ISSUE TITLE
link to jFed

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1092]
- Put a link to jFed in the portal
 - Brecht has a link that downloads/installs the jFed application. Use that link
 - Ideally, pass the user's cert/key to preserve user context

 _Imported from trac ticket [#1092](http://trac.gpolab.bbn.com/proto-ch/ticket/1092),  created by ahelsing on 07-16-2014 at 13:05, last modified: 09-08-2014 at 13:28_

**Comment by innnkkki** [comment]
BTW this is where jFed is launch:
http://jfed.iminds.be/

It does not work with the combination of Chrome+Mac

_Trac comment by nriga (github user: innnkkki) on 07-17-2014 at 08:34_

**Comment by ahelsing** [comment]
Marks says a link is OK.

Brecht provides some richer options:
```
Option 1: simple start up without PEM argument.
----------------
Put jfed-plain.html, jfed-geni.jnlp and dtjava_orig.js on a webserver 
and browse to jfed-plain.html
Example: 
https://flsmonitor.fed4fire.eu/jfedexperimenter/geni/jfed-plain.html

Option 2: start up with PEM integrated
---------------
Put jfed.php, jfed-geni.jnlp and dtjava_orig.js on a webserver and 
browse to jfed.php
https://flsmonitor.fed4fire.eu/jfedexperimenter/geni/jfed.php

Option 3: one of the previous but with local jars
----------------
in the previous two options, the jars are located at iMinds site, with a 
special version geni-portal that we can change easily (symlink).
I think it might be most handy to start as such, but of course, if you 
just copy over all stuff from 
http://jfed.iminds.be/releases/geni-portal/webstart/experimenter/ and 
adapt the paths a little in the jnlp, you can have a local copy.


It should be straight forward to integrate this with e.g. the database 
of PEMs, or the portal I think.
```

_Trac comment by ahelsing on 07-23-2014 at 15:42_

**Comment by ahelsing** [comment]
Files Brecht refers to are here: https://flsmonitor.fed4fire.eu/jfedexperimenter/geni/jfedweb.tar.gz

_Trac comment by ahelsing on 07-23-2014 at 15:42_

**Comment by ahelsing** [comment]
Brecht says:
 - The PEM should be cert plus key. jFed then stores this locally in its own store. So really you only need this once (which is why downloading the cert and then importing it into jFed isn't too bad)
 - Basically, we'd treat this like Omni or Flack
 - The cert/key we pass is over HTTPS in the page and then javascript to jnlp locally.
 - Putting a passphrase on the private key in the PEM would also be good.
 - They don't currently support taking a slice URN to take slice context, but that'd be a good future idea.

_Trac comment by ahelsing on 07-23-2014 at 16:16_

**Comment by ahelsing** [comment]
After discussion with Marshall
 - Aim for option 2
 - We'll pass jFed the user's outside cert and key. 
  - Find out from Brecht if he would rather that we pass nothing if we have no key, which will happen sometimes


_Trac comment by ahelsing on 07-28-2014 at 16:30_

**Comment by ahelsing** [comment]
Brecht confirms: if we have no key, send nothing (as in option 1)

_Trac comment by ahelsing on 07-28-2014 at 16:38_

**Comment by ahelsing** [comment]
It'd be nice if
 - we could supply a slice URN
 - we could supply the SR URL, to use jFed with our dev servers

_Trac comment by ahelsing on 08-01-2014 at 12:24_

**Comment by ahelsing** [comment]
Added a php file with supporting files on a branch I pushed.

Waiting an answer from Brecht to get the format of cert+key correct and resolve an error launching jFed (something about unclosed img tag).

Additionally note that jFed seems to require Java7 which requires a 64bit browser, which rules out Chrome on Mac. Mac users will (a) have to update to Java 7, eliminating any Java 6, which would have run inside their Chrome browser, and (b) use Firefox or Safari. Note that Google analytics says 23% of portal users use Chrome on Mac.  I'm hoping Brecht can also clarify that I have this restriction correct.



_Trac comment by ahelsing on 08-01-2014 at 15:54_

**Comment by ahelsing** [comment]
Tried closing our img tags. (See #1145), plus in the shib/sp code: `sp/common/www/eds/index.html`

Brecht says I am supplying the key and cert correctly.

Brecht confirms Java7 is required, and on a Mac Java7 requires a 64bit browser. He also says "there is now a 64 bit chrome https://www.google.com/chrome/browser/canary.html?platform=macosx but I didn't get it working on Mac with java yet"

_Trac comment by ahelsing on 08-08-2014 at 14:41_

**Comment by ahelsing** [comment]
Hmm. Indeed looking more closely at the error from jfed, the problem is that file in the sp.

But after manually fixing that, it is not complaining about the `<p>` tag on line 136.

_Trac comment by ahelsing on 08-08-2014 at 14:59_

**Comment by ahelsing** [comment]
At Brecht's suggestion, I tried manually loading the jnlp. I had to click through some warnings and tell my Mac to install untrusted Apps. Now I'm getting errors that it cannot download some of the jars hosted at jfed.iminds.be

Chrome cannot load the jfed.iminds.be website - or sometimes does after long timeout. FF is quicker. curl won't connect. Ping and wget look OK.


_Trac comment by ahelsing on 08-08-2014 at 15:27_

**Comment by ahelsing** [comment]
I found a page to use to try to validate the IDP select page and find the error:
http://validator.w3.org/#validate_by_input

I have done a bunch of cleanup of that IdP select page. The validator doesn't like the early / in tags closing the tags on one line in many places. And then starts complaining about things like body and head which is weird.
Meanwhile, the jfed launcher now complains about the p tag on line 143 not being closed properly. But I haven't figured out the real source of that problem yet.

_Trac comment by ahelsing on 08-08-2014 at 16:48_

**Comment by ahelsing** [comment]
Internet routing problems to jfed on Friday are now better.

New theory: javaws thinks it is parsing the jnlp file. But that file is behind shib, so our server sent instead the IDP select page. javaws isn't ready to handle shib login and isn't expecting this HTML file. So hosting the jnlp file outside the secure area might solve the problem.

_Trac comment by ahelsing on 08-11-2014 at 12:36_

**Comment by ahelsing** [comment]
Hosting the jnlp file gets me further. Now I get an error saying the Application was blocked by my java security settings. You have to tell java to trust the portal server (https://portal-ah.gpolab.bbn.com) and the jfed url (https://jfed.iminds.be)

Now I get:
java.lang.SecurityException: JAR manifest application-library-allowable-codebase  mismatch for http://jfed.iminds.be/releases/geni-portal/webstart/experimenter/lib/experimenter-gui-5.0.1-SNAPSHOT.jar
	at com.sun.deploy.security.DeployManifestChecker.verify(Unknown Source)

Note whenever this happens, java is left running and you have to force quit it.

_Trac comment by ahelsing on 08-12-2014 at 10:17_

**Comment by ahelsing** [comment]
jFed can't handle running on a development server.

So I temporarily deployed jfed.php to nye.
I found a bug handling the case where the experimenter has no private key (like me) and fixed that.

Note that the experimenter needs a single file with both the cert and key, where user's who used a CSR will have to generate such a file.
Once I did that I was able to log in. jFed found my projects and slices, and I was able to make a reservation at an AM (though I didn't get SSH to work right).

_Trac comment by ahelsing on 08-12-2014 at 14:21_

**Comment by ahelsing** [comment]
Brecht confirms that manually pointing jFed at a dev server won't work for the moment. He suggests:
```
I think the easiest thing to verify:
- start up jFed as you did, but choose then your ch.geni.net pem file, then you can test some stuff (against the real CH, but that's as we do :-) )
- close jFed
- start up jFed as you did, go to advanced login to verify that the certificate is the one you sent from the portal as argument
```


_Trac comment by ahelsing on 08-12-2014 at 15:10_

**Comment by ahelsing** [comment]
Added buttons on Home, Slice, Slices pages. Button warns if you have no keys or are using a bad browser.

_Trac comment by ahelsing on 08-13-2014 at 13:05_

**Comment by ahelsing** [comment]
To test
 - In Chrome, hit jFed button on Home, Slices, Slice pages (see error popup)
 - Remove outside cert
 - In FF, hit jFed button - see popup
 - User where portal has both cert&key for outside cert, use FF to hit jFed button. jFed starts with cert/key filled in.
 - User where portal has only cert (no key), use FF to hit jFed button. jFed starts and has no cert/key. User has to provide a single file with both the cert and key



_Trac comment by ahelsing on 09-08-2014 at 13:28_
