### ISSUE TITLE
create openid wiki page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1098]
Create a public wiki page explaining our use of openid and the available attributes.

 _Imported from trac ticket [#1098](http://trac.gpolab.bbn.com/proto-ch/ticket/1098),  created by ahelsing on 07-18-2014 at 10:34, last modified: 10-08-2014 at 11:42_

**Comment by tcmitchell** [comment]
Done: http://groups.geni.net/geni/wiki/PortalOpenId

_Trac comment by tmitchel (github user: tcmitchell) on 10-08-2014 at 11:42_
