### ISSUE TITLE
Show sliver expiration in print-rspec-pretty

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1107]
The manifest 'expires' attribute usually indicates the expiration time of the reserved sliver. Show this when giving a pretty view of an RSpec - ie the results of a reservation and the Details page.

For some logic, see omnilib.util.handler_utils#expires_from_rspec

Note that this is not reliable from ION at the moment (unless a code update Wednesday fixed this), and from FOAM it is not usable at all.
From EG you do not use the expires attribute, but a different RSpec extension.

 _Imported from trac ticket [#1107](http://trac.gpolab.bbn.com/proto-ch/ticket/1107),  created by ahelsing on 07-18-2014 at 15:46, last modified: 01-22-2015 at 13:00_

**Comment by ahelsing** [comment]
Pushed some code to branch tkt1107-expires

Untested at an AM that supplies an expires attribute. And missing code to get expiration from EG manifests.

_Trac comment by ahelsing on 11-07-2014 at 14:53_

**Comment by MarshallBrinn** [comment]
Fixed as part of #1043 - the expiration shows up in the new combined details/status page.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-22-2015 at 13:00_
