### ISSUE TITLE
Consider GENI user switching IdP

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#111]
When an academic switches institutions, how can we help them keep their GENI account?

We would somehow need them to prove that under their new ID they are the same person as the old ID. 

Try to make this work.

 _Imported from trac ticket [#111](http://trac.gpolab.bbn.com/proto-ch/ticket/111),  created by ahelsing on 06-06-2012 at 14:59, last modified: 12-11-2013 at 10:01_

**Comment by tcmitchell** [comment]
This is why the identity points to an account. Multiple identities (ie. IdP logins) can point to a single GENI "account". There's a human in the loop to verify they're the same person, and to do the database adjustments (link new identity to existing account).

We could also use this mechanism during a pgeni.gpolab migration. We could create accounts on a GENI IdP for all pgeni users, then transition those accounts that have InCommon logins.

_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2012 at 15:22_

**Comment by ahelsing** [comment]
A side comment:
As we discussed offline, for a transition: If we're creating the IdP accounts, we can also create both the portal accounts and the projects, and copy over the SSH keys. Then when they come in with their pgeni accounts, they have everything but their slices.


_Trac comment by ahelsing on 06-06-2012 at 15:46_

**Comment by ahelsing** [comment]
This has happened a couple times now. We need a story.

_Trac comment by ahelsing on 12-05-2013 at 09:49_

**Comment by ahelsing** [comment]
Replaced by chapi ticket 177

_Trac comment by ahelsing on 12-11-2013 at 10:01_
