### ISSUE TITLE
Update to latest xml-signer

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1116]
Jack Hong of NICTA says the xml-signer tool was updated around May 31, and includes their changes to support their preferred page flow. Update the CH hosted xml-signer to the latest from master.

 _Imported from trac ticket [#1116](http://trac.gpolab.bbn.com/proto-ch/ticket/1116),  created by ahelsing on 07-25-2014 at 08:48, last modified: 08-05-2014 at 09:36_

**Comment by tcmitchell** [comment]
I picked up the latest xml-signer code and will build a package.

_Trac comment by tmitchel (github user: tcmitchell) on 08-04-2014 at 17:12_

**Comment by tcmitchell** [comment]
I created a 0.8 debian package with Jack's changes and installed it on ch.geni.net. It is backward compatible with the portal's use of xml-signer.

_Trac comment by tmitchel (github user: tcmitchell) on 08-05-2014 at 09:36_
