### ISSUE TITLE
Clean up temporary files created by forked omni processes

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1118]
Write a cleanup script that will delete temporary files created by forked omni processes, as these files are persistent after the omni call is invoked.

 _Imported from trac ticket [#1118](http://trac.gpolab.bbn.com/proto-ch/ticket/1118),  created by bujcich on 07-28-2014 at 09:44, last modified: 01-27-2015 at 10:49_

**Comment by ahelsing** [comment]
From notes with Aaron:

At the moment, all files go to a per-call directory in `/tmp`. As `/tmp` is purged every time that the server restarts, this may not be the best location to send files.

Each omni invocation generates around 100 KB of data. Some statistics on the number of times that `sliceresource.php` was visited according to Google Analytics:

 * Within the last 30 days: 410
 * Within the month of May (no tutorials that I know of or GECs): 335
 * Within GEC 20:243
 * Within GEC 19: 79
 * Within GEC 18: 77

Practically speaking, not much data is generated given the number of requests in a period of a month or a period during a GEC.

Aaron suggested to purge files if the number of directories is greater than 300 or the size of the files is greater than 30 MB, and to purge if files are older than 21 days.

A possible solution would be to run a cron job that checked the following:

```
if tmp size > 30 MB || directories in tmp > 300:
    for each directory:
        if directory age > 21 days:
            purge directory
```

The implications would be that:
 * for sudden spikes of use such as during the GECs, the limits could be exceeded, but we would know that the results files would only stick around for at most three weeks and
 * for periods with little activity, the results files would stay around longer than three weeks, but we would know that they would go away when activity spiked again

_Trac comment by bujcich on 07-28-2014 at 09:53_

**Comment by ahelsing** [comment]
Note that root currently has a crontab entry to delete files > 7 days old. That job could be reworked to be closer to this idea.

_Trac comment by ahelsing on 09-08-2014 at 12:40_

**Comment by tcmitchell** [comment]
The current cron job:
```
55 23 * * * /usr/bin/find /tmp -name '*-omni-log-??????' -mtime +7 | /usr/bin/xargs /bin/rm -f 
```

A possible updated cron job:
```
55 23 * * * /usr/bin/find /tmp -name 'omni-invoke-*-??????' -mtime +7 | /usr/bin/xargs /bin/rm -rf
```

That would delete directories more than 7 days old. We can change the 7 to another number, like 21, if we really want 3 weeks worth of log files. The counting of matching directories and checking of size (is that 30 MB per directory or 30 MB total?) complicates things. I suspect simplifying to just the last N days is fine, and we could bump up the number if we're worried about losing files more than 7 days old.

_Trac comment by tmitchel (github user: tcmitchell) on 01-19-2015 at 15:45_

**Comment by tcmitchell** [comment]
We agreed to hold files for 14 days. A request has been submitted to infra to update this cron job in puppet.

_Trac comment by tmitchel (github user: tcmitchell) on 01-19-2015 at 17:14_

**Comment by tcmitchell** [comment]
This issue was completed by infra on ticket http://groups.geni.net/syseng/ticket/6419

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2015 at 10:49_
