### ISSUE TITLE
usernames must obey AM API rules

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#112]
Make sure usernames (see do-register.php) obey GENI username rules:
http://groups.geni.net/geni/wiki/GeniApiIdentifiers#Name

 _Imported from trac ticket [#112](http://trac.gpolab.bbn.com/proto-ch/ticket/112),  created by ahelsing on 06-07-2012 at 12:48, last modified: 09-14-2012 at 16:10_

**Comment by tcmitchell** [comment]
Usernames now obey the naming rules set forth in http://groups.geni.net/geni/wiki/GeniApiIdentifiers#Name

 * Added trimming to 8 characters
 * Added trimming to 6 characters if the 8 character version conflicts
 * Always append two digits: 01 -> 99
 * Added removal of non-alphabetic leading characters
 * Added some comments to explain the sanitization as it unfolds
 
If, after all the cleansing, no username remains (ie. it was all digits), start with a base of "geni1" and deconflict as usual.


_Trac comment by tmitchel (github user: tcmitchell) on 09-14-2012 at 16:10_
