### ISSUE TITLE
Slice page Jacks prototype

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1126]
The goal is to prototype out a slice page that uses Jacks to display the known resources and to provide basic workflow functionality.

 _Imported from trac ticket [#1126](http://trac.gpolab.bbn.com/proto-ch/ticket/1126),  created by kdownie on 07-30-2014 at 10:37, last modified: 09-30-2014 at 14:18_

**Comment by ahelsing** [comment]
This branch exists on the repository under the branch: tkt1126-jacks-app-prototype

Below are some descriptions for what will eventually need to change with this Jacks implementation.


_Trac comment by kdownie on 08-08-2014 at 12:30_

**Comment by ahelsing** [comment]
Changes dependent on Jacks:

First and most important is Jacks supporting the ability to provide multiple manifests into the same instance Jacks and have it draw with multiple topologies. Once Jacks supports this, the change in the Portal code I have provided will be trivial. All that needs to change is line 85 of jacks-app.js. On this line, it currently triggers 'change-topology', but it will need to instead trigger the command for adding to the current topology once it is supported.

Second is how to handle the information about each node that Jacks passes out when a node is clicked on, or multiple nodes have been selected. Unfortunately, it has hard to figure out a good way to make a skeleton for this part since what Jacks passes back could be done in many different ways, so I believe that it will be easiest if I make something once Jacks is closer to supporting this. Once it is ready, the code will be dropped onto what is currently like 56.

Third is how the Portal page will highlight nodes/sites that have had status returned as ready. My initial implementation had a pretty hack-ey method of doing this, and was done as a way to show that the embedding page could modify what Jacks does. This was fine for the demo, but with Jack potentially changing how it is constructing the HTML classes it would be best if Jacks supports this internally. Luckily, this path will be easier to implement for the Portal, and the Portal will only have to trigger an event with the node information (More information on how to use this will be given in the Jacks Documentation when the feature is ready).

_Trac comment by kdownie on 08-08-2014 at 12:30_

**Comment by MarshallBrinn** [comment]
Merging into develop with jacks functionality hidden or labeled beta. Keeping this open to capture results of testing. Goal to push this to master on Oct 1 install.

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-25-2014 at 16:41_

**Comment by MarshallBrinn** [comment]
We have added 'beta' pages to the portal and buttons that allow access to these pages from standard pages:
 * slice.php => slice-jacks.php
 * slice-add-resources.php=> slice-add-resources-jacks.php

These pages embed jacks viewer and editor into the page to graphically show (or act on)  or allow for creating topologies. 
Additionally, have added/corrected support for RSpec parsing to support determining if an rspec is partially bound. Note: we only handle completely bound or completely unbound rspecs. A partially bound rspec must be bound through Jacks.

We are closing this ticket at this point as the basic functionality has been deployed. Any new features to add or bugs to fix on these pages (or merging these pages into the non-beta pages) should be handled through new tickets.

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-30-2014 at 14:18_
