### ISSUE TITLE
View RSpecs using Jacks viewer

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1127]
When selecting an RSpec to view in the RSpec management page, the RSpec should be displayed in a Jacks viewer container instead of showing the raw XML. (Or show both.)

 _Imported from trac ticket [#1127](http://trac.gpolab.bbn.com/proto-ch/ticket/1127),  created by bujcich on 07-30-2014 at 10:48, last modified: 08-08-2014 at 10:59_

**Comment by innnkkki** [comment]
I would say show both because there will always be rspec attributes that will not be understood by Jacks. 

_Trac comment by nriga (github user: innnkkki) on 07-30-2014 at 15:49_

**Comment by ahelsing** [comment]
Agreed. My current implementation of the viewer container has a button within it that links to view the raw RSpec as well as download it.

_Trac comment by bujcich on 07-30-2014 at 16:05_

**Comment by ahelsing** [comment]
Fixed and merged to develop.

_Trac comment by bujcich on 08-08-2014 at 10:59_
