### ISSUE TITLE
Make sure slice names obey AM API rules

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#113]
Users pick slice names. But the AM API has rules.
Ensure we obey.
http://groups.geni.net/geni/wiki/GeniApiIdentifiers#Name

In particular:
Slice names are <=19 characters, only alphanumeric plus hyphen (no hyphen in first character): '^[a-zA-Z0-9][-a-zA-Z0-9]\{0,18\}$'

 _Imported from trac ticket [#113](http://trac.gpolab.bbn.com/proto-ch/ticket/113),  created by ahelsing on 06-07-2012 at 12:49, last modified: 09-05-2012 at 11:50_

**Comment by MarshallBrinn** [comment]
Fixed in createslice.php

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-05-2012 at 11:20_

**Comment by ahelsing** [comment]
This fix is in the portal.
We need the same fix in the SA.


_Trac comment by ahelsing on 09-05-2012 at 11:34_

**Comment by MarshallBrinn** [comment]
Factored out is_valid_slice_name and called from both portal and sa_controller

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-05-2012 at 11:50_
