### ISSUE TITLE
Distinguish between 'Finished' and 'Failed' on results page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1134]
On the results page, the 'Finished' status displays when:
 1. resources were added, and a manifest RSpec was returned with results from the aggregate that the user specified (what we would probably consider 'Success')
 1. no resources were added with a bound RSpec that was bound to a different AM than the AM specified by the user in the request (returns nothing and the user doesn't get any results, but does this really 'succeed'?)
 1. no resources were added, _and the AM generated the error'' (via the JSON string in stdout) rather than the tool

The 'Failed' status displays when:
 1. no resources were added, ''and omni/stitcher generated the error_ (via a raised exception with contents written to stderr)

Separately, the 'Running' status may display (incorrectly) when:
 1. an omni/stitcher process is killed, and no `stop` file is written

Determine if there's a way to refactor the logic of what determines if a process finishes/fails/succeeds/is killed. How should these be defined? Is there a definitive way to define a 'successful' request?

 _Imported from trac ticket [#1134](http://trac.gpolab.bbn.com/proto-ch/ticket/1134),  created by bujcich on 07-31-2014 at 16:49, last modified: 08-07-2014 at 11:17_

**Comment by ahelsing** [comment]
'Finished' should be changed to 'Completed' or 'Done - See Status Below' for consistency with what other tools use to describe this state.

_Trac comment by bujcich on 08-07-2014 at 11:17_

**Comment by ahelsing** [comment]
'Finished' will display if nothing was written to stderr. Apparently that includes a failed reservation at ExoGENI that gets an NDL converter error: http://grab.by/HDPa

**Comment by MarshallBrinn** [comment]
This has been fixed by adding a check into get_omni_inovcation_data.php to look at the omni result for "rror from Aggregate" to find errors that omni doesn't catch.
