### ISSUE TITLE
Redesign the home page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1146]
Redesign the home page.
Google Analytics shows many users Go to Home then Slices then the slice page.
Maybe they don't see the list of slices cause of the big map?

 - Shrink or move the map?
 - Make the Projects and Slices pages be tabs on the home page (so 1 fewer page load)?

 _Imported from trac ticket [#1146](http://trac.gpolab.bbn.com/proto-ch/ticket/1146),  created by ahelsing on 08-08-2014 at 16:50, last modified: 03-31-2015 at 10:21_

**Comment by tcmitchell** [comment]
This is complete.
