### ISSUE TITLE
Buttons on per slice rows should act on This Slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1147]
The buttons to Renew, Delete, Details, Status for the slice in a row are hitting every aggregate. Can we make those buttons work only on AMs in This Slice?

 _Imported from trac ticket [#1147](http://trac.gpolab.bbn.com/proto-ch/ticket/1147),  created by ahelsing on 08-08-2014 at 16:51, last modified: 09-17-2014 at 16:06_

**Comment by tcmitchell** [comment]
The tool-slice buttons that appear on the home, project, and slices pages now check for sliver info. If sliver info is present, the process continues with the known aggregates based on the sliver info. If no sliver info is present for the slice, a pop-up informs the user and they stay on the same page.

_Trac comment by tmitchel (github user: tcmitchell) on 09-17-2014 at 16:06_
