### ISSUE TITLE
Group and Filter Aggregates by Status and Provenance

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1150]
Request from Mark, reflecting conversations with Chip and Heidi.

Group all the aggregates in the portal into three categories:
 * Production
 * Development
 * Federated Third-Party

Then on the profile page, indicate which of these you want to see (default: production only).

Then on the slice page we can see ALL the aggregates, but those not selected are greyed out. 

That is, remove these categories from the "Select Only" pull-down from the slice page.

Not sure what should go there. Perhaps only 'This Slice' and 'All' and perhaps 'Stitchable'?

 

 _Imported from trac ticket [#1150](http://trac.gpolab.bbn.com/proto-ch/ticket/1150),  created by mbrinn on 08-12-2014 at 13:29, last modified: 12-03-2014 at 12:55_

**Comment by ahelsing** [comment]
We have a new plan, making this plan OBE.

_Trac comment by ahelsing on 12-03-2014 at 12:55_
