### ISSUE TITLE
Integrate omni/gcf 2.7

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1163]
_Imported from trac ticket [#1163](http://trac.gpolab.bbn.com/proto-ch/ticket/1163),  created by tmitchel on 09-17-2014 at 10:17, last modified: 09-19-2014 at 13:39_

**Comment by ahelsing** [comment]
No changes needed in CHAPI or proto-ch (so far).

I've started a release ticket with instructions for updating omni. Note those instructions assume a tarball is already on nye.

cascade has already been updated.


_Trac comment by ahelsing on 09-17-2014 at 13:15_

**Comment by ahelsing** [comment]
must change amclient to include `useslicemembers=False` in the omni_config

_Trac comment by ahelsing on 09-19-2014 at 13:39_
