### ISSUE TITLE
bug report attachments are inline in Apple Mail

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1169]
In Apple Mail, the zip file attachment to bug reports comes through inline. It works in Thunderbird.

 - The message is missing a final boundary separator with trailing two hyphens, as in:
```
--PHP-mixed-37e293eae30434a7622c73fd3b51ff86--

```
 - Perhaps in the initial header the name of the boundary should not be quoted?
 - See EG http://en.wikipedia.org/wiki/MIME#Multipart_messages

 _Imported from trac ticket [#1169](http://trac.gpolab.bbn.com/proto-ch/ticket/1169),  created by ahelsing on 09-18-2014 at 15:27, last modified: 09-22-2014 at 14:24_

**Comment by ahelsing** [comment]
My attempts so far are in branch tkt1169-bugreport on origin.

_Trac comment by ahelsing on 09-18-2014 at 15:35_

**Comment by ahelsing** [comment]
Sarah reports she also gets the raytheon complaint about a zip file - presumably when she sees her own message coming from geni-users@googlegroups

_Trac comment by ahelsing on 09-19-2014 at 09:18_

**Comment by ahelsing** [comment]
On the zip file, Niky says:
```
  1. live with this and we have to email raytheon to release the emails to us
  2. if the files in the zip are not too many just attach the files
  3. upload the zip file somewhere in the portal and send an email with a url, this might make
some sense but we might need to come up with policies about when to delete these files.
```


_Trac comment by ahelsing on 09-22-2014 at 08:42_

**Comment by seledwards** [comment]
Replying to [ahelsing](comment:2):
> Sarah reports she also gets the raytheon complaint about a zip file - presumably when she sees her own message coming from geni-users@googlegroups

I didn't send this message to geni-users@. I sent it directly to myself.

_Trac comment by sedwards (github user: seledwards) on 09-22-2014 at 09:20_

**Comment by ahelsing** [comment]
Ah. My mistake. It works going to my geni.net address, but not to my bbn.com address. It's possible this is a way around the issue. But I suspect that in general non BBN controlled mailing lists (maybe even those) will go via Raytheon and have this problem.
And as I recalled, Raytheon doesn't provide a way to retrieve these .zip files.

As a side note, mail to portal-help@geni.net somehow auto fixed the PHP boundaries so the attachment came through as an attachment correctly.

Mail going direct has headers like this:
```
Content-type: multipart/mixed;boundary="PHP-mixed-5d12bed35b47130c2dadabcf2fbfa949"
```

Where going through the mailing list it is:
```
Content-type: multipart/mixed;
	boundary="PHP-mixed-dfdf386b957accbb97cfdb17888bc3d3"
```

More interestingly, the direct mail ends:
```
AAAJHgAAAAA=

    


```

Where that via the mailing list ends:
```
AAAJHgAAAAA=

    


--PHP-mixed-dfdf386b957accbb97cfdb17888bc3d3--


```


_Trac comment by ahelsing on 09-22-2014 at 09:40_

**Comment by ahelsing** [comment]
For the Raytheon zip issue: one alternative would be to make the .zip files public but not indexed. EG. Available at https://portal.geni.net/error-reports.php?zip-file-name.zip

For that matter, we wouldn't need to change the email - it could continue to contain the .zip. We could just _also_ post it here.


_Trac comment by ahelsing on 09-22-2014 at 09:44_

**Comment by ahelsing** [comment]
experimenter support consensus appears to be to not rename the .zip but investigate posting the zip files for later download

_Trac comment by ahelsing on 09-22-2014 at 10:07_

**Comment by ahelsing** [comment]
Niky sent a test message to geni-users. Mail headers there seem broken:
```
Content-Type: text/plain; charset=ISO-8859-1
...
```


_Trac comment by ahelsing on 09-22-2014 at 10:42_

**Comment by ahelsing** [comment]
If I go to the google site and look at the original for the message
https://groups.google.com/forum/#original/geni-users/tqq8muG7yps/mp-NBlMG188J

the headers are:
```
Content-type: multipart/mixed;boundary="PHP-mixed-1dae41e9638c57dd15e43ff40acae026"
```

(and the closing boundary tag is missing).

Other messages (with the closing boundary tag) show up correctly on the website.

So:
 - who changed the headers?
 - Did the headers get changed because the multipart / boundary thing was broken?

_Trac comment by ahelsing on 09-22-2014 at 10:48_

**Comment by ahelsing** [comment]
Spacing fixes the attachment processing.

Niky says .tar.gz gets past Raytheon just fine.

Renaming the file gets it past Raytheon, but then mail readers (at least Thunderbird) don't know what to do with it - they don't rely on the mime type in the message.

Mail from gpolab to geni.net doesn't go through Raytheon. After portal transition, that own't be true.
Mail to a mailing list outside BBN with an archive (like geni-users) is OK cause we can read archives.

Google blocks .tgz files (or at least, those with type of application/zip). See http://support.google.com/mail/bin/answer.py?answer=6590



_Trac comment by ahelsing on 09-22-2014 at 14:19_

**Comment by ahelsing** [comment]
Move the .zip issue to ticket #1117

_Trac comment by ahelsing on 09-22-2014 at 14:24_
