### ISSUE TITLE
sliverdelete print error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#117]
When deleting slivers, we get an error in the logs. I believe $fail or $success is a list in sliverdelete.php

```

[Thu Jun 07 16:02:59 2012] [error] [client 128.89.255.182] DeleteSliver output = Array, referer: https://illyrica.gpolab.bbn.com/secure/confirm-sliverdelete.php?slice_id=04923297-d0d6-47d0-aace-0a332d96fdb2
[Thu Jun 07 16:02:59 2012] [error] [client 128.89.255.182] PHP Warning:  explode() expects parameter 2 to be string, array given in /var/www/secure/print-text-helpers.php on line 30, referer: https://illyrica.gpolab.bbn.com/secure/confirm-sliverdelete.php?slice_id=04923297-d0d6-47d0-aace-0a332d96fdb2
```

 _Imported from trac ticket [#117](http://trac.gpolab.bbn.com/proto-ch/ticket/117),  created by ahelsing on 06-07-2012 at 16:30, last modified: 06-08-2012 at 14:12_

**Comment by tcmitchell** [comment]
Fixed,

`print_list()` was calling `explode()` but never using the value.  That call has been eliminated.

_Trac comment by tmitchel (github user: tcmitchell) on 06-08-2012 at 14:12_
