### ISSUE TITLE
Protect saverspectoserver

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1177]
The script saverspectoserver should protect itself
 - Only valid users
 - Log the user and file name
 - Can we filter the contents of the file?
  * For starters, ensure that it parses as XML
 - ~~chmod the file to make sure it is not executable?~~
  * This is handled by [tempnam()](http://php.net/manual/en/function.tempnam.php) automatically

 _Imported from trac ticket [#1177](http://trac.gpolab.bbn.com/proto-ch/ticket/1177),  created by ahelsing on 09-26-2014 at 11:30, last modified: 09-29-2014 at 13:05_

**Comment by tcmitchell** [comment]
Added error checking, data validation, and logging to upload page. Added sanity check(s) on file path on download page. Added error dialog on web page if an upload error occurs.

_Trac comment by tmitchel (github user: tcmitchell) on 09-29-2014 at 13:05_
