### ISSUE TITLE
Invalid RSpec in Jacks editor with Safari

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1186]
When using Safari the Jacks editor (on the slice add resources page) always shows "This RSpec is invalid: Not well-formed (invalid token) at line 1, column 1" when creating a topology in the Jacks editor.

 _Imported from trac ticket [#1186](http://trac.gpolab.bbn.com/proto-ch/ticket/1186),  created by ahelsing on 10-01-2014 at 13:50, last modified: 02-18-2015 at 10:53_

**Comment by tcmitchell** [comment]
As of today the Jacks viewer (on the slice page) no longer gets stuck in "Starting Jacks...". Jacks now shows my topology, including highlighting the ready nodes.

_Trac comment by tmitchel (github user: tcmitchell) on 10-09-2014 at 10:59_

**Comment by ahelsing** [comment]
Still true using Jacks stable, Safari 7.1

_Trac comment by ahelsing on 12-03-2014 at 13:00_

**Comment by tcmitchell** [comment]
Still true using Jacks stable (version 2015-02-09-C).

_Trac comment by tmitchel (github user: tcmitchell) on 02-09-2015 at 13:18_

**Comment by tcmitchell** [comment]
This appears to be fixed with the current release.

_Trac comment by tmitchel (github user: tcmitchell) on 02-18-2015 at 10:52_
