### ISSUE TITLE
AM table broken on Slice Jacks

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1187]
On the Slice Jacks page, the old table by AMs is broken - some kind of javascript / css thing is wrong

 _Imported from trac ticket [#1187](http://trac.gpolab.bbn.com/proto-ch/ticket/1187),  created by ahelsing on 10-01-2014 at 13:51, last modified: 11-13-2014 at 16:27_

**Comment by MarshallBrinn** [comment]
The problem appears to have been typos in the CSS files. Once there's an error the rest of the file is ignored (silently). 

It is good to download "pip install csstools" and validate all CSS files from time to time.

The table looks the same as on the slice page now.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-13-2014 at 16:27_
