### ISSUE TITLE
Highlight selected nodes in Jacks

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1190]
Fix CSS / etc so we can highlight the selected node/link/site in Jacks

 _Imported from trac ticket [#1190](http://trac.gpolab.bbn.com/proto-ch/ticket/1190),  created by ahelsing on 10-01-2014 at 14:02, last modified: 11-12-2014 at 13:38_

**Comment by MarshallBrinn** [comment]
Fixed. Needed to add a CSS clause for 

#jacks-app .checkbox.selected {
  stroke-width: 5px;
}


_Trac comment by mbrinn (github user: MarshallBrinn) on 11-12-2014 at 13:38_
