### ISSUE TITLE
Add a 'clear' button in Jacks Add Resources

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1191]
Add a way to clear the pasted RSpec in the Jacks Add Resources page, and to clear the topology in Jacks

 _Imported from trac ticket [#1191](http://trac.gpolab.bbn.com/proto-ch/ticket/1191),  created by ahelsing on 10-01-2014 at 14:04, last modified: 12-02-2014 at 14:59_

**Comment by MarshallBrinn** [comment]
This is fixed as part of the adding the 'Delete All' button on the Jacks editor. It passes a 'topology-change' event which causes the associated buttons (especially the "reserve resources" button) to clear.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-18-2014 at 15:34_

**Comment by ahelsing** [comment]
Note that the download button remains active, but it downloads an empty RSpec. Note that the text in the TextBox remains there, similarly any selection in from the portal drop-down remains selected. But that is no longer the RSpec you are using.

_Trac comment by ahelsing on 12-02-2014 at 14:59_
