### ISSUE TITLE
jacks-editor-app.js hard codes a poor context

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1193]
The jacks-editor-app.js hard codes a default context that isn't great.
Specifically, it gives the link type for a stitched link as 'stitched', when it should be 'vlan'.

There are likely other issues.

Note that we shouldn't be using this default if at all possible.

 _Imported from trac ticket [#1193](http://trac.gpolab.bbn.com/proto-ch/ticket/1193),  created by ahelsing on 10-02-2014 at 13:39, last modified: 04-07-2015 at 10:32_

**Comment by tcmitchell** [comment]
I think this has been repaired. The JacksEditorApp constructor takes a context (`constraints`) as an argument. If the constraints are null, a default context (set of constraints) is used. That seems entirely appropriate. The portal passes the context from `/etc/geni-ch/jacks-context.json`.

Can this ticket be closed?


_Trac comment by tmitchel (github user: tcmitchell) on 02-16-2015 at 09:54_

**Comment by ahelsing** [comment]
The idea with this ticket was to fix that default context. Changes to do so are on the branch for ticket #1298.

_Trac comment by ahelsing on 02-16-2015 at 10:18_
