### ISSUE TITLE
Provide a simple Jacks context

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1194]
Build and upload a very simple Jacks context that allows experimenters to do just about anything legal, ideally while also not listing things no one is likely to pick.

We should always have a context and avoid using the default hard coded into jacks-editor-app.js

 _Imported from trac ticket [#1194](http://trac.gpolab.bbn.com/proto-ch/ticket/1194),  created by ahelsing on 10-02-2014 at 13:40, last modified: 10-08-2014 at 11:36_

**Comment by tcmitchell** [comment]
Added `etc/jacks-context.json`. This file requires manual install to `/etc/geni-ch/jacks-context.json` on the target host.

_Trac comment by tmitchel (github user: tcmitchell) on 10-08-2014 at 11:36_
