### ISSUE TITLE
Rename select from URL to load from URL

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1201]
On Jacks Add Resources, rename Select to Load for getting from a URL

 _Imported from trac ticket [#1201](http://trac.gpolab.bbn.com/proto-ch/ticket/1201),  created by ahelsing on 10-07-2014 at 09:02, last modified: 11-06-2014 at 08:21_

**Comment by tcmitchell** [comment]
Mission accomplished.

_Trac comment by tmitchel (github user: tcmitchell) on 11-06-2014 at 08:21_
