### ISSUE TITLE
Add View RSpec to Jacks Viewer, or equivalent on slice-jacks

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1202]
When viewing a manifest in the Jacks viewer, there is no way to see the raw manifest XML.

Add one.

This could be 'View RSpec' within Jacks, or a button in the Jacks App.

 _Imported from trac ticket [#1202](http://trac.gpolab.bbn.com/proto-ch/ticket/1202),  created by ahelsing on 10-07-2014 at 09:03, last modified: 11-14-2014 at 14:58_

**Comment by ahelsing** [comment]
Jon says:
```
show: {
  menu: true,
  rspec: true
}

And an rspec button along with the little 'menu' will appear. If you don't like the looks of that, you can create your own button that uses the 'show-rspec' event to toggle the display.
```


_Trac comment by ahelsing on 11-06-2014 at 10:33_

**Comment by MarshallBrinn** [comment]
JOn's instructions were right on. I added it to the viewer instantiated by the Jacks app and it looks and works fine.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-14-2014 at 14:58_
