### ISSUE TITLE
Name downloaded request rspec with slice name

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1204]
When downloading the request RSpec on Jacks Add Resources, the output files should be named <slice>_request_rspec.xml or similar
 - with the slice name
 - xml file extension

 _Imported from trac ticket [#1204](http://trac.gpolab.bbn.com/proto-ch/ticket/1204),  created by ahelsing on 10-07-2014 at 22:48, last modified: 01-09-2015 at 13:21_

**Comment by ahelsing** [comment]
I think the fix is somewhere in jacks-editor-app.js

_Trac comment by ahelsing on 12-04-2014 at 16:47_

**Comment by MarshallBrinn** [comment]
This was fix in #1205 (the allocation result page) but not here. I'll do this now.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-10-2014 at 10:32_

**Comment by MarshallBrinn** [comment]
Fixed and checked in on proto-ch branch tkt1204_download_slicename

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-10-2014 at 11:17_

**Comment by MarshallBrinn** [comment]
Merged into develop.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-09-2015 at 10:01_
