### ISSUE TITLE
Name request rspec in results page with slice name

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1205]
Name the request rspec that you can download from your allocation result page something like <slice>_request_rspec.xml
 - with slice name
 - xml extension
 - same name as on the Jacks Add Resources page when you download

 _Imported from trac ticket [#1205](http://trac.gpolab.bbn.com/proto-ch/ticket/1205),  created by ahelsing on 10-07-2014 at 22:49, last modified: 12-02-2014 at 10:55_

**Comment by MarshallBrinn** [comment]
Fixed for downloaded request and manifest rspecs.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-02-2014 at 10:55_
