### ISSUE TITLE
Update Jacks on sliceresources page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1216]
Update the Jacks window on sliceresources.php (page showing allocation log) to:

 * show sites
 * display the View RSpec button
 * show attributes of nodes when selected

See `updateJacks()` in sliceresource.js for the Jacks construction:
```
            if(data.code == 0 && data.obj) {
                thisInstance = new window.Jacks({
                  mode: 'viewer',
                  source: 'rspec',
                  size: { x: 756, y: 400},
                  show: {
                  	menu: true,
                  	rspec: true,
                  	version: true
                  },
                  nodeSelect: true,
		  multiSite: true,
                  root: '#jacksContainer',
                  readyCallback: function (input, output) {
                    input.trigger('change-topology',
                                  [{ rspec: data.obj }]);
                  }
                });
                $("jacksContainer").css("display", "block");
```

 _Imported from trac ticket [#1216](http://trac.gpolab.bbn.com/proto-ch/ticket/1216),  created by ahelsing on 10-22-2014 at 15:00, last modified: 11-10-2014 at 10:09_

**Comment by ahelsing** [comment]
Do something similar on the RSpec viewer off of the profile page

_Trac comment by ahelsing on 10-29-2014 at 09:32_

**Comment by ahelsing** [comment]
To get a View RSpecs  button, Jon says:

```
show: {
  menu: true,
  rspec: true
}

And an rspec button along with the little 'menu' will appear. If you don't like the looks of that, you can create your own button that uses the 'show-rspec' event to toggle the display.
```


_Trac comment by ahelsing on 11-06-2014 at 10:35_

**Comment by tcmitchell** [comment]
Updated.

Note that the View RSpec does not appear to work. It is likely a Jacks bug, since it is out of our control as the embedding page. Leave the View RSpec available to provide a good debug environment for the Jacks developers.

_Trac comment by tmitchel (github user: tcmitchell) on 11-06-2014 at 13:26_

**Comment by tcmitchell** [comment]
The RSpec display issue is a CSS problem. The text is displayed white-on-white, making it invisible.

Handing off to Marshall to work CSS magic.


_Trac comment by tmitchel (github user: tcmitchell) on 11-06-2014 at 13:39_

**Comment by tcmitchell** [comment]
Added the following to portal.css to show rspec in black text on white background:
```
.jacks #leftNav pre {
   color: black;
}
```

_Trac comment by tmitchel (github user: tcmitchell) on 11-10-2014 at 10:07_

**Comment by tcmitchell** [comment]
Done.

_Trac comment by tmitchel (github user: tcmitchell) on 11-10-2014 at 10:09_
