### ISSUE TITLE
Move radio buttons to left side of labels on jacks-add-resources

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1217]
In the jacks add resources page, the radio buttons should be on the left of the label (like File, URL, etc)

 _Imported from trac ticket [#1217](http://trac.gpolab.bbn.com/proto-ch/ticket/1217),  created by ahelsing on 10-22-2014 at 15:12, last modified: 11-06-2014 at 09:43_

**Comment by tcmitchell** [comment]
Moved radio buttons to left side of labels.

_Trac comment by tmitchel (github user: tcmitchell) on 11-06-2014 at 09:43_
