### ISSUE TITLE
Increase size of URL textbox

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1218]
On jacks add resources, increase the length of the URL textbox

 _Imported from trac ticket [#1218](http://trac.gpolab.bbn.com/proto-ch/ticket/1218),  created by ahelsing on 10-22-2014 at 15:13, last modified: 11-06-2014 at 09:09_

**Comment by tcmitchell** [comment]
Fixed syntax errors in slice-add-resources-jacks.css, then changed width to 500px.

_Trac comment by tmitchel (github user: tcmitchell) on 11-06-2014 at 09:09_
