### ISSUE TITLE
Error parsing login entries

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1225]
The RSpec parser assumes the logins are an array, which apparently is not always true.

Logs show:

  [Mon Nov 03 22:23:02 2014] [error] [client 72.207.240.178] am_client invoke_omni_function COMMAND = /usr/share/geni-ch/portal/gcf/src/stitcher_php.py -c /tmp/omni-invoke-rplata1-lQXAjD/omni_configuration.txt -l /tmp/omni-invoke-rplata1-lQXAjD/omni_logging_configuration.txt --logoutput /tmp/omni-invoke-rplata1-lQXAjD/omni_debug_log.txt --api-version 2 --GetVersionCacheName /tmp/omni-invoke-rplata1-lQXAjD/omniVersionCache --ForceUseAggNickCache --AggNickCacheName /tmp/omni-invoke-rplata1-lQXAjD/omniAggCache --fileDir /tmp/omni-invoke-rplata1-lQXAjD -a https://clemson-clemson-control-1.clemson.edu:5002 --slicecredfile /tmp/rplata1-cred-7BorH0 -t GENI 3 listresources urn:publicid:IDN+ch.geni.net:SG-GENI+slice+PGA, referer: https://portal.geni.net/secure/listresources.php?slice_id=766ee487-c915-421a-8397-e70ad8658c33&am_id[]=147&am_id[]=107&am_id[]=129

  ...

  [Mon Nov 03 22:23:09 2014] [error] [client 72.207.240.178] PHP Warning:  Invalid argument supplied for foreach() in /var/www/secure/print-text-helpers.php on line 223, referer: https://portal.geni.net/secure/listresources.php?slice_id=766ee487-c915-421a-8397-e70ad8658c33&am_id[]=147&am_id[]=107&am_id[]=129

  [Mon Nov 03 22:23:09 2014] [error] [client 72.207.240.178] PHP Warning:  Invalid argument supplied for foreach() in /var/www/secure/print-text-helpers.php on line 223, referer: https://portal.geni.net/secure/listresources.php?slice_id=766ee487-c915-421a-8397-e70ad8658c33&am_id[]=147&am_id[]=107&am_id[]=129

  [Mon Nov 03 22:23:09 2014] [error] [client 72.207.240.178] PHP Warning:  Invalid argument supplied for foreach() in /var/www/secure/print-text-helpers.php on line 223, referer: https://portal.geni.net/secure/listresources.php?slice_id=766ee487-c915-421a-8397-e70ad8658c33&am_id[]=147&am_id[]=107&am_id[]=129

 _Imported from trac ticket [#1225](http://trac.gpolab.bbn.com/proto-ch/ticket/1225),  created by ahelsing on 11-04-2014 at 10:51, last modified: 11-06-2014 at 11:45_

**Comment by tcmitchell** [comment]
Cannot reproduce this error. The loop in question is 18 months old, but this error has never been encountered before. The slice is gone, as are the relevant log files for the allocation, so we can't see the manifest. The user has an ssh key. We don't know what state the slice or slivers may have been in at the time.

_Trac comment by tmitchel (github user: tcmitchell) on 11-06-2014 at 11:45_
