### ISSUE TITLE
Jacks Add Resources uses stale RSPEC

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1226]
The reserve button of the jacks add resource page appears to take the version from the last 'modified-topology'  call and not the rspec currently held in Jacks. We should call fetch topology and grab the latest before proceeding with reserve.

 _Imported from trac ticket [#1226](http://trac.gpolab.bbn.com/proto-ch/ticket/1226),  created by mbrinn on 11-05-2014 at 09:22, last modified: 11-19-2014 at 14:50_

**Comment by MarshallBrinn** [comment]
Calling fetch-topology from reserve resources before calling validate submit. Works in this case and doesn't break the other (download, setting current rspec text) cases.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-12-2014 at 12:21_

**Comment by ahelsing** [comment]
Symptom: Bind site before making some other substantive change, and the downloaded RSpec is correct but the reserved RSpec is wrong. With the fix, both are the same.


_Trac comment by ahelsing on 11-19-2014 at 14:50_
