### ISSUE TITLE
Jacks displays incorrect site name

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1232]
To reproduce:
 1. Draw an rspec with Jacks (drag 1 "VM" onto the editor canvas)
 1. Save it unbound using the "Download" button
 1. Load the saved rspec on Jacks using the "File" radio button
 1. Bind the site to an InstaGENI rack aggregate
 1. Reserve resources
 1. Go to the slice page, and then slice jacks beta
 1. Note that the site displays a number, not a name

_Note: This appears to be a Jacks issue, not a portal issue_

 _Imported from trac ticket [#1232](http://trac.gpolab.bbn.com/proto-ch/ticket/1232),  created by tmitchel on 11-11-2014 at 14:31, last modified: 03-31-2015 at 10:22_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [site-manifest.xml](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1232/site-manifest.xml) on 11-11-2014 at 15:49_

**Comment by MarshallBrinn** [comment]
Just retested this today (12/2/2014) and the problem still exists. - Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-02-2014 at 10:25_

**Comment by ahelsing** [comment]
I get a # for the side ID as soon as I load the saved RSpec. But on the Slice Jacks page, it looks fine.


_Trac comment by ahelsing on 02-23-2015 at 10:58_

**Comment by ahelsing** [comment]
If I load a saved RSpec into the Jacks Add REsources page, the site ID is included in the RSpec passed to Jacks.

EG:
http://www.gpolab.bbn.com/experiment-support/HelloGENI/hellogeni.rspec

As a result, Jacks labels the site with this number.

When I then reserve with this RSpec, the request RSpec still includes a site ID - but a different number, even though the site is now bound. And the manifest includes the same site ID, and Jacks labels the site on the sliceresources page with a site ID.


_Trac comment by ahelsing on 02-24-2015 at 11:59_

**Comment by ahelsing** [comment]
Most if not all instances of Jacks displaying a # for the site label are now fixed. Hold this open to confirm.

_Trac comment by ahelsing on 03-04-2015 at 09:34_

**Comment by MarshallBrinn** [comment]
I tested this pretty broadly today and can no longer see instances of this. Closing.
