### ISSUE TITLE
Jacks on results page missing RSpec scrollbar

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1235]
The Jacks viewer on the results page (sliceresource.php) needs a scrollbar on the RSpec viewer.

 _Imported from trac ticket [#1235](http://trac.gpolab.bbn.com/proto-ch/ticket/1235),  created by ahelsing on 11-19-2014 at 15:21, last modified: 02-03-2015 at 12:56_

**Comment by MarshallBrinn** [comment]
Marking this as WONT_FIX: the jacks viewer on the slice resource.php page is going away with the combination of details and status (#1043).

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 15:24_

**Comment by ahelsing** [comment]
Wait, really?

The results page is the page that shows you your log messages. It is not either the status or details pages. Are we really removing the jacks instance from this page?

I thought that we would leave this Jacks instance alone.

_Trac comment by ahelsing on 01-19-2015 at 16:01_

**Comment by tcmitchell** [comment]
I'm reopening this one. I think the wrong ticket got closed. We can close it again if we're sure.

_Trac comment by tmitchel (github user: tcmitchell) on 01-19-2015 at 16:43_

**Comment by MarshallBrinn** [comment]
Yep, my bad. I took Jacks out of slice resources. Put it back in and enabled the CSS processing for the scrollbar.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-03-2015 at 12:56_
