### ISSUE TITLE
Jacks viewer on Details page should show 'menus' and sites

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1236]
The Jacks viewer on the Details page (listresources.php) does not allow showing node/site details by clicking on the nodes/sites. It also does not show the site labels.

 _Imported from trac ticket [#1236](http://trac.gpolab.bbn.com/proto-ch/ticket/1236),  created by ahelsing on 11-19-2014 at 15:22, last modified: 01-19-2015 at 15:21_

**Comment by MarshallBrinn** [comment]
Changing this to WONT_FIX: The jacks views on the details page are going away with the merging of status and details (#1043).

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 15:21_
