### ISSUE TITLE
Jacks viewer on Manage RSpecs should show menus, sites

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1237]
The Jacks viewer on the Manage RSpecs page should show menus (that is, allow clicking a node to see details) and sites (if it does not already).

 _Imported from trac ticket [#1237](http://trac.gpolab.bbn.com/proto-ch/ticket/1237),  created by ahelsing on 11-19-2014 at 15:26, last modified: 01-19-2015 at 15:39_

**Comment by ahelsing** [comment]
I think the change is this:
```
show: {
  menu: true,
  rspec: true
}
```

As shown here: http://trac.gpolab.bbn.com/proto-ch/ticket/1202#comment:2

_Trac comment by ahelsing on 12-04-2014 at 17:01_

**Comment by MarshallBrinn** [comment]
All fixed. What was required was not only the suggestion above but also 

```
nodeSelect: true
```



_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 15:39_
