### ISSUE TITLE
Change tab names on slice jacks

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1238]
Change the labels on the tabs on the Slice Jacks page. Something like 'Aggregate View' and 'Graphical View', with the Graphical (aka Jacks) view being first & default.

 _Imported from trac ticket [#1238](http://trac.gpolab.bbn.com/proto-ch/ticket/1238),  created by ahelsing on 11-19-2014 at 15:49, last modified: 12-01-2014 at 14:17_

**Comment by MarshallBrinn** [comment]
Fixed, tested and checked into develop.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-01-2014 at 14:17_
