### ISSUE TITLE
Add new aggregate categories

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1239]
Per experimenter support group, add "Experimental" and "Federated" aggregate categories to portal.

See http://trac.gpolab.bbn.com/chapi/ticket/342 for aggregates that will be in these categories in the service registry.

 _Imported from trac ticket [#1239](http://trac.gpolab.bbn.com/proto-ch/ticket/1239),  created by mbrinn on 11-24-2014 at 12:03, last modified: 01-20-2015 at 12:36_

**Comment by MarshallBrinn** [comment]
I have made the changes to slice.php, slice-jacks.php and slice-jacks1.php (whatever that is) and sr_constants.php. 

I have tested this and it works for PROD, EXP and FED aggregates.

Once we get the right lists from Experimental Support, we can edit populate_am_type_attribute.sql accordingly.



_Trac comment by mbrinn (github user: MarshallBrinn) on 11-24-2014 at 14:53_

**Comment by tcmitchell** [comment]
In addition to editing populate_am_type_attribute.sql we will need to update the data in `chapi/data/sr/aggdata.csv` and `chapi/data/sr/future-aggs.csv` to use the new categories.


_Trac comment by tmitchel (github user: tcmitchell) on 11-24-2014 at 15:28_

**Comment by tcmitchell** [comment]
A list of aggregates by category was received by email on December 5.

_Trac comment by tmitchel (github user: tcmitchell) on 12-08-2014 at 07:27_

**Comment by ahelsing** [comment]
Regina says add BBN-OG to this list (not BOS)


_Trac comment by ahelsing on 12-10-2014 at 13:27_

**Comment by ahelsing** [comment]
Niky says do not yet add NCSU.

Tom notes we probably must contact the federated aggregates to confirm their desire to be listed on our portal. Like say, PlanetLab.

_Trac comment by ahelsing on 12-16-2014 at 10:22_

**Comment by tcmitchell** [comment]
The addition of 'Experimental' and 'Federated' is on branch `tkt1239-categories`. It is on hold pending addition of aggregates that require those categories.

_Trac comment by tmitchel (github user: tcmitchell) on 01-08-2015 at 10:25_

**Comment by tcmitchell** [comment]
"Experimental" has been added as a category. "Federated" is on hold until a federated aggregate is ready to be added so that we don't have an empty category listed on the UI.

_Trac comment by tmitchel (github user: tcmitchell) on 01-09-2015 at 15:42_

**Comment by ahelsing** [comment]
When adding new aggregates, be sure each is in the Omni agg_nick_cache for omni users but also the version of this file installed on nye for the portal.

_Trac comment by ahelsing on 01-13-2015 at 16:24_

**Comment by ahelsing** [comment]
Max gave approval for adding NICTA as a federated aggregate.


_Trac comment by ahelsing on 01-15-2015 at 08:49_

**Comment by tcmitchell** [comment]
Added the Federated category to support the addition of Apt on http://trac.gpolab.bbn.com/chapi/ticket/343

That completes this ticket.


_Trac comment by tmitchel (github user: tcmitchell) on 01-20-2015 at 12:36_
