### ISSUE TITLE
Some aggregates appear as 0.0 on the map

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1240]
Mostly OpenFlow aggregates, but also ExoSM and a few others. 

 _Imported from trac ticket [#1240](http://trac.gpolab.bbn.com/proto-ch/ticket/1240),  created by mbrinn on 11-24-2014 at 12:05, last modified: 11-25-2014 at 08:30_

**Comment by MarshallBrinn** [comment]
I have a fix for this. There are essentially three cases where this happens:
1. OPENFLOW returns all the data paths but only puts lat/long info on the first one.
2. EXOGENI returns nodes of name 'orca-transit-net-vlan' which don't have a location (they're a vlan)
3. EXOGENI returns nodes of name 'unknown' (which are also some kind of vlan or transit).

I made the fix to avoid these three cases and voila, nothing appears at 0.0. But I'm not thrilled with this fix. It feels hackish. I wrote to Nick to ask him about the OF RSpecs. But I think that EG is returning correct stuff (VLAN's don't have locations, and perhaps are legitimately nodes).

Let's talk about this and decide whether to push it.

- Marshall


_Trac comment by mbrinn (github user: MarshallBrinn) on 11-24-2014 at 14:25_

**Comment by ahelsing** [comment]
We should be setting the location per-DPID in the case of OpenFlow advertisements.  If there are any specific ones which are incorrect at this time, please let me know and I will work on fixing them.

_Trac comment by tupty on 11-24-2014 at 14:57_

**Comment by MarshallBrinn** [comment]
I put in a more general (and principled) fix. Nodes that have no lat/long don't get displayed. No special casing. If there is a problem with the ad RSPEC (and it SHOULD have a lat/long) we print error messages to the log. But there's nothing the parsing code should do to construct a lat/long out of thin air. Tested, installed on cascade and pushed to develop.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-25-2014 at 08:30_
