### ISSUE TITLE
Portal crashes looking for GENI_PENDING in get_sliver_status

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1243]
When reading status from GRAM resources, we get

 PHP Fatal error:  Undefined class constant 'GENI_PENDING' in /var/www/secure/amstatus.php on line 72

It is strange because it appears to be defined. But this variable $GENI_MESSAGES_REV is already defined in status constants.php and shouldn't be overridden.

When we remove the copy and use the original, the problem goes away and GRAM resources "turn green".

 _Imported from trac ticket [#1243](http://trac.gpolab.bbn.com/proto-ch/ticket/1243),  created by mbrinn on 12-02-2014 at 10:19, last modified: 12-02-2014 at 11:27_

**Comment by MarshallBrinn** [comment]
Fixed and tested.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-02-2014 at 10:19_

**Comment by ahelsing** [comment]
test by reserving a node at a GRAM AM

_Trac comment by ahelsing on 12-02-2014 at 11:27_
