### ISSUE TITLE
Slice Jacks re-fetches manifest and status after doing delete

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1244]
Reserve resources at InstaGENI.
Wait on the Slice Jacks page for the resource to be ready and change to green.
Hit Delete (without anything in particular selected).

Jacks logs show:
 - Deleting resources at ...
 - Resources Deleted
 - Gathering manifest (and the old resources are shown)
 - Polling resource status
 - After a very long time, we see:
 - Gathering manifest
 - No resources found (and the jacks pane is empty)

 _Imported from trac ticket [#1244](http://trac.gpolab.bbn.com/proto-ch/ticket/1244),  created by ahelsing on 12-02-2014 at 15:32, last modified: 02-24-2015 at 12:28_

**Comment by MarshallBrinn** [comment]
Not sure what the problem here is. It takes a long time because IG takes a long time to delete and reflect this in the manifests. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-03-2014 at 08:11_

**Comment by ahelsing** [comment]
I can't reproduce any problem either.

_Trac comment by ahelsing on 02-24-2015 at 12:28_
