### ISSUE TITLE
Missing scrollbar on View RSpec pane in jacks

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1248]
On the slice jacks page, hit View RSpec. There is no scroll bar.

Also on the slice-resources page where it shows results (Ben's page).

 _Imported from trac ticket [#1248](http://trac.gpolab.bbn.com/proto-ch/ticket/1248),  created by ahelsing on 12-03-2014 at 10:49, last modified: 01-19-2015 at 15:13_

**Comment by MarshallBrinn** [comment]
This has been fixed since the merges for making the jacks windows expandable. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 15:13_
