### ISSUE TITLE
Prettify all rspecs shown in the portal

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1252]
Independent of the format of the rspecs (requests, manifests) that the portal has 
when displayed to the user it should be prettified. Example of malformed rspec:

http://grab.by/CMl6

 _Imported from trac ticket [#1252](http://trac.gpolab.bbn.com/proto-ch/ticket/1252),  created by nriga on 12-04-2014 at 11:42, last modified: 02-23-2015 at 16:20_

**Comment by ahelsing** [comment]
See #1290

_Trac comment by ahelsing on 02-04-2015 at 15:56_

**Comment by ahelsing** [comment]
RSpecs look OK on the details page. But on sliceresources.php (where you first see your reservation and the manifest), the RSpec looks ugly.

View RSpec from within Jacks looks OK.


_Trac comment by ahelsing on 02-23-2015 at 11:12_

**Comment by ahelsing** [comment]
Also the request rspec on sliceresources.php

Fix is likely in get_omni_invocation_data.php: make_pretty_code()

print-text-helpers just does this:
```
	  $xml = str_replace(">", ">\n", $xml);
```

If we want to be clever, do that only where it is not `>\n` already.


_Trac comment by ahelsing on 02-23-2015 at 11:54_

**Comment by ahelsing** [comment]
Using DOMDocument to parse the XML, suppressing errors. If there are errors, fall back on inserting newlines.

_Trac comment by ahelsing on 02-23-2015 at 16:20_
