### ISSUE TITLE
Removing install/execute scripts from Jacks doesn't modify the RSPec

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1254]
If I do the following:
      1. Load an RSpec from a URL (I did: http://www.gpolab.bbn.com/experiment-support/HelloGENI/hellogeni.rspec)
      2. Edit the RSpec (I removed the install and execute scripts from both nodes using the Remove button)
      3. View, Download, or Reserve the RSpec

The resulting RSpec includes the install and execute scripts even though they are deleted in the GUI.

 _Imported from trac ticket [#1254](http://trac.gpolab.bbn.com/proto-ch/ticket/1254),  created by sedwards on 12-05-2014 at 15:01, last modified: 02-24-2015 at 11:55_
   CCing: gpo-expt-support@...

**Comment by tcmitchell** [comment]
This must be fixed before Jacks comes out of beta.

_Trac comment by tmitchel (github user: tcmitchell) on 12-05-2014 at 15:28_

**Comment by ahelsing** [comment]
The given test case now seems to work. I do note the resulting RSpec has an empty services tag, but this doesn't seem to cause any problems.

_Trac comment by ahelsing on 02-24-2015 at 11:55_
