### ISSUE TITLE
Jacks devel not showing topology when RSpec is loaded

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1255]
When using Jacks with source=devel, loading a saved RSpec fails with nothing on the console.

Original bug report:
Recently, I started using Jacks to build a topology for a stitched testing slice I am creating between two sites.  Prior to the last portal upgrade, I was able to load my RSpec, view the topology, modify the topology, and download the RSpec again.

Now, I am unable to view my topology when I upload any RSpec.  I have tried this with stitched topologies when I upload an RSpec, but even if I select an RSpec with a single VM from the portal, that does not show up.  I am not 100% sure that this stopped working when the portal upgrade happened, but the timing seems to line up.

If I upload the same RSpec to https://www.emulab.net/protogeni/jacks-stable/editor.html, then the topology is drawn.

More details to come...

 _Imported from trac ticket [#1255](http://trac.gpolab.bbn.com/proto-ch/ticket/1255),  created by tupty on 12-08-2014 at 14:11, last modified: 02-06-2015 at 20:10_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
_tupty attached [gpo-ig-ukypks2-ig.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1255/gpo-ig-ukypks2-ig.rspec) on 12-09-2014 at 10:52_

**Comment by ahelsing** [comment]
_tupty attached [bbn-ig-utah-pg.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1255/bbn-ig-utah-pg.rspec) on 12-09-2014 at 10:51_

**Comment by ahelsing** [comment]
I am running Ubuntu 14.04.

I have tried this with both Chrome and Firefox, and I see the same results in both browsers (works with emulab.net jacks editor, but doesn't work with portal.geni.net jacks editor).
 * Current Chrome version: 39.0.2171.71
 * Current FF version: 34.0 for Ubuntu

I am not sure of what else may have changed recently other than running my daily software updates on my laptop.

If I am the only one experiencing this issue, I can work around it for now by using the editor embedded at emulab.net.

_Trac comment by tupty on 12-08-2014 at 14:15_

**Comment by ahelsing** [comment]
I also wanted to mention that if a slice exists, the jacks viewer does render a topology.  The editor, however, doesn't.

_Trac comment by tupty on 12-09-2014 at 10:53_

**Comment by MarshallBrinn** [comment]
This seems to be a problem with this particular OS (note that it does the same for him on Chrome and Ubuntu). Sarah and I can't reproduce it on other OS's (for same browser). 

We'll need to find a copy of a machine running Tim's OS to reproduce and fix this.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-09-2014 at 13:48_

**Comment by ahelsing** [comment]
Seems to work in an Ubu 10 VM on Firefox

I do see this in the console though:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create main.js:5
NS_ERROR_FAILURE:  main.js:8
```


_Trac comment by ahelsing on 12-09-2014 at 14:18_

**Comment by ahelsing** [comment]
I just sat down with Peter and reproduced my issue on an Ubuntu 14.04 VM with firefox 34.0, a Windows system with firefox 34.0, and a Mac with firefox 34.5.

Each time, I logged in with my account, I used the same slice (jackstest under the tuptyexplore project), and the same RSpec (the ukypks2 rspec that is attached here).  I can reproduce the issue every time across each system.

Perhaps the issue is specific to my RSpecs, my slice, my project, or my process for getting to the Jacks editor in the portal?  It might be worthwhile for me to see how other people access jacks and get this to work for them.

_Trac comment by tupty on 12-09-2014 at 14:29_

**Comment by ahelsing** [comment]
Using a just updated Ubu14.04 VM and FF 34.0, I can load Tim's RSpecs as attached and see them on the Jacks Add Resources page. No new error messages on the console.
I did:
 - click on a slice
 - click Add Resources
 - click Add Resources with Jacks
 - select File from the chooser under the jacks instance
 - browse for the file and click OK

Works for both Tim's RSpecs.

Is there anything in the FF web console?

_Trac comment by ahelsing on 12-09-2014 at 14:34_

**Comment by ahelsing** [comment]
Also works for me on Mac (10.9.5) with FF 33.0.3

Also seems to work for me on FF 34.0.5


_Trac comment by ahelsing on 12-09-2014 at 14:40_

**Comment by ahelsing** [comment]
The process you outlined works for me too, when I use the same slice/project/rspec.  So the issue must be hitting me due to the process I was following.  Here is what I was doing:
 * click on a slice
 * click on "Slice Jacks (beta)"
 * click on "Add Resources" in the Jacks viewer frame
 * select File from the chooser under the hacks instance
 * browse for the file and click OK

Can you try that process and see if it works for you?


_Trac comment by tupty on 12-09-2014 at 14:40_

**Comment by ahelsing** [comment]
The key difference with that process is that the URL ends with "&source=devel", indicating that it is using the development version of Jacks.

Indeed, no saved RSpecs seem to appear when I use the development version of Jacks. This is a Jacks bug.

If you use this process to get to the Add Resources page, edit the url to take off the "&source=devel" portion of the URL, and things should work for you again.

Meantime, I'll report the bug to Jon Duerig.

_Trac comment by ahelsing on 12-09-2014 at 14:49_

**Comment by ahelsing** [comment]
I'm glad we got this figured out.  I still need to ask though, is there a specific reason why both the devel and production versions of jacks are available for portal users?  If so, does it make sense to make them both accessible in the same places (e.g. provide links to both, side by side)?

_Trac comment by tupty on 12-10-2014 at 11:28_

**Comment by ahelsing** [comment]
It's a bug that you could get to the devel version that will be fixed at the next release.

Well, you can always get to both releases by modifying the URL. But the button should not have taken you to the devel version.

_Trac comment by ahelsing on 12-10-2014 at 11:39_
