### ISSUE TITLE
Jacks sshes into wrong node when there are duplicate client_ids in a slice

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1257]
I had a slice where I had reserved the same rspec at two different aggregates (see attached screenshot).  This means that the client_ids were repeated (e.g. there are two "client" nodes).

I notice that when I tried to login to the "server" node at Cornell (orange background) using the SSH button, that it actually logged me into the "server" node at Kansas (blue background).  

The Jacks App should have provided the ssh URL for the "server" node at Cornell.

 _Imported from trac ticket [#1257](http://trac.gpolab.bbn.com/proto-ch/ticket/1257),  created by sedwards on 12-08-2014 at 17:47, last modified: 01-09-2015 at 13:12_
   CCing: duerig@...

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [Jacks.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1257/Jacks.png) on 12-08-2014 at 17:48_

**Comment by MarshallBrinn** [comment]
This is fixed on branch tkt1257_ssh_node. I do notice that there are several places in jacks-app that assumes that client_id are unique, though and will open a separate ticket for these.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-09-2014 at 13:45_
