### ISSUE TITLE
Renew slivers when you renew slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#126]
When you renew your slice, the portal could auto renew your slivers. Maybe you don't always want that?

 _Imported from trac ticket [#126](http://trac.gpolab.bbn.com/proto-ch/ticket/126),  created by ahelsing on 06-07-2012 at 16:44, last modified: 06-11-2013 at 19:51_

**Comment by ahelsing** [comment]
If you're taking comments from the peanut gallery: I think you may not always want that, and a nice interface would be to list your slivers, and let you check the ones you want to renew, plus an "all" checkbox. (Which could be checked by default, if we think "renew everything" is actually the most common case, which maybe it is.)

_Trac comment by jbs on 06-07-2012 at 16:47_

**Comment by ahelsing** [comment]
another suggestions was a 3rd button to let you renew all slivers if you want

_Trac comment by ahelsing on 10-02-2012 at 16:25_

**Comment by seledwards** [comment]
This is covered by #603.

_Trac comment by sedwards (github user: seledwards) on 06-11-2013 at 19:51_
