### ISSUE TITLE
Move or duplicate Wimax button

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1262]
Niky says the Wimax button is hidden at the bottom of the home page. Particularly for her during a GEC when she has a lot of slices on her home page, it is hard to fine.
 - Move tools to above slices & projects on the home page?
 - Replicate the Wimax button to the tools section of the Profile page?

 _Imported from trac ticket [#1262](http://trac.gpolab.bbn.com/proto-ch/ticket/1262),  created by ahelsing on 01-08-2015 at 08:29, last modified: 03-31-2015 at 10:23_

**Comment by MarshallBrinn** [comment]
Note: The new Dashboard will cover moving the Wimax button

**Comment by tcmitchell** [comment]
Complete in new portal UI
