### ISSUE TITLE
Add access to CloudLab from GENI Portal

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1263]
Make CloudLab available to Geni PORTAL users from the Portal.

Rob says for now to use this destination for the button:

    https://www.cloudlab.us/login.php

Rob lists two possible icons for the button, depending on our desires (i.e. square vs. rectangular):

 * http://cloudlab.us/img/cloudlab-flask.png (small & squarish)
 *  http://www.cloudlab.us/img/cloudlab-big.png (more rectangular)

 _Imported from trac ticket [#1263](http://trac.gpolab.bbn.com/proto-ch/ticket/1263),  created by mbrinn on 01-09-2015 at 07:00, last modified: 01-20-2015 at 13:30_

**Comment by ahelsing** [comment]
This should go in the tools section on the home page.

An alternative (larger/rectangular) logo would be: http://www.cloudlab.us/img/cloudlab-big.png

_Trac comment by ahelsing on 01-15-2015 at 13:30_

**Comment by MarshallBrinn** [comment]
Added to portal home-active.php. If we want to push the tool bar higher to the top of the home page, we should open another ticket.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 14:51_
