### ISSUE TITLE
Remove warning if affiliation is not present

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1269]
Remove the warning in do-register if affiliation is not present from the identity provider. This field is optional.

Determine the appropriate value to be stored in the identity table if affiliation is not present. Currently the value is an empty string, which may be fine. NULL might also be appropriate depending on the table definition.

 _Imported from trac ticket [#1269](http://trac.gpolab.bbn.com/proto-ch/ticket/1269),  created by tmitchel on 01-14-2015 at 12:27, last modified: 01-19-2015 at 15:17_

**Comment by MarshallBrinn** [comment]
The warning is removed. A "" entry in the affiliation table in this case seems to be fine.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-19-2015 at 15:17_
