### ISSUE TITLE
Slice page for non project lead is broken

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#127]
Due to user->privSlice I think, many things on the slice page look broken for a normal user (not a project lead)

 _Imported from trac ticket [#127](http://trac.gpolab.bbn.com/proto-ch/ticket/127),  created by ahelsing on 06-07-2012 at 16:45, last modified: 06-11-2012 at 14:26_

**Comment by MarshallBrinn** [comment]
I think this is fixed. I replaced the call to privSlice and the behavior (what is disabled, what is available) seems to be reasonable.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-11-2012 at 14:26_
