### ISSUE TITLE
GEO View only shows half on first display

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1272]
When the geo view shows up on slice-jacks.php, only the left half of the pane is filled. Once the page is refreshed, the full map is shown and marked properly with resources.

 _Imported from trac ticket [#1272](http://trac.gpolab.bbn.com/proto-ch/ticket/1272),  created by mbrinn on 01-22-2015 at 13:05, last modified: 03-31-2015 at 10:23_

**Comment by tcmitchell** [comment]
Fixed by #1428
