### ISSUE TITLE
Error check filenames to upload-file

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1279]
Recent logs show:
```
[Thu Jan 29 03:04:19 2015] [error] [client 184.66.142.128] PHP Warning:  file_get_contents(10.10.1.100): failed to open stream: No such file or directory in /var/www/secure/upload-file.php on line 27, referer: https://portal.geni.net/secure/slice-add-resources-jacks.php?slice_id=46e24f8c-28ed-4edd-9bb3-c5727d3d9ef3
[Thu Jan 29 03:04:28 2015] [error] [client 184.66.142.128] PHP Warning:  file_get_contents(): Filename cannot be empty in /var/www/secure/upload-file.php on line 27, referer: https://portal.geni.net/secure/slice-add-resources-jacks.php?slice_id=46e24f8c-28ed-4edd-9bb3-c5727d3d9ef3
```

The script should error check what filenames it will accept:
 - trim first
 - forbid bad characters (those not allowed in filenames, plus those we are never going to be sending it so why would it allow them)
 - forbid empty
 - probably forbid any forward slashes at all: there's no reason to be looking in a different directory (or perhaps it insists on a particular directory, but same thing)

 _Imported from trac ticket [#1279](http://trac.gpolab.bbn.com/proto-ch/ticket/1279),  created by ahelsing on 01-30-2015 at 10:40, last modified: 02-03-2015 at 09:58_

**Comment by MarshallBrinn** [comment]
I think this is fixed. I put checks in file-upload.php to make sure this is a valid url and not allow file:// and then made sure that failures propagated properly through the editor widgets.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-02-2015 at 12:56_

**Comment by MarshallBrinn** [comment]
Tom suggests using parse_url instead of split. Will re-open and close when done.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-02-2015 at 14:33_

**Comment by MarshallBrinn** [comment]
Replaced call to split with parse_url and tested/checked in.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-03-2015 at 09:58_
