### ISSUE TITLE
"Raw" manifest text box doesn't format XML

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1290]
At one point "raw" responses from sliverstatus and listresources were displayed on a separate page and just left to your browser to render as they saw fit.  Now at least for manifests there is a text panel that expands if you ask to see the raw xml.  However, because this literally displays the "raw" xml (which has little to no formatting), it tends to contain the entire manifest on two lines:

http://grab.by/Eso2

It is possible (but difficult in some browsers) to copy this text out and view it in another editor, but is otherwise not useful.  Can we either go back to the old way of dumping it all on a new page, or pretty-print it so it can be viewed in the browser?

 _Imported from trac ticket [#1290](http://trac.gpolab.bbn.com/proto-ch/ticket/1290),  created by nick.bastin on 02-04-2015 at 15:53, last modified: 02-17-2015 at 11:01_

**Comment by ahelsing** [comment]
See ticket #1252

_Trac comment by ahelsing on 02-04-2015 at 15:57_

**Comment by MarshallBrinn** [comment]
Put in a replace < with </n on the XML before putting it in the box and all seems to work well (the indentation was already good but the newlines got lost.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-17-2015 at 11:01_
