### ISSUE TITLE
Update Jacks context

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1298]
Jon's latest Jacks introduces 2 new fields for the default Jacks context

```
    "linkTypes": [
...
     {
        "id": "gre-tunnel",
        "name": "GRE Tunnel",
    "ip": "auto"
      },
      {
        "id": "egre-tunnel",
        "name": "EGRE Tunnel",
    "ip": "auto"
      }
```

```
    "images": [
      {
        "id": "urn:publicid:IDN+emulab.net+image+emulab-ops:Ubuntu12-64-OVS",
        "name": "Ubuntu 12.04 with OVS for ProtoGeni (by Niky)",
        "nomac": true
      },
```

 _Imported from trac ticket [#1298](http://trac.gpolab.bbn.com/proto-ch/ticket/1298),  created by ahelsing on 02-06-2015 at 20:13, last modified: 03-04-2015 at 11:20_

**Comment by ahelsing** [comment]
Emailed experimenter support for input on which disk images and link types to set these bits on.

Then we'll want to edit etc/jacks-context.json and portal/www/portal/jacks-editor-app.js


_Trac comment by ahelsing on 02-10-2015 at 09:49_

**Comment by ahelsing** [comment]
Niky says the no mac learning thing should have to do with the links. I emailed Jon.

On images and auto IP, she says definitely on the GRE tunnels, but maybe also stitched or even all links. They'll discuss and get back to us.

On images:
The list of images looks ok but it misses Ubuntu 14.04. If we have the option of ordering the images I would say:
Ubuntu14.04, Ubuntu 12.04, Ubuntu OVS and then the rest.

What is the OpenVZ image used for? Is it used for OpenVZ containers? Or is it used for when you want
a bare metal node to be an OpenVZ container? 


_Trac comment by ahelsing on 02-10-2015 at 10:51_

**Comment by ahelsing** [comment]
Niky says add this UBU 14.04 disk image:

```
<disk_image name="urn:publicid:IDN+geni.it.cornell.edu+image+emulab-ops:UBUNTU14-64-STD" os="Linux" url="https://www.geni.it.cornell.edu/image_metadata.php?uuid=df2c08a5-4ed1-11e4-81fe-000000000000" version="14.04" description="Ubuntu 14.04 LTS" />
```

And ask Utah what the OpenVZ image is for.

_Trac comment by ahelsing on 02-10-2015 at 10:57_

**Comment by ahelsing** [comment]
Jon says tag images with OVS to get Niky's (a) above, and for (b) there is likely some kind of UI needed.

_Trac comment by ahelsing on 02-10-2015 at 11:10_

**Comment by ahelsing** [comment]
Jon and Niky continue to discuss. But for teh original intent of this ticket, any image that has OVS installed on it should get this flag. In our current jacks-context I think that is only:
```
	        "name": "OVS in Ubuntu 12 64-bit",
	        "id": "urn:publicid:IDN+emulab.net+image+emulab-ops:Ubuntu12-64-OVS"
```


_Trac comment by ahelsing on 02-10-2015 at 13:23_

**Comment by tcmitchell** [comment]
The following images are labeled as "nomac":
```
    "nomac_images": {
        "urn:publicid:IDN+emulab.net+image+emulab-ops:Ubuntu12-64-OVS": true,
        "urn:publicid:IDN+emulab.net+image+ubuntu-14.04-OVS": true
    },
```

GRE Tunnels are only available between openvz nodes and raw-pc nodes, not xen nodes :
```
            {
	        "node": {
	            "types": [ "emulab-openvz", "raw-pc" ]
	        },
	        "link": {
	            "linkTypes": [ "gre-tunnel" ]
	        },
	        "node2": {
	            "types": [ "emulab-openvz", "raw-pc" ]
	        }
            },
```

EGRE Tunnels are only available between emulab-xennodes, not openvz or raw-pc nodes:
```
            {
	        "node": {
	            "types": [ "emulab-xen" ]
	        },
	        "link": {
	            "linkTypes": [ "egre-tunnel" ]
	        },
	        "node2": {
	            "types": [ "emulab-xen" ]
	        }
            },
```


_Trac comment by tmitchel (github user: tcmitchell) on 02-27-2015 at 15:43_

**Comment by ahelsing** [comment]
Installed a new Jacks context that is 99% complete.

Open a new ticket for further updates.


_Trac comment by ahelsing on 03-04-2015 at 11:20_
