### ISSUE TITLE
Details button on slice-jacks not filtered by sliver_info?

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1302]
Hitting Details on slice-jacks when I have no resources goes to listresources.php with no AMs and that queries all known aggregates.

 _Imported from trac ticket [#1302](http://trac.gpolab.bbn.com/proto-ch/ticket/1302),  created by ahelsing on 02-11-2015 at 09:28, last modified: 02-11-2015 at 10:11_

**Comment by MarshallBrinn** [comment]
Fixed. Needed to filter out the 'empty list' case before invoking the list resources code.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-11-2015 at 10:11_
