### ISSUE TITLE
show users RSpec parse errors

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1303]
tool-rspec-parse generates errors that might be useful to experimenters to understand why their RSpec doesnt work.

EG:

```
[Wed Feb 11 00:43:00 2015] [error] [client 50.157.208.121] PHP Warning:  DOMDocument::loadXML(): Namespace prefix xsi for schemaLocation on rspec is not defined in Entity, line: 1 in /usr/share/geni-ch/lib/php/tool-rspec-parse.php on line 91, referer: https://portal.geni.net/secure/rspecupload.php
```

 _Imported from trac ticket [#1303](http://trac.gpolab.bbn.com/proto-ch/ticket/1303),  created by ahelsing on 02-11-2015 at 16:28, last modified: 02-17-2015 at 10:06_

**Comment by MarshallBrinn** [comment]
We get these errors in the log but we also display them in the RSpec uploading code in  slice-add-resources and slice-add-resources-jacks. Something like:

ERROR: This RSpec is invalid: Mismatched tag at line 12, column 15

I think there isn't a problem here.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-17-2015 at 10:06_
