### ISSUE TITLE
Sliverstatus indication on the details page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1307]
Requested changes:
 * Rename 'Refresh All' as 'Refresh All Details'
 * Rename 'Refresh Status' as 'Refresh Status Only'
 * When the user his 'Refresh Status Only' or 'Refresh All Details', change the current status to '... refreshing ...'

Old text:

The new combined Details/status page is great!

However when I click on the Refresh Status page there is no indication that anything is happening. For the first few times I though I didn't press it and I was keep pressing the button. 

Maybe an easy solution is to replace the current status with a blank (just remove it) and when the new status comes back add it, just an idea. 

 _Imported from trac ticket [#1307](http://trac.gpolab.bbn.com/proto-ch/ticket/1307),  created by nriga on 02-15-2015 at 09:23, last modified: 02-17-2015 at 09:37_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Another request: It isn't clear (to me at least) what Refresh All does vs. Refresh Status.  (I.e does all refer to all the aggregates there or does it refer to all the information there).  Can we do one (or both) of the following:
   1. Rename "Refresh All" to "Refresh All Details". 
   2. Add tool-tips to the buttons so the tip for one says "Refresh all details" and the other stays "Refresh status only"

Thank you!

_Trac comment by vthomas on 02-15-2015 at 18:57_

**Comment by MarshallBrinn** [comment]
Fixed as indicated above.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-17-2015 at 09:37_
