### ISSUE TITLE
Remove the warning when pressing slice action buttons on the home page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1308]
In tool-slices, remove the intermediate warning dialogue that you are querying N aggregates and this may take a while.
 - This is no longer ever all aggregates, but instead is only ever the aggregates known to have resources for this slice.

Old text:

The buttons listed next to the slice name [there is a list of slices](when) now use the --useSliceAggregates flag (or something equivalent). When I have no resources I actually get a pop-up telling me to choose AMs, so there is no way to query all AMs unless I really want to do that.

No reason to have the extra warning in this case:
http://grab.by/EN8C

 _Imported from trac ticket [#1308](http://trac.gpolab.bbn.com/proto-ch/ticket/1308),  created by nriga on 02-15-2015 at 10:27, last modified: 02-17-2015 at 09:45_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
I'm not sure I follow this request. Are you asking that these buttons act on all known aggregates if you have no reservations? Or are you asking that if the slice has resources in only 1 aggregate, that there be no warning? Or are you asking that there never be a warning that this operation may take a while?

_Trac comment by ahelsing on 02-15-2015 at 10:36_

**Comment by innnkkki** [comment]
Sorry for not being clear:-) I meant the last one of your options. If you only acting on the slice AMs, no need to be a warning. 

These buttons now act the same way as the buttons on the slice page, i.e. they act on only the AMs on your slice, so I don' t think 
there is any reason to have a Warning here and not on the other place. I thought originally we had the warning because it would ask ALL AMs and that really took a while. 

_Trac comment by nriga (github user: innnkkki) on 02-15-2015 at 10:39_

**Comment by MarshallBrinn** [comment]
Fixed. We now skip the tool-aggwarning redirect and go directly to the list resources page.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-17-2015 at 09:45_
