### ISSUE TITLE
Allow retrieving more log messages

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1318]
The home, project, and slice pages list 'recent' log actions at the bottom.
Currently, they all use the default, showing entries from the last 24 hours.

It would be nice to show more. Consider:
 - Allow an AJAX thing to "Show Older"
 - User setting of how  long back to look
 - Change the default to 72 hours (cover a weekend)

 _Imported from trac ticket [#1318](http://trac.gpolab.bbn.com/proto-ch/ticket/1318),  created by ahelsing on 02-19-2015 at 08:58, last modified: 02-27-2015 at 11:17_

**Comment by seledwards** [comment]
Can we change the logs (especially on the slice page) to show more entries?

I'd like to see all logs in the set:
anything in the last 72 hours but at least including the last 6 entries


Niky reserved some resources 12 hours ago and then renewed them, and the log message that would get me to the request RSpec has already fallen off the list.  Actually, I'd love to see the link to Ben's page with all the reservation log information stick around more permanently.


_Trac comment by sedwards (github user: seledwards) on 02-27-2015 at 11:17_

**Comment by ahelsing** [comment]
Now supporting 1 day, 2 days, 3 days, week.

**Comment by ahelsing** [comment]
Still need the same fix on the Project and Slice pages.
