### ISSUE TITLE
SITE ID shouldn't be changed unless component_manager_id is set

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1323]
We shouldn't remove the site id tag unless component manager_id is set. Otherwise we get a random number each time.

 _Imported from trac ticket [#1323](http://trac.gpolab.bbn.com/proto-ch/ticket/1323),  created by mbrinn on 02-25-2015 at 14:36, last modified: 03-03-2015 at 13:55_

**Comment by MarshallBrinn** [comment]
This is harder than I thought. We already are removing the site id tag only when the CMID is set. The issue is that Jacks creates a new site tag when it reads in a topology without site tags.

What we need to do is when we're writing an RSPEC (when we pull it from Jacks) we need to change the ID of the site in the rspec to the NAME of the site. 

Same is true for when we post the rspec to the expanded editor, though obviously this is lower priority.

That is id=100 changes to id="Site 0". The name of the site can be found in jacksEditorApp.currentTopology['sites'].

This rspec will load properly again (with the same site name, though different invisible ID's.

Glad to help anyone who wants to work on this. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-26-2015 at 07:20_

**Comment by ahelsing** [comment]
Presumably this is why the Auto IP and Duplicate Node buttons where the site is not bound cause the site label to become a number.

_Trac comment by ahelsing on 02-26-2015 at 11:35_

**Comment by ahelsing** [comment]
Sarah found an example where an RSpec that was unbound, loaded into Jacks where it gets a site ID, then is bound, and when then exported from Jacks to make a reservation, it still has a site ID - which is then preserved in the manifest from the AM, so it is labeled using a site # in the sliceresources.php page.


_Trac comment by ahelsing on 02-27-2015 at 12:40_

**Comment by ahelsing** [comment]
jacks-editor-app has remove_superfluous_site_tags. Presumably this is related.
Perhaps we need to run this function when we get a new RSpec out of Jacks.
But also perhaps


_Trac comment by ahelsing on 03-02-2015 at 11:41_

**Comment by ahelsing** [comment]
Key places to update
 - upload to Jacks editors on profile, slice-add-resources-jacks
 - download/save from Jacks editors on profile, slice-add-resources-jacks
 - load into viewer on slice-resources, slice-jacks

Things to do
 - ID javascript to find site names, IDs, component_manager_id on nodes
 - ID javascript hooks where to put the protections

Rough logic:
 - If node has component_manager_id, remove the site id
 - else if site name is != site ID, change site ID to the name
  - check firs that site name is unique across site IDs in the RSpec
 - if all nodes in the rspec have same site ID, remove it
  - extra credit: if the site ID is not all $s, leave it

Use cases:
 - Unbound Rspec on tool-rspecs. Hit save. 
  - Now use that in slice-add-resources-jacks or download and re-upload or close/re-open the profile rspecs viewer, see a site ID that is a #
 - Hit expand on slice add resources jacks with some site unbound
 - feed slice add resources jacks or normal add resources jacks an RSpec that is both bound and has a site ID. Does sliceresources.php show the site name or ID? slice-jacks?
 - slice add resources-jacks. 
  - Unbound site
  - Download
  - upload from that same file


_Trac comment by ahelsing on 03-02-2015 at 13:23_

**Comment by ahelsing** [comment]
Another use case:
 - slice add resources jacks
  - unbound site
  - duplicate node


_Trac comment by ahelsing on 03-02-2015 at 13:24_

**Comment by ahelsing** [comment]
create jacks-lib.js
 - put remove_superfluous_site_tags in there for use on XML before
 handing to Jacks
 - Add to it a function to be called from fetch-topology that has
 access to the jacks list of sites with their names, for doing rest of
 the logic

Edit remove_superflous: if all nodes have same site ID, then remove
all site IDs

Write editSitesFromJacks(topology)
 - full rough logic described on ticket

Use the 2 functions and jacks-lib.js in
 - tool-rspecs (85, 91, 113, 163)
 - sliceresource (91)
 - slice-add-resources-jacks (494, 513, 534, 695, 763, 771)
 - jacks-editor-app (131, 609 , 625, 702)
 - jacks-app:200, 757, 764


_Trac comment by ahelsing on 03-02-2015 at 15:08_

**Comment by ahelsing** [comment]
To get sites out of jacks currentTopology, look at jacksEditorApp.currentTopology.sites (a list, so can get ..sites.lengthand sites[i] and then look at .id and .name



_Trac comment by ahelsing on 03-02-2015 at 15:14_
