### ISSUE TITLE
Duplicate nodes doesn't work if site is set

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1328]
Per bug report from Sarah and Niky:

Duplicate nodes not work if Aggregate is bound after dropping a single node on the canvas

We were testing that on the production portal and Sarah was using a Chrome browser I think. 

I just tried it (same setup as above) and saw the same behavior. 

Playing around with it some more, there is a step 0, 
load the Jacks Add resources page, i.e. it has to be the first thing you do. If you draw a topology 
and before binding it into a site you duplicate nodes (which works) and then you delete all 
and try to reproduce this bug, you won't be able to reproduce it. So:
(0) Load Jacks add resources page
(1) drop a VM on a canvas
(2) then bind the aggregate. 
(3) If you select the VM and click "Duplicate Nodes only" nothing happens.

Marshall,

On Jacks on the Add Resources page:
(1) drop a VM on a canvas
(2) then bind the aggregate. (This MUST be second.)
(3) If you select the VM and click "Duplicate Nodes only" nothing happens.

The same thing happens if in step 1 you draw two nodes and in step 2 you draw and then bind two aggregates. I didn't try it with three aggregates.

However, if you bind the aggregate and then drag the node on the canvas everything works ok and the node will duplicate. (That is do the above steps in the order 2 then 1 then 3.)

That is all,
Sarah

 _Imported from trac ticket [#1328](http://trac.gpolab.bbn.com/proto-ch/ticket/1328),  created by mbrinn on 03-02-2015 at 08:24, last modified: 03-02-2015 at 11:00_

**Comment by ahelsing** [comment]
On nye, following these instructions results in:
```
Uncaught ReferenceError: selected_rspec_node is not defined     slice-add-resources-jacks.js:612 
```

This does not happen on cascade, with the latest code.


_Trac comment by ahelsing on 03-02-2015 at 11:00_

**Comment by ahelsing** [comment]
Since it was fixed as a side effect of other changes, closing it.

_Trac comment by ahelsing on 03-02-2015 at 11:00_
