### ISSUE TITLE
Account changes posts telephone changes when it is unchanged

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1339]
The change account details page emails about changes to "Telephone" even when it appears it did not change. 

Example:
```
Changes posted:

Telephone was '', now ''
```

 _Imported from trac ticket [#1339](http://trac.gpolab.bbn.com/proto-ch/ticket/1339),  created by tmitchel on 03-09-2015 at 08:28, last modified: 03-09-2015 at 08:28_

**Comment by ahelsing** [comment]
Probably this is because the type of the data from the DB is not the same as the type of the new value, and we are using `===`
