### ISSUE TITLE
Downloaded RSpec is not in pretty format

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1340]
A user reports:

```
Hi,

Although jacks fixed the rspec viewer to be readable:
http://grab.by/Fo7S

when I download the same rspec it is still pretty unreadable (not pretty-fied),
see attached.

In the JacksIssues page this is reported as fixed on 2/6/15. Anything changed since then?

I used Chrome.

Thanks,
Niky
```

 _Imported from trac ticket [#1340](http://trac.gpolab.bbn.com/proto-ch/ticket/1340),  created by tmitchel on 03-09-2015 at 08:31, last modified: 03-09-2015 at 10:59_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [testnysernet_request_rspec.xml](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1340/testnysernet_request_rspec.xml) on 03-09-2015 at 08:31_

**Comment by ahelsing** [comment]
This looks to be something that changed in the xml string we get from Jacks.

However, we can improve things in jacks-lib in the existing function cleanSiteIDs.....

Jacks uses vkbeautify, which seems like the 'right' solution (assuming newlines come out OK).
Given Jacks will have already loaded that library, we could simply use it in place.

Alternatively, we can put in a little code to get newlines inserted.




_Trac comment by ahelsing on 03-09-2015 at 09:50_
