### ISSUE TITLE
Remove Geo Map button?

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1341]
Now that the Jacks slice page is the default, and it has a Geographic view, I am not sure the geo map button is needed any more in the slice  page

 _Imported from trac ticket [#1341](http://trac.gpolab.bbn.com/proto-ch/ticket/1341),  created by nriga on 03-12-2015 at 06:31, last modified: 03-30-2015 at 11:25_
   CCing: gpo-expt-support@...

**Comment by tcmitchell** [comment]
I think this issue no longer applies with the UI overhaul from Summer 2015. @vicraj please reopen if you disagree.
