### ISSUE TITLE
Consider adding an "Add GENI Desktop Global Node" button in Jacks App

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1351]
GENI Desktop asks if we should add a capability to the Jacks Editor App that would add their Global Node to a topology.

 _Imported from trac ticket [#1351](http://trac.gpolab.bbn.com/proto-ch/ticket/1351),  created by tmitchel on 03-25-2015 at 16:26, last modified: 05-04-2015 at 07:53_
   CCing: nasir@...

**Comment by MarshallBrinn** [comment]
Working on this. Got some PHP code from Hussar and Charles to make the appropriate changes.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-01-2015 at 07:31_

**Comment by MarshallBrinn** [comment]
I have a working version of this using their PHP code as the back end. The question I raised to Hussam and Charles is what jacks 'site' the GN should be placed in. Currently, it is placed in a different site than any of the current nodes (i.e. a new site). That may be right, or it may not be. 

Waiting for feedback from them before proceeding.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-01-2015 at 08:39_

**Comment by MarshallBrinn** [comment]
This is all set and checked in. What they want is to add a GN to every site. That's what their code does, but it requires us to disable the "add global node" button until all sites are bound  (at least all sites with resources). This is the same logic as we use for 'enable reserve resources' so we piggy back off of this.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-04-2015 at 07:53_
