### ISSUE TITLE
Summarize slice contents on slices / home pages

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1354]
Niky would like a list of where each slice has resources on Home Page / Project page.

Sarah in contrast would like a count of # of AMs where the slice has resources.

 _Imported from trac ticket [#1354](http://trac.gpolab.bbn.com/proto-ch/ticket/1354),  created by ahelsing on 04-01-2015 at 14:03, last modified: 04-01-2015 at 14:03_

**Comment by ahelsing** [comment]
charliemeyer added and indication of when you have resources expiring. This is neither what Niky or Sarah asked for, but seemed most useful to us. Will need to get feedback.

**Comment by tcmitchell** [comment]
There is a display issue on the home page when multiple slices are listed. There are warnings in the log about redefining a PHP function.
