### ISSUE TITLE
Add SAVI button to portal

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1355]
The SAVI button will send the user's certificate, probably via POST, to a SAVI URL.

URL to be determined.

 _Imported from trac ticket [#1355](http://trac.gpolab.bbn.com/proto-ch/ticket/1355),  created by tmitchel on 04-08-2015 at 16:30, last modified: 05-13-2015 at 16:47_

**Comment by MarshallBrinn** [comment]
I added the button to home-active.php and added savi.php to do the proper 'put' of the cert. It seems to work as well as the python script. I'll wait for some more testing with the SAVI team to check this in. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-14-2015 at 15:47_

**Comment by tcmitchell** [comment]
The SAVI team and the experimenter support group have tested the savi.php page and approve. They agree the SAVI button should go on the home page.

_Trac comment by tmitchel (github user: tcmitchell) on 05-13-2015 at 16:47_
