### ISSUE TITLE
Add SAVI identity provider to set trusted by Shibboleth

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1356]
The SAVI project will set up an identity provider to allow SAVI users to access the GENI portal.

 _Imported from trac ticket [#1356](http://trac.gpolab.bbn.com/proto-ch/ticket/1356),  created by tmitchel on 04-08-2015 at 16:31, last modified: 04-08-2015 at 16:31_

**Comment by ahelsing** [comment]
This was fixed in the portal upgrade of yesterday
