### ISSUE TITLE
Add new OVS image to Jacks constraints

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1361]
There is a new image added to the IG ad rspec with URN:

  urn:publicid:IDN+instageni.ku.gpeni.net+image+emulab-ops:UBUNTU14-OVS2.31

Add it to the constraint system in Jacks. It should work in all XENs and
IG rack raw pcs.

 _Imported from trac ticket [#1361](http://trac.gpolab.bbn.com/proto-ch/ticket/1361),  created by tmitchel on 04-16-2015 at 08:31, last modified: 04-21-2015 at 16:38_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
From Niky:

URN could be emulab.net - that was just a sample.

nomac attribute should be set.


_Trac comment by ahelsing on 04-20-2015 at 16:09_

**Comment by tcmitchell** [comment]
The new image has been added to the jacks context file with nomac flag set to true. The generic URN is:

  urn:publicid:IDN+emulab.net+image+emulab-ops:UBUNTU14-OVS2.31


_Trac comment by tmitchel (github user: tcmitchell) on 04-21-2015 at 16:38_
