### ISSUE TITLE
listresources.php gets stuck "...refreshing..." when no resources at an aggregate

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1365]
There appear to be a couple of problems with `listresources.php`, the combined details and status page:

 1. The page can get stuck saying "...refreshing..." on aggregates where there are no resources. To replicate:
  * Create a new slice
  * You're now at the slice page, choose "Aggregate View"
  * Click on the ExoGENI and InstaGENI checkboxes to show all aggregates of those types
  * Click on the "Resource Details" button
  * Watch `listresources.php` get stuck saying "...refreshing..." for all aggregates
 2. This also seems to lock the SESSION
  * To replicate do the above steps on the staging host which does not federate with all aggregates
  * When the page is stuck in "...refreshing..." try clicking command-click on the slice name (on a mac) to bring up that page in a new tab (on other OSes, use the equivalent whatever it is)
  * See the page stuck trying to load because the SESSION is locked
 3. *_Low Priority_*: This page could better detect that the aggregate is not federated so that the display of manifests shows something other than empty.
  * To replicate, use the steps above on cascade, then click on "Show Raw XML Resource Specification"

 _Imported from trac ticket [#1365](http://trac.gpolab.bbn.com/proto-ch/ticket/1365),  created by tmitchel on 04-22-2015 at 10:28, last modified: 04-22-2015 at 10:28_

**Comment by ahelsing** [comment]
* Found a spot where `listresources.php` needed to close the session
 * Added some text in the raw results to make it clearer when no results came back
 * Added some text when an AM has a slice but no resources
 * Moved logic to change the 'refreshing' text to 'READY' or 'FAILED' so it is outside the block that looks at the resources listed in the status return.
