### ISSUE TITLE
Pages that send mail hardcode the sender

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1371]
invite-to-project, do-upload-project-members, join-this-project, ask-for-project, send_bug_report all hardcode the From as 'www-data@gpolab.bbn.com'.

This should not be hard coded, and should be set to the proper sender for other installs (like on the AWS system)

 _Imported from trac ticket [#1371](http://trac.gpolab.bbn.com/proto-ch/ticket/1371),  created by ahelsing on 04-23-2015 at 20:48, last modified: 04-23-2015 at 20:48_

**Comment by tcmitchell** [comment]
This was fixed by #1769
