### ISSUE TITLE
Details page loops indefinitely at AL2S

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1378]
I have a slice that uses resources at AL2S.

I click 'Details' to bring up `listresources.php`

I can see the page getting status at all my AMs, including AL2S.

But as soon as the page shows 'ready' at AL2S, it changes to 'refreshing' and polls again.

I end up with lots of empty sections for listing the resources at AL2S.

This does not happen on a slice with no resources at AL2S.

 _Imported from trac ticket [#1378](http://trac.gpolab.bbn.com/proto-ch/ticket/1378),  created by ahelsing on 05-20-2015 at 11:46, last modified: 05-20-2015 at 11:46_

**Comment by ahelsing** [comment]
See issue #1280 that recently worked on this code.

See also possibly related issue #1365.

**Comment by ahelsing** [comment]
Possible solutions include:
 - only look for login info at AMs where the manifest says there are nodes. This may not be reliable though.
 - Have the various functions in `amstatus.js` take a last named argument `loopedOnce=False`, and when `check_for_completeness` loops back by calling `add_one_am_login` again, set that argument to `True`. Then `check_for_completeness` refuses to loop again if that argument is `True`.

**Comment by ahelsing** [comment]
Adding the extra arg `lastCall` to cut off re-looping. It still flickers more than I like, but at least it isn't endless.

**Comment by tcmitchell** [comment]
Check the details page for the following:
* Use Jacks to create a stitched topology via AL2S
* Use the non Jacks Add Resources to submit an RSpec bound for one InstaGENI AM to a different InstaGENI AM
* An AM where there are no resources for the slice

**Comment by tcmitchell** [comment]
Querying details for an AM where there are no resources results in steady looping between “NO RESOURCES” and “…refreshing…”.

**Comment by ahelsing** [comment]
fix is installed on cascade
