### ISSUE TITLE
Disable the "disable project" button

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#138]
Disable project is currently broken because it deletes the project but leaves dangling references in the project members table. This cause unsatisfactory displays on the portal UI.

Disable that button until appropriate disable functionality is determined and implemented.

 _Imported from trac ticket [#138](http://trac.gpolab.bbn.com/proto-ch/ticket/138),  created by tmitchel on 06-14-2012 at 14:06, last modified: 06-18-2012 at 14:55_

**Comment by seledwards** [comment]
Code currently says:
```
$disable_project = "";
if (!$user->isAllowed(PA_ACTION::DELETE_PROJECT, CS_CONTExT_TYPE::PROJECT, $project_id)) {
  $disable_project = $disabled;
}
```

Added an `else` and a comment so that it now says this:

```
$disable_project = "";
if (!$user->isAllowed(PA_ACTION::DELETE_PROJECT, CS_CONTExT_TYPE::PROJECT, $project_id)) {
  $disable_project = $disabled;
}
/* for now, always disable the project */
else {
  $disable_project = $disabled;
}
```

_Trac comment by sedwards (github user: seledwards) on 06-18-2012 at 14:55_
