### ISSUE TITLE
Support new model for wireless accounts

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1392]
We are changing the wireless account model.

All GENI users will be in a GENI wireless group, but disabled (on orbit side).
Project leads/admins will be allowed to enable/disable any of their projects for wireless. Checkboxes.

All users in a project will be added to the appropriate wireless group. Changing project membership should auto change wireless group membership. So this will require lib/php wireless functions similar to what we do for irods.

When a user has been removed from all their projects (and therefore from all their wireless groups), orbit will disable the orbit user. As a result, their state won't go away but they won't have live access.

Orbit will grant some portal operators ability to enable/disable geni group orbit users.

Orbit will also expose an API to disable users. Disabling a user will remove them from all their orbit groups. This would be used as backup when we disable a geni portal user.

**Comment by ahelsing** [comment]
From Olivera:
```
Here is API extension to fulfill new requirements:
Note: baseDN i optional parameter and by default is dc=ch,dc=geni,dc=net

*
addMemberToGroup?groupname=<groupname>&username=<username>[&baseDN=<baseDN>]

Response is : " User <username> added to group <groupname> successfully"
*
removeMemberFromGroup?groupname=<groupname>&username=<username>[&baseDN=<baseDN>]

Response is : " User <username> removed from group <groupname> successfully"
New error codes are:
ERROR13 = 'ERROR 13: User is not member of the group'
  ERROR14 = 'ERROR 14: Cannot remove user from its primary group'

* getProjectMembers?groupname=<groupname>[&baseDN=<baseDN>]
* getUserProjects?username=<username>[&baseDN=<baseDN>]

If a user is removed from last group he is member of (except his primary
group) he becomes inactive.
There are also(:
* disableUser?username=<username>[&baseDN=<baseDN>]
* enableUser?username=<username>[&baseDN=<baseDN>]
```

**Comment by ahelsing** [comment]
To implement this:
 - refactor wimax-enable to be library functions
 - Call those functions whenever someone is added to or removed from a project, or when a project is enabled for wireless
 - Change the UI page:
  - For non project leads, it simply shows you your wireless groups and wireless username, and has links to Orbit and Witest
  - For project leads, a series of checkboxes for each project, to enable/disable wireless in that project
 - geni-disable-user probably needs to call a new function to disable the user at orbit
 - ma_member_attribute currently stores your wimax project ID. This needs to become a multi valued attribute in some form

Questions
 - how can a project admin enable a project for wireless? Can they specify that the group admin is the project lead, without being the lead? I think so....
 - wimax-enable.php is a bit of a mess. Lots of the code is error checking code, code to keep state in sync. How much of that should be preserved?

**Comment by ahelsing** [comment]
While fixing this, consider doing the state sync functions as in issue #1076

**Comment by ahelsing** [comment]
Consider also moving the WiMAX attributes from the MA and PA tables and into portal tables as in issue #850

**Comment by MarshallBrinn** [comment]
All checked in including
  * New wimax-enable.php page that allows for enable/disable/sync of projects
  * geni-wireless-sync script (and man page) to sync between GENI project/member and ORBIT group/user state
 * Sync user before redirect to wireless site (WiTEST, ORBIT)
 * Sync project button
 * Ignore disabled users from geni rosters
 * Printing error when sync has failed
