### ISSUE TITLE
Some error messages are page redirects on the admin page

### ISSUE THREAD

**Issue by charliemeyer** [GENI-NSF/geni-portal#1417]
When slice searches by URN and user searches by email fail, the error message is a "page within a page" with an info box about a bad URN. This should be handled more gracefully.

**Comment by ahelsing** [comment]
Logs when a search for a slice by owner email failed:
`
[Fri Jul 17 11:33:48 2015] [error] [client 128.89.69.240] PHP Notice:  Undefined index: asdf in /var/www/secure/do-slice-search.php on line 70, referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
[Fri Jul 17 11:33:48 2015] [error] [client 128.89.69.240] Cannot get_member_urn for empty id: , referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
[Fri Jul 17 11:33:48 2015] [error] [client 128.89.69.240] SCRIPT_NAME = /secure/do-slice-search.php, referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
[Fri Jul 17 11:33:48 2015] [error] [client 128.89.69.240] ERROR.CODE 3, referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
[Fri Jul 17 11:33:48 2015] [error] [client 128.89.69.240] ERROR.VALUE , referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
[Fri Jul 17 11:33:48 2015] [error] [client 128.89.69.240] ERROR.OUTPUT [ARGUMENT] ARGUMENT_ERROR (Ill-formed argument of type URN field member_urn: ), referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
`
