### ISSUE TITLE
Implement clearer "progress tracker" in portal

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#142]
Implement Joanne Achin's proposed changes to the "progress tracker" on the portal.

These include:
 1) colored circle icons for the numbers
 2) highlight the item you are currently doing and gray out items that are not currently being attempted

 _Imported from trac ticket [#142](http://trac.gpolab.bbn.com/proto-ch/ticket/142),  created by sedwards on 06-18-2012 at 14:44, last modified: 10-03-2012 at 15:49_

**Comment by ahelsing** [comment]
we've decided to ditch the progress tracker

_Trac comment by ahelsing on 10-03-2012 at 15:49_
