### ISSUE TITLE
Decide how/whether to remove redundancy between "home", "projects" and "slices" pages

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#143]
The information on the "Home" page is repeated on the "projects" and "slices" pages.  

Consider removing some of this redundancy, perhaps by removing "projects" and "slices" pages.

 _Imported from trac ticket [#143](http://trac.gpolab.bbn.com/proto-ch/ticket/143),  created by sedwards on 06-18-2012 at 14:46, last modified: 04-07-2014 at 16:00_

**Comment by seledwards** [comment]
We decided this is ok for now, but we should revisit later.

Moving out of GEC14.

_Trac comment by sedwards (github user: seledwards) on 06-22-2012 at 14:27_

**Comment by ahelsing** [comment]
Still OK

_Trac comment by ahelsing on 04-07-2014 at 16:00_
