### ISSUE TITLE
Search for unknown user email gives PHP Notice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1430]
On admin page, user search, search for a bad email address. Logs show:
`
[Fri Jul 17 11:28:21 2015] [error] [client 128.89.69.240] PHP Notice:  Undefined index: dpedroia in /var/www/secure/do-user-search.php on line 62, referer: https://portal-ah.gpolab.bbn.com/secure/admin.php
`

**Comment by tcmitchell** [comment]
use `array_key_exists` to determine of `$term` is in the results. If not, return NULL or an empty array. Either will work fine with the code in `make_result_table`.
