### ISSUE TITLE
Remove project lead checkbox from modify page for project leads

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1431]
The Profile page suggests that you can request to not be a project lead.

Making that request appears to store a new request to _be_ a project lead.

Handling that request appears to try to make the person a lead (again). This results in the logs message:
`User 35faf212-2577-43b8-89d7-d60e469d33dc already a project lead, cannot be made a project lead`

On the modify account page, take out the ability to not be a project lead. No one does this. .

**Comment by tcmitchell** [comment]
Putting this in actionable terms, remove the checkbox and accompanying language about wanting to remain a 'Project Lead' if someone is already a project lead.
