### ISSUE TITLE
TZ on lead requests is wrong

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1446]
The timezone for when a lead request was requested is wrong. It says the time was UTC, but the actual time being displayed is in local time.

For example, the DB for request 1 says the time was "2015-07-22 11:13:44.371414". The UI says "2015-07-22 11:13:44 UTC".

We received the email about this request at 11:13 EDT.

**Comment by charliemeyer** [comment]
Possible solution: in lead request db table, make default value for timestamp (now() at time zone 'utc').

**Comment by ahelsing** [comment]
Also fix `last_seen` and `km_asserted_attribute`.

Fix schema files and produce and update.sql
