### ISSUE TITLE
Remove dependency on AM certificates

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#145]
The gcf-pgch uses AM certificates to generate HRNs for display in flack. That's the only use of the AM certificates that I can find. We should replace the cert->URN->HRN conversion in gcf-pgch by storing the desired HRN in the service registry table. That gives us more control over the flack label, while eliminating the need for AM certificates.

 _Imported from trac ticket [#145](http://trac.gpolab.bbn.com/proto-ch/ticket/145),  created by tmitchel on 06-20-2012 at 13:53, last modified: 12-11-2013 at 09:21_

**Comment by ahelsing** [comment]
This is just the AM certs, not the signer of the AMs, which Flack does need, right?

_Trac comment by ahelsing on 10-09-2013 at 13:03_

**Comment by tcmitchell** [comment]
Correct. Just the AM certs, not the signer certs. Flack gets the signer certs in the HTML file and the AM HRNs (via the AM certs) from pgch.

_Trac comment by tmitchel (github user: tcmitchell) on 10-09-2013 at 15:58_

**Comment by ahelsing** [comment]
The new PGCH.py gets the URN and HRN from the DB, but also returns the AM cert. Useful still? Necessary?

_Trac comment by ahelsing on 12-05-2013 at 09:56_

**Comment by ahelsing** [comment]
Moved to CHAPI ticket # 165

_Trac comment by ahelsing on 12-11-2013 at 09:21_
