### ISSUE TITLE
Admin page: add note to lead request then switch tabs, message follows

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1459]
On the admin page
 - add a note on a lead request
 - You get 'Response successfully stored'
 - switch to user search tab
 - still see that message. You should not.
 - Do a user search
 - still see that message

**Comment by tcmitchell** [comment]
This matches behavior on other pages with tabs. The message only gets cleared when you go to a new page. Switching tabs does not reload the page, so the message does not get cleared.

I don't think we want to inject code to clear the messages into the tab javascript code. Especially not for the admin page. Click refresh and the message should go away.

**Comment by tcmitchell** [comment]
It's not worth changing the behavior.
