### ISSUE TITLE
Create a place for host-specific configuration

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#146]
Panther has a different database password. It would be convenient to have a settings file that is local to a host, and does not get overwritten by a make install. For now I am editing the file each time I install.

 _Imported from trac ticket [#146](http://trac.gpolab.bbn.com/proto-ch/ticket/146),  created by tmitchel on 06-20-2012 at 17:11, last modified: 12-05-2013 at 09:56_

**Comment by ahelsing** [comment]
long since fixed I believe

_Trac comment by ahelsing on 12-05-2013 at 09:56_
