### ISSUE TITLE
Make sure slice action buttons on home page are enabled consistently with those on slice page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#147]
The slice action buttons on the slice page are enabled/disabled based on permissions.

Make sure the slice action buttons on the home page are enabled/disabled in the same way.

 _Imported from trac ticket [#147](http://trac.gpolab.bbn.com/proto-ch/ticket/147),  created by sedwards on 06-21-2012 at 11:35, last modified: 06-21-2012 at 16:44_

**Comment by MarshallBrinn** [comment]
This is fixed. Additionally made the labels consistent between the tool-project/slice pages and the project/slice pages. And removed project-email from the home page (on projects) and removed slice URL and Credential from the slice portion of the home page.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-21-2012 at 16:44_
