### ISSUE TITLE
dashboard storage is confused on shared computers

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1477]
local storage for dashboard state is not per user. So on a shared computer for example:

 - filter slices by a slice
 - log out
 - log in as different user, not in that slice
 - slices tab will not display the 'New Slice' button and will say "No slices for project <foo>"

**Comment by ahelsing** [comment]
possible solution:
 - store username in local storage
 - when rendering dashboard, if the local storage name is not the current name, clear local storage
 - state is lost between users on a shared browser

Fancier solution:
 - make the local storage keynames include the person's username
 - makes state preserved in a shared browser

**Comment by nbastin** [comment]
Also keep in mind that local storage is not protected in any way, so if you're going to store anything sensitive there make sure you encrypt it using a token bound to the portal login info.
