### ISSUE TITLE
'New Slice' from project card gives page where you cannot create a slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1478]
If you go to createslice.php with a projectid set, then the 'has_projects' var remains false, and so the create slice button is disabled - at least on Firefox.

Set hasprojects at the top when you extract the projectid from the REQUEST, or else simply init it based on whether projectid is set.

**Comment by ahelsing** [comment]
please check that createslice.php without a project id also sets hasproject appropriately. This is failing for me on firefox as well.

**Comment by tcmitchell** [comment]
Closed by #1480
