### ISSUE TITLE
On "DeleteSliver" confirmation page, remove words like "Fail"/"Error"

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#148]
Use kinder words which don't look like something went wrong.  We don't want to get email from confused and angry experimenters.

 _Imported from trac ticket [#148](http://trac.gpolab.bbn.com/proto-ch/ticket/148),  created by sedwards on 06-22-2012 at 17:44, last modified: 04-07-2014 at 16:15_

**Comment by ahelsing** [comment]
Those kinds of words appear to be gone. Must have been fixed at some point.

_Trac comment by ahelsing on 04-07-2014 at 16:15_
