### ISSUE TITLE
Renew slice button on dashboard pops up incorrect warning about too many aggregates

### ISSUE THREAD

**Issue by charliemeyer** [GENI-NSF/geni-portal#1481]
When a user tries to renew a slice&resources with 10+ slivers (regardless of how many aggregates they are located at), a javascript confirmation box warns them that they are renewing slices at many aggregates, which is false. Furthermore, the slice is renewed regardless of their choice in the confirmation box.

**Comment by tcmitchell** [comment]
Closed by #1490
