### ISSUE TITLE
Project cards grow on text overflow, making weird gaps on project tab.

### ISSUE THREAD

**Issue by charliemeyer** [GENI-NSF/geni-portal#1484]
See screenshot http://grab.by/JlkM

**Comment by tcmitchell** [comment]
A second instance has cropped up with slices:

![screenshot 2015-08-05 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/340136/9094329/2d0c9274-3b7f-11e5-9a99-290fcababfac.png)
