### ISSUE TITLE
Add "contact us" page and link to it under "Help" dropdown.

### ISSUE THREAD

**Issue by charliemeyer** [GENI-NSF/geni-portal#1486]
Add link to GENI Help Wiki as well.

**Comment by tcmitchell** [comment]
* [A draft "contact us" page](https://docs.google.com/document/d/1pRMryLwytn87Tudsy9q45VcislOpmTOapZUSQzV5PzY/edit)
* [GENI Help Wiki](http://groups.geni.net/geni/wiki/GENIExperimenter/GetHelp)
