### ISSUE TITLE
Add google analytics to "expanded view" pages.

### ISSUE THREAD

**Issue by charliemeyer** [GENI-NSF/geni-portal#1488]
These include jacks-app-expanded.php and jacks-editor-app-expanded.php. Should be as simple as including header.php in both files.

**Comment by tcmitchell** [comment]
I can see that google analytics has been enabled on the two jacks expanded pages by watching the analytics real-time content. There are issues with each page, however. See next comments.

**Comment by tcmitchell** [comment]
The jacks-app-expanded page displays jacks with a very short height in Chrome, Firefox, and Safari:

![screen shot 2015-08-07 at 12 10 43 pm](https://cloud.githubusercontent.com/assets/340136/9140312/366b9ca4-3cfe-11e5-974d-1d4120a01cd1.png)

**Comment by tcmitchell** [comment]
The jacks-editor-app-expanded has no palette of nodes & sites to drag onto the jacks canvas. I can't tell if it is a CSS issue or an initialization issue or what:

![screen shot 2015-08-07 at 12 12 25 pm](https://cloud.githubusercontent.com/assets/340136/9140349/7f1e6e9a-3cfe-11e5-8fe7-ece374437f51.png)

**Comment by charliemeyer** [comment]
Combined with the changes of #1502, the jacks-expanded pages should look good and be totally usable.
