### ISSUE TITLE
Flack uncaught exception when aggregate URN ends in "cm"

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#15]
When we run Flack against `pgch.py` and `pgch.py` returns a URN ending in "cm" from `ListComponents`, Flack has an uncaught exception.

This appears to be the result of Flack detecting a ProtoGENI ComponentManager and following a code path that uses the ProtoGENI CM API instead of the GENI AM API. When we forced flack (via code modification) to use the GENI AM API path, Flack successfully talks to the ProtoGENI CM (pgeni3).

 _Imported from trac ticket [#15](http://trac.gpolab.bbn.com/proto-ch/ticket/15),  created by tmitchel on 05-14-2012 at 15:31, last modified: 01-04-2013 at 16:39_

**Comment by MarshallBrinn** [comment]
This is fixed in the most recent version of flack 14.47

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-04-2013 at 16:39_
