### ISSUE TITLE
Add logging for "add resources" action

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#151]
We log "delete resources".  We should do the same for "add resources".

 _Imported from trac ticket [#151](http://trac.gpolab.bbn.com/proto-ch/ticket/151),  created by sedwards on 06-22-2012 at 17:48, last modified: 06-22-2012 at 18:19_

**Comment by tcmitchell** [comment]
Add resources is logged. We don't detect failure of an attempt to add resources, so if something goes wrong, it will still look like the user added resources. This could be improved in the future.

_Trac comment by tmitchel (github user: tcmitchell) on 06-22-2012 at 18:19_
