### ISSUE TITLE
Add something like "Logged in as Tom Mitchell" in header

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#152]
Identifier the person logged in in the header.

 _Imported from trac ticket [#152](http://trac.gpolab.bbn.com/proto-ch/ticket/152),  created by sedwards on 06-22-2012 at 17:49, last modified: 06-22-2012 at 17:54_

**Comment by tcmitchell** [comment]
Added. Used "metanav" and "nav" styles based on reverse engineering Trac. Removed the "Welcome!" message.

_Trac comment by tmitchel (github user: tcmitchell) on 06-22-2012 at 17:54_
