### ISSUE TITLE
allow removing members from projects, slices

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#153]
We don't yet have a mechanism for removing someone from a project or slice

 _Imported from trac ticket [#153](http://trac.gpolab.bbn.com/proto-ch/ticket/153),  created by ahelsing on 06-25-2012 at 14:02, last modified: 05-14-2013 at 16:47_

**Comment by innnkkki** [comment]
Before we open the portal for more general use, we should have a way of removing users from projects. I don't think that removing them from slices is as important, but there might be something I am missing. 

It would be great if this is in place for GEC16, where we would have a wider use of the portal. 

_Trac comment by nriga (github user: innnkkki) on 02-20-2013 at 09:14_

**Comment by seledwards** [comment]
Chaos stopped by to chat and reminded me that this ticket is in fact really important in the near term.

People who are responsible for projects should be able to easily remove people from them.

_Trac comment by sedwards (github user: seledwards) on 04-15-2013 at 14:36_

**Comment by ahelsing** [comment]
Basic removing from projects is implemented.

To do:
 - When removing a member from a project, also explicitly remove them from any active slices in that project
  - But if they are the lead on the slice, then what?  We don't want an active slice with no lead, right? Or do we make the project lead become the slice lead?
 - Are project auditors allowed to be members of a slice? If not, what happens if we change a members role in a project to degrade them to auditor? Do we need to change their role on any active slices to auditor? And if they were the lead, make the project lead be the slice lead?
 - Make the 'Remove' option on the project page be last (membership changes first)
 - Move the 'Change Project Membership' button closer to the table, aligned with the column of choices
 - Remove the attempt at a pop-up: use an intermediate page instead
 - Make project membership and slice membership pages consistent


_Trac comment by ahelsing on 04-25-2013 at 08:58_

**Comment by ahelsing** [comment]
- Change 'Keep as' to be 'No Change'
 - Sort project members by role (Lead, Admin, Member, Auditor, ...)
 - Move project membership editing to the project edit page, and have an 'Edit' button that takes you to an anchor on the edit-project page.
 - Eventually allow handling project join requests on the edit-project page as well
 - Eventually, edit project page with membership table should also allow you to confirm your edits, but Niky isn't insistent
  - And only for deleting members


_Trac comment by ahelsing on 04-25-2013 at 15:07_

**Comment by MarshallBrinn** [comment]
A few more notes.

If a person is deleted from a project, they should be removed from slice. Unless lead, in which case it should change to the lead of the project.

Sort non-members below members.

Move project member editing into project edit page. Don't allow editing project membership from project page.

Should have an 'edit' button near the project membership stuff on project page that goes to the project membership page, but at a tag near the project membership part of the project edit page.


_Trac comment by mbrinn (github user: MarshallBrinn) on 04-25-2013 at 15:14_

**Comment by MarshallBrinn** [comment]
This is fixed. Here's what I did:

Made project and slice membership editing symmetric (an edit button goes to a separate page with tables).

Made the tables sort by member/non-member and then by role

Made the default/selected choice be labeled "No Change"

Removed Operator as a visible/selectable option.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-26-2013 at 12:59_
