### ISSUE TITLE
Orbit wireless account email should include contact information

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#1576]
The wording to the automated email informing you that you have an Orbit Wireless account should include contact information.

Perhaps replace:
"If you have any trouble with your account or if you have any questions, please feel free to send us an email." 
with 
"If you have any trouble with your account or if you have any questions, please feel free to send us an email at USER@EXAMPLE.COM".

An example email as I received it is below:
```
Sarah,
     Your ORBIT group geni-PROJECT has been created with USERNAME as primary administrator. 


You can find a collection of documentation as well as tutorials by visiting http://geni.orbit-lab.org.

Also, as part of the registration process your were subscribed to the ORBIT user mailing list. Its a place to hear announcements, ask questions, and read about other users' experiences.

If you have any trouble with your account or if you have any questions, please feel free to send us an email.
Sincerely,
The ORBIT Team
```

**Comment by tcmitchell** [comment]
This is a message from ORBIT, not a message from the GENI portal.
