### ISSUE TITLE
Clean up CH API

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#158]
Clean up the API of CH components
 - common naming conventions of arguments and method names
 - remove unused methods or duplicate methods
 - Add a GetVersion style call to each service

 _Imported from trac ticket [#158](http://trac.gpolab.bbn.com/proto-ch/ticket/158),  created by ahelsing on 06-25-2012 at 14:31, last modified: 09-19-2012 at 10:44_

**Comment by MarshallBrinn** [comment]
I checked in a revision based on latest CH API (controller) files. I believe this is complete for the GEC15 release.

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-19-2012 at 10:44_
