### ISSUE TITLE
Document CH API

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#159]
Document the CH components and the API - transport mechanism, authorization, methods, etc. Document also the portal functions.

 _Imported from trac ticket [#159](http://trac.gpolab.bbn.com/proto-ch/ticket/159),  created by ahelsing on 06-25-2012 at 14:32, last modified: 09-19-2012 at 10:45_

**Comment by MarshallBrinn** [comment]
Checked in version for the CH API containing all recent changes to CH API (controllers). I believe this is done for the GEC15 release.

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-19-2012 at 10:45_
