### ISSUE TITLE
portal needs a cert/key

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#160]
Give the portal its own cert/key so it can send S/MIME messages to the MA on initial user login

 _Imported from trac ticket [#160](http://trac.gpolab.bbn.com/proto-ch/ticket/160),  created by ahelsing on 06-25-2012 at 14:39, last modified: 08-21-2012 at 08:21_

**Comment by MarshallBrinn** [comment]
I believe this is now fixed.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:21_
