### ISSUE TITLE
mark slices inactive when disabled, expired

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#162]
The DB must allow marking slices that expired for example, then we don't show those (by default)

 _Imported from trac ticket [#162](http://trac.gpolab.bbn.com/proto-ch/ticket/162),  created by ahelsing on 06-25-2012 at 14:43, last modified: 06-21-2013 at 09:40_

**Comment by seledwards** [comment]
We currently mark slices expired in the DB and they show up appropriately in the UI.

Can we close this?

_Trac comment by sedwards (github user: seledwards) on 06-21-2013 at 09:21_
