### ISSUE TITLE
Add status page link from the home dashboard

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1629]
Maybe as a new tab

**Comment by tcmitchell** [comment]
The following comments were received in email:

A few comments (hopefully minor):

1. For cases where the aggregate status is not available, can we change "Unknown" to "N/A"?  And the legend for N/A would be "Status not available to GENI monitoring".
2. Please remove the OpenFlow aggregates from the status listing.
3. Either move the legend to the top of the list or add tool tips to the column headers with the legend items relevant to that column.
4. Can the "View current aggregate status" link on the Add Resources page go to the same page as the new Status page?  If not, can you modify the "View current aggregate status" page to:
 * Include status from monitoring
 * Incorporate comments 1-3 above?

**Comment by tcmitchell** [comment]
Per the above comments:

1. Changed "Unknown" to "N/A" and updated the legend and also removed the question mark icon
2. Interpreted "OpenFlow" aggregates to mean "FOAM" aggregates and filtered them out using 'ui_foam_am'
3. Moved the legend to the top
4. Changed the "View current aggregate status" link to point to the new status tab on the dashboard

**Comment by tcmitchell** [comment]
Per request, the public status page was also updated with comments 1-3 above.
