### ISSUE TITLE
Allow adding notes/comments

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#163]
Add a mechanism for adding notes, comments - on actions, slices, etc. 

 _Imported from trac ticket [#163](http://trac.gpolab.bbn.com/proto-ch/ticket/163),  created by ahelsing on 06-25-2012 at 14:44, last modified: 08-21-2012 at 07:59_

**Comment by MarshallBrinn** [comment]
I believe this was implemented in GEC14.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 07:59_
