### ISSUE TITLE
Add link to request RSpec on slice page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#165]
Slice page should show you the RSpecs you used in the slice

 _Imported from trac ticket [#165](http://trac.gpolab.bbn.com/proto-ch/ticket/165),  created by ahelsing on 06-25-2012 at 14:46, last modified: 08-08-2014 at 10:37_

**Comment by seledwards** [comment]
I second this.

I had a guy at the coding sprint who wanted to understand more about what was happening under the covers.  It might be nice to be able to click on the RSpec used at each aggregate both at home and during tutorials.

_Trac comment by sedwards (github user: seledwards) on 03-22-2013 at 22:59_

**Comment by ahelsing** [comment]
given that we allow on demand uploading of rspecs, this is hard without saving those requests.

_Trac comment by ahelsing on 07-15-2014 at 13:25_

**Comment by ahelsing** [comment]
Partially fixed by #1106. The request RSpecs are stored for a short amount of time until the omni invocation data are deleted. They can be found by going to the results page links on the slice/project pages.

_Trac comment by bujcich on 08-08-2014 at 10:37_
