### ISSUE TITLE
Email Admins on Join Requests

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#1672]
It seems like only the Project Lead gets emails about join requests. Admins should also get the emails since they can act on them. That would facilitate scenarios like tutorials or classes where the TA/helpers can approve users instead of just the professor/instructor.

**Comment by tcmitchell** [comment]
There's a data access/privacy issue with sending email to project admins. Project leads agree to have their info (name and email) made public. Admins do not. At present, the clearinghouse will block access to the identifiable attributes of the admin(s) so the user cannot send email to the admins as well as the project lead.

**Comment by vicraj** [comment]
I don't recall all the pages users see when they join a project.  If I am remembering correctly, the only page where users see the address of the Project Lead is the page that shows them the email that will be sent to the Project Lead.  Can we change the text in this page to read something like "The following email will be sent to the Project Lead John Smith (smith@state.edu) and possibly to the admins on the project."  The Portal sends the emails and so users do not have to know the email addresses of the admins.

**Comment by nbastin** [comment]
At the very least it'd be nice if there was an xml-rpc call admins could make that would poll the pending requests - then we could write a tool where they could just check them without going into the portal.

**Comment by tcmitchell** [comment]
@nbastin there is a clearinghouse xml-rpc call to [list the pending requests that can be handled by a given user](https://github.com/GENI-NSF/geni-ch/blob/develop/docs/RequestAPI.adoc#get_pending_requests_for_user). Per #1773 I have taken a stab at some documentation for that call and the related calls that make up the request api. Since that is a clearinghouse API, followups should go to [the geni-ch repository](https://github.com/GENI-NSF/geni-ch).

**Comment by tcmitchell** [comment]
Per @vicraj, we will use the portal's own certificate to fetch the admin email addresses from the clearinghouse since the experimenter who is joining the project cannot access this information.

**Comment by nbastin** [comment]
Just as a side note, `geni-lib` does now fully support managing project join requests programmatically - we're working on docs and a few wrapper scripts, but then admins will be able to handle these without going to the portal UI to check.
