### ISSUE TITLE
Improve error reporting for createimage

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#1694]
While creating an image in the GENI portal which failed due to my using a "-" in the name. The portal reports this error:
     " Error creating image: Internal Server Error"
The equivalent command in omni returns:
    "ERROR: Image name must be alphanumeric: ubuntu-xorp"
The portal should handle the failure , and check to enforce the image name formatting requirement and report a clearer message like omni.

**Comment by ahelsing** [comment]
Omni requires that the image name be non-empty and alphanumeric (based on guidance from ProtoGENI). If this is not true, it exits raising an Exception. For the portal, that looks like an empty return with the real error message going to STDERR.

am_client's `invoke_omni_function` logs the interesting error to the portal_error log file, but does not return it. Instead, it returns what went in the return - an empty string.

`image_operations.php` erroneously assumes that `invoke_omni_function` will always return a tuple. This causes the internal server error.

Changing Omni or `invoke_omni_function` is too risky. Instead, fix `image_operations` to handle a non-tuple return (pointing the experimenter at the `contact-us.php` page for help), and make `createimage.php` warn the user that the name must be alphanumeric and check that this is so.

**Comment by ahelsing** [comment]
To handle non tuple returns, use code something like:
```
  if ( !is_null($retVal) && (count($retVal)==2) ) {
    $msg = $retVal[0];
    $obj = $retVal[1];
    $good = TRUE;
  } elseif (count($retVal)==1) {
    $msg = $retVal;
    $obj[$am_url] = "";
  } else {
    $msg = "Call to create_image() FAILed";
    $obj = Array();
  }
```

**Comment by ahelsing** [comment]
Regex to ensure proper image names: `/^[a-zA-Z0-9]+$/`
