### ISSUE TITLE
Provide user more information when sending OpenID authentication info.

### ISSUE THREAD

**Issue by vicraj** [GENI-NSF/geni-portal#1697]
When the Portal authenticates users for tools such as LabWiki, the user gets the following dialog about "some of your information" being released to the other tool (screenshot attached).  Can we be more specific about what is released (my name? my email address?  my email address and those of others in my project?) so the user can make an informed decision?

![openid](https://cloud.githubusercontent.com/assets/13670873/15186608/530ddfb2-1763-11e6-9b4f-772b66e08784.png)

**Comment by tcmitchell** [comment]
The source for this page is in `openid/src/server-indirect/server.php`. We could do one of the following:

1. List the information that is always released and make a general statement (e.g. "may include...") about optional information that may be released.
2. Iterate over each AX entry in the request (see `send_geni_user()`) and be very specific about the fields that the relying party is requesting.

**Comment by vicraj** [comment]
Being specific about the fields being requested would be better.

**Comment by tcmitchell** [comment]
If the data is available at the time this page is displayed, perhaps we could provide a table with an English phrase for each attribute (i.e. "Project Names" instead of "http://geni.net/projects") and the value of that attribute, or some reasonable printed version of that value.

**Comment by ahelsing** [comment]
New page looks like this. Comments?

![screen shot 2016-07-27 at 11 45 34 am](https://cloud.githubusercontent.com/assets/12136824/17181888/b022d2e8-53ef-11e6-95c6-d893b8368a69.png)

**Comment by tcmitchell** [comment]
A few questions/suggestions on the sample page:

* Can the projects list just have the names, not the UUIDs?
* Can we omit rows where values are empty (i.e. that PHP would cast to false)?
* Can we use the original URN instead of the URN encoded for OpenID?

**Comment by ahelsing** [comment]
Done. Better?

![screen shot 2016-07-27 at 12 43 01 pm](https://cloud.githubusercontent.com/assets/12136824/17183927/b3670872-53f7-11e6-81b5-5e786880761d.png)

**Comment by tcmitchell** [comment]
Looks good. A nit: use a colon instead of a period at the end of the first sentence ("You are about to release...")

**Comment by ahelsing** [comment]
done

**Comment by tcmitchell** [comment]
Looks good, thanks

**Comment by vicraj** [comment]
This is very nice. Thank you!

The page say "Do you trust <URL>?".  Can we instead say something like 
"Do you trust SAVI (<URL for SAVI>)?" Not sure the URL alone will mean 
much to the user.

**Comment by tcmitchell** [comment]
To the best of my knowledge we don't get any more information than the URL in the OpenID protocol. We could have a static list of known URLs for "partners", I suppose, and fall back to the URL if it isn't on our known list. Would that be ok?

**Comment by vicraj** [comment]
That would be just fine.  I was hoping you'd know who the partner is 
because the user clicked on a button such as "SAVI" to get to this page.

< Vic

**Comment by tcmitchell** [comment]
@vicraj, please open a new issue for OpenID pretty names. The page you see comes up in response to an OpenID authentication request, not as a direct result of a button press on the portal. We'd need to explore options to choose the best way to convert the URLs to pretty names. There may a way for the relying party to specify their pretty name as part of the protocol, for instance. We can also include a mapping for known URLs in a config file.

**Comment by vicraj** [comment]
Do you still want me to do this?  I see the "pretty name" now when, for 
example, I click on the button for "SAVI".

< Vic

**Comment by tcmitchell** [comment]
The OpenID page still shows URLs. That SAVI page is not an OpenID display. As long as you're ok with the OpenID URLs, and per our discussion you are, no issue needs to be open. If that changes in the future, please open a new issue to display pretty names instead of OpenID server URLs.
