### ISSUE TITLE
bulk add to project

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#171]
Provide some way for a professor to create accounts for all their students.
Or a tutorial leader.

 _Imported from trac ticket [#171](http://trac.gpolab.bbn.com/proto-ch/ticket/171),  created by ahelsing on 06-25-2012 at 15:00, last modified: 05-14-2013 at 16:59_

**Comment by ahelsing** [comment]
from the aggregates-in-the-lab meeting of 8/15:
```
Bulk account creation: Marshall raised, people like: the ability of a
professor to pre-approve accounts. EG the TA provides a list of email
addresses. It emails the student. They click the link and it logs them in.
JBS: It would also be nice if the student who pre-applied could be auto
approved once the TA submits the pre-approval.
```


_Trac comment by ahelsing on 08-21-2012 at 15:18_

**Comment by ahelsing** [comment]
We may want this to support Mike Zink's class, for which he'll do testing in mid January.

Note this would be a way to not so much pre-approve accounts, as to pre add them to a given Project (once they manage to log in).

Do we need to add any security rules to verify that InCommon reports (roughly) the same address as the TA entered? Do we care if the TA emails my BBN address and InCommon reports my geni address? Is there any danger that someone else uses that 1 time link that was meant for me? 

Would the link have an expiration time on it?


_Trac comment by ahelsing on 12-18-2012 at 14:53_

**Comment by seledwards** [comment]
Seconding this.  It was a huge problem at the GEC16 tutorials.

_Trac comment by sedwards (github user: seledwards) on 03-22-2013 at 23:07_

**Comment by MarshallBrinn** [comment]
I am working on this now - I have a prototype checked into branch tkt171-bulkenroll. 

It takes a CSV file of [name, role (optional, default=Member)](email,) and allows you to upload such a file. 
Then one can edit their actions, but essentially it will add all the members whose emails are recognized, and invite those
who are not. Then the email contains a URL that the user can click on to  accept an invitaiton.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-03-2013 at 15:43_

**Comment by seledwards** [comment]
This is done.

_Trac comment by sedwards (github user: seledwards) on 05-14-2013 at 16:59_
