### ISSUE TITLE
Add Global Node Button Sometimes Fails 

### ISSUE THREAD

**Issue by BenNewton1** [GENI-NSF/geni-portal#1718]
When creating a topology in Jacks, if you draw a topology and then select a Site, and with the site entry panel open on the left,  you then click Add Global Node, it sometimes doesn't appear to add a Global Node  (Either in the GUI or the rpsec).  The only thing that happens is the panel on the left closes.  Clicking the button a second time usually resolves the issue.

**Comment by tcmitchell** [comment]
This is easy to reproduce. Go to the add resources page, add a Xen VM, then set the site to an InstaGENI site and leave the site configuration drawer (slide out on left side) open. Then click the "Add Global Node" button. No global node is added. Click the "Add Global Node" button again and the global node gets added.

**Comment by tcmitchell** [comment]
Fixed by #1719
