### ISSUE TITLE
Make button-like things be buttons

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#175]
On `edit-project.php`, `tools-profile.php`, and `createslice.php` there are places that should be buttons with bold labels.

Note that perhaps the boldness of buttons should be controlled in the css stylesheet.

 _Imported from trac ticket [#175](http://trac.gpolab.bbn.com/proto-ch/ticket/175),  created by sedwards on 06-25-2012 at 16:49, last modified: 07-31-2013 at 12:22_

**Comment by ahelsing** [comment]
a quick review should be able to resolve this

_Trac comment by ahelsing on 10-30-2012 at 16:07_

**Comment by ahelsing** [comment]
Fixed. Added as part of #717.

_Trac comment by bujcich on 07-31-2013 at 12:21_
