### ISSUE TITLE
Link to Monitoring pages on Aggregate Status pages

### ISSUE THREAD

**Issue by vicraj** [GENI-NSF/geni-portal#1751]
Please add the following text (or something similar) to the top of the aggregate status summary page (https://portal.geni.net/amstatus.php).

The following is a summary up/down status for each aggregate as reported by [GENI Monitoring](https://genimon.uky.edu/login).  For detailed information go to the [monitoring page](https://genimon.uky.edu/login) and click on the blue "Aggregate Status Page" button (no login required).

**Comment by tcmitchell** [comment]
Should the same or similar text go on the [aggregate status tab of the home page](https://portal.geni.net/secure/dashboard.php#status)?
