### ISSUE TITLE
xml-rpc API for pending join requests

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-portal#1773]
It would be nice if the pending project join requests were accessible from tools other than the portal web UI.

**Comment by tcmitchell** [comment]
There is a request API in the [clearinghouse](https://github.com/GENI-NSF/geni-ch) to manage join requests. This is the API that the portal uses. The API has thus far been undocumented. I have taken a stab at [documenting the request API](https://github.com/GENI-NSF/geni-ch/blob/develop/docs/RequestAPI.adoc).

It should be possible to use the request API to view pending requests and close them. Note, however, that the request API only manages the request objects themselves. It does not add experimenters to projects. Other slice authority API methods must be used to add experimenters to projects.

Caution:

* This documentation was hastily assembled and may be inaccurate
* The API may be frustrating to use
* The API may also be buggy if used in ways the portal does not use it.

Bug reports and/or pull requests on the API and the documentation (such as it is) are welcome in the [geni-ch](https://github.com/GENI-NSF/geni-ch) repository.

**Comment by nbastin** [comment]
Just as a note, we already support adding people to projects through geni-lib but you have to know the URNs to add ahead of time (we do this for our classes, but it's not really the most user-friendly thing to suggest to other instructors to use).  With this API we can write tools with geni-lib to handle the requests and the joins.
