### ISSUE TITLE
slice credentials for GMOC staff

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#178]
We need to work out how operators / GMOC get credentials that let them read things they need to read, and do emergency shutdown if necessary.

 _Imported from trac ticket [#178](http://trac.gpolab.bbn.com/proto-ch/ticket/178),  created by ahelsing on 06-29-2012 at 09:15, last modified: 02-18-2013 at 09:18_

**Comment by ahelsing** [comment]
This means slice credentials: you aren't in this slice but you're an operator, so you can get the slice credential.

And the portal needs to show the shutdown button for you

_Trac comment by ahelsing on 10-30-2012 at 16:03_

**Comment by ahelsing** [comment]
For GEC16, via Omni people with the operator privilege (i.e. the SW group) will be able to get any slice credential. But no Portal pages.

_Trac comment by ahelsing on 02-12-2013 at 15:38_

**Comment by tcmitchell** [comment]
This capability has been tested and documented at http://groups.geni.net/syseng/wiki/SwClearinghouse/OperatorPrivilege

_Trac comment by tmitchel (github user: tcmitchell) on 02-18-2013 at 09:18_
