### ISSUE TITLE
Error reported while uploading public RSpec

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#1797]
When uploading an RSpes for public use,  the operation fails with this error:

_Not Found
  The requested URL /secure/profile was not found on this server."_

Note that the RSpec is uploaded even though an error is reported.  Also according to Tom Mitchell: 

_"This is similar to an issue you reported in January shortly after the move to Amazon Web Services. Please open a new issue on GitHub so that this one can be addressed. For reference, the other issue you reported is at: https://github.com/GENI-NSF/geni-portal/issues/1778"_

**Comment by tcmitchell** [comment]
The upload operation succeeds, and then there is a redirect error. This involves a mismatch between the code and the Apache configuration. Make the code safer by always specifying `.php` on redirect URLs.
