### ISSUE TITLE
Check in and install `logging.conf`

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#18]
Add `logging.config` to git and have it installed in the right place on the portal host.

 _Imported from trac ticket [#18](http://trac.gpolab.bbn.com/proto-ch/ticket/18),  created by tmitchel on 05-23-2012 at 13:45, last modified: 05-24-2012 at 12:26_

**Comment by seledwards** [comment]
Added `logging.conf` and added reference to it in the `portal` Makefile.

_Trac comment by sedwards (github user: seledwards) on 05-24-2012 at 12:24_

**Comment by seledwards** [comment]
Closing.  Will reopen if there are issues.

_Trac comment by sedwards (github user: seledwards) on 05-24-2012 at 12:26_
