### ISSUE TITLE
address coding sprint critiques

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#180]
Rob/Jeff/Prateek didn't like several things about our key management. See if we can address their critiques.

From my notes:
```
The clearinghouse generates your keys, and stores your private keys. The
portal is a privileged client of the clearinghouse, and is authorized to
get your private key and act on your behalf when talking to aggregates.
(Experimenters may also download their certificate and key, and never
use the portal). In addition, the proxy aggregates that the GPO is
building are also privileged clients of the clearinghouse, and are
authorized to retrieve your keys from the clearinghouse, and act as the
experimenter when talking to aggregates. Jeff, Rob, and Prateek
expressed concerns with this approach.
 - In the name of protecting naive users, all users are required to give
up control of their private keys. There should be a way for more
advanced users to retain control of their private keys - both for normal
use of the Clearinghouse and AM APIs, and for use with proxy aggregates.
 - Only tools that run local to the experimenter and are explicitly
authorized by the experimenter should be able to identify themselves as
the experimenter in the AM API. The portal and proxy are not local. A
proxy should identify itself as a proxy.
 - Tools that are not local to the experimenter should have their own keys.
 - Only privileged proxies are currently supported. There should be a
way for an experimenter to authorize a proxy aggregate, and for that
proxy to identify the 'real' experimenter when talking to the aggregate
(see
http://groups.geni.net/geni/wiki/GAPI_AM_API_DRAFT?version=47#ChangeSetJ:Proxyaggregatemanagersaresupported).
This requires something like a 'Speaks For' assertion, signed by the
experimenter.
 - Currently, the portal tool only works with experimenters with
accounts at the GENI Clearinghouse identity provider. Rob would like it
to be available to ProtoGENI users directly.

Several solutions to these critiques were discussed, but nothing was
resolved. Jeff and Prateek suggested an ABAC style 'Speaks For'
assertion, that an experimenter could sign and grant to a tool,
particularly to a proxy aggregate. Rob suggested developing some
Javascript that could run in a browser, and could retrieve an
experimenters password protected private key (either from a server or a
local file), and sign statements on behalf of the experimenter. In
particular, this would allow an experimenter to sign a 'Speaks For'
assertion with some short expiration, without having to locally manage
their private key, if the experimenter doesn't want to do so. Jeff
suggested a button in the portal where the experimenter explicitly
grants permission for the proxy and/or portal to 'Speaks For' them
(again, with some short expiration time.
```

 _Imported from trac ticket [#180](http://trac.gpolab.bbn.com/proto-ch/ticket/180),  created by ahelsing on 07-12-2012 at 11:31, last modified: 11-30-2012 at 16:14_

**Comment by ahelsing** [comment]
review this relative to the GEC15 coding sprint and what we've done with the KM. Is this all done?

_Trac comment by ahelsing on 10-30-2012 at 16:01_

**Comment by tcmitchell** [comment]
Most of these topics were discussed further at the GEC 15 coding sprint. Some are closed issues, some are still under discussion for various reasons. Those that are still open are being tracked individually elsewhere.

 * Users are no longer required to give up control of their private keys. There is now a way to upload a certificate signing request while keeping the private key private. The resulting certificate can then be downloaded and used with tools like omni or Flack (but not with the portal).
 * The KM provides a way for a user to authorize the portal (or not) as a tool they trust.
 * Non-local tools, like the portal, now have their own keys. The portal uses those keys to retrieve an experimenter certificate specific to the portal. This is Speaks As, and is discussed below.
 * Proxy Aggregates are not active at this time, and there are no immediate plans to put them in place. If that choice is revisited, some of the above commentary will need to be revisited as well.
 * Use of the portal by ProtoGENI users is not currently supported. This came up again at GEC 15 and is a topic under investigation.

 * Speaks As vs. Speaks For is still an issue. There is agreement on all sides that Speaks For is preferable. There is currently no mechanism for doing Speaks For in GENI without effort towards design and implementation on the part of numerous developers and projects. We will continue to work towards Speaks For, but until that is ready, Speaks As is the only way for a tool like the portal to properly identify the experimenter who is requesting actions in GENI.

_Trac comment by tmitchel (github user: tcmitchell) on 11-30-2012 at 16:14_
