### ISSUE TITLE
Have CH SA submit monitoring info to GMOC DB

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#181]
The clearinghouse SA should report information to the GMOC DB.

GMOC interfaces may be getting revamped in the August time frame, so we should wait to do this until September.

 _Imported from trac ticket [#181](http://trac.gpolab.bbn.com/proto-ch/ticket/181),  created by sedwards on 07-19-2012 at 10:20, last modified: 10-26-2012 at 11:05_

**Comment by seledwards** [comment]
In particular, the SA should report slice related info (creation, expiration, people) to GMOC.

_Trac comment by sedwards (github user: seledwards) on 09-11-2012 at 13:49_

**Comment by seledwards** [comment]
This code is written but Chaos is going to manage it via puppet.

See [syseng ticket 4263](http://groups.geni.net/syseng/ticket/4263)

_Trac comment by sedwards (github user: seledwards) on 10-18-2012 at 10:20_

**Comment by tcmitchell** [comment]
This appears to be complete.

_Trac comment by tmitchel (github user: tcmitchell) on 10-26-2012 at 11:05_
