### ISSUE TITLE
Allow operations at single aggregates

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#182]
This is an issue of renewing and deleting slivers at different aggregates. We can already create slivers on different aggregates.

 _Imported from trac ticket [#182](http://trac.gpolab.bbn.com/proto-ch/ticket/182),  created by sedwards on 07-23-2012 at 13:21, last modified: 09-21-2012 at 16:22_

**Comment by MarshallBrinn** [comment]
This is really an issue of renewing and deleting slivers at different aggregates. We can already create slivers on different aggregates.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 15:13_

**Comment by seledwards** [comment]
Added single AM versions of sliverstatus (pretty and raw versions), manifest (pretty and raw versions) and delete to slice.php.

Closing.

_Trac comment by sedwards (github user: seledwards) on 09-21-2012 at 16:22_
