### ISSUE TITLE
Syslog of critical events

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#190]
Need to add a capability to log certain critical events (logging in, creating accounts) to syslog and not merely to the AM API.

 _Imported from trac ticket [#190](http://trac.gpolab.bbn.com/proto-ch/ticket/190),  created by mbrinn on 08-21-2012 at 07:49, last modified: 09-25-2012 at 16:48_

**Comment by MarshallBrinn** [comment]
From ticket 108:

http://php.net/manual/en/function.syslog.php

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:12_

**Comment by ahelsing** [comment]
FYI, we believe that PHP logs to the `user` facility by default, so anything you syslog should show up in `/var/log/user.log` on the relevant machine.

_Trac comment by chaos on 08-21-2012 at 09:24_

**Comment by ahelsing** [comment]
Huh, never mind: that link actually suggests explicitly setting a facility.  In that case, take a look at:
```
/etc/rsyslog.d/50-default.conf
```
to see where things are likely to wind up depending on which facility you set.  Infra captures everything, so we are more-or-less indifferent to what you pick.

_Trac comment by chaos on 08-21-2012 at 09:25_

**Comment by tcmitchell** [comment]
The issue about syslog and apache errors that I mentioned is described at http://www.php.net/manual/en/function.syslog.php#97843

Reading more carefully, it looks like we won't have that problem. The issue appears to only happen if apache is configured to use syslog, but the default on ubuntu (which we use) does not use syslog for apache logs. Our config is:
```
ErrorLog /var/log/apache2/error.log
```

So let's give syslog a try. Relevant documentation:
 * http://php.net/manual/en/function.syslog.php
 * http://www.php.net/manual/en/function.openlog.php
 * http://www.php.net/manual/en/function.closelog.php


_Trac comment by tmitchel (github user: tcmitchell) on 08-21-2012 at 16:35_

**Comment by MarshallBrinn** [comment]
Added a new PHP utility : geni_syslog.php which can put things in the "USER" log.

I made a call in header.php to log every time the SHIB session ID changes (which is a proxy for a user login).

Next, I'll put AM actions from the portal.

Once the MA is ready, I'll put in MA create actions.


_Trac comment by mbrinn (github user: MarshallBrinn) on 08-23-2012 at 16:48_

**Comment by ahelsing** [comment]
To do
 - Check that MA and SA are being logged


_Trac comment by ahelsing on 09-24-2012 at 16:37_

**Comment by tcmitchell** [comment]
MA events are logged. Added SA CreateSliver and RenewSliver logging to syslog (user).

_Trac comment by tmitchel (github user: tcmitchell) on 09-25-2012 at 16:48_
