### ISSUE TITLE
Log all aggregate calls

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#191]
Add logging of any invocation of AM API calls from the portal.

 _Imported from trac ticket [#191](http://trac.gpolab.bbn.com/proto-ch/ticket/191),  created by mbrinn on 08-21-2012 at 07:52, last modified: 09-17-2012 at 13:41_

**Comment by tcmitchell** [comment]
All calls are now logged to syslog and to the logging service.

_Trac comment by tmitchel (github user: tcmitchell) on 09-17-2012 at 13:41_
