### ISSUE TITLE
Logging in Proxy AM

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#192]
Need to add CH logging to proxy AM to capture all AM calls that flow through the proxy. 

Per our discussion 8/20, we won't make this a priority for GEC15.

 _Imported from trac ticket [#192](http://trac.gpolab.bbn.com/proto-ch/ticket/192),  created by mbrinn on 08-21-2012 at 07:53, last modified: 11-21-2013 at 15:55_

**Comment by ahelsing** [comment]
we no longer intend to do the proxy AM

_Trac comment by ahelsing on 11-21-2013 at 15:55_
