### ISSUE TITLE
Separate Portal and User and Key management

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#194]
Remove anything privileges from portal in terms of user or key management, and make it just a regular tool, with privileges (access to keys) set by standard privilege mechanisms.

 _Imported from trac ticket [#194](http://trac.gpolab.bbn.com/proto-ch/ticket/194),  created by mbrinn on 08-21-2012 at 07:54, last modified: 09-06-2012 at 22:46_

**Comment by MarshallBrinn** [comment]
From (duplicate) ticket 21:

The portal does too much with respect to user management, and the MA does too little. Cause the MA to do more, and expose APIs so that the portal can access the information it needs.

Make sure accounts belong to the MA. Identity, membership, certs/keys. All in the MA


_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:35_

**Comment by tcmitchell** [comment]
The bulk of this task is complete. Bugs and further enhancements should be handled on other tickets.

_Trac comment by tmitchel (github user: tcmitchell) on 09-06-2012 at 22:46_
