### ISSUE TITLE
Parse manifest RSpecs for pretty display in portal

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#20]
Parse the manifest RSpec output from omni (CreateSliver and ListResources) for pretty display on portal pages.

 _Imported from trac ticket [#20](http://trac.gpolab.bbn.com/proto-ch/ticket/20),  created by tmitchel on 05-23-2012 at 13:48, last modified: 06-03-2012 at 21:50_

**Comment by seledwards** [comment]
Started this.  Currently printing nodes and links as lists.

_Trac comment by sedwards (github user: seledwards) on 05-25-2012 at 22:10_

**Comment by seledwards** [comment]
Now formatting info as tables.

Closing.

_Trac comment by sedwards (github user: seledwards) on 06-03-2012 at 21:50_
