### ISSUE TITLE
dont hardcode URNs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#207]
Currently, the CH logs creation of assertions (which aren't intelligible, e.g.
Created assertion ATTRIB=1 PRINC=31455b21-9f4f-4dc5-8f68-ea448a7b319f
Instead, we should have the PA and SA log something like
User X added to Project/Slice Y in role Z

 _Imported from trac ticket [#207](http://trac.gpolab.bbn.com/proto-ch/ticket/207),  created by mbrinn on 09-7-2012, last modified: 09-07-2012_

**Comment by tcmitchell** [comment]
Looking for hardcoded URNs:
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
reveals occurrences in:
 * `lib/php/am_client.php`
 * `portal/gcf.d/gcf.ini`
 * `portal/www/portal/db-util.php`
 * `portal/www/portal/flack.php`
 * `sa/php/sa_db.php`


_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2012 at 08:38_

**Comment by tcmitchell** [comment]
Looking again for hardcoded URNs:
```
find . -type f -exec grep -H -i ':gpo:' {} \;
```
reveals occurrences in:
 * `lib/php/am_client.php`
 * `portal/gcf.d/gcf.ini`
 * `portal/gcf.d/omni.ini`
 * `portal/www/portal/db-util.php`
 * `portal/www/portal/flack.php`
 * `sa/php/sa_db.php`


_Trac comment by tmitchel (github user: tcmitchell) on 08-20-2012 at 17:09_

**Comment by ahelsing** [comment]
This is fixed - we now have proper logging of membership additions (not assertions)
Additionally, added time sorting to the lists shown on portal.

_mbrinn 9/7/12_
