### ISSUE TITLE
Add port to ssh command for ProtoGENI VMs

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#208]
After successfully adding a sliver via the portal, an ssh command is shown in the resulting table of information. In the case of ProtoGENI VMs, the command requires a port number, which is available in the underlying manifest. Add the "-p <port number>" to the displayed ssh command.

 _Imported from trac ticket [#208](http://trac.gpolab.bbn.com/proto-ch/ticket/208),  created by tmitchel on 09-11-2012 at 16:00, last modified: 10-18-2012 at 10:23_

**Comment by seledwards** [comment]
I tried this against the PG and Kentucky and got the following manifest which includes the port number in the `<login>` tag:

```
<rspec type="manifest" xmlns="http://www.protogeni.net/resources/rspec/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.protogeni.net/resources/rspec/2                            http://www.protogeni.net/resources/rspec/2/manifest.xsd">
    <node client_id="my-node" component_id="urn:publicid:IDN+uky.emulab.net+node+pc62" component_manager_id="urn:publicid:IDN+uky.emulab.net+authority+cm" exclusive="false" sliver_id="urn:publicid:IDN+uky.emulab.net+sliver+55976">
        <sliver_type name="emulab-openvz"/>
      <rs:vnode name="pcvm62-1" xmlns:rs="http://www.protogeni.net/resources/rspec/ext/emulab/1"/>    <host name="my-node.setest.pgeni-gpolab-bbn-com.uky.emulab.net"/>    <services>      <login authentication="ssh-keys" hostname="pc62.uky.emulab.net" port="33594" username="sedwards"/>    </services>  </node>
</rspec>

```

Checking now to see if can replicate with the portal.

_Trac comment by sedwards (github user: seledwards) on 09-24-2012 at 09:44_

**Comment by seledwards** [comment]
Added some text to line 212 in `proto-ch/portal/www/portal/print-text-helpers.php`.

Added port number if it exists and isn't port 22 (ssh).

Fixed and closing. 

Reopen if there are any issues.



_Trac comment by sedwards (github user: seledwards) on 09-24-2012 at 10:07_

**Comment by seledwards** [comment]
This didn't work on panther. Fix it!

_Trac comment by sedwards (github user: seledwards) on 09-27-2012 at 14:44_

**Comment by ahelsing** [comment]
`!$port==22` is not the same as `$port!==22`

I believe that's the bug.


_Trac comment by ahelsing on 10-09-2012 at 15:48_

**Comment by seledwards** [comment]
D'oh!  

Checked in the fix.  Can't test due to VMs being down, leaving open.

_Trac comment by sedwards (github user: seledwards) on 10-09-2012 at 15:59_

**Comment by seledwards** [comment]
Aaron says this is fixed. Closing.

_Trac comment by sedwards (github user: seledwards) on 10-18-2012 at 10:23_
