### ISSUE TITLE
improve portal/MA interactions

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#21]
The portal does too much with respect to user management, and the MA does too little. Cause the MA to do more, and expose APIs so that the portal can access the information it needs.

 _Imported from trac ticket [#21](http://trac.gpolab.bbn.com/proto-ch/ticket/21),  created by tmitchel on 05-23-2012 at 13:54, last modified: 09-05-2012 at 10:40_

**Comment by ahelsing** [comment]
Make sure accounts belong to the MA. Identity, membership, certs/keys. All in the MA


_Trac comment by ahelsing on 06-25-2012 at 14:38_

**Comment by MarshallBrinn** [comment]
I believe this is subsumed by a number of efforts that Tom has been doing to rework the MA and refactor the portal.

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-05-2012 at 10:40_
