### ISSUE TITLE
Send email when user SSL certs are about to expire

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#211]
Mark Berman points out that ProtoGENI sends a nice email like the following when certs are about to expire and recommends that this would be a nice feature of the GENI clearinghouse: 

```
From: testbed-ops@ops.pgeni.gpolab.bbn.com
Subject: PGENI.GPOLAB.BBN.COM: Emulab SSL Certificate Expiring!
Date: September 12, 2012 6:00:02 AM EDT
To: Mark Berman <mberman@bbn.com>

Your encrypted emulab certificate is going to expire on 2012-09-19 11:18:42.
To generate a new certificate, please go to:

   https://www.pgeni.gpolab.bbn.com/gensslcert.php3?user=10004
```

 _Imported from trac ticket [#211](http://trac.gpolab.bbn.com/proto-ch/ticket/211),  created by sedwards on 09-13-2012 at 13:13, last modified: 12-11-2013 at 09:34_
   CCing: mberman@...

**Comment by seledwards** [comment]
See also #241.

_Trac comment by sedwards (github user: seledwards) on 06-21-2013 at 09:19_

**Comment by ahelsing** [comment]
Replaced by chapi ticket 169

_Trac comment by ahelsing on 12-11-2013 at 09:34_
