### ISSUE TITLE
SA must notify experimenters about expiring slices

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#212]
The SA does not expire slices.
It needs a daemon to expire slices. Then the portal can see that the slice has expired, before trying to operate on it.
And then we can also do a notification process to warn experimenters of slices that will expires soon.

 _Imported from trac ticket [#212](http://trac.gpolab.bbn.com/proto-ch/ticket/212),  created by ahelsing on 09-18-2012 at 16:22, last modified: 12-11-2013 at 09:36_

**Comment by ahelsing** [comment]
Could be related to ticket #211


_Trac comment by ahelsing on 10-30-2012 at 15:49_

**Comment by tcmitchell** [comment]
Slices are expired by the SA, but no notification occurs at this time.

_Trac comment by tmitchel (github user: tcmitchell) on 02-11-2013 at 17:35_

**Comment by tcmitchell** [comment]
This should be OBE with the new CH.

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:25_

**Comment by ahelsing** [comment]
Replaced by chapi ticket 170

_Trac comment by ahelsing on 12-11-2013 at 09:36_
