### ISSUE TITLE
Upload SSH keys fails

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#213]
When I try to upload an SSH key, it fails.

Apache error log says:
```

[Wed Sep 19 14:56:37 2012] [error] [client 128.89.81.32] SCRIPT_NAME = /secure/uploadsshkey.php, referer: https://illyrica.gpolab.bbn.com/secure/uploadsshkey.php
[Wed Sep 19 14:56:37 2012] [error] [client 128.89.81.32] ERROR.CODE 3, referer: https://illyrica.gpolab.bbn.com/secure/uploadsshkey.php
[Wed Sep 19 14:56:37 2012] [error] [client 128.89.81.32] ERROR.VALUE , referer: https://illyrica.gpolab.bbn.com/secure/uploadsshkey.php
[Wed Sep 19 14:56:37 2012] [error] [client 128.89.81.32] ERROR.OUTPUT  is not authorized to register_ssh_key., referer: https://illyrica.gpolab.bbn.com/secure/uploadsshkey.php
```

 _Imported from trac ticket [#213](http://trac.gpolab.bbn.com/proto-ch/ticket/213),  created by ahelsing on 09-19-2012 at 15:09, last modified: 09-19-2012 at 16:39_

**Comment by tcmitchell** [comment]
The error messages indicate this is a signing problem.

_Trac comment by tmitchel (github user: tcmitchell) on 09-19-2012 at 16:33_

**Comment by tcmitchell** [comment]
The `register_ssh_key` message was going unsigned to the MA. Added the signer arguments to `put_message` and it works.

_Trac comment by tmitchel (github user: tcmitchell) on 09-19-2012 at 16:39_
