### ISSUE TITLE
Flack fails to get user credential

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#214]
I tried to launch flack on a slice.
When trying to get the user credential, Flack says: `ioError: Error #2031`

 _Imported from trac ticket [#214](http://trac.gpolab.bbn.com/proto-ch/ticket/214),  created by ahelsing on 09-19-2012 at 15:35, last modified: 09-21-2012 at 17:13_

**Comment by tcmitchell** [comment]
We've got a conflict brewing. The file `portal/gcf.d/gcf.ini` is needed by `gcf-pgch.py` and `gcf-ch.py`. The former wants to be on port 8443, and the latter wants to be on port 8000. But they read the same data file for their ports. I recently found this conflict and changed the gcf.ini clearinghouse port to 8000 to support "Debug" `ListResources()` (which uncovered an authorization issue at ExoGENI).

I changed the port back to 8443 in gcf.ini and got further. It looks like an issue getting the slice credential:
```
ERROR:gcf-pgch:invokeCH failed to open conn to https://dagoola.gpolab.bbn.com/sa/sa_controller.php: HTTP Error 302: Found
ERROR:gcf-pgch:Exception doing get_slice_cred: invokeCH failed to open conn to https://dagoola.gpolab.bbn.com/sa/sa_controller.php: HTTP Error 302: Found
```

The apache error log contains:
```
[Wed Sep 19 17:52:14 2012] [error] [client 128.89.91.42] DB ERROR CS_AUTH: Array
[Wed Sep 19 17:52:14 2012] [error] [client 128.89.91.42] SCRIPT_NAME = /sa/sa_controller.php
[Wed Sep 19 17:52:14 2012] [error] [client 128.89.91.42] ERROR.CODE 3
[Wed Sep 19 17:52:14 2012] [error] [client 128.89.91.42] ERROR.VALUE -1
[Wed Sep 19 17:52:14 2012] [error] [client 128.89.91.42] ERROR.OUTPUT No authorization for action get_slice_credential for  in context 2 52f2cd33-7167-44d3-b7e1-18a12a95e245
```

That looks like it might be a signing issue.

_Trac comment by tmitchel (github user: tcmitchell) on 09-19-2012 at 17:55_

**Comment by ahelsing** [comment]
I believe both gcf-ch and gcf-pgch accept the -c argument to specify the path to the gcf.ini file. 

They also both accept the -p argument to specify the server port, if we want to do it that way.

We just need to split those up.

_Trac comment by ahelsing on 09-20-2012 at 08:32_

**Comment by tcmitchell** [comment]
Added logging to gcf am2.py to capture internal errors to track down why Flack reports an error when am2 returns code 12 (no slice found) from ListResources(slice_urn) if the slice has no resources at the AM.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 15:14_

**Comment by tcmitchell** [comment]
Flack is working once again. Message signing was added to pgch, fixing most of the issues.

am2.py seems to be incompatible with Flack and it seems to be on the Flack side. I've asked Matt to take a look.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 17:13_
