### ISSUE TITLE
OBE: MA must produce user credentials

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#216]
We run gcf-ch in order to get user credentials only, which are required to get Ad RSpecs.

The MA should provide these instead, so we don't need gcf-ch

 _Imported from trac ticket [#216](http://trac.gpolab.bbn.com/proto-ch/ticket/216),  created by ahelsing on 09-20-2012 at 09:53, last modified: 12-05-2013 at 13:18_

**Comment by tcmitchell** [comment]
This should be OBE with the new CH.

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:29_

**Comment by MarshallBrinn** [comment]
The new CH handles this.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-21-2013 at 15:18_
