### ISSUE TITLE
Add message signing to pgch

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#218]
pgch must do message signing.

We will treat pgch and flack as part of the portal. pgch will use portal keys to retrieve the user's inside keys (authorized for portal).

Then pgch can sign messages.

Later, figure out if we can lock down pgch to only accept connections from our portal-launched flack.

 _Imported from trac ticket [#218](http://trac.gpolab.bbn.com/proto-ch/ticket/218),  created by ahelsing on 09-20-2012 at 10:07, last modified: 09-21-2012 at 17:11_

**Comment by tcmitchell** [comment]
There's a bunch of M2Crypto work here. Use the portal key/cert to get the user's inside keys, where user is determined from the SSL client cert. Then use the inside keys for individual calls like get_slice_credential, etc.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 12:25_

**Comment by tcmitchell** [comment]
Added S/MIME message signing to gcf ch_interface.py.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 15:13_

**Comment by tcmitchell** [comment]
Updated pgch.py to use message signing.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 17:11_
