### ISSUE TITLE
Update the host build instructions

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#22]
Sarah took notes when she built sergyar from scratch as a portal/CH host. Update the instructions based on those notes.

Where are they instructions? Add a link here.

 _Imported from trac ticket [#22](http://trac.gpolab.bbn.com/proto-ch/ticket/22),  created by tmitchel on 05-23-2012 at 13:56, last modified: 05-31-2012 at 13:27_

**Comment by seledwards** [comment]
Ok.  Compiled a single set of very rough instructions on this page:
http://groups.geni.net/syseng/wiki/SwClearinghouse/Install

They start out really good and get worse as you go along, but they are something to start with. (That is, the first section or two is pretty accurate, but the last two likely have some holes.)

_Trac comment by sedwards (github user: seledwards) on 05-29-2012 at 18:28_

**Comment by seledwards** [comment]
Tom tried these out.

Closing.

_Trac comment by sedwards (github user: seledwards) on 05-31-2012 at 13:27_
