### ISSUE TITLE
If you register an account without filling in a telephone number there is no obvious error msg

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#220]
I tried to register a new account without filling in the required telephone number and it appeared that nothing was happening.  I didn't see an error message.

 _Imported from trac ticket [#220](http://trac.gpolab.bbn.com/proto-ch/ticket/220),  created by sedwards on 09-20-2012 at 20:46, last modified: 10-02-2012 at 16:21_

**Comment by ahelsing** [comment]
register.php needs Javascript that checks inputs - and complains if a required field is not provided.

Nothing in do-register appears to check validity of inputs (see ticket #2).
Nothing there checks that required fields are provided either.



_Trac comment by ahelsing on 09-21-2012 at 11:45_

**Comment by tcmitchell** [comment]
I believe the MA is returning an error to the client if a required field is missing (the code looks like it does). So do-register could or should be handling and propagating that error.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 11:48_

**Comment by ahelsing** [comment]
It is not checking the return of ma_create_account (line 91), and should be. The return is a DB triple, RESPONSE_ERROR::ARGS when a field is missing, and the message indicates what is missing.


_Trac comment by ahelsing on 09-21-2012 at 11:53_
