### ISSUE TITLE
portal-users mailing list

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#224]
We're going to want a portal-users mailing list at some point. Maybe we can hook this in to registering at the portal directly.

Maybe there is also a portal-project-leads list?

 _Imported from trac ticket [#224](http://trac.gpolab.bbn.com/proto-ch/ticket/224),  created by ahelsing on 09-21-2012 at 10:40, last modified: 12-05-2013 at 12:59_

**Comment by ahelsing** [comment]
We talked about having the portal run an MTA (mail server) at one point, right?  I don't remember what the status of that is, but it should be possible for any MTA or mailing list manager to populate a mailing list based on the contents of a flat file.  So if you can dump your list of user email addresses out one-per-line as a flat file, sending mail to them under a common name is easy.

_Trac comment by chaos on 09-21-2012 at 10:44_

**Comment by ahelsing** [comment]
maybe instead we piggy-back on the geni-users mailing list if/when there is one

_Trac comment by ahelsing on 10-30-2012 at 15:41_

**Comment by tcmitchell** [comment]
There is a geni-users google group now. This is OBE.
