### ISSUE TITLE
RSpecs: Allow editing properties

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#226]
We need a way to edit the RSpec name and description, and change its visibility.

Also:
 * Remove visibility column from tables (it is always redundant info)
 * Add the owner's name to public rspecs and make it a mailto link

 _Imported from trac ticket [#226](http://trac.gpolab.bbn.com/proto-ch/ticket/226),  created by ahelsing on 09-21-2012 at 11:11, last modified: 06-02-2014 at 16:04_

**Comment by seledwards** [comment]
FYI.  Deletion of RSpecs works.

_Trac comment by sedwards (github user: seledwards) on 02-08-2013 at 21:06_

**Comment by seledwards** [comment]
Jeanne Ohren just asked me about whether it was possible to change an rspec from private to public. 

_Trac comment by sedwards (github user: seledwards) on 06-14-2013 at 15:15_

**Comment by tcmitchell** [comment]
In addition to editing name, description, and visibility, experimenter support has requested:
 * Remove visibility column from tables (it is always redundant info)
 * Add the owner's name to public rspecs and make it a mailto link

_Trac comment by tmitchel (github user: tcmitchell) on 05-20-2014 at 12:24_

**Comment by tcmitchell** [comment]
A prototype is available for internal review.

_Trac comment by tmitchel (github user: tcmitchell) on 05-21-2014 at 16:18_

**Comment by innnkkki** [comment]
I think this is great! A few quick comments:
  1. Is it easy in the edit page of an rspec to also add an option of "Upload a new version"? This will just overwrite the old rspec
  2. Is it easy on the email window that pops up when I click on a name to have a default subject:
      "About GENI Portal rspec: <rspec_name>"?

_Trac comment by nriga (github user: innnkkki) on 05-21-2014 at 16:49_

**Comment by tcmitchell** [comment]
Replying to [nriga](comment:13):

 1. While not hard, file upload is out of scope for this ticket and for the feature request for GEC 20. I have created issue #1035 for this enhancement request.
 2. Adding a subject to the mailto link is easy. This is done and available for preview internally.

_Trac comment by tmitchel (github user: tcmitchell) on 05-21-2014 at 17:26_

**Comment by tcmitchell** [comment]
Experimenter support has asked that this enhancement be delayed to a later release.

_Trac comment by tmitchel (github user: tcmitchell) on 05-27-2014 at 12:34_

**Comment by tcmitchell** [comment]
Watch for a warning:
  [Tue May 27 10:46:09 2014] [error] [client 128.89.69.110] PHP Notice: Undefined property: Member::$email_address in /var/www/secure/tool-rspecs.php on line 137, referer:  https://portal1.gpolab.bbn.com/secure/home.php

_Trac comment by tmitchel (github user: tcmitchell) on 05-27-2014 at 16:47_

**Comment by MarshallBrinn** [comment]
We have a fix for this for testing. Currently installed on marilac and cascade. The fix allows for editing current rspec features as well as replacing their rspec contents (optionally), thus subsuming #1035 (since closed as duplicated).

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-29-2014 at 09:15_

**Comment by tcmitchell** [comment]
This enhancement is complete and merged.

_Trac comment by tmitchel (github user: tcmitchell) on 06-02-2014 at 16:04_
