### ISSUE TITLE
RSpecs: allow online viewing

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#227]
It would be nice to be able to view RSpecs within the portal: Maybe a new tab and let the browser format it or something

 _Imported from trac ticket [#227](http://trac.gpolab.bbn.com/proto-ch/ticket/227),  created by ahelsing on 09-21-2012 at 11:11, last modified: 11-19-2012 at 17:21_

**Comment by seledwards** [comment]
Which of RSpecs are you talking about?

Currently we have a way of parsing manifest RSpecs and also a way of showing their raw text.

Are you thinking about something else?

_Trac comment by sedwards (github user: seledwards) on 09-21-2012 at 11:23_

**Comment by ahelsing** [comment]
All stored RSpecs. This may just be re-using existing code.

_Trac comment by ahelsing on 09-21-2012 at 11:26_

**Comment by tcmitchell** [comment]
RSpecs owned and uploaded by a user are viewable (there is a view button in the rspec table). Other public rspecs (the preloaded ones and those uploaded by other users) are do not appear in the table, and thus are not viewable at present. The viewing occurs in the same tab right now, but that should be easy to change to show in a separate tab. If the view button were a link it would be easy for the user to decide whether to show the rspec in the same tab or a different one.

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2012 at 11:56_

**Comment by seledwards** [comment]
Added a table for public RSpecs.  Don't display Edit and Delete buttons for public RSpecs.

Also changed deleterspec.php to check to make sure this user created the RSpec before letting him to delete it.

The only possible thing to do here is to consider converting buttons to links.  I'm tempted to not bother at the moment.  I think we should make a systemic choice regarding buttons vs links.

Closing for now.

_Trac comment by sedwards (github user: seledwards) on 11-19-2012 at 17:21_
