### ISSUE TITLE
RSpecs: management page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#230]
Under Profile tab, we need a page for managing your RSpecs.

Picture a table with the basic attributes, and then a few buttons
 - Edit
 - Delete
 - Download
 - View
 - Use This

Basic Attributes include
 - Name
 - Description
 - Visibility
 - Last Use (a link to full usage history)
 - Owner / poster?

RSpecs might have additional attributes, but those would be on the edit page

This page also would then have buttons for
 - Search 
 - Upload

 _Imported from trac ticket [#230](http://trac.gpolab.bbn.com/proto-ch/ticket/230),  created by ahelsing on 09-21-2012 at 11:17, last modified: 12-05-2013 at 09:43_

**Comment by ahelsing** [comment]
For GEC15, the various buttons do not need to work (or even be there)


_Trac comment by ahelsing on 09-21-2012 at 11:18_

**Comment by tcmitchell** [comment]
Added a simple RSpec management page. Features include:
 * Table showing name and visibility (public/private) of RSpec
 * Disabled buttons for Edit and Download
 * An Upload button to add new RSpecs


_Trac comment by tmitchel (github user: tcmitchell) on 09-26-2012 at 07:50_

**Comment by tcmitchell** [comment]
Everything is implemented but the following:
 * *Use This_' -- requires infrastructure to supply rspec before slice to add sliver page. Advanced feature.
 * '''Last Use''' -- this info is not available, we don't track and/or store RSpec use
 * '''Owner/poster''' -- this is implicit because you can only manage RSpecs for which you are the owner
 * '_Search* -- advanced feature. What field(s) do we search on? We don't have enough RSpecs to merit adding this feature.

Reassigning to Aaron for thoughts on the missing features.

_Trac comment by tmitchel (github user: tcmitchell) on 09-26-2012 at 12:00_

**Comment by ahelsing** [comment]
- Use This: Right - advanced
 - Last Use: Relevant mostly for manifests. But we should be tracking request use as well. I'm happy with this being advanced.
 - Owner: Can I not search over RSpecs that are public are visible to my project? How does that work?
 - Search - right, this is advanced. As for what to search on: remember how I suggested adding name/value pairs?

We also want
 - View. Sarah has code we might be able to use here that listresources.php uses I think.
 - Delete (can be off of Edit)


_Trac comment by ahelsing on 09-27-2012 at 09:14_

**Comment by tcmitchell** [comment]
View and Delete are implemented, which is why they weren't on the list of things that are not implemented.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2012 at 11:29_

**Comment by tcmitchell** [comment]
On the owner issue, I suppose we could include public RSpecs not owned by the current user, but that set could become onerous and make it difficult to see the ones actually owned by the user. Also, the set of functions available on those would be limited (cannot edit or delete, for instance).

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2012 at 11:31_

**Comment by ahelsing** [comment]
The ticket is old and desires have changed.

_Trac comment by ahelsing on 12-05-2013 at 09:43_
