### ISSUE TITLE
key/cert revocation

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#232]
We need a story on key/cert revocation.

Is there an MA function to do this? A way to get a CRL?

 _Imported from trac ticket [#232](http://trac.gpolab.bbn.com/proto-ch/ticket/232),  created by ahelsing on 09-21-2012 at 11:22, last modified: 12-11-2013 at 09:39_

**Comment by tcmitchell** [comment]
Consider [OCSP](http://www.ietf.org/rfc/rfc2560.txt) as well.

_Trac comment by tmitchel (github user: tcmitchell) on 09-26-2012 at 12:24_

**Comment by ahelsing** [comment]
chapi ticket 171 replaces this

_Trac comment by ahelsing on 12-11-2013 at 09:39_
