### ISSUE TITLE
Flack: update to latest

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#233]
We need to sync up our flack to the latest version, ensuring it includes our local fixes.

We should also figure out our general process for doing this in the future. How often?

 _Imported from trac ticket [#233](http://trac.gpolab.bbn.com/proto-ch/ticket/233),  created by ahelsing on 09-21-2012 at 14:06, last modified: 01-04-2013 at 17:08_

**Comment by MarshallBrinn** [comment]
Done - built the most recent version of flack from scratched and tested it with portal. All seems to work.

Will publish WIKI page describing how to build flack from scratch : SwFlackRebuild

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-04-2013 at 16:53_

**Comment by tcmitchell** [comment]
As part of updating flack, a couple of changes to pgch.py were made:
 * Added logging to ListComponents. It would be nice to have generic logging of some sort on each call at debug level indicating arguments and results. But I didn't go that far.
 * Allowed XML-RPC paths ending in "`/ch`". This was a matter of overriding our SecureXMLRPCRequestHandler to add a tuple of `rpc_paths`). See [python docs](http://docs.python.org/2/library/simplexmlrpcserver.html#SimpleXMLRPCServer.SimpleXMLRPCRequestHandler.rpc_paths).

These changes were also made to gcf, where there is a copy of pgch.py.

_Trac comment by tmitchel (github user: tcmitchell) on 01-04-2013 at 17:08_
