### ISSUE TITLE
Flack: GCF manifests fail

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#234]
Flack does not like the gcf-am manifest RSpecs.

These RSpecs pass rspeclint. But they are missing component_id, component_manager_id, etc. Flack doesn't like that.

Do we fix gcf? Or just not use flack with gcf am?

 _Imported from trac ticket [#234](http://trac.gpolab.bbn.com/proto-ch/ticket/234),  created by ahelsing on 09-21-2012 at 14:33, last modified: 04-07-2014 at 16:44_

**Comment by tcmitchell** [comment]
It should be low effort to add component_id and component_manager_id to the manifest. The AM seems to have them because they're present in the advertisement.

_Trac comment by tmitchel (github user: tcmitchell) on 09-21-2012 at 15:57_
