### ISSUE TITLE
SA fails to detect expired slice

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#235]
get_slice_credential returns successfully with an empty string if the slice is expired. It should return an error indicating that the slice is expired.

 _Imported from trac ticket [#235](http://trac.gpolab.bbn.com/proto-ch/ticket/235),  created by tmitchel on 09-21-2012 at 16:17, last modified: 09-27-2012 at 11:37_

**Comment by tcmitchell** [comment]
Added an "expired" column. SA checks for expiration on each API call (this should be a daemon in the future). Queries check the expired flag. get_slice_credential ensures slices are expired, then checks the requested slice to see if it is expired. If it has expired, an error is returned.

_Trac comment by tmitchel (github user: tcmitchell) on 09-26-2012 at 15:18_

**Comment by tcmitchell** [comment]
There appears to be a problem with get_slice_credential misinterpreting the expired column. It always reports a slice as expired.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2012 at 10:14_

**Comment by tcmitchell** [comment]
This is odd. Sarah sees this issue consistently, and it does not happen for me on dagoola. More info is needed.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2012 at 10:17_

**Comment by tcmitchell** [comment]
I can replicate Sarah's issue, but it presents itself differently. I see the error_text page showing the slice as expired (which is incorrect), while Sarah sees the start of the slice page, and then it stops because of the error redirect happening after some of the HTML is displayed.

As far as the real problem, the expired column is boolean in the database, but is being returned as type string, with value "f". We need a graceful way to interpret that as false.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2012 at 10:27_

**Comment by tcmitchell** [comment]
I added a conversion routine to db_utils to convert the single char to a boolean.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2012 at 11:23_

**Comment by seledwards** [comment]
Just confirming that this change fixed my problem on sergyar.  Thanks!

_Trac comment by sedwards (github user: seledwards) on 09-27-2012 at 11:37_
