### ISSUE TITLE
Flack slice creation does not work with pgch

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#236]
Apparently the return from Resolve misleads Flack into believing the slice name is already taken or otherwise erroneous. It is not possible to create a slice from Flack when using pgch.

 _Imported from trac ticket [#236](http://trac.gpolab.bbn.com/proto-ch/ticket/236),  created by tmitchel on 09-21-2012 at 16:19, last modified: 04-07-2014 at 16:28_

**Comment by ahelsing** [comment]
Could this have something to do with getting the right project name?

_Trac comment by ahelsing on 03-04-2013 at 11:36_
