### ISSUE TITLE
Provide UI for renewing experimenter certificate

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#241]
Allow an experimenter to request an updated certificate when their certificate is expiring. Consider whether they can use the same key pair, or generate a new one.

 _Imported from trac ticket [#241](http://trac.gpolab.bbn.com/proto-ch/ticket/241),  created by tmitchel on 09-26-2012 at 12:22, last modified: 04-28-2014 at 16:59_

**Comment by seledwards** [comment]
See also #211.

_Trac comment by sedwards (github user: seledwards) on 06-21-2013 at 09:19_

**Comment by ahelsing** [comment]
See chapi ticket 169 for the new server side of this

_Trac comment by ahelsing on 12-11-2013 at 09:34_

**Comment by tcmitchell** [comment]
Links and UI are available to renew certificates. Improvements are needed in chapi to maintain private key.

_Trac comment by tmitchel (github user: tcmitchell) on 04-28-2014 at 16:59_
