### ISSUE TITLE
Integrate ExoGENI with Flack

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#243]
Allow Flack to talk to ExoGENI racks by:
 * Asking ExoGENI team to install the flash socket security policy everywhere an SM runs (each rack plus the ExoSM)
 * Update the AM certificates on each SM:
  * They are currently expired
  * They are currently all identical, but should be unique per SM

 _Imported from trac ticket [#243](http://trac.gpolab.bbn.com/proto-ch/ticket/243),  created by ahelsing on 09-27-2012 at 14:00, last modified: 06-07-2013 at 18:09_

**Comment by ahelsing** [comment]
Opened an ExoGENI ticket: http://groups.geni.net/exogeni/ticket/116


_Trac comment by ahelsing on 09-28-2012 at 14:30_

**Comment by ahelsing** [comment]
Note we've discovered that the AM certificate
 1. Is the same at all 3 racks. Meaning that the BBN rack mis-identifies itself
 2. Is expired.

1 or both of these may make Flack refuse to talk to them.


_Trac comment by ahelsing on 10-10-2012 at 10:01_

**Comment by tcmitchell** [comment]
The expired ExoGENI certificate exposes a Flack bug that prevents Flack from communicating to any aggregates (issue #298). These will need to be updated before Flack can communicate with an ExoGENI rack.

_Trac comment by tmitchel (github user: tcmitchell) on 10-18-2012 at 12:55_

**Comment by ahelsing** [comment]
Also, the EG AM certs have no URN in them.

_Trac comment by ahelsing on 03-07-2013 at 14:05_

**Comment by ahelsing** [comment]
From the coding sprint we IDed 4 items
 - flash security policy
 - non expired certs. Gary argues self signed allows people to trust them selectively. Mark wants them signed
 - put the certs in the CH DB (and PG put them in their DB)
 - Ensure the EG AM urns end in +am --- and not +cm, as that is the key Flack uses to decide if the AM is PG or not

_Trac comment by ahelsing on 03-21-2013 at 17:21_

**Comment by ahelsing** [comment]
Later conversations indicate we will want the AM' URN in the subjectAltName

_Trac comment by ahelsing on 03-21-2013 at 19:14_

**Comment by tcmitchell** [comment]
Per the original requirements of this ticket:
 * ExoGENI has enabled the flash security policy on the RENCI rack
  * BBN rack and ExoSM have _not_ had the flash security policy enabled.
 * ExoGENI had already updated the SSL certificates to new certificates that are not expired and are unique to each rack

It is now possible to allocate ExoGENI resources through Flack, although not without some warts:
 * ExoGENI added sliver_type to the advertisement so that Flack knows what kind of resource to request
 * ExoGENI requires an image name and version or the request fails. It's possible to do that in Flack, but it's extra work
  * ExoGENI is willing to put a default image in the RSpec translator, which will help.


_Trac comment by tmitchel (github user: tcmitchell) on 04-05-2013 at 14:09_

**Comment by tcmitchell** [comment]
Still waiting for the ExoGENI team to enable the flash security policy on the ExoSM. That's the last remaining item on this ticket.


_Trac comment by tmitchel (github user: tcmitchell) on 05-08-2013 at 13:04_

**Comment by tcmitchell** [comment]
Ilia says:
  Tom I apologize for the delay. I think the best time to do this will be during our upcoming maintenance window, when we enable other features.

  I anticipate it will be within the next two weeks.


_Trac comment by tmitchel (github user: tcmitchell) on 05-08-2013 at 13:25_

**Comment by tcmitchell** [comment]
Indications are that this will be working. ExoGENI isn't out of maintenance yet, but we've seen the ExoSM show up successfully a couple of times in Flack.

Keep the ticket open until the ExoGENI maintenance is complete and we verify that ExoSM is working.


_Trac comment by tmitchel (github user: tcmitchell) on 05-31-2013 at 22:04_

**Comment by tcmitchell** [comment]
ExoSM now has the flash security policy, so it shows up in Flack.

Unfortunately, I am unable to allocate resources on ExoSM via Flack. I get the following error:

 Task encountered a fault: Error: Embedding workflow ERROR: 1:Insufficient resources or Unknown domain: http://geni-orca.renci.org/owl/exogeni.net.rdf#exogeni.net/Domain/vm:vm:0! Requested: vm:1.
 Please see https://geni-orca.renci.org/trac/wiki/orca-errors for possible solutions.

_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2013 at 12:49_

**Comment by tcmitchell** [comment]
The issue in comment:14 appears to have something to do with Flack using the ExoSM domain, and ExoSM advertising resources from individual rack domains. Flack and ExoSM are crossing each other up. That test was done using the Flack canvas to create the RSpec.

If instead I upload a minimal RSpec, it works:
```xml
<rspec xmlns="http://www.geni.net/resources/rspec/3"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.geni.net/resources/rspec/3 http://www.geni
.net/resources/rspec/3/request.xsd"
       type="request">
  <node client_id="request1" exclusive="false"/>
</rspec>
```

_Trac comment by tmitchel (github user: tcmitchell) on 06-07-2013 at 18:07_

**Comment by tcmitchell** [comment]
We should consider this effort complete. ExoGENI works with Flack thanks to the efforts of both teams.

_Trac comment by tmitchel (github user: tcmitchell) on 06-07-2013 at 18:09_
