### ISSUE TITLE
EG racks: must grab full cert chain and install in SR

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#244]
The SR needs the full certificate chain for the AM of each EG rack - for the AM entry, and then the signer as a trusted CA

 _Imported from trac ticket [#244](http://trac.gpolab.bbn.com/proto-ch/ticket/244),  created by ahelsing on 09-27-2012 at 14:01, last modified: 10-10-2012 at 11:04_

**Comment by tcmitchell** [comment]
Use `openssl s_client`. See:
 * http://www.madboa.com/geek/openssl/#cert-retrieve
 * http://fdmanana.wordpress.com/2008/07/01/getting-a-servers-certificate-with-openssl/

_Trac comment by tmitchel (github user: tcmitchell) on 10-09-2012 at 14:51_

**Comment by ahelsing** [comment]
All 6 possible certs are really the same: ExoSM, EG-BBN and EG-RENCI are all the same cert, all self signed.

So add_exo_ams now has 4 inserts that all include the same file


_Trac comment by ahelsing on 10-10-2012 at 11:04_
