### ISSUE TITLE
Add resources: include all Slice member ssh keys

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#248]
Make sure that the 'Add Resources' page supplies all the SSH keys for all members of a slice with all createsliver calls

 _Imported from trac ticket [#248](http://trac.gpolab.bbn.com/proto-ch/ticket/248),  created by ahelsing on 10-01-2012 at 14:09, last modified: 05-14-2013 at 16:49_

**Comment by seledwards** [comment]
I did a test yesterday which showed that multiple keys for the lead of a slice get loaded when nodes are reserved.

Multiple members in a slice isn't supported yet.

_Trac comment by sedwards (github user: seledwards) on 11-13-2012 at 10:27_

**Comment by ahelsing** [comment]
Note that this should include the separate user URNs, so that each member gets their own unix account at PG based AMs.

Also note that this would mean that resources reserved through the portal have multiple SSH keys, but not those reserved through omni - until we fix that.



_Trac comment by ahelsing on 04-25-2013 at 15:10_

**Comment by seledwards** [comment]
Keys for all members of a slice are now installed via the createsliver command.
Made new related tickets #508, #509, #510.

_Trac comment by sedwards (github user: seledwards) on 05-10-2013 at 15:42_
