### ISSUE TITLE
Add Resources page is slow

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#250]
The Add Resources page is slow, waiting on the AM.
 - parallelize?
 - go to a waiting page?

 _Imported from trac ticket [#250](http://trac.gpolab.bbn.com/proto-ch/ticket/250),  created by ahelsing on 10-01-2012 at 14:37, last modified: 12-04-2012 at 16:35_

**Comment by seledwards** [comment]
Use AJAX to make this render the results page immediately and then update the status when createsliver call is done.  Pass rspec id, agg id, slice id to results page so that it can call createsliver.

_Trac comment by sedwards (github user: seledwards) on 11-27-2012 at 16:15_

**Comment by seledwards** [comment]
* `slice-addresource.php` is the page to select resources to reserve.  It does an HTTP PUT to ...
 * `sliceresource.php` looks up the passed in rspec by id and the AM url and makes the call to createsliver

I think we can move most of the sliver creation into a separate file (perhaps `createsliver.php`) which does all of the heavy lifting and returns the rspec as an XML file (or maybe a json containing XML files) leaving `sliceresource.php` to just load the HTML.  


_Trac comment by sedwards (github user: seledwards) on 11-30-2012 at 22:42_

**Comment by seledwards** [comment]
Ok.  This is done.

`createsliver.php` returns the prettily parsed XML to display on the page.  If something bad happens it returns the error message instead.

If we want to change `createsliver.php` to return the raw XML some day (perhaps based on some flag).  That will be easy to do, but I didn't need it now so I didn't bother.

Closing.

_Trac comment by sedwards (github user: seledwards) on 12-04-2012 at 16:35_
