### ISSUE TITLE
Slice page: drop slice row in status table

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#262]
Drop the whole row about the slice in the status table. This is all information repeated elsewhere

 _Imported from trac ticket [#262](http://trac.gpolab.bbn.com/proto-ch/ticket/262),  created by ahelsing on 10-01-2012 at 15:45, last modified: 10-02-2012 at 16:47_

**Comment by seledwards** [comment]
Oh!  Just saw this ticket.  I would have eliminated the copy of the information from the tool bar and left the copy in the status table below.  That way you get the same information in parallel for slices and slivers.

Just an opinion.

_Trac comment by sedwards (github user: seledwards) on 10-02-2012 at 16:47_
