### ISSUE TITLE
Create interactive map of resources

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#28]
Replace the static map on the landing page and home page with an interactive map.

 _Imported from trac ticket [#28](http://trac.gpolab.bbn.com/proto-ch/ticket/28),  created by tmitchel on 05-23-2012 at 14:13, last modified: 07-31-2013 at 12:22_

**Comment by MarshallBrinn** [comment]
We should take this from GMOC, not create one ourselves.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:02_

**Comment by seledwards** [comment]
Not getting map from GMOC for GEC15.  Moving away from GEC15 milestone.

_Trac comment by sedwards (github user: seledwards) on 10-18-2012 at 10:22_

**Comment by tcmitchell** [comment]
It's not clear whether a map will be available from GMOC. If so, it can be embedded in the portal. If not, we may need to create our own interactive map.

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2012 at 12:06_

**Comment by ahelsing** [comment]
Fixed. Added as part of #717.

_Trac comment by bujcich on 07-31-2013 at 12:21_
