### ISSUE TITLE
Replace help email with portal-help@geni.net

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#282]
New IdP accounts need to use a mailing list that is not help@geni.net

~~Get that address from infra, and~~ The address is portal-help@geni.net, put it on the Sign In Page, and probably login-help.php and most (if not all) places where help@geni.net appears.

 _Imported from trac ticket [#282](http://trac.gpolab.bbn.com/proto-ch/ticket/282),  created by ahelsing on 10-04-2012 at 16:39, last modified: 10-05-2012 at 12:42_

**Comment by ahelsing** [comment]
Mostly done.

1 remaining spot currently says help@geni.net: On the landing page, under 'Find out more about using GENI', there is a linke 'Get help using GENI'

Should that also be portal-help?


_Trac comment by ahelsing on 10-05-2012 at 12:28_

**Comment by tcmitchell** [comment]
I think the "Get help using GENI" link should be left as help@geni.net.

_Trac comment by tmitchel (github user: tcmitchell) on 10-05-2012 at 12:34_
