### ISSUE TITLE
sign in page: pick schools from a drop-down

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#283]
The list of schools to pick from should be a drop-down

 _Imported from trac ticket [#283](http://trac.gpolab.bbn.com/proto-ch/ticket/283),  created by ahelsing on 10-04-2012 at 16:39, last modified: 10-05-2012 at 10:24_

**Comment by tcmitchell** [comment]
The embedded discover service ("sign in page") already has a drop-down list capability. Click on the "Allow me to pick from a list" link and the search box turns into a drop down. When it's a drop down you can return to the search box by clicking "Allow me to specify the site".

_Trac comment by tmitchel (github user: tcmitchell) on 10-05-2012 at 10:24_
