### ISSUE TITLE
Work with Joanne Achin on UI

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#29]
_Imported from trac ticket [#29](http://trac.gpolab.bbn.com/proto-ch/ticket/29),  created by tmitchel on 05-23-2012 at 14:15, last modified: 05-31-2012 at 19:36_

**Comment by seledwards** [comment]
Met with Joanne Achin for an hour and explained what we were doing and why.

The proposal is that she create mockups of the screens and SW Group implement those screens.

Marshall is checking on job number and approval of her spending time on the project.

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 15:00_

**Comment by seledwards** [comment]
Henry approved 20 hours on Joanne's GENI job number for this.

Emailed Joanne and suggested that we talk on Wednesday.  We'll discuss schedule when we talk.

Request an account for her on cetaganda (#61) so that she can see the pages that we already have.

_Trac comment by sedwards (github user: seledwards) on 05-29-2012 at 17:38_

**Comment by seledwards** [comment]
Met with Joanne.  Gave her username and password so she can log in.

She and I will talk again over the course of the next couple of days to answer questions after she's had a chance to log in and look around a bit and develop some questions.

To start with, I owe her a typed up list of steps in the workflow. We'll make sure that's right and that can form the basis of the workflow she'll design.

We discussed schedule.  Our goal is that she and I will meet on the morning of Friday June 15 to go over what she's got for us. (I'm out of town M-Th of that week and she's out of town the Mon-Wed of the following week. So this is the day to do that.)  I'm sure we'll will meet other times before June 15.  She's planning on doing the bulk of the work between Tuesday's demo and June 15.

_Trac comment by sedwards (github user: seledwards) on 05-30-2012 at 14:19_

**Comment by seledwards** [comment]
Wrote up a workflow for the steps of using the CH portal.

E-mailed to Joanne Achin and [posted](http://trac.gpolab.bbn.com/proto-ch/wiki/PortalWorkflow) on the `proto-ch` wiki.

_Trac comment by sedwards (github user: seledwards) on 05-31-2012 at 19:35_

**Comment by seledwards** [comment]
I think I've done the intent of this ticket. 

I'll open separate tickets as they come up from talking with Joanne.

_Trac comment by sedwards (github user: seledwards) on 05-31-2012 at 19:36_
