### ISSUE TITLE
Flack hangs if a server certificate is expired

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#298]
If Flack is given an expired certificate via the `setServerCert()` javascript function, it fails to communicate with any aggregates. Work with Matt to resolve this bug.

The javascript that loads the signer certificates (passed to Flack via `setServerCert()`) throws an exception when it encounters an invalid cert (in this case expired). The thrown exception causes a null http connection object to be returned, but Flack assumes the http connection is valid and tries to use it. The result is that Flack thinks it has sent a request, but no request was sent via the null http connection. Flack hangs.

 _Imported from trac ticket [#298](http://trac.gpolab.bbn.com/proto-ch/ticket/298),  created by tmitchel on 10-18-2012 at 12:53, last modified: 04-07-2014 at 16:32_

**Comment by ahelsing** [comment]
For now, we could have the portal avoid sending Flack expired certificates.

_Trac comment by ahelsing on 10-30-2012 at 15:13_
