### ISSUE TITLE
Remove "account" and "identity" tables

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#299]
User management has moved to the MA. Remove the legacy "account" and "identity" tables, as well as related tables like "account_status", "account_privilege", and "account_slice".

 _Imported from trac ticket [#299](http://trac.gpolab.bbn.com/proto-ch/ticket/299),  created by tmitchel on 10-18-2012 at 13:01, last modified: 03-31-2015 at 10:24_

**Comment by ahelsing** [comment]
We do use the identity table, but only barely - getting the affiliation, provider_url, and other such things. If we ditch these tables, we need to put those things in the MA tables.

_Trac comment by ahelsing on 11-09-2012 at 13:52_

**Comment by ahelsing** [comment]
See ticket #111 which says that the account and identity tables are how we would handle someone switching their IdP

_Trac comment by ahelsing on 12-11-2013 at 09:19_

**Comment by tcmitchell** [comment]
Fixed by #1415
