### ISSUE TITLE
Add new user checklist to home page

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#30]
Walk new users through the process of getting an account, joining or creating a project, creating a slice, etc. via a checklist/wizard type thing.

 _Imported from trac ticket [#30](http://trac.gpolab.bbn.com/proto-ch/ticket/30),  created by tmitchel on 05-23-2012 at 14:17, last modified: 05-31-2012 at 16:37_

**Comment by ahelsing** [comment]
Create a sidebar box on home page
 - Get an Account
 - Get SSH keys
 - In a project
 - In a slice in that project
 - Reserve resources

Maybe a read-only box with the 5 steps you need to take on the home page, and checkbox version on home page.

This would be a tool-workflow.php to include on the home page.


_Trac comment by ahelsing on 05-29-2012 at 14:37_

**Comment by ahelsing** [comment]
Maybe it's on all pages - like tool-breadcrumbs.php

_Trac comment by ahelsing on 05-29-2012 at 14:38_

**Comment by seledwards** [comment]
Do we want Joanne's input before doing this?  She had some ideas about how to do this. I think.

_Trac comment by sedwards (github user: seledwards) on 05-29-2012 at 15:51_

**Comment by ahelsing** [comment]
The idea here was to get something in for next Tuesday that people could look at. If Joanne has simple feedback we could get now, we could try to include that.


_Trac comment by ahelsing on 05-29-2012 at 16:03_

**Comment by MarshallBrinn** [comment]
I have a version of this working: ACCOUNT, KEYS, PROJECT, REQUESTS, SLICES appear under the tool bar in red or green depending on whether there is work to be done. I don't think this is good enough in a couple of ways. First, we need to present it to show that this is a flow. Second, this should go away (permanently?) once a user has shown that they have done each of these steps once.

Also I think that REQUESTS (do you have any pending requests?) and SLIVERS (have you ever allocated resources?) might be more than we want to add. 

To be discussed at 5/31 afternoon meeting.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-31-2012 at 12:50_

**Comment by MarshallBrinn** [comment]
This is all set. I put in a cache so that once you have ever achieved each of the starter tasks ever during the session, the starter bar doesn't appear again. But until that time, they appear as 

>> ACCOUNT    >> SSH_KEYS    >> PROJECTS    >> SLICES

with the labels in red (if not satisfied) or green (if satisfied).

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-31-2012 at 16:37_
