### ISSUE TITLE
button on Create Project page should say Create

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#300]
the createproject.php page has a button that says Register, but should say "Create Project", as the create slice page has a button that says "Create Slice".

 _Imported from trac ticket [#300](http://trac.gpolab.bbn.com/proto-ch/ticket/300),  created by ahelsing on 10-18-2012 at 13:55, last modified: 11-02-2012 at 11:06_

**Comment by seledwards** [comment]
There is no `createproject.php` and I can't find use of the word `Register` with regards to projects.

Could someone clarify this ticket?

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 10:57_

**Comment by tcmitchell** [comment]
`edit-project.php` is the page that is displayed when the "Create New Project" button is clicked on the home page. `edit-project.php` has a button that is labeled "Register". That button should say "Create Project" if the experimenter is creating a project.

_Trac comment by tmitchel (github user: tcmitchell) on 11-02-2012 at 11:01_

**Comment by seledwards** [comment]
Yep.  Just figured that out. 
Done. Closing.

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:06_
