### ISSUE TITLE
Delete Resources page has button called Delete Slivers

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#301]
Make the terminology consistent: the 'Delete Resources' page should have a button that says 'Delete Resources'

And the result page should similarly say 'Resources' not slivers'

 _Imported from trac ticket [#301](http://trac.gpolab.bbn.com/proto-ch/ticket/301),  created by ahelsing on 10-18-2012 at 14:07, last modified: 11-02-2012 at 11:17_

**Comment by seledwards** [comment]
Fixed in a number of places.

Closing.

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:17_
