### ISSUE TITLE
Be consistent about project lead request text

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#303]
On the home page, the explanatory text (in red) says you can "request to be a project lead", but the button says "ask to be a project lead". Make the two agree.

 _Imported from trac ticket [#303](http://trac.gpolab.bbn.com/proto-ch/ticket/303),  created by ahelsing on 10-19-2012 at 13:13, last modified: 11-02-2012 at 11:31_

**Comment by seledwards** [comment]
Fixed. Closing.

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:31_
