### ISSUE TITLE
modify account: 2 periods

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#304]
'is severely mis-behaving..'
 - extra period

 _Imported from trac ticket [#304](http://trac.gpolab.bbn.com/proto-ch/ticket/304),  created by ahelsing on 10-19-2012 at 13:14, last modified: 11-02-2012 at 11:24_

**Comment by seledwards** [comment]
Fixed.  Also removed hyphen from "mis-behaving".

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:24_
