### ISSUE TITLE
Add resources: awhile to a while

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#305]
On the Add Resources page, change awhile to 2 words: a while

 _Imported from trac ticket [#305](http://trac.gpolab.bbn.com/proto-ch/ticket/305),  created by ahelsing on 10-19-2012 at 13:22, last modified: 11-02-2012 at 11:20_

**Comment by seledwards** [comment]
Fixed. Closing.

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:20_
