### ISSUE TITLE
kmactivate page should have a link to the InCommon privacy policy

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#307]
We have a vetted Incommon privacy policy. Provide a link to it from the kmactivate page

 _Imported from trac ticket [#307](http://trac.gpolab.bbn.com/proto-ch/ticket/307),  created by ahelsing on 10-19-2012 at 13:28, last modified: 11-02-2012 at 11:48_

**Comment by seledwards** [comment]
Privacy policy lives here on sergyar:
```
https://sergyar.gpolab.bbn.com/policy/privacy.html
```

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:42_

**Comment by seledwards** [comment]
Added link to:
```
proto-ch/kmtool/www/kmtool/kmactivate.php
```

To:
```
   <li><a href="../policy/privacy.html">Privacy</a>: Some personal information, including that provided from InCommon, may be shared among GENI operators.</li>
```

_Trac comment by sedwards (github user: seledwards) on 11-02-2012 at 11:48_
