### ISSUE TITLE
make ssh login a link

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#309]
Rob suggests that enough browsers make SSH commands a usable link that we should do this.

 _Imported from trac ticket [#309](http://trac.gpolab.bbn.com/proto-ch/ticket/309),  created by ahelsing on 10-24-2012 at 15:33, last modified: 03-08-2013 at 12:58_

**Comment by tcmitchell** [comment]
On a mac safari handles it automatically, firefox prompts the user about launching terminal, and chrome doesn't handle it. It looks like there may be a third party ssh extension for chrome, but it isn't handled out of the box.

_Trac comment by tmitchel (github user: tcmitchell) on 11-09-2012 at 15:52_

**Comment by ahelsing** [comment]
For firefox, see: https://addons.mozilla.org/en-us/firefox/addon/firessh/

firessh.net claims that the same add-on works for Chrome

I also found this:
https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?


_Trac comment by ahelsing on 03-07-2013 at 15:14_

**Comment by tcmitchell** [comment]
ssh commands are now links. Chrome appears to handle the ssh URL now, at least on a Mac. Tested with ProtoGENI and InstaGENI compute resources (VMs and physical nodes).

Leaving this open to test with ExoGENI VMs.

_Trac comment by tmitchel (github user: tcmitchell) on 03-07-2013 at 18:20_

**Comment by tcmitchell** [comment]
Aaron tested on with ExoGENI VMs and the ssh link worked.

_Trac comment by tmitchel (github user: tcmitchell) on 03-07-2013 at 20:34_

**Comment by tcmitchell** [comment]
There is a request to open the ssh link on a new tab. This is to support the use of FireSSH on Firefox.

That might be a matter of adding a `target="_blank"` attribute to the anchor tag.


_Trac comment by tmitchel (github user: tcmitchell) on 03-08-2013 at 12:41_

**Comment by ahelsing** [comment]
that's it

_Trac comment by ahelsing on 03-08-2013 at 12:58_
