### ISSUE TITLE
Add slice notes

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#31]
_Imported from trac ticket [#31](http://trac.gpolab.bbn.com/proto-ch/ticket/31),  created by tmitchel on 05-23-2012 at 14:17, last modified: 06-08-2012 at 12:02_

**Comment by seledwards** [comment]
Add: 
 * slice creation timestamp 
 * description
 * notes

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 17:18_

**Comment by seledwards** [comment]
Added placeholder to slice.php for:
 * slice creation timestamp
 * description

_Trac comment by sedwards (github user: seledwards) on 05-25-2012 at 22:45_

**Comment by ahelsing** [comment]
added slice creation and description.

Description is not yet editable (need sa_client and sa_controller methods)

_Trac comment by ahelsing on 06-07-2012 at 12:41_

**Comment by ahelsing** [comment]
Split off making slice description editable into a post GEC14 ticket

_Trac comment by ahelsing on 06-08-2012 at 11:08_
