### ISSUE TITLE
Create a database backup cron job

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#310]
Use `pg_dump` to back up the database periodically via a cron job.

 _Imported from trac ticket [#310](http://trac.gpolab.bbn.com/proto-ch/ticket/310),  created by tmitchel on 10-25-2012 at 11:36, last modified: 11-19-2012 at 09:54_

**Comment by ahelsing** [comment]
For the record, the syntax we use for backups of Trac's pgsql databases on Ubuntu nodes, and which i expect we'll use on panther when i get there, is:
```
/usr/bin/pg_dump -F c -f <output_file> <dbname>
```


_Trac comment by chaos on 10-25-2012 at 11:45_

**Comment by tcmitchell** [comment]
A more comprehensive backup strategy is in place courtesy of the infra/ops team.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2012 at 09:54_
