### ISSUE TITLE
Make `pgch` support `listmyslices`

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#317]
Calling `listmyslices` in omni against `pgch` gives the wrong answer.

See #314 for details on omni commands run against `pgch`.

 _Imported from trac ticket [#317](http://trac.gpolab.bbn.com/proto-ch/ticket/317),  created by sedwards on 11-02-2012 at 20:58, last modified: 11-28-2012 at 14:36_

**Comment by seledwards** [comment]
Ok.  So this doesn't work because the `pgch.py` implementation of `Resolve(user URN)` isn't implemented.  Indeed it kindly says the following:

```
Resolve(user) unimplemented. Was asked about user with hrn=sedwards (or urn=urn:publicid:IDN+user+sedwards, uuid=None)
```

And indeed there is no method in the CH API documentation to get a user ID from a user URN.

On the one hand, this isn't the most important method to be supported by omni.

On the other hand, it would be fine (desirable even) for it to default to ask about your own slices if you don't pass in a username. 

Either way, I think this might not be a milestone 1.2 item. 

I'm open to suggestions.

_Trac comment by sedwards (github user: seledwards) on 11-09-2012 at 20:31_

**Comment by ahelsing** [comment]
Why not do the easy thing: If the client cert's subjectAltName contains the same URN as was queried about in the Resolve call, then you can get the UUID from the client cert and complete the resolve that way. But if the client cert has a different URN, then give the existing error.

I suspect that covers 90% of uses - in particular, Flack will be happy.


_Trac comment by ahelsing on 11-12-2012 at 09:04_

**Comment by ahelsing** [comment]
pgch now implements resolve as suggested

Matching changes to omni (framework_pgch) have also been made.
Matching changes to the gcf-ch have also been made (gcf ticket 214)


_Trac comment by ahelsing on 11-28-2012 at 14:36_
