### ISSUE TITLE
Add project creation timestamp

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#32]
_Imported from trac ticket [#32](http://trac.gpolab.bbn.com/proto-ch/ticket/32),  created by tmitchel on 05-23-2012 at 14:18, last modified: 06-07-2012 at 12:39_

**Comment by seledwards** [comment]
Added placeholder to project.php for:
 * project creation timestamp

_Trac comment by sedwards (github user: seledwards) on 05-25-2012 at 22:46_

**Comment by ahelsing** [comment]
added

_Trac comment by ahelsing on 06-07-2012 at 12:39_
