### ISSUE TITLE
Widen the renew text entry boxes

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#322]
The text entry boxes holding renewal dates are too narrow to hold both date and time. Make them wider.

 _Imported from trac ticket [#322](http://trac.gpolab.bbn.com/proto-ch/ticket/322),  created by tmitchel on 11-06-2012 at 10:26, last modified: 04-07-2014 at 16:33_

**Comment by seledwards** [comment]
This works on Firefox but not Chrome. Not sure about Safari.

_Trac comment by sedwards (github user: seledwards) on 11-27-2012 at 16:38_

**Comment by ahelsing** [comment]
This is browser dependent and changed with the stylesheet changes.

_Trac comment by ahelsing on 04-07-2014 at 16:33_
