### ISSUE TITLE
Add an option to renew for a number of hours or days

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#323]
Flack has an option to extend the life of a slice by some number of hours or days. A user suggested this feature for the portal to make it easier to renew.

 _Imported from trac ticket [#323](http://trac.gpolab.bbn.com/proto-ch/ticket/323),  created by tmitchel on 11-06-2012 at 10:27, last modified: 04-26-2013 at 20:53_

**Comment by seledwards** [comment]
Resolving this issue by adding a datepicker to allow you to pick the date from a calendar widget.

_Trac comment by sedwards (github user: seledwards) on 04-26-2013 at 20:51_
