### ISSUE TITLE
Disable reserve button to prevent multiple presses

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#324]
A user suggested that in order to prevent multiple presses of the reserve button, and thus prevent multiple allocations, the reserve button should be disabled once pressed.

 _Imported from trac ticket [#324](http://trac.gpolab.bbn.com/proto-ch/ticket/324),  created by tmitchel on 11-06-2012 at 14:34, last modified: 12-04-2012 at 16:36_

**Comment by seledwards** [comment]
In particular, the right thing here is to prevent requesting resources at AMs that we've already requested resources at. 

It should be fine to request resources at a new AM.

So I think that we don't want to disable the reserve button so much as filter the list of available AMs on the page where you reserve resources.

_Trac comment by sedwards (github user: seledwards) on 11-06-2012 at 16:58_

**Comment by seledwards** [comment]
Google suggests: 
 * using jquery to disable the button on click: http://www.mkyong.com/jquery/how-to-disable-submit-button-after-clicked-with-jquery/
 * and this: http://www.developertutorials.com/tutorials/javascript/how-disable-submit-button-050416-1275/


_Trac comment by sedwards (github user: seledwards) on 11-12-2012 at 11:31_

**Comment by seledwards** [comment]
Fixing #250 may make this OBE.

_Trac comment by sedwards (github user: seledwards) on 11-27-2012 at 16:16_

**Comment by seledwards** [comment]
This is indeed OBE based on fixing #250.

_Trac comment by sedwards (github user: seledwards) on 12-04-2012 at 16:36_
