### ISSUE TITLE
Flack fails getting slice credential

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#325]
Flack gives an error: `Get Slice Credential Fault: Bad Version: Slice xxxxx expired`

This happens when an experimenter creates a slice with the same name as an earlier slice that has since expired.

This happens because Flack uses the slice URN, and then pgch.py uses lookup_slice_by_urn to get the slice ID. And that function in the sa_controller does not includes 'where not expired' clause.

 _Imported from trac ticket [#325](http://trac.gpolab.bbn.com/proto-ch/ticket/325),  created by ahelsing on 11-08-2012 at 14:15, last modified: 11-09-2012 at 16:52_

**Comment by ahelsing** [comment]
The fix is to make the sa_controller lookup_slice_by_urn only return slices that have not been expired.

_Trac comment by ahelsing on 11-08-2012 at 14:16_

**Comment by ahelsing** [comment]
Be sure to update docs to indicate that lookup_slice only gets active slices

_Trac comment by ahelsing on 11-08-2012 at 14:22_

**Comment by tcmitchell** [comment]
lookup_slice_by_urn honors the expired flag. API docs updated to reflect methods that retrieve active slices (not expired slices).

_Trac comment by tmitchel (github user: tcmitchell) on 11-09-2012 at 16:52_
