### ISSUE TITLE
pgch is not restarted on machine reboot

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#326]
When the CH machine reboots, the gcf-pgch daemon is not restarted. We really ought to have a process to check that pgch is running.
At a minimum, we should run launch-pgch on machine reboot

 _Imported from trac ticket [#326](http://trac.gpolab.bbn.com/proto-ch/ticket/326),  created by ahelsing on 11-08-2012 at 14:19, last modified: 01-11-2013 at 12:48_
   CCing: chaos@...

**Comment by seledwards** [comment]
Chaos can probably provide us with some guidance on how to set this up on Ubuntu.

_Trac comment by sedwards (github user: seledwards) on 11-09-2012 at 20:45_

**Comment by seledwards** [comment]
Actually cc'ing Chaos now.

_Trac comment by sedwards (github user: seledwards) on 11-09-2012 at 20:47_

**Comment by ahelsing** [comment]
FTR, you don't need to CC me on tickets --- i get copied on all tickets.

Do you want me to actually take this task?  Either way is fine with me.

_Trac comment by chaos on 11-12-2012 at 10:51_

**Comment by seledwards** [comment]
Chaos says that most of doing this is to look up a good example.

Also, she's working on setting up her own portal instance and she'll look at what it starts when it boots.  

_Trac comment by sedwards (github user: seledwards) on 11-12-2012 at 11:21_

**Comment by seledwards** [comment]
Tom says he will just do this.

_Trac comment by sedwards (github user: seledwards) on 11-13-2012 at 15:07_

**Comment by ahelsing** [comment]
Sounds good --- sorry i couldn't help in a timely fashion.

_Trac comment by chaos on 11-13-2012 at 18:33_

**Comment by tcmitchell** [comment]
Ubuntu provides /etc/init.d/skeleton to get started on a boot script.

_Trac comment by tmitchel (github user: tcmitchell) on 12-05-2012 at 17:04_

**Comment by tcmitchell** [comment]
geni-pgch has been added to the source tree. It is builds as a debian package to install and run pgch as a service at boot time. The package needs a home, and I'm working that out.

_Trac comment by tmitchel (github user: tcmitchell) on 01-03-2013 at 15:19_

**Comment by tcmitchell** [comment]
The geni-pgch package now has a home, and the repository is configured on all portal/clearinghouse hosts. I have updated the [instructions](PortalTesting#Refreshingyourinstall) to reference the new package instead of the launch script.

To update a lab host:
```
# Kill a running pgch if it exists
sudo pkill -f -u root "python .*gcf-pgch"

# Update package information
sudo apt-get update

# install (unsigned) 
sudo apt-get install -y --allow-unauthenticated geni-pgch
```

I tested this procedure on cascade. The pgch daemon is automatically started on package installation and on reboot.

Remaining task(s):
 * Remove `bin/launch_pgch_daemon.sh`
 * Update development hosts (marilac, illyrica, sergyar)
 * Update infra host (tau-ceti)
 * Update panther

_Trac comment by tmitchel (github user: tcmitchell) on 01-07-2013 at 12:42_

**Comment by ahelsing** [comment]
I updated illyrica

_Trac comment by ahelsing on 01-07-2013 at 14:10_

**Comment by ahelsing** [comment]
I updated tau-ceti, which wasn't running pgch before, but is now:
```
root     20643     1  2 14:19 ?        00:00:00 /usr/sbin/geni-pgch
```


_Trac comment by chaos on 01-07-2013 at 14:19_

**Comment by seledwards** [comment]
I updated sergyar.

_Trac comment by sedwards (github user: seledwards) on 01-09-2013 at 19:58_

**Comment by tcmitchell** [comment]
marilac has been updated.

Remaining tasks:
 * Update panther
 * Remove `bin/launch_pgch_daemon.sh`


_Trac comment by tmitchel (github user: tcmitchell) on 01-10-2013 at 13:31_

**Comment by tcmitchell** [comment]
* Panther has been updated
 * `bin/launch_pgch_daemon.sh` has been removed from git

Old copies of bin/launch_pgch_daemon.sh are still floating around on dev hosts, and those should get cleaned up. I think that's the last subtask on this ticket.

_Trac comment by tmitchel (github user: tcmitchell) on 01-10-2013 at 17:07_

**Comment by ahelsing** [comment]
File removed on tau-ceti:
```
tau-ceti,[~],12:46(0)$ rm /home/chaos/proto-ch/bin/launch_pgch_daemon.sh
rm: remove regular file `/home/chaos/proto-ch/bin/launch_pgch_daemon.sh'? y 
```


_Trac comment by chaos on 01-11-2013 at 12:46_

**Comment by tcmitchell** [comment]
No more copies of `bin/launch_pgch_daemon.sh` exist on the lab hosts. All done.

_Trac comment by tmitchel (github user: tcmitchell) on 01-11-2013 at 12:48_
