### ISSUE TITLE
OBE: Fix permissions for viewing member slices

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#328]
get_slices_for_member has a guard requiring you be the member to see the slices. But this is what the slice-member page uses. So this page isn't that useful.

Meanwhile,  the project-member page shows you the slices a member has within the project - and that is not restricted (you just have to be in the project with them). 

Do we like that (visible on project page, not generally)?

Should the slice-member page go away? Or do we fix the permissions to let this work?

 _Imported from trac ticket [#328](http://trac.gpolab.bbn.com/proto-ch/ticket/328),  created by ahelsing on 11-09-2012 at 10:36, last modified: 12-05-2013 at 13:18_

**Comment by tcmitchell** [comment]
This should be OBE with the new CH.

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:37_

**Comment by ahelsing** [comment]
I think the slice-member page should go away, and we like the permissions on the project-member page.

_Trac comment by ahelsing on 09-12-2013 at 10:55_
