### ISSUE TITLE
Record portal user last seen timestamp

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#330]
It would be nice to be able to track activity, to know when people last used the portal
Record the last seen timestamp

 _Imported from trac ticket [#330](http://trac.gpolab.bbn.com/proto-ch/ticket/330),  created by ahelsing on 11-09-2012 at 11:26, last modified: 02-19-2013 at 14:46_

**Comment by tcmitchell** [comment]
A new last_seen table has been added It records the timestamp and request uri of a user's most recent page. One record per user, updated with every visit.

geni-ops-report should add support for this table to show last seen timestamp on user report.


_Trac comment by tmitchel (github user: tcmitchell) on 02-18-2013 at 20:06_

**Comment by tcmitchell** [comment]
geni-ops-report now includes the last_seen timestamp.

_Trac comment by tmitchel (github user: tcmitchell) on 02-19-2013 at 14:46_
