### ISSUE TITLE
Change identity attributes if new values come from Shib

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#331]
If the Shib IdP reports a new value for an attribute, we should do something with this. For now, we don't even notice.

 _Imported from trac ticket [#331](http://trac.gpolab.bbn.com/proto-ch/ticket/331),  created by ahelsing on 11-09-2012 at 13:25, last modified: 03-30-2015 at 16:51_

**Comment by ahelsing** [comment]
now at least we note this in the syslog....

_Trac comment by ahelsing on 11-09-2012 at 13:39_

**Comment by ahelsing** [comment]
changes to things other than email address should be pretty easy. Changing email address requires regenerating certs.

_Trac comment by ahelsing on 07-16-2014 at 11:32_

**Comment by tcmitchell** [comment]
We give people an option to change their name now, as well as populate some other fields like telephone number. We probably no longer want to overwrite the user's chosen name with the value from their identity provider. Many identity provider names are not what people really want to see.

_Trac comment by tmitchel (github user: tcmitchell) on 02-24-2015 at 16:09_

**Comment by tcmitchell** [comment]
This is as done as it is going to be. People can edit these values to be what they want or prefer. There is no reasonable way to handle email address changes from the IdP because the email is in the user's certificate and has already been communicated out. Done.
