### ISSUE TITLE
Modify portal to support download of `omni_config` with CH

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#334]
Download of the external cert will now be handled through the KM.

Have the portal always show the button to download the `omni_config`.  Remove any places where you could download the external cert.  

 _Imported from trac ticket [#334](http://trac.gpolab.bbn.com/proto-ch/ticket/334),  created by sedwards on 11-12-2012 at 09:47, last modified: 12-06-2012 at 10:49_

**Comment by seledwards** [comment]
Removing references to `certificate.php`. Leaving file in git in case it's useful for the KM work Tom is doing.

Rearranged contents of the command line tool portion of `profile.php` to include a table of tools and their configurations so we can add more as we get them.



_Trac comment by sedwards (github user: seledwards) on 11-12-2012 at 10:27_

**Comment by seledwards** [comment]
Ok.  I think this is in pretty good shape.

Once the KM piece is working, I'd like to add a link to the text "SSL certificate and private key" to point to the place in the KM where you can download your cert.

Leaving open.

_Trac comment by sedwards (github user: seledwards) on 11-12-2012 at 10:51_

**Comment by seledwards** [comment]
We should also consider whether we want the `omni_config` to be a popup (as it is now) or a separate page with a download button for the `omni_config`.

_Trac comment by sedwards (github user: seledwards) on 11-12-2012 at 10:55_

**Comment by ahelsing** [comment]
I think the pop up is kind of ugly. A download is probably better.

_Trac comment by ahelsing on 11-12-2012 at 12:15_

**Comment by seledwards** [comment]
Ok.  There is now a download page and it's MUCH better.  

Only remaining item is to add the link to the KM page.

_Trac comment by sedwards (github user: seledwards) on 11-12-2012 at 18:24_

**Comment by seledwards** [comment]
Ok.  So I did [gcf:208](http://trac.gpolab.bbn.com/gcf/ticket/208) which created a new pgch framework and added the `default_project` field to the `omni_config`.

I added (but commented out) code in `get_template_omni_config()` in `am_client.php` to set the framework type to `pgch` and also to generate a comment and some sample `default_project` code.

It should look like this:
```
# 'default_project' is the name of the project that will be assumed
# unless '--project' is specified on the command line.
# Uncomment only one of the following lines if you want to use this feature
default_project = testing
# default_project = another
``` 

I commented this out because these two things won't work with the released versions of gcf and I didn't want it to get pushed to the production portal. 

There are two places to uncomment when we are ready for this to go live.

Alternatively we could have pre and post omni2.2 versions of the omni_config.

_Trac comment by sedwards (github user: seledwards) on 11-16-2012 at 18:20_

**Comment by seledwards** [comment]
Moved uncommenting the two lines to #363.

_Trac comment by sedwards (github user: seledwards) on 12-06-2012 at 10:49_
