### ISSUE TITLE
Project join email should include url

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#337]
I joined Niky's project and received the following email:
```
Your request to join GENI project SampleExperiments was accepted!
You have been added to the project with role Member.
Log in to the GENI portal to start using this project.

Reason:


Thank you,
Niky Riga
```

There is no reason this shouldn't include a URL to the project page for the new or forgetful.

 _Imported from trac ticket [#337](http://trac.gpolab.bbn.com/proto-ch/ticket/337),  created by sedwards on 11-12-2012 at 17:27, last modified: 11-14-2012 at 10:57_
   CCing: nriga@...

**Comment by ahelsing** [comment]
How about:
```
To start using this project at the GENI portal, visit this page: 
https://$hostname/secure/project.php?project_id=$project_id
```
instead of the line:
```
Log in to the GENI portal to start using this project.
```


_Trac comment by ahelsing on 11-13-2012 at 08:40_

**Comment by seledwards** [comment]
Sounds good to me.

(Also if I'm being picky, the "Reason:" should only show up if there a reason was filled in.)

_Trac comment by sedwards (github user: seledwards) on 11-13-2012 at 09:59_
