### ISSUE TITLE
Make the pointer into an hourglass when the portal is thinking

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#338]
To make it clear that the portal is doing something and the user should wait, either make 
the pointer into thinking something or even better pop-up a window that says something to that effect, that disappears when it is done. 

 _Imported from trac ticket [#338](http://trac.gpolab.bbn.com/proto-ch/ticket/338),  created by nriga on 11-12-2012 at 17:38, last modified: 04-07-2014 at 16:35_

**Comment by ahelsing** [comment]
This could presumably be done with javascript - essentially AJAXify _every_ page.

But given that all the slow pages are AJAXified, this is probably not necessary.

_Trac comment by ahelsing on 04-07-2014 at 16:35_
