### ISSUE TITLE
Create a script to add pre-asserted attributes to the km database

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#343]
Allow an operator to use a script to insert pre-asserted attributes like email address into the km_asserted_attribute table. Create an API and have the script use that API to post these attributes so that the asserter can be tracked.

 _Imported from trac ticket [#343](http://trac.gpolab.bbn.com/proto-ch/ticket/343),  created by tmitchel on 11-16-2012 at 18:21, last modified: 12-11-2013 at 09:44_

**Comment by tcmitchell** [comment]
See `bin/assert_email.sh`

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:39_

**Comment by ahelsing** [comment]
Replaced by chapi ticket 173

_Trac comment by ahelsing on 12-11-2013 at 09:44_
