### ISSUE TITLE
If user requests to join one project, the project owner sees requests for the user to join each project

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#344]
I have two projects ("testing" and "another").  I have a second user request to join "testing" and I see two notes on the main page saying that I have a request to handle for each project I own.

Also, if I click on the "another" project page, I get a notice that I need to handle a project join request on this page.

When I accept this request, the second user is added to the "testing" project.

 _Imported from trac ticket [#344](http://trac.gpolab.bbn.com/proto-ch/ticket/344),  created by sedwards on 11-19-2012 at 16:08, last modified: 11-26-2012 at 13:23_

**Comment by ahelsing** [comment]
Silly. Missing logic to append to the WHERE clause (so it replaced instead).

_Trac comment by ahelsing on 11-26-2012 at 13:23_
