### ISSUE TITLE
Add "use omni" button to slice page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#345]
Remove "slice credential" button and replace with a "use omni" button.

 _Imported from trac ticket [#345](http://trac.gpolab.bbn.com/proto-ch/ticket/345),  created by sedwards on 11-27-2012 at 16:08, last modified: 12-03-2012 at 15:13_

**Comment by tcmitchell** [comment]
Done.

_Trac comment by tmitchel (github user: tcmitchell) on 12-03-2012 at 15:13_
