### ISSUE TITLE
omni_config nicknames are unwieldy

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#348]
The current version of the `omni_config` generated by the portal gives aggregate nicknames like this:
```
InstaGENI-Utah=,https://www.utah.geniracks.net:12369/protogeni/xmlrpc/am/2.0
ProtoGENI-Utah=,https://www.emulab.net:12369/protogeni/xmlrpc/am/2.0
Kentucky-ProtoGENI=,https://www.uky.emulab.net:12369/protogeni/xmlrpc/am/2.0
```

The current nicknames are unwieldy.

The current nicknames are based on the `service_name` from the `service_registry` table.  Here are some examples from panther.

```
    service_name    |            service_description            |                          service_url                          
--------------------+-------------------------------------------+---------------------------------------------------------------
 InstaGENI Utah     | InstaGENI Utah AM                         | https://www.utah.geniracks.net:12369/protogeni/xmlrpc/am/2.0 
 Local gcf AM       | Empty AM                                  | https://localhost:8001/
 ExoGENI BBN        | ExoGENI BBN Rack                          | https://bbn-hn.exogeni.net:11443/orca/xmlrpc
 ExoGENI ExoSM      | ExoGENI ExoSM                             | https://geni.renci.org:11443/orca/xmlrpc
 ExoGENI RENCI      | ExoGENI RENCI Rack                        | https://rci-hn.exogeni.net:11443/orca/xmlrpc
 ProtoGENI Utah     | ProtoGENI Utah AM                         | https://www.emulab.net:12369/protogeni/xmlrpc/am/2.0 
 Kentucky ProtoGENI | ProtoGENI Kentucky AM                     | https://www.uky.emulab.net:12369/protogeni/xmlrpc/am/2.0
```

Should we have a separate `service_nickname` or `service_shortname` column in the `service_registry` table?  

 _Imported from trac ticket [#348](http://trac.gpolab.bbn.com/proto-ch/ticket/348),  created by sedwards on 11-28-2012 at 17:02, last modified: 09-12-2013 at 14:15_

**Comment by seledwards** [comment]
We should add a nickname column to the DB and use that.

_Trac comment by sedwards (github user: seledwards) on 02-12-2013 at 15:57_

**Comment by ahelsing** [comment]
Nicknames should match the nicknames used in the sample omni_config files


_Trac comment by ahelsing on 03-05-2013 at 09:38_

**Comment by ahelsing** [comment]
With omni 2.4 omni gets the nicknames for you, regardless of your omni config. So this is OBE

_Trac comment by ahelsing on 09-12-2013 at 14:15_
