### ISSUE TITLE
Eliminate GeniUser->urn()

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#351]
The urn method in GeniUser should go away. We should use the MA information to find the urn, rather than generate a urn.

 _Imported from trac ticket [#351](http://trac.gpolab.bbn.com/proto-ch/ticket/351),  created by tmitchel on 11-29-2012 at 15:44, last modified: 08-05-2013 at 12:27_

**Comment by ahelsing** [comment]
Is this indeed fixed now? It looks like the urn comes from the MA now?

_Trac comment by ahelsing on 07-02-2013 at 11:20_

**Comment by tcmitchell** [comment]
This was fixed as part of the 1.5 release in late May.

_Trac comment by tmitchel (github user: tcmitchell) on 08-05-2013 at 12:27_
