### ISSUE TITLE
Renew Sliver expiration wrong

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#361]
The sliver expiration time on slice.php lists the slice expiration time not the sliver expiration time.  It's a fine time to want to renew to, but it doesn't say when the sliver will expire.

 _Imported from trac ticket [#361](http://trac.gpolab.bbn.com/proto-ch/ticket/361),  created by sedwards on 12-05-2012 at 17:10, last modified: 04-26-2013 at 20:53_

**Comment by tcmitchell** [comment]
The renew error (No new sliver expiration time specified.) has been moved to issue #364.

_Trac comment by tmitchel (github user: tcmitchell) on 12-06-2012 at 11:15_

**Comment by ahelsing** [comment]
We could get the sliver expiration by parsing the sliver status return, looking for pg_expores and orca_expires and pl_expires.


_Trac comment by ahelsing on 12-06-2012 at 13:19_

**Comment by tcmitchell** [comment]
The slice page is already getting the sliver status, so it shouldn't be hard to pull the expiration date/time and display it.

_Trac comment by tmitchel (github user: tcmitchell) on 01-03-2013 at 13:52_

**Comment by seledwards** [comment]
Need to add:
 1. Have `amstatus.php` return the sliver expiration time
 2. Have this field be filled in by the calling code in `update_agg_row()`

That said, I still think this is confusing because it encourages folks to renew to the current sliver expiration time.  Hum....

_Trac comment by sedwards (github user: seledwards) on 02-08-2013 at 19:54_

**Comment by seledwards** [comment]
Have updated code to display the current sliver expiration time and have a separate datepicker for the time you want to renew the sliver until.

The datepicker prevents you from trying to renew past the slice expiration.

_Trac comment by sedwards (github user: seledwards) on 04-26-2013 at 20:53_
