### ISSUE TITLE
On createsliver clearly log sliver creation details

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#362]
Looking at `error.log` and the `logging_entry` table in the DB, the details of a sliver creation are not obvious.

Make sure it's easy to determine all of the things you might want to know to reproduce a sliver:
 * slice urn and slice UUID
 * rspec (and rspec_id)
 * AM involved.
 * sliver creator

 _Imported from trac ticket [#362](http://trac.gpolab.bbn.com/proto-ch/ticket/362),  created by sedwards on 12-05-2012 at 18:22, last modified: 07-16-2014 at 10:12_

**Comment by ahelsing** [comment]
The portal_error.log shows the omni command. The new stuff Ben is working on will produce more and save it if the create fails.

_Trac comment by ahelsing on 07-16-2014 at 10:12_
