### ISSUE TITLE
Update portal_omni_config once gcf-2.2 is release

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#363]
I did  gcf:208 which created a new pgch framework and added the default_project field to the omni_config.

I added (but commented out) code in get_template_omni_config() in am_client.php to set the framework type to pgch and also to generate a comment and some sample default_project code.

It should look like this:
```
# 'default_project' is the name of the project that will be assumed
# unless '--project' is specified on the command line.
# Uncomment only one of the following lines if you want to use this feature
default_project = testing
# default_project = another
```
I commented this out because these two things won't work with the released versions of gcf and I didn't want it to get pushed to the production portal.

There are two places to uncomment when we are ready for this to go live.

 _Imported from trac ticket [#363](http://trac.gpolab.bbn.com/proto-ch/ticket/363),  created by sedwards on 12-06-2012 at 10:48, last modified: 03-04-2013 at 15:46_

**Comment by tcmitchell** [comment]
Modified portal_omni_config to generate either version of omni config based on argument. Added a simple UI to allow a user to request either. UI help is needed to make it easier to understand. Functionality works.

_Trac comment by tmitchel (github user: tcmitchell) on 02-28-2013 at 18:56_

**Comment by tcmitchell** [comment]
Feedback on UI has been incorporated. Task complete.

_Trac comment by tmitchel (github user: tcmitchell) on 03-04-2013 at 15:46_
