### ISSUE TITLE
Undefined variables in log file

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#366]
Marshall reports seeing undefined variable warnings in the apache error log file:
```
[Fri Dec 07 11:57:17 2012] [error] [client 128.89.81.158] PHP Notice:  Undefined variable: am_id in /var/www/secure/slice.php on line 137
```
```
[Fri Dec 07 10:44:48 2012] [error] [client 128.89.81.158] PHP Notice:  Undefined variable: m in /var/www/secure/amstatus.php on line 163
```

 _Imported from trac ticket [#366](http://trac.gpolab.bbn.com/proto-ch/ticket/366),  created by tmitchel on 01-03-2013 at 15:38, last modified: 02-08-2013 at 20:04_

**Comment by ahelsing** [comment]
The first error is legit I think: we should comment out line 137 in slice.php I believe. There is no single am_id on the slice page, and none is needed.

The 2nd error: there are 3 cases where $m is not defined: When there are 0 lines of return from sliver status, when the status is that 'Failed to get...' text, and when the returned text is neither the usual success of failure. Initializing the variable to 0 around line 135 would solve that. However, the $m is used as the 2nd element in the retval array. But that 2nd element is ignored in the only place this function is called - the bottom of this file. So this whole piece of logic could just go away.

_Trac comment by ahelsing on 02-06-2013 at 10:13_

**Comment by seledwards** [comment]
This looks about right.  I did both of these.

Closing, but reopen it if we discover any issues.


_Trac comment by sedwards (github user: seledwards) on 02-08-2013 at 20:04_
