### ISSUE TITLE
Add project expiration

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#367]
Allow limiting the duration of projects by including an expiration. Tutorial projects could have a short duration (1 - 3 weeks), class projects could be medium duration (a semester), and research projects could be open-ended.

The slice authority should honor the project expiration by limiting the maximum lifetime of slices to the project's expiration. Aggregates already limit the expiration of slivers to the expiration of the slice.

 _Imported from trac ticket [#367](http://trac.gpolab.bbn.com/proto-ch/ticket/367),  created by tmitchel on 01-03-2013 at 15:47, last modified: 01-10-2013 at 16:00_

**Comment by tcmitchell** [comment]
Step 1 is to allow projects to be edited. That's complete in development. Next is to provide a way to input an expiration date/time and pass it into the database. This will also require a way to unset the expiration to change an expiring project into an long-lived project.

_Trac comment by tmitchel (github user: tcmitchell) on 01-04-2013 at 19:54_

**Comment by tcmitchell** [comment]
Project expiration has been incorporated. The SA honors the project expiration on creation and renewal. The portal allows setting the project expiration.

We don't have an established mechanism for updating an existing database, and this change requires an updated schema. That needs to get worked out before closing this ticket.

_Trac comment by tmitchel (github user: tcmitchell) on 01-10-2013 at 13:26_

**Comment by tcmitchell** [comment]
We discussed and decided that we don't yet know enough about the requirements of database updates to create a general mechanism at this time. Some updates should be installed before code updates, others after. We also need to know which version of the schema is present, and is that the overall schema, or just a module's schema (pa, sa, etc)? And we need a way to compare a database version with a set of updates and install those updates (either before or after code updates).

So for now, we'll do it ad hoc. I created an update script (`pa/db/postgresql/update-1.sql` that alters the pa_project table, adding the expiration column. Then I manually applied that updated to:
 * cascade
 * illyrica
 * marilac
 * sergyar
 * panther

Note that dagoola already had the patch.

The only remaining host that needs the update applied is tau-ceti. To apply this update, the current code must be synced to tau-ceti, and then run this command:
```
psql -U portal -h localhost -f pa/db/postgresql/update-1.sql portal
```

In case the database name or database user name are different on tau-ceti, here's the general form:
```
psql -U <DB-USER> -h <DB-HOST> -f <UPDATE-FILE> <DATABASE>
```


_Trac comment by tmitchel (github user: tcmitchell) on 01-10-2013 at 14:39_

**Comment by ahelsing** [comment]
Done on tau-ceti.  Looks fine afaict:
```
tau-ceti,[~/proto-ch],14:47(0)$ psql -U portal -h localhost -f pa/db/postgresql/update-1.sql portal
Password for user portal: 
ALTER TABLE
tau-ceti,[~/proto-ch],14:48(0)$ 
```


_Trac comment by chaos on 01-10-2013 at 14:48_

**Comment by tcmitchell** [comment]
All the hosts have been updated with the database change. This task is complete.

_Trac comment by tmitchel (github user: tcmitchell) on 01-10-2013 at 16:00_
