### ISSUE TITLE
Add canned RSpecs

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#37]
Mark Berman made the following suggestions for initial canned RSpecs in an email on May 23:

 I agree with you that there's a simple set of topologies that would provide a lot of mileage for relatively little effort. As Tom points out, there's a free parameter in most of these (number of points in star, nodes in line, etc.), but we probably can't support that in our initial rollout. I'd suggest starting with a minimal set:

 1. Single node (very useful as a build / test host, not so much for actual experiment)
 2. Two nodes, one link (dumbbell, with n=1 for each star).
 3. Two nodes, one link with a delay node. (Technically, this is a three-node linear topology, but the delay node is special.)
 4. A diamond topology for simple multipath. (Perhaps see the click router example for a variation with two end nodes, plus four router nodes in a diamond, figure at http://groups.geni.net/geni/wiki/ClickExampleExperiment.)

 That may be enough for the first round. Could we support a selection between two different OSs / images, to be applied across the board to all nodes in the topology (except delay nodes)?

 _Imported from trac ticket [#37](http://trac.gpolab.bbn.com/proto-ch/ticket/37),  created by tmitchel on 05-23-2012 at 14:42, last modified: 08-30-2012 at 09:53_

**Comment by ahelsing** [comment]
_ahelsing attached [pg-4vm-star-V3.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/37/pg-4vm-star-V3.rspec) on 06-06-2012 at 09:40_

**Comment by ahelsing** [comment]
_ahelsing attached [pg-3vm-ring-V3.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/37/pg-3vm-ring-V3.rspec) on 06-06-2012 at 09:40_

**Comment by ahelsing** [comment]
_ahelsing attached [pg-2vm-1lan-V3.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/37/pg-2vm-1lan-V3.rspec) on 06-06-2012 at 09:10_

**Comment by ahelsing** [comment]
_ahelsing attached [pg-3vm-linear-V3.rspec](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/37/pg-3vm-linear-V3.rspec) on 06-06-2012 at 09:40_

**Comment by ahelsing** [comment]
Emailed Mark & Niky to ask for some RSpecs


_Trac comment by ahelsing on 06-05-2012 at 15:50_

**Comment by ahelsing** [comment]
Mark & Niky haven't said any more.
But I've added
2 nodes
2 nodes + 1 link
3 nodes in a line
3 nodes in a triangle
4 nodes in a diamond
4 nodes in a star
click router

The only thing I haven't added is 2 nodes with a delay node in the middle. Which is Utah specific.

Also note I haven't tested more than 2 nodes.


_Trac comment by ahelsing on 06-06-2012 at 10:05_

**Comment by tcmitchell** [comment]
All the suggested RSpecs have been added, including 2 nodes with a delay node, which was demonstrated at GEC 14.

_Trac comment by tmitchel (github user: tcmitchell) on 08-30-2012 at 09:53_
