### ISSUE TITLE
Put more information to the member page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#371]
I have two accounts in the portal (one from BU and one from GPO) and it is hard to tell 
who did what. Even if I press on the name the only information is :
  * Project
  * Role

Although I understand that most people won't have multiple accounts, having people with the same name might not be extremely rare. The best would be to add the email in the above page, or if this is considered private at least the affiliated institution. 

 _Imported from trac ticket [#371](http://trac.gpolab.bbn.com/proto-ch/ticket/371),  created by nriga on 01-16-2013 at 15:57, last modified: 04-07-2014 at 16:39_

**Comment by ahelsing** [comment]
This is on the project-member page.

We don't have pretty institution names in general. For some institutions, it's a URN or a URL

Does sharing email addresses violate privacy concerns? It might. This needs some thought.



_Trac comment by ahelsing on 02-12-2013 at 15:20_

**Comment by innnkkki** [comment]
Maybe we can share the second part of the email address i.e. Niky Riga @bu.edu or @bbn.net etc. 
Currently even if I am the lead in a project I don't get any information about the people on my project. 



_Trac comment by nriga (github user: innnkkki) on 06-06-2013 at 16:31_

**Comment by seledwards** [comment]
Heidi says via e-mail: 
```
As an aside, do we ever expect to include the organization that a project lead is part of on the project page? Might help when we start getting lots of projects and maybe even people with the same name.
```

_Trac comment by sedwards (github user: seledwards) on 06-11-2013 at 19:12_

**Comment by ahelsing** [comment]
See ticket #77 for adding a project member's email address on the project-member page.

For Heidi's comment about the Join a Project page, see ticket #93.

Given those two tickets, marking this as a duplicate.


_Trac comment by ahelsing on 04-07-2014 at 16:39_
