### ISSUE TITLE
If someone already have an account the invitation does not show up in the home page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#374]
I know that there might be a problem when people are inviting since they might not use the right address, but if they do I should be able to see their invitation in my home page. 

 _Imported from trac ticket [#374](http://trac.gpolab.bbn.com/proto-ch/ticket/374),  created by nriga on 01-16-2013 at 16:12, last modified: 04-07-2014 at 16:42_

**Comment by ahelsing** [comment]
Invitations now do a better job at checking if the person has an account. So I think this is covered.

_Trac comment by ahelsing on 04-07-2014 at 16:42_
