### ISSUE TITLE
home page is slow

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#381]
The home page is slow to load - particularly once you have a few slices and a few projects.

 _Imported from trac ticket [#381](http://trac.gpolab.bbn.com/proto-ch/ticket/381),  created by ahelsing on 01-17-2013 at 16:55, last modified: 01-18-2013 at 11:23_

**Comment by ahelsing** [comment]
the theory is that we are looking up a list of ids, and then for each id looking up the details of that thing.

Additionally, we often look up the same ID many times - like the name of the project lead once per slice in that project


_Trac comment by ahelsing on 01-17-2013 at 16:56_

**Comment by MarshallBrinn** [comment]
Much faster - reduced number of calls from ~100 TO ~10 by in-page caching. The time went down from 10 seconds to 1.5 seconds. Much more comfortable user experience.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-18-2013 at 11:23_
