### ISSUE TITLE
logs show member lookups many times per page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#382]
The logs seem to show that we do a bunch of lookups 2-3x per page load:
 - lookup member by eppn
 - lookup member by id

Why the repetitions?

 _Imported from trac ticket [#382](http://trac.gpolab.bbn.com/proto-ch/ticket/382),  created by ahelsing on 01-17-2013 at 16:57, last modified: 01-18-2013 at 11:21_

**Comment by ahelsing** [comment]
do we really need to be both looking up by eppn and id? Could that be combined?

are we calling some lookup function 2-3 times?

Could we cache info on the member by eppn in the session cache?


_Trac comment by ahelsing on 01-17-2013 at 16:58_

**Comment by MarshallBrinn** [comment]
Fixed by caching calls to services on a per-page basis.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-18-2013 at 11:21_
