### ISSUE TITLE
Clean up files in /tmp

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#383]
The portal creates an omni log file for each invocation of omni. Nothing deletes them. They build up over time.

Add a  cron job to delete files that are old.

 _Imported from trac ticket [#383](http://trac.gpolab.bbn.com/proto-ch/ticket/383),  created by ahelsing on 01-23-2013 at 11:56, last modified: 09-12-2013 at 15:35_

**Comment by tcmitchell** [comment]
A cron job is a nice safety net, but we should also endeavor to remove those files if the action was successfully completed so they don't build up in the first place. Ultimately, we should be leaving the files if they are related to unsuccessful actions so debugging can occur.

_Trac comment by tmitchel (github user: tcmitchell) on 01-23-2013 at 13:03_

**Comment by tcmitchell** [comment]
The stray cert and key files appears to be a commit that commented out the unlink call for those files. Probably commented out for debugging and accidentally left there. The omni logs can be useful, so those may need a cron job to clean up after some time passes, like a week.

_Trac comment by tmitchel (github user: tcmitchell) on 03-07-2013 at 06:21_

**Comment by tcmitchell** [comment]
The cert and key files are now deleted. The omni logs remain.

_Trac comment by tmitchel (github user: tcmitchell) on 03-07-2013 at 08:46_

**Comment by tcmitchell** [comment]
As a temporary workaround:
```
sudo find /tmp -name '*-omni-log-*' -mtime +3 -exec rm {} \;
```


_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:44_

**Comment by tcmitchell** [comment]
I see the following file name patterns:
 * `foo-omni-log-ABC123`
 * `sshABC123`
 * `sshABC123.pub`
 * `UUID.html` (related to Flack?)
 * `*-ssh-key-*`
 * `geni-ABC123`

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:50_

**Comment by tcmitchell** [comment]
The following temp files have been cleaned up:
 * `foo-omni-log-ABC123` -- these are now deleted on success but held if an omni error occurs
 * `sshABC123` -- removed
 * `sshABC123.pub` -- removed
 * `UUID.html` (related to Flack) -- was for debugging, removed

Still to look at:
 * `*-ssh-key-*`
 * `geni-ABC123`


_Trac comment by tmitchel (github user: tcmitchell) on 09-12-2013 at 13:21_

**Comment by tcmitchell** [comment]
`*-ssh-key-*` was an interesting one. We were using the plus operator (`+`) to combine arrays. That can result in some loss of data if keys overlap. With numerically keyed arrays that's frequently the case. Use `array_merge()` to preserve numerically keyed elements across the merge.

_Trac comment by tmitchel (github user: tcmitchell) on 09-12-2013 at 15:21_

**Comment by tcmitchell** [comment]
There are no `geni-ABC123` files in /tmp on nye presently. That leads me to believe that those files were actively in use and not left behind.

I think this ticket is complete.

_Trac comment by tmitchel (github user: tcmitchell) on 09-12-2013 at 15:35_
