### ISSUE TITLE
Support bound RSpecs

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#389]
* Detect bound RSpecs on user upload
 * Annotate RSpecs as either bound or unbound
 * Note which aggregate(s) the RSpec is bound to in RSpec metadata (in DB)
 * If an RSpec is bound, disable the aggregate chooser on the slice-add-resources page
 * Automatically send the RSpec to the appropriate aggregate(s) on the sliceresource page.

 _Imported from trac ticket [#389](http://trac.gpolab.bbn.com/proto-ch/ticket/389),  created by tmitchel on 02-05-2013 at 17:36, last modified: 03-06-2015 at 14:29_
   CCing: nriga@...

**Comment by ahelsing** [comment]
On the Add Resources page, if you first pick an aggregate, and then pick a bound RSpec, the selected aggregate stays selected.

We should un-select that aggregate so it doesn't appear your RSpec is being submitted to the wrong AM

_Trac comment by ahelsing on 02-21-2013 at 09:15_

**Comment by innnkkki** [comment]
If the user does not get a choice then maybe completely remove the second chooser and add a text that explains that:
"Your RSpec uses specific aggregates. We will submit your RSpec to all the appropriate aggregates."

_Trac comment by nriga (github user: innnkkki) on 02-21-2013 at 09:26_

**Comment by seledwards** [comment]
Also, disable the aggregate if the default RSpec is bound.

_Trac comment by sedwards (github user: seledwards) on 02-21-2013 at 09:29_

**Comment by seledwards** [comment]
Aaron's notes from the scaling test:
```
- Pick a bound RSpec
- AM dropdown greyed out
- Hit submit.
  2 issues:
     a) Error: No aggregate id specified
     b) The error page is ugly
Even if you then pick the right AM first and then pick the bound RSpec,
same error
```

_Trac comment by sedwards (github user: seledwards) on 02-25-2013 at 10:20_

**Comment by innnkkki** [comment]
It came up recently in an email thread at the GENI-ORCA-USERS mailing list that the ExoSm does not have a separate component_manager_id, just something to keep in mind when adding support for bound rspecs. 

_Trac comment by nriga (github user: innnkkki) on 05-10-2013 at 09:59_

**Comment by ahelsing** [comment]
Latest code from Ben
 - detects partially bound RSpecs (see other ticket for cleaning this up)
 - disables the aggregate chooser for such bound RSpecs
 - sends the RSpec to stitcher to allocate

_Trac comment by ahelsing on 09-08-2014 at 12:34_

**Comment by ahelsing** [comment]
Note that currently on the Add Resources page if you upload a bound RSpec it correctly detects that the RSpec is bound, but still insists that you pick an Aggregate - it does not know which aggregate the RSpec is bound to. It should extract that and skip forcing you to select an aggregate.

_Trac comment by ahelsing on 09-08-2014 at 12:47_

**Comment by ahelsing** [comment]
This should be fixed by switching to the Jacks Add Resources page, I believe.

_Trac comment by ahelsing on 10-29-2014 at 15:44_
