### ISSUE TITLE
Use "Slice owner" and "Project lead" (instead of "owner" and "lead")

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#39]
Feedback indicated that we should use qualifiers for these terms.

 _Imported from trac ticket [#39](http://trac.gpolab.bbn.com/proto-ch/ticket/39),  created by tmitchel on 05-23-2012 at 14:45, last modified: 05-23-2012 at 15:45_

**Comment by seledwards** [comment]
Standardize usage of "slice owner" and "project lead".

Removed "lead", "leader", and "project leader".

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 15:42_

**Comment by seledwards** [comment]
Did not change "LEAD" to "PROJECT LEAD" in the database.  (This field value gets printed various places.)

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 15:45_
