### ISSUE TITLE
Add domain to URNs

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#391]
The ProtoGENI team reports that the clearinghouse URNs do not have domains, only hostnames. This is problematic because it doesn't indicate the site. Indeed, both user and slice URNs only have the short hostname:
 * `urn:publicid:IDN+dagoola:demo+slice+demo-slice-1`
 * `urn:publicid:IDN+dagoola+user+tmitchel`

To fix:
 1. Add the domain name to the URNs.
 2. Consider using "portal.geni.net" for panther since that's a likely transition path
 3. Notify "geni-dev-utah@flux.utah.edu" when this gets fixed

 _Imported from trac ticket [#391](http://trac.gpolab.bbn.com/proto-ch/ticket/391),  created by tmitchel on 02-13-2013 at 09:38, last modified: 06-06-2013 at 12:28_

**Comment by ahelsing** [comment]
If you're changing this anyway, i definitely would favor using portal.geni.net for panther.  I think it will be less pain later for transitioning existing data.

_Trac comment by chaos on 02-13-2013 at 10:17_

**Comment by tcmitchell** [comment]
This will get fixed with the transition to portal.geni.net/ch.geni.net.

_Trac comment by tmitchel (github user: tcmitchell) on 05-22-2013 at 17:50_

**Comment by ahelsing** [comment]
emailed Utah

_Trac comment by ahelsing on 06-06-2013 at 12:28_
