### ISSUE TITLE
Update portal to use gcf-2.4

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#392]
gcf 2.3.1 was release in June. The portal should transition from gcf 2.1 to gcf 2.3.1.

 _Imported from trac ticket [#392](http://trac.gpolab.bbn.com/proto-ch/ticket/392),  created by tmitchel on 02-14-2013 at 08:53, last modified: 09-06-2013 at 16:40_

**Comment by seledwards** [comment]
To test this:
 1. copy code for gcf-2.2 tag to dev machine
 2. `make install`
 3. restart `pg-ch` daemon
 4. test Flack/omni

Once this works, do same on panther.

_Trac comment by sedwards (github user: seledwards) on 02-18-2013 at 14:18_

**Comment by tcmitchell** [comment]
Note that panther is currently running version 4094de01de, September 21, 2012. This version predates gcf-2.1 by a couple of weeks.

_Trac comment by tmitchel (github user: tcmitchell) on 02-27-2013 at 16:31_

**Comment by seledwards** [comment]
Ok.  It appears that gcf-2.2's pgch does NOT properly support `listmyslices`.  

Regardless of the number of slices I have, I always get:

```
$ ~/gcf/src/omni.py -c ~/.gcf/omni_config.ch.sergyar2 listmyslices sedwards 
INFO:omni:Loading config file /home/geniuser/.gcf/omni_config.ch.sergyar2
INFO:omni:Using control framework portal
INFO:omni:User 'sedwards' has NO slices.
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed listmyslices:

  Options as run:
		configfile: /home/geniuser/.gcf/omni_config.ch.sergyar2
		framework: portal

  Args: listmyslices sedwards

  Result Summary: Found 0 slice(s) for user 'sedwards'.
 
INFO:omni: ============================================================
```

_Trac comment by sedwards (github user: seledwards) on 02-27-2013 at 16:34_

**Comment by ahelsing** [comment]
I pushed a few fixes to pgch.

When testing, we need to make sure (based on mistakes I made):
 - gcf.ini has correct base_name and rootcadir and port
 - slice/project not expired
 - omni config point to a current / correct cert/key
 - gcf-pgch.py being run is the one from the proto-ch module (no True arg to creating the PGCH)

With these fixes, I can do listmyslices and creatslice and listmykeys

_Trac comment by ahelsing on 03-01-2013 at 20:53_

**Comment by seledwards** [comment]
Turns out I've been running an updated version of gcf on sergyar for a couple of weeks at least.  I'm running a version with a tag starting with `260b4935e3f392`.  I haven't seen any issues.  So I suspect this will work, but we should formally test it.  

_Trac comment by sedwards (github user: seledwards) on 06-12-2013 at 14:51_

**Comment by seledwards** [comment]
Updating this ticket to reference a more recent version of omni.

_Trac comment by sedwards (github user: seledwards) on 06-12-2013 at 14:54_

**Comment by ahelsing** [comment]
I've just discovered that in the course of updating to nye, we updated gcf to 2.2.1

That is not the same as 2.3.*, but is a good sign that this update is not as risky as we might have thought.

_Trac comment by ahelsing on 07-02-2013 at 13:37_

**Comment by ahelsing** [comment]
Note that gcf-2.3.1 does not have the CH multithreading fix. So either we backport that (as we already did for the code currently running on nye), or we wait for gcf 2.4.




_Trac comment by ahelsing on 08-08-2013 at 13:49_

**Comment by ahelsing** [comment]
Going to 2.4

_Trac comment by ahelsing on 09-06-2013 at 16:36_
