### ISSUE TITLE
geni-pgch.log should have timestamps in it

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#398]
The log `/var/log/geni-pgch.log` doesn't have timestamps on the entries.  It would be very helpful if it did.

 _Imported from trac ticket [#398](http://trac.gpolab.bbn.com/proto-ch/ticket/398),  created by chaos on 02-20-2013 at 18:04, last modified: 06-07-2013 at 14:41_

**Comment by tcmitchell** [comment]
Python logging can use syslog. Something along these lines:
```
f = logging.Formatter('pgch: %(message)s')
h = logging.handlers.SysLogHandler(address = '/dev/log')
h.setFormatter(f)
logger.addHandler(h)
```


_Trac comment by tmitchel (github user: tcmitchell) on 03-15-2013 at 20:44_

**Comment by ahelsing** [comment]
Syslog would be great --- then (in GPO lab) we'd automatically collect the logs on our syslog server, where we store them for six months.

_Trac comment by chaos on 03-15-2013 at 20:53_

**Comment by ahelsing** [comment]
pgch logs have timestamps. Opening a separate ticket to do syslog

_Trac comment by ahelsing on 06-07-2013 at 14:41_
