### ISSUE TITLE
OBE: undefined index on email_address in ma_utils

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#399]
```
[Wed Feb 20 20:18:57 2013] [error] [client 128.89.91.43] PHP Notice:  Undefined index: email_address in /usr/share/geni-ch/ma/php/ma_utils.php on line 268
```

 _Imported from trac ticket [#399](http://trac.gpolab.bbn.com/proto-ch/ticket/399),  created by ahelsing on 02-20-2013 at 20:37, last modified: 12-05-2013 at 13:19_

**Comment by tcmitchell** [comment]
This appears to be an issue with privilege bootstrapping. The invocation that caused this error was the initial operator privilege granted by the MA, not by a user. The log message for the initial privilege elevation matches the timestamp of the error message above.

The pretty log name generation should verify the result and use something else (urn? uuid?) if no pretty name is available. For instance, get_member_id_log_name could take an extra argument, the URN from the signer cert, and use it as a fallback.

_Trac comment by tmitchel (github user: tcmitchell) on 02-21-2013 at 07:43_
