### ISSUE TITLE
Add to FAQ: no such thing as logout

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#401]
Document that there is no such thing as logging out, for those that get curious

 _Imported from trac ticket [#401](http://trac.gpolab.bbn.com/proto-ch/ticket/401),  created by ahelsing on 02-21-2013 at 09:07, last modified: 04-16-2013 at 21:55_

**Comment by innnkkki** [comment]
A logout functionality was added, maybe we still need an FAQ about why don't I have to enter my username and password when 
I try to login again. 

_Trac comment by nriga (github user: innnkkki) on 04-09-2013 at 17:42_

**Comment by ahelsing** [comment]
What happens if you sign in to your IDP in general, for some other reason, and then browse to the portal? Is it the same as if you sign in to your IDP via the portal and then log out from the portal (but stay logged in to your IDP)? Because that's another thing people might do (sign in to the IDP in order to access other resources, then browse to the portal), so we might want to have something in the FAQ about what to expect in that case.

_Trac comment by jbs on 04-10-2013 at 09:55_

**Comment by seledwards** [comment]
We added a logout button.  Closing as WONTFIX.

_Trac comment by sedwards (github user: seledwards) on 04-16-2013 at 21:55_
