### ISSUE TITLE
give AMs consistent short names

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#402]
Name AMs with a consistent style of short names: site name then type of AM. Not type first.
That way they are easier to find.

 _Imported from trac ticket [#402](http://trac.gpolab.bbn.com/proto-ch/ticket/402),  created by ahelsing on 02-21-2013 at 09:59, last modified: 03-07-2013 at 13:58_

**Comment by tcmitchell** [comment]
All AMs are now listed as "SITE TYPE" like "Utah ProtoGENI" and "RENCI ExoGENI". The one exception is "ExoGENI ExoSM". It's a meta-aggregate, if you will, so not sure how to best handle it. It's at RENCI, but "RENCI ExoGENI" is taken. We could try "RENCI ExoSM", or leave it as "ExoGENI ExoSM".

Reopen if the name should be changed to something other than "ExoGENI ExoSM", which is how it is currently named.

_Trac comment by tmitchel (github user: tcmitchell) on 03-07-2013 at 13:58_
