### ISSUE TITLE
Create script to readily see oustanding project lead requests

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#404]
We need a script to readily see outstanding requests to be a project
lead (I lost track) - you can't rely on emails.

 _Imported from trac ticket [#404](http://trac.gpolab.bbn.com/proto-ch/ticket/404),  created by sedwards on 02-21-2013 at 15:49, last modified: 03-30-2015 at 16:51_

**Comment by ahelsing** [comment]
Note this depends on storing these requests in a DB table.



_Trac comment by ahelsing on 07-30-2013 at 16:48_

**Comment by ahelsing** [comment]
Charlie's admin page will cover this

**Comment by ahelsing** [comment]
Charlie's admin page is in.
