### ISSUE TITLE
On text box to invite project members, clarify if text box takes newlines, commas, etc

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#405]
On the page to invite someone: clarify if the text box takes newlines, commas, etc.

 _Imported from trac ticket [#405](http://trac.gpolab.bbn.com/proto-ch/ticket/405),  created by sedwards on 02-21-2013 at 16:12, last modified: 07-01-2013 at 09:44_
   CCing: nriga@...

**Comment by ahelsing** [comment]
Or, even better, also let it take newlines, commas, whitespace, etc.

_Trac comment by jbs on 02-21-2013 at 16:16_

**Comment by seledwards** [comment]
Someone mentioned today that they found this confusing.

_Trac comment by sedwards (github user: seledwards) on 04-05-2013 at 14:43_
