### ISSUE TITLE
Clarify display of when users have submitted a project join request

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#407]
Hard to tell if a user has submitted a project join request.

See also #408

 _Imported from trac ticket [#407](http://trac.gpolab.bbn.com/proto-ch/ticket/407),  created by sedwards on 02-21-2013 at 16:14, last modified: 08-29-2013 at 11:52_

**Comment by ahelsing** [comment]
Sarah - is this OBE?

_Trac comment by ahelsing on 08-29-2013 at 11:44_

**Comment by seledwards** [comment]
I think this is fixed.  Closing.

_Trac comment by sedwards (github user: seledwards) on 08-29-2013 at 11:52_
