### ISSUE TITLE
Clarify display of when users have a project join request to handle

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#408]
Better distinguish whether you have a project join request to handle

See also #407

 _Imported from trac ticket [#408](http://trac.gpolab.bbn.com/proto-ch/ticket/408),  created by sedwards on 02-21-2013 at 16:16, last modified: 08-29-2013 at 11:49_

**Comment by ahelsing** [comment]
Sarah, is this OBE?

_Trac comment by ahelsing on 08-29-2013 at 11:45_

**Comment by seledwards** [comment]
I think so.  Closing.

_Trac comment by sedwards (github user: seledwards) on 08-29-2013 at 11:49_
