### ISSUE TITLE
Handle mistyped email address in Project Join Invitations

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#409]
If you mistype an email address of someone to invite to a project:
should the sender user get the bounce message, so they know the message did not get through?

 _Imported from trac ticket [#409](http://trac.gpolab.bbn.com/proto-ch/ticket/409),  created by sedwards on 02-21-2013 at 16:19, last modified: 07-01-2013 at 09:45_

**Comment by ahelsing** [comment]
Josh says:
```
IMHO, it'd be fine for it to go just to the inviting user; I don't think
portal admins or gpo-ops care about typos, especially if users can hear
about and correct the problem themselves.

The key thing is that you need the envelope sender be the inviting user,
not just the From: line. (You should also put the inviting user's in the
From: line, IMHO, but that's not enough to cause bounces to go to them.) 
This is probably pretty easy, but depends on how you're sending mail. I'm
happy to help sort this out if you need a hand.
```

_Trac comment by ahelsing on 02-22-2013 at 09:58_

**Comment by ahelsing** [comment]
Chaos notes that we should require an '@' in email addresses - otherwise it uses an @gpolab.bbn.com address, which surely is not right.


_Trac comment by ahelsing on 03-04-2013 at 15:22_

**Comment by ahelsing** [comment]
We should check each address with FILTER_VALIDATE_EMAIL (http://php.net/manual/en/filter.filters.validate.php)

see upload-project-members.php, join-this-project, invite-to-project, invite-to-geni, do-upload-project-members, ask-for-project, do-modify, do-register, and under kmtool, kmnoemail

_Trac comment by ahelsing on 06-25-2013 at 12:50_

**Comment by ahelsing** [comment]
Then also sa_controller and ma_utils to be sure

_Trac comment by ahelsing on 06-25-2013 at 13:00_
