### ISSUE TITLE
Change "you are not in a project" warning from green to red

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#41]
Feedback from Niky

 _Imported from trac ticket [#41](http://trac.gpolab.bbn.com/proto-ch/ticket/41),  created by tmitchel on 05-23-2012 at 14:50, last modified: 05-23-2012 at 16:28_

**Comment by seledwards** [comment]
Changed `portal.css` to use red instead of green.

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 16:28_
