### ISSUE TITLE
Properly handle repeated project join requests

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#410]
What happens if you request to join a project twice? Josh tried joining a
test project of Manu's, where Tim was an admin; Tim approved one of my
requests, and then Manu rejected the second one. Josh seemed to still be a
member after all of that. What should happen?

 _Imported from trac ticket [#410](http://trac.gpolab.bbn.com/proto-ch/ticket/410),  created by sedwards on 02-21-2013 at 16:22, last modified: 01-10-2014 at 12:11_

**Comment by seledwards** [comment]
Aaron suggests:

- Detect a user has an outstanding request to join the same project and
refuse the duplicate request
- If a user is added to a project, delete other outstanding join
requests to the same project
- If a user join request is denied, and there is another identical
(same role) join request, delete that other duplicate request

_Trac comment by sedwards (github user: seledwards) on 02-21-2013 at 16:23_

**Comment by ahelsing** [comment]
Also, if we are denying a join request and the user is already a member of the project, do not send a rejection email (or at least make the text reasonable)

_Trac comment by ahelsing on 11-13-2013 at 14:42_
