### ISSUE TITLE
Add "View RSpec" button on the Add Resources page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#412]
Put a 'View RSpec' button on the 'Add Resources' page to view the selected RSpec

 _Imported from trac ticket [#412](http://trac.gpolab.bbn.com/proto-ch/ticket/412),  created by sedwards on 02-21-2013 at 16:26, last modified: 07-29-2014 at 12:33_

**Comment by ahelsing** [comment]
Added a button that shows you all RSpecs.

Even better would be a button to show the selected RSpec. Leave the ticket open to do that later.

_Trac comment by ahelsing on 03-01-2013 at 15:45_

**Comment by ahelsing** [comment]
Fixed by #581. Managing RSpecs, including viewing RSpecs, can now be accessed via a tab on the 'Add Resources' page.

_Trac comment by bujcich on 07-29-2014 at 12:27_

**Comment by ahelsing** [comment]
Note that the selected RSpec isn't carried over to the Manage Resources tab in any way yet, which might be nice. You can't see the content of the RSpec direct from this page yet.

_Trac comment by ahelsing on 07-29-2014 at 12:33_
