### ISSUE TITLE
Tell Flack not to load all AMs at once

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#414]
Need a way to tell Flack to not load Ads all at once - it won't scale.

It's slow as is.

 _Imported from trac ticket [#414](http://trac.gpolab.bbn.com/proto-ch/ticket/414),  created by sedwards on 02-21-2013 at 18:39, last modified: 08-29-2013 at 12:37_

**Comment by ahelsing** [comment]
Flack isn't going to be making big changes.


_Trac comment by ahelsing on 08-29-2013 at 11:43_
