### ISSUE TITLE
Shrink the header images (geni portal) on the public help page to match other pages

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#42]
Adjust the height/width of these images per the portal header and public landing page.

 _Imported from trac ticket [#42](http://trac.gpolab.bbn.com/proto-ch/ticket/42),  created by tmitchel on 05-23-2012 at 14:51, last modified: 05-23-2012 at 16:39_

**Comment by seledwards** [comment]
Done

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 16:39_
