### ISSUE TITLE
Add new rspec page: explain the fields

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#420]
When I try to add an rspec it asks me for :
  * short name 
  * description

It is not clear what I should put on each field so maybe we should add some text explaining tthat: For example:
  * short name : The name of your rspec as it will appear in the drop down menu
   * description : a more detailed explanation of your rspec about the purpose, topology, AMs it uses etc. 

Also since description is expected to be longer, the input text should also be bigger to indicate that. 

 _Imported from trac ticket [#420](http://trac.gpolab.bbn.com/proto-ch/ticket/420),  created by nriga on 02-25-2013 at 16:45, last modified: 07-22-2014 at 12:30_

**Comment by ahelsing** [comment]
When deploying this, remove /var/www/secure/rspecedit.php and rspechandleedit.php


_Trac comment by ahelsing on 07-22-2014 at 12:30_
