### ISSUE TITLE
Add new rspec page: should new rspecs be public by default?

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#421]
Should the new rspecs be public by default? I am afraid that as people add new rspecs, the list that everyone sees will get too clattered, since people don't tend to change the default selections. Given also that we have no way of checking the short names and description of peoples rspecs, it might get very confusing to find what you are looking for. 

I have thought of that for just a few minutes, so I am willing to be convinced otherwise if you have thought of that more. 

Also do we have a way of ensuring that two short names are not the same? 

 _Imported from trac ticket [#421](http://trac.gpolab.bbn.com/proto-ch/ticket/421),  created by nriga on 02-25-2013 at 16:48, last modified: 08-16-2013 at 14:48_

**Comment by tcmitchell** [comment]
Uploaded RSpecs are now private by default.

_Trac comment by tmitchel (github user: tcmitchell) on 08-16-2013 at 14:48_
