### ISSUE TITLE
sa_controller redundancy

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#423]
Sarah and I noticed that when you create a slice, you get two identical assertions (that you, the creator, are the lead) as well as two identical calls to request_authorization (that you are allowed to call create_slice).

I have looked into both of these and they are real bugs. But I'm not inclined to mess with it right now (we want something stable out soon) and to open a ticket on it instead. Just not that important to rush out a fix.

Essentially,
	- create_slice calls create_assertion and then calls add_slice_member (which does a create_assertion). I think the direct call from create_slice can be removed.

	- create_slice calls request_authorization for 'create_slice'. I think this is old code: all the SAGuard stuff should be doing this for us and I think this can be removed from create_slice.

 _Imported from trac ticket [#423](http://trac.gpolab.bbn.com/proto-ch/ticket/423),  created by mbrinn on 02-27-2013 at 13:23, last modified: 03-01-2013 at 08:30_

**Comment by tcmitchell** [comment]
I fixed both of these. They were, in fact, real bugs and fully redundant. Easy to fix.

_Trac comment by tmitchel (github user: tcmitchell) on 03-01-2013 at 08:30_
