### ISSUE TITLE
geni-ops-report script requires a manual install of python-psycopg2 package

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#425]
On tau-ceti:
```
tau-ceti,[~/proto-ch/bin],16:01(0)$ ./geni-ops-report --help
Traceback (most recent call last):
  File "./geni-ops-report", line 8, in <module>
    import psycopg2
ImportError: No module named psycopg2
```

After running:
```
sudo apt-get install python-psycopg2
```

I get the expected:
```
tau-ceti,[~/proto-ch/bin],16:02(0)$ ./geni-ops-report --help
Usage: geni-ops-report [options]

Options:
  -h, --help            show this help message and exit
  --debug               enable debugging output
  -d DATABASE, --database=DATABASE
                        database name
  --host=HOST           database host
  -u USER, --user=USER  database user
  -p PASSWORD, --password=PASSWORD
                        database password
```

 _Imported from trac ticket [#425](http://trac.gpolab.bbn.com/proto-ch/ticket/425),  created by chaos on 03-01-2013 at 16:03, last modified: 03-01-2013 at 16:12_

**Comment by ahelsing** [comment]
Purpose of the ticket is for tracking for y'all, in case you want to add this package to a documented or scripted install process.  Feel free to close it once you've gotten any information you want out of it.

_Trac comment by chaos on 03-01-2013 at 16:04_

**Comment by tcmitchell** [comment]
psycopg is already in browser:prep-ch.sh as a requirement.

_Trac comment by tmitchel (github user: tcmitchell) on 03-01-2013 at 16:12_
