### ISSUE TITLE
proto-ch make install should put some useful /bin/ scripts into central bin directories

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#426]
It would be useful if some of the executable scripts which are intended to be executed on portal systems were installed into a central location so they could be predictably executed.

 _Imported from trac ticket [#426](http://trac.gpolab.bbn.com/proto-ch/ticket/426),  created by chaos on 03-02-2013 at 19:11, last modified: 03-04-2013 at 15:41_

**Comment by ahelsing** [comment]
Of particular interest to GPO infra are:
```
report_genich_relations
geni-ops-report
```

I think `/usr/local/bin` is probably the best place for a "make install" type execution to install binaries for general use.

_Trac comment by chaos on 03-02-2013 at 19:12_

**Comment by ahelsing** [comment]
Tested on tau-ceti: /usr/local/bin now contains:
```
-rwxr-xr-x  1 root root  7762 Mar  4 15:21 report_genich_relations*
-rwxr-xr-x  1 root root   619 Mar  4 15:21 gmoc_list_slices*
-rwxr-xr-x  1 root root   840 Mar  4 15:21 gmoc_list_contacts*
-rwxr-xr-x  1 root root 11755 Mar  4 15:21 geni-ops-report*
```
Looks good.

_Trac comment by chaos on 03-04-2013 at 15:25_

**Comment by tcmitchell** [comment]
The `bin/Makefile` now installs the following scripts in `/usr/local/bin`:
 * geni-ops-report
 * report_genich_relations
 * gmoc_list_contacts
 * gmoc_list_slices


_Trac comment by tmitchel (github user: tcmitchell) on 03-04-2013 at 15:41_
