### ISSUE TITLE
SSH public key identifier says www-data

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#427]
When the portal generates an SSH keypair for you, the identifier in the public key says www-data@<machine name>.

It would be ideal if this were instead <portal username>@<machine name>

 _Imported from trac ticket [#427](http://trac.gpolab.bbn.com/proto-ch/ticket/427),  created by ahelsing on 03-04-2013 at 12:57, last modified: 03-07-2013 at 19:51_

**Comment by tcmitchell** [comment]
Fixed to use the active username instead of www-data.

_Trac comment by tmitchel (github user: tcmitchell) on 03-07-2013 at 19:51_
