### ISSUE TITLE
Sliver status returns error for AMs with no resources

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#429]
The sliver status page returns error from the AMs with no slices. This is parsed correctly
in the slice page, so maybe identify the error and print no resources. 

 _Imported from trac ticket [#429](http://trac.gpolab.bbn.com/proto-ch/ticket/429),  created by nriga on 03-04-2013 at 19:45, last modified: 08-13-2013 at 17:49_

**Comment by ahelsing** [comment]
This may already be fixed. If so, close as invalid. If not look at amstatus.* to see what it does to parse the error return from aggregates and produce a status string.

_Trac comment by ahelsing on 08-01-2013 at 14:38_

**Comment by ahelsing** [comment]
In addition to fixing the status of AMs with no slices to "no resources", I also fixed the status table to report "failed" from the aggregates where the query fails (previously there was no status reported for those aggregates).  When all the queries are complete, I update the "Querying" message in the blue box to say "Queried X aggregates."  (Previously this message wasn't updated so it just said "Querying X aggregates..." forever.

_Trac comment by phelinek on 08-13-2013 at 17:49_
