### ISSUE TITLE
Sliver details should be grouped to show relevant information at the top of results

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#432]
This is an enhancement request.

The "Resource Status" (ex. Home -> Project projectname -> Slice slicename -> Sliver Status for slicename) page groups results so that the aggregates that have status information are grouped together at the top of the page, while the ones that do not have information are at the bottom of the page. 

This grouping of results should also be applied to the "Details" (Home -> Project projectname -> Slice slicename -> Resources on Slice slices) page, which currently mixes resource status information with "invalid URN" results. 

 _Imported from trac ticket [#432](http://trac.gpolab.bbn.com/proto-ch/ticket/432),  created by lnevers on 03-05-2013 at 09:24, last modified: 07-16-2014 at 10:32_

**Comment by ahelsing** [comment]
Is this still an issue? That is, do we still show error messages for AMs that do not report results?

_Trac comment by ahelsing on 07-16-2014 at 10:29_

**Comment by seledwards** [comment]
I think this is no longer an issue.

_Trac comment by sedwards (github user: seledwards) on 07-16-2014 at 10:31_
