### ISSUE TITLE
PG insists slice names are unique

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#433]
ProtoGENI seems to insist that slice names are unique, independent of project names. 

2 slices at the same PG AM cause an error `code 2. protogeni AM code: 2: Error creating container experiment. `

 _Imported from trac ticket [#433](http://trac.gpolab.bbn.com/proto-ch/ticket/433),  created by ahelsing on 03-05-2013 at 10:09, last modified: 11-04-2013 at 14:27_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Rob & Leigh explained:

PG puts slices in a 'project' named by the slice authority (e.g. panther). Within all of that currently, slice names must be unique.

Sub SAs (e.g. our project name) are used to partition visibility, but do not currently partition the namespace. Leigh and Rob agree that this needs to be fixed, but say it won't happen any time soon.

In detail:
Leigh:
```
Emulab maps slices onto experiments, which exist in projects. Within a
project on an Emulab, experiments names have to be unique *within* the
project. So there can be multiple experiments named "test" as long as they
are in separate projects.

The project is named by the Slice Authority that granted the slice
credential. For slices coming from the portal, this is "Panther". So, there
is a project called Panther on Emulab.

Sub Authorities are mapped onto subgroups of projects. Within each project
a subgroup is just a protection domain; users in one subgroup of a project
cannot see what is going on inside another subgroup of that project. This
was primarily intended to support classes where groups of students could be
partitioned from each other, but still all exist within a single project so
that the instructor/TA did not have to create dozens of projects.

But even with subgroups, experiment names (and thus slice names) must still
be unique to the entire project. It would be too confusing otherwise (this
is already confusing enough for new and inexperienced users!).
```

Rob:
```
we currently need them to be unique across all sub-SAs of the same top-level SA, which is what 'projects' in the portal map to. We are clearly going to need to fix this; this is only showing up now because the portal is the first place to really exercise the sub-SA functionality. 
```

Leigh:
```
it would be a big change to the subgroup mechanism
```

Rob:
```
sub-SA namespace ought to be self-contained like the top-level SA namespace is. 
```


_Trac comment by ahelsing on 03-05-2013 at 10:12_

**Comment by ahelsing** [comment]
I added code to sa_controller making slice names unique across the whole SA. But with a comment so we can take the whole check out when PG fixes their bug.


_Trac comment by ahelsing on 03-05-2013 at 10:16_

**Comment by ahelsing** [comment]
Sarah asked Leigh about this at the GEC18 coding sprint. Leigh fixed it at PG Utah.
I tested the fix from cascade. Wait for Leigh to tell us when it is safe to deploy this fix on the production server.
Code for this fix is on the branch tkt433-sliceuniq


_Trac comment by ahelsing on 10-31-2013 at 12:26_

**Comment by seledwards** [comment]
This sounds great.  Adding gpo-expt-support and marking GEC19 for the milestone.

_Trac comment by sedwards (github user: seledwards) on 11-04-2013 at 14:06_
