### ISSUE TITLE
Make it easier for Windows users to use keys generated by the Portal.

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#434]
Currently we have no easy way for our Windows users to ssh into the VM/raw-machine slivers they create.  This is because putty, the most common Windows ssh client, uses a key format that is different from the key format generated by the portal.

To use the portal generated ssh keys, Windows users have to install puttygen (http://manpages.ubuntu.com/manpages/hardy/man1/puttygen.1.html) and use it to convert the keys to a putty-friendly format.  They then have to tell putty about their private key, which isn't very easy (http://www.howtoforge.com/ssh_key_based_logins_putty_p3).

To work around this we have been asking Windows users at tutorials and networking classes to run Linux as a VirtualBox VM.  We distribute a ~1.5GB VM image just so they can use ssh.

It'll be nice if experimenters can ssh into their VMs right from the portal without having to rely on an ssh client on their computer.  I think Jim Griffioen's portal provides some such functionality.

 _Imported from trac ticket [#434](http://trac.gpolab.bbn.com/proto-ch/ticket/434),  created by vthomas on 03-05-2013 at 13:47, last modified: 05-05-2015 at 15:07_

**Comment by ahelsing** [comment]
_ahelsing attached [PuttyTest.java](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/434/PuttyTest.java) on 07-25-2014 at 08:45_

**Comment by ahelsing** [comment]
_ahelsing attached [PuTTYPrivateKeyFile.java](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/434/PuTTYPrivateKeyFile.java) on 07-25-2014 at 08:45_

**Comment by ahelsing** [comment]
maybe we can include in the portal a script to generate putty format keys and allow users to download those?

_Trac comment by ahelsing on 03-11-2013 at 15:55_

**Comment by ahelsing** [comment]
Info from Wim of iMinds about putty:
```

Basic information about the PPK file format, and the reason why it
exists can be found here:
http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/key-formats-natively.html

There is also a lot of info in the PuTTY source. At
http://svn.tartarus.org/sgt/putty/sshpubk.c?view=markup in the comment
starting from line 382 the format is described. I remember that when
implementing this, I discovered that the info in this comment is not
100% accurate. The code did something not explained very well in the
comment, so you have to read the code itself as well to figure out
some details.

jFed has support for the PPK format, so the jFed code is also a source
of information. This code might be more readable than the PuTTY source
code.
I've attached PuTTYPrivateKeyFile.java from the jFed sources. This is
the implementation of the PPK format. I've also attached
PuttyTest.java which contains related tests (the test PPK and PEM test
files this uses could be useful).
You can find this code in the jFed source at
http://jfed.iminds.be/releases as well (find the latest releases at
the bottom).
```

_Trac comment by ahelsing on 07-25-2014 at 08:45_

**Comment by ahelsing** [comment]
Nick said at the GEC that puttygen runs on Linux, so we should be able to generate putty keys for Windows users to download from the portal.


_Trac comment by ahelsing on 03-30-2015 at 11:02_

**Comment by ahelsing** [comment]
If we generate these, it would be nice to include them in the omni.bundle and make omni-configure use them on Windows

_Trac comment by ahelsing on 03-30-2015 at 11:03_

**Comment by MarshallBrinn** [comment]
I think this is all set. It is checked in on a branch (tkt434_putty). It only works if you have a private SSH key loaded into the portal (and thus, probably, you created it at the portal). It asks you for the passphrase to create and download the putty key. And then putty asks you for the pass phrase again when you use it to SSH into a machine.

I'll merge this into develop once I've gotten a little thumbs-up from experimenter-support.



_Trac comment by mbrinn (github user: MarshallBrinn) on 04-28-2015 at 14:52_

**Comment by MarshallBrinn** [comment]
All set: Text is modified and approved by experimenter support. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-04-2015 at 16:08_
