### ISSUE TITLE
Undefined HTTP_REFERER in sshkeyedit.php

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#438]
I see this in the error_log:

```
[Wed Mar 06 12:46:08 2013] [error] [client 38.97.228.96] PHP Notice:  Undefined index: HTTP_REFERER in /var/www/secure/sshkeyedit.php on line 96
```

 _Imported from trac ticket [#438](http://trac.gpolab.bbn.com/proto-ch/ticket/438),  created by mbrinn on 03-06-2013 at 12:49, last modified: 03-06-2013 at 14:57_

**Comment by tcmitchell** [comment]
One way to reproduce:
 1. You need an ssh key, so upload or generate one
 2. On the profile page, click the edit button next to an ssh key
 3. Click in the URL bar of your browser and hit return

In other words, manually loading the sshkeyedit page with appropriate args set causes no REFERER to be set.


_Trac comment by tmitchel (github user: tcmitchell) on 03-06-2013 at 13:35_

**Comment by tcmitchell** [comment]
`rspecupload.php` appears to be the only other page with unchecked access to HTTP_REFERER. Fix that up as well.

_Trac comment by tmitchel (github user: tcmitchell) on 03-06-2013 at 14:44_

**Comment by tcmitchell** [comment]
Both `rspecupload.php` and `sshkeyedit.php` are now more careful with HTTP_REFERER and set a fallback if it is not set.

_Trac comment by tmitchel (github user: tcmitchell) on 03-06-2013 at 14:57_
