### ISSUE TITLE
Undefined variable ams in raw-sliverstatus.php

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#439]
[Wed Mar 06 12:51:12 2013] [error] [client 38.97.229.41] PHP Notice:  Undefined variable: ams in /var/www/secure/raw-sliverstatus.php on line 70, referer: https://panther.gpolab.bbn.com/secure/sliverstatus.php?slice_id=0978d9dd-e7bf-481b-8cbe-f5dc0a3c6538

 _Imported from trac ticket [#439](http://trac.gpolab.bbn.com/proto-ch/ticket/439),  created by mbrinn on 03-06-2013 at 12:52, last modified: 03-06-2013 at 14:24_

**Comment by ahelsing** [comment]
to reproduce
 - hit Resources Status 
  - on a per aggregate spot
  - or on the whole slice
 - his Raw

try this possibly at an AM that has no resources


_Trac comment by ahelsing on 03-06-2013 at 13:21_

**Comment by ahelsing** [comment]
I can reproduce this using 'Resource Status' at the top of the slice page. 

_Trac comment by ahelsing on 03-06-2013 at 13:52_
