### ISSUE TITLE
Flack launch should pop up a new window or tab

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#44]
Feedback from demo 2.

 _Imported from trac ticket [#44](http://trac.gpolab.bbn.com/proto-ch/ticket/44),  created by tmitchel on 05-23-2012 at 14:56, last modified: 05-23-2012 at 17:04_

**Comment by seledwards** [comment]
Instead of:
```
<button onClick=\"window.location='$sliceflack_url'\">
```

Use:
```
<button onClick=\"window.open('$sliceflack_url')\">
```

Replaced on both `slice.php` and `tool-slices.php`.

_Trac comment by sedwards (github user: seledwards) on 05-23-2012 at 17:04_
