### ISSUE TITLE
save error Omni results

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#444]
It would be nice if the portal pages had a link to show the error result  from omni commands. In particular, parsing out the PG log url

 _Imported from trac ticket [#444](http://trac.gpolab.bbn.com/proto-ch/ticket/444),  created by ahelsing on 03-06-2013 at 20:56, last modified: 06-24-2013 at 14:58_

**Comment by ahelsing** [comment]
Niky says:
```
 I realized that if my creation failed
I have no way of getting the raw output to send it along.

Maybe we can add a link to the end of the page that will give you the raw output.

Also it might be worth while to parse out the URL that PG returns, it is really
useful for debugging. 
```


_Trac comment by ahelsing on 03-06-2013 at 20:56_

**Comment by seledwards** [comment]
Another tricky bit here is how to handle errors from multiple AMs on a single page.
 

_Trac comment by sedwards (github user: seledwards) on 06-08-2013 at 00:50_

**Comment by innnkkki** [comment]
I see that the error log is added to the output (yey!!), it would be very useful if the link was an actual link that a user can follow instead of plain text. 

_Trac comment by nriga (github user: innnkkki) on 06-17-2013 at 12:15_

**Comment by tcmitchell** [comment]
Created snapshot ACTIVE-pre-proto-ch-444 of cascade so that it can be used for testing. This task will require use of a modern ProtoGENI-based aggregate in order to see and parse the new log URL in the error messages.

_Trac comment by tmitchel (github user: tcmitchell) on 06-24-2013 at 10:50_

**Comment by ahelsing** [comment]
Several notes:

 1. Parsing of URL to error log: When there's an error in creating slices on InstaGENI AMs, a URL is parsed and linked so the user can click on it to see the full error log. If the URL cannot be parsed, then it's not displayed at all. This change is in `createslice.php`. This doesn't affect some AMs that don't provide the URL, like pgeni3.
 1. When testing on cascade, I could not request resources from places like Northwestern InstaGENI. Before, the result was a blank box. The error message from omni was received by `am_client.php` but was not returned to `createslice.php` because the `invoke_omni_function` function in `am_client.php` was expecting a JSON structure. Now, if the JSON structure cannot be decoded, the full error message from omni (in the form of a stack traceback) is returned as a string to `createslice.php` and displayed to the user. While not the most ideal format, it's more descriptive than a blank box and lets the user know that something went wrong.
 1. At present, the code changes have been pushed to origin in the `tkt444-omnierror` branch.

_Trac comment by bujcich on 06-24-2013 at 13:44_

**Comment by ahelsing** [comment]
Fixed. I opened a new ticket #649 for fixing the traceback that omni returns.

(Typo in the previous comment: `createslice.php` should be `createsliver.php`.)

_Trac comment by bujcich on 06-24-2013 at 14:58_
