### ISSUE TITLE
slice-add-resources and sliceresource.php must check for expired slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#445]
From the home page, click Add Resources on an expired slice. Works fine. Then click Reserve Resources.
The resulting error page is ugly.

 _Imported from trac ticket [#445](http://trac.gpolab.bbn.com/proto-ch/ticket/445),  created by ahelsing on 03-08-2013 at 12:46, last modified: 03-11-2013 at 15:52_

**Comment by tcmitchell** [comment]
The home page and slice page used to filter out expired slices. Maybe this is a regression introduced by the recent optimizations?


_Trac comment by tmitchel (github user: tcmitchell) on 03-08-2013 at 12:48_

**Comment by ahelsing** [comment]
see ticket #448

_Trac comment by ahelsing on 03-11-2013 at 11:15_
