### ISSUE TITLE
Error page of trying to add resources in an expired slice

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#448]
I tried to add resources in an expired slice  and I got the attached error page. 

Main comment is that I need to know the name of the slice and the UID. 

And Sarah says it needs to be prettier:-)

 _Imported from trac ticket [#448](http://trac.gpolab.bbn.com/proto-ch/ticket/448),  created by nriga on 03-11-2013 at 11:01, last modified: 03-11-2013 at 15:53_

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [Screen Shot 2013-03-11 at 11.01.37 AM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/448/Screen Shot 2013-03-11 at 11.01.37 AM.png) on 03-11-2013 at 11:02_

**Comment by ahelsing** [comment]
see ticket #445

_Trac comment by ahelsing on 03-11-2013 at 11:15_

**Comment by ahelsing** [comment]
Sarah says Niky got to this from the Slice page. Perhaps the 'Add Resources' button needs to be disabled for an expired slice. Ditto in tool-slices. And probably ditto for a bunch of other buttons.

_Trac comment by ahelsing on 03-11-2013 at 11:49_
