### ISSUE TITLE
Filename when downloading rspec from the portal

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#454]
When trying to download an rspec from the portal the name defaults to rspec.xml
which is pretty generic, maybe use the short description that also appears in the list 
for the name. 

 _Imported from trac ticket [#454](http://trac.gpolab.bbn.com/proto-ch/ticket/454),  created by nriga on 03-14-2013 at 14:10, last modified: 04-02-2013 at 17:30_

**Comment by seledwards** [comment]
Committed.

_Trac comment by sedwards (github user: seledwards) on 04-02-2013 at 17:30_
