### ISSUE TITLE
projects listing does not differentiate between active and expired projects

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#456]
When i browse to [https://panther.gpolab.bbn.com/secure/projects.php], i see all projects i have ever been in, including the `scaleTest*` and `sigcse` projects, which have expired.

The projects listing should only show projects which are still active, or at the least should have some kind of indication that a given project has expired.

 _Imported from trac ticket [#456](http://trac.gpolab.bbn.com/proto-ch/ticket/456),  created by chaos on 03-19-2013 at 18:48, last modified: 03-20-2013 at 13:21_

**Comment by tcmitchell** [comment]
This topic is covered on issue #422, specifically comment:ticket:422:2.

_Trac comment by tmitchel (github user: tcmitchell) on 03-20-2013 at 13:21_
