### ISSUE TITLE
On home page add prompt to upload an ssh key if you don't already have one

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#46]
_Imported from trac ticket [#46](http://trac.gpolab.bbn.com/proto-ch/ticket/46),  created by tmitchel on 05-23-2012 at 14:57, last modified: 06-05-2012 at 15:40_

**Comment by ahelsing** [comment]
we have the nav bar

_Trac comment by ahelsing on 06-05-2012 at 15:40_
