### ISSUE TITLE
KM undefined index

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#460]
During tutorial with flaky wireless:

```
unable to load X509 request
22646:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:650:Expecting: CERTIFICATE REQUEST
[Wed Mar 20 16:42:08 2013] [error] [client 155.99.106.108] PHP Notice:  Undefined index: file in /var/www/secure/kmcert.php on line 119, referer: https://panther.gpolab.bbn.com/secure/kmcert.php?close=1
```

 _Imported from trac ticket [#460](http://trac.gpolab.bbn.com/proto-ch/ticket/460),  created by ahelsing on 03-20-2013 at 17:07, last modified: 04-08-2014 at 09:29_

**Comment by tcmitchell** [comment]
Likely that submit was clicked without uploading a file. See if that reproduces this error message.

_Trac comment by tmitchel (github user: tcmitchell) on 03-21-2013 at 12:49_

**Comment by ahelsing** [comment]
Not reproduced in 13 months.

_Trac comment by ahelsing on 04-08-2014 at 09:29_
