### ISSUE TITLE
Print the total number of project members

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#461]
It would be useful, especially in tutorials to easily have the total number of members that are registered

 _Imported from trac ticket [#461](http://trac.gpolab.bbn.com/proto-ch/ticket/461),  created by nriga on 03-22-2013 at 11:12, last modified: 04-02-2013 at 16:36_

**Comment by seledwards** [comment]
Committed this fix.

_Trac comment by sedwards (github user: seledwards) on 04-02-2013 at 16:36_
