### ISSUE TITLE
AJAX-ify the _slice_ details page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#465]
The page to login information _for all aggregates_ is very slow to come up.  Should be AJAX-ified so we can point people to this.

 _Imported from trac ticket [#465](http://trac.gpolab.bbn.com/proto-ch/ticket/465),  created by sedwards on 03-23-2013 at 10:41, last modified: 02-24-2014 at 14:53_
   CCing: nriga@...

**Comment by tcmitchell** [comment]
Not actively being worked. Bumping back from next release.

_Trac comment by tmitchel (github user: tcmitchell) on 01-23-2014 at 13:59_

**Comment by tcmitchell** [comment]
There is a branch with work in progress if you want to start with that. Or you can start on your own. The branch is on origin as `tkt465-ajax-details`. Let me know if you have questions.

_Trac comment by tmitchel (github user: tcmitchell) on 02-05-2014 at 11:07_

**Comment by seledwards** [comment]
I started over on this ticket.  Changes are in.

To test:
 * Click Details for a single AM
 * Then click "Raw RSpec" for that single AM
 * Details for the whole slice (at the top of the page)
 * Then click "Raw RSPec" 
 * Also check manifest shown after createsliver
 

_Trac comment by sedwards (github user: seledwards) on 02-24-2014 at 14:53_
