### ISSUE TITLE
Make the list of RSpecs be ordered or organized in some way

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#467]
During tutorials it can be hard for people to find the appropriate RSpec which may be buried at the bottom of the list.  This will only get worse with time.  

Can we make certains RSpecs stick to the top of the list?  Perhaps RSpecs for tutorials?  Or RSpecs made by you or your project?  

 _Imported from trac ticket [#467](http://trac.gpolab.bbn.com/proto-ch/ticket/467),  created by sedwards on 03-23-2013 at 10:45, last modified: 07-29-2014 at 12:30_
   CCing: nriga@...

**Comment by ahelsing** [comment]
Niky says we need to be able to organize Openflow vs non openflow RSpecs in some way. Like OF rspecs are in a separate list.

See #800

_Trac comment by ahelsing on 09-17-2013 at 17:04_

**Comment by ahelsing** [comment]
RSpecs are now alphabetical

_Trac comment by ahelsing on 10-09-2013 at 13:08_

**Comment by ahelsing** [comment]
The manage RSpecs page will soon let you search over rspec names as well.

_Trac comment by ahelsing on 07-17-2014 at 09:53_

**Comment by ahelsing** [comment]
Partially fixed by #581. While RSpecs aren't necessarily grouped, they can now be searched or sorted based on name, description, or owner.

_Trac comment by bujcich on 07-29-2014 at 12:30_
