### ISSUE TITLE
Add instructions to the ssh key page(s)

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#47]
The ssh pages need instructions - what to do with the thing you downloaded or how to create one for upload (ask Niky if she already has this)

 _Imported from trac ticket [#47](http://trac.gpolab.bbn.com/proto-ch/ticket/47),  created by tmitchel on 05-23-2012 at 14:58, last modified: 12-05-2013 at 09:47_

**Comment by ahelsing** [comment]
No one has asked for more instructions in a long while, so I assume what we have is enough

_Trac comment by ahelsing on 12-05-2013 at 09:47_
