### ISSUE TITLE
Clean up the labels on the aggregate buttons in Flack

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#470]
The aggregate labels have backslashes ("\") and plus signs ("+"), etc. Clean these up.

What string or field does Flack use for these labels, and where along the pipeline (service registry -> pgch -> flack) are the characters added?

 _Imported from trac ticket [#470](http://trac.gpolab.bbn.com/proto-ch/ticket/470),  created by tmitchel on 03-28-2013 at 11:05, last modified: 03-29-2013 at 13:38_

**Comment by ahelsing** [comment]
Yup, it was the sfa code in pgch.
Putting in a fix

_Trac comment by ahelsing on 03-29-2013 at 13:26_
