### ISSUE TITLE
Support revoking / re-generating certificates

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#471]
We need a UI and functions to let users revoke or more like re-generate outside certificates.

Doing so means adding the old cert to the CRL

 _Imported from trac ticket [#471](http://trac.gpolab.bbn.com/proto-ch/ticket/471),  created by ahelsing on 03-28-2013 at 14:32, last modified: 05-15-2014 at 08:55_

**Comment by tcmitchell** [comment]
For regeneration see #241.
For revocation see chapi ticket 171.
See also #232.

_Trac comment by tmitchel (github user: tcmitchell) on 05-15-2014 at 08:55_
