### ISSUE TITLE
Re-order generate certificate options

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#472]
Make option 3 (all on the portal) be option 1. Slide options 1&2 down with a preface that these are more advanced but more secure options.

 _Imported from trac ticket [#472](http://trac.gpolab.bbn.com/proto-ch/ticket/472),  created by ahelsing on 03-28-2013 at 14:34, last modified: 03-29-2013 at 18:21_
   CCing: nriga@...

**Comment by seledwards** [comment]
Option 1 is now a version where the key and cert are supplied to you.  And Option 2 has two variations but you are required to submit a CSR.

Committed and pushed to panther.

_Trac comment by sedwards (github user: seledwards) on 03-29-2013 at 18:21_
