### ISSUE TITLE
Lauch Flack with all your slices

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#474]
Have a Launch Flack button that will load all the slices of the user within the project. 

 _Imported from trac ticket [#474](http://trac.gpolab.bbn.com/proto-ch/ticket/474),  created by nriga on 03-29-2013 at 14:38, last modified: 04-08-2014 at 09:14_

**Comment by ahelsing** [comment]
Flack development is over, so we can't get PG support to make this work.

_Trac comment by ahelsing on 08-29-2013 at 11:48_

**Comment by tcmitchell** [comment]
Flack has been removed from the portal. This is OBE.
