### ISSUE TITLE
Detail pages should mention manifest rspec

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#475]
In the bottom of the Details page in a slice it should it currently say:
"Raw Resource Specification"

And it is hard to understand what rspec this is maybe say :
Raw XML (Manifest rspec)

Or something similar...

 _Imported from trac ticket [#475](http://trac.gpolab.bbn.com/proto-ch/ticket/475),  created by nriga on 03-29-2013 at 15:45, last modified: 07-21-2014 at 15:48_

**Comment by ahelsing** [comment]
I carefully removed the word 'rspec' from this page.

But perhaps we need the word 'manifest'


_Trac comment by ahelsing on 03-29-2013 at 15:57_

**Comment by ahelsing** [comment]
Now calling it: `Raw XML Resource Specification (Manifest)`

_Trac comment by ahelsing on 07-21-2014 at 15:48_
