### ISSUE TITLE
Move Account Summary to top of Profile page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#479]
The Account Summary includes info about the user like their username.  Put it at the top of the page.

 _Imported from trac ticket [#479](http://trac.gpolab.bbn.com/proto-ch/ticket/479),  created by sedwards on 04-02-2013 at 09:22, last modified: 10-09-2013 at 14:31_
   CCing: nriga@...

**Comment by ahelsing** [comment]
done

_Trac comment by ahelsing on 10-09-2013 at 14:31_
