### ISSUE TITLE
Replace the aggregate URL with the nickname in aggregate table(s)

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#48]
_Imported from trac ticket [#48](http://trac.gpolab.bbn.com/proto-ch/ticket/48),  created by tmitchel on 05-23-2012 at 15:00, last modified: 05-24-2012 at 16:38_

**Comment by seledwards** [comment]
Added `am_mapping.php` with a method which creating an array that maps AM urls to AM names once for reuse later.  Also adds a method `am_name()` which takes an AM url and returns an AM name.

Replaced AM urls on `slice.php` and `sliverstatus.php` with AM names.

Closing.

_Trac comment by sedwards (github user: seledwards) on 05-24-2012 at 16:38_
