### ISSUE TITLE
Limit project names to 32 characters

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#481]
ProtoGENI translates the project name into a group name and imposes a 32 character limit. 32 characters ought to be enough to convey meaning and create a unique project name, so we should adopt that limit as well.

This requires a change in the PA to check for and enforce the limit, as well as a change in the portal to provide a reasonable UI for the limit on project names.

 _Imported from trac ticket [#481](http://trac.gpolab.bbn.com/proto-ch/ticket/481),  created by tmitchel on 04-04-2013 at 12:15, last modified: 04-11-2013 at 15:40_

**Comment by ahelsing** [comment]
See lib/php/pa_constants#is_valid_project_name
At the same time maybe
```
 do something more like what I think we do for slice names, which is to define what is acceptable rather than what is unacceptable. We could then constrain the project names to 32 characters, letters and numbers (maybe enforce leading character), hyphen, underscore, etc. But choose what characters are OK, rather than trying to weed out all the characters we think are not OK.
```


_Trac comment by ahelsing on 04-05-2013 at 09:43_

**Comment by tcmitchell** [comment]
See is_valid_slice_name in [lib/php/sa_constants.php](../tree/master/lib/php/sa_constants.php) for a good example of what to do.

_Trac comment by tmitchel (github user: tcmitchell) on 04-05-2013 at 09:56_

**Comment by ahelsing** [comment]
Note that for our purposes, project names end up in the authority part of a URN - where, after converting to ASCII, the string must be < 64 characters. And so the base name of the SA plus a '.' counts against that 64 char limit.

Put another way: If we allow 32 char project names, then our SA name (e.g. ch.geni.net) is limited to 31 characters (which isn't much of a restriction in practice).


_Trac comment by ahelsing on 04-05-2013 at 10:33_
