### ISSUE TITLE
Limit project names to legal characters

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#483]
project names end up in the authority part of URNs, so must be internationalized domain names, and should not include characters that are used in the publicid/URN conversion.

project names end up in email addresses (eventually), so are restricted there too.

And project names end up in other systems, which have character limits.

Figure out what that all means and do the right thing.

 _Imported from trac ticket [#483](http://trac.gpolab.bbn.com/proto-ch/ticket/483),  created by ahelsing on 04-05-2013 at 10:48, last modified: 04-11-2013 at 15:40_

**Comment by ahelsing** [comment]
My read is that we should exclude any unicode/ascii whitespace or control characters.
Internally, we should treat project names as case insensitive (for uniqueness purposes), and lowercase them in URNs.
And we should limit the length to something under 50 characters (63 less the base SA name and a .) - even further than that really.

Beyond that its harder to tell:

http://en.wikipedia.org/wiki/Internationalized_domain_name

In particular, note that non-ASCII is allowed.
The main limit is that the complicated ToASCII algorithm must result in an ASCII string that does not exceed the 63char limit of a DNS name. Part of this process includes first _lowercasing_ the string.

ASCII characters are preserved as is.

Humph. So clearly project names should be lowercase. And it looks like any form of whitespace should not be allowed. And control characters. And if you combine the ASCII version of the project name with the base SA authority name plus a '.', that needs to be < 64 characters at least. But beyond that, I think the standard allows anything.

So implementing that would be hard.

I did find this:
http://pecl.php.net/package/idn
or maybe
http://repo.or.cz/w/htmlpurifier.git/commit/974fe3f25e795cdb3eca9e9044959997e8aefde0
or
http://www.php.net/manual/en/function.idn-to-ascii.php
or
http://idnaconv.phlymail.de/

Meanwhile, our intent to make these email addresses is interesting.

From what I can tell, email addresses can have funny characters in them - you just have to wrap them in quotes. In particular, both spaces and @ signs are legal - they just have to be escaped.
See:
http://en.wikipedia.org/wiki/Email_address#Local_part
or
http://tools.ietf.org/html/rfc3696#page-5



_Trac comment by ahelsing on 04-05-2013 at 10:50_

**Comment by seledwards** [comment]
It occurs to me that escaping characters and the like can make what would be a single character take extra characters.  Do we want to take that into account?


_Trac comment by sedwards (github user: seledwards) on 04-05-2013 at 10:53_

**Comment by ahelsing** [comment]
I plan to make project name legal characters highly restrictive for now - we can always expand the set later. Alphanumeric plus underscore or hyphen.

`  $pattern = '/^[a-zA-Z0-9-_]{1,32}$/';  `



_Trac comment by ahelsing on 04-11-2013 at 14:57_

**Comment by ahelsing** [comment]
Slight modification to the regex - exclude leading hyphen or underscore.


_Trac comment by ahelsing on 04-11-2013 at 15:40_
