### ISSUE TITLE
Create a mechanism to disable accounts of people who are behaving badly

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#486]
If someone behaves badly in a way that causes an operator to believe that they should have NO permission in the portal (eg shouldn't even be able join a project), we should have a way to enforce that.

 _Imported from trac ticket [#486](http://trac.gpolab.bbn.com/proto-ch/ticket/486),  created by sedwards on 04-15-2013 at 14:39, last modified: 12-05-2013 at 13:11_

**Comment by ahelsing** [comment]
Per discussions with Chaos
 - Start by disabling this in the portal (not the CH). Perhaps a check in user.php of a flag in the DB
 - Aim for that much at least by GEC17
 - Then also protect CH calls. Perhaps require a new assertion in the CS that the user is OK in all guards.


_Trac comment by ahelsing on 04-25-2013 at 08:52_

**Comment by ahelsing** [comment]
maybe an attribute in ma_member_attribute checked by user.php (direct to diff page) and the ma (refuse to give out user cred or cert/keys

Plus remove them from projects


_Trac comment by ahelsing on 07-18-2013 at 13:27_

**Comment by ahelsing** [comment]
Just wanted to ping on this to note that "freeze user" is still a capability infra would really like the portal and the CH services to have.

_Trac comment by chaos on 09-04-2013 at 14:45_

**Comment by ahelsing** [comment]
There is a disable-user script on the new clearinghouse

_Trac comment by ahelsing on 12-05-2013 at 12:58_
