### ISSUE TITLE
clean up privilege table

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#493]
See the email thread. Make the privileges for different roles consistent and as expected.

 _Imported from trac ticket [#493](http://trac.gpolab.bbn.com/proto-ch/ticket/493),  created by ahelsing on 04-25-2013 at 14:41, last modified: 05-14-2013 at 16:46_

**Comment by MarshallBrinn** [comment]
Fixed. Made the following changes to the database.

1. Make a new PRIVILEGE called USE. Auditors don't have this but everyone else does. create_slice on project is in this category.
2. Made PROJECT and SLICE membership operations part of the DELEGATE group (was in the WRITE group)
3. Remove WRITE privileges from PROJECT members

Also removed delete_project on client, controller and privilege side
And removed privileges associated with delete_slice: there is no such method.

                           
-- Remove the action 'delete_slice' : no such thing                                     


_Trac comment by mbrinn (github user: MarshallBrinn) on 04-26-2013 at 10:06_
