### ISSUE TITLE
Fix Slice/Project Membership functionality according to recent feedback

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#496]
Fix the following aspects of Slice/Project Membership portal functionality based on recent feedback:
* Make the lists of members by role type
* Make resource status and details greyed out for auditors
* Add headers to the slice and project membership edit pages
* Change "Edit" to "Edit Membership" for editing slice/project membership
* Either duplicate the logic to let you edit project members on the project edit page or include a button to get to the project member editing page

 _Imported from trac ticket [#496](http://trac.gpolab.bbn.com/proto-ch/ticket/496),  created by mbrinn on 05-01-2013 at 07:07, last modified: 07-10-2013 at 13:55_

**Comment by ahelsing** [comment]
is this fixed?

_Trac comment by ahelsing on 07-02-2013 at 11:54_

**Comment by ahelsing** [comment]
Fixed. Most of these were already done. The headers on the edit pages for slices/projects were changed to make the page function clearer to the user (e.g. "Edit GENI Slice Membership" for `edit-slice-member.php`).

_Trac comment by bujcich on 07-10-2013 at 13:55_
