### ISSUE TITLE
Removing from project doesn't remove access to slice

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#497]
Per Aaron's note:
When I remove a member from a project, they still have access to the slice. Sort of.
Slices tab lists no slices
But the individual slie page still shows that person as a member. But the 'Edit slice membership' page does not show them.
My logs show "Added Marshall Brinn to Slice asfd in role Admin" just after I thought I removed Marshall form the slice. How did he get added back?

 _Imported from trac ticket [#497](http://trac.gpolab.bbn.com/proto-ch/ticket/497),  created by mbrinn on 05-01-2013 at 07:08, last modified: 07-05-2013 at 09:53_

**Comment by MarshallBrinn** [comment]
I recall that the semantics we want is:
	- When a project lead or admin removes X from project P
		- We remove X from any slices of project P.
		- If any of these slices have X as the lead, we make the lead of project P as the lead of the slice.
		- Then we remove X from the project.


_Trac comment by mbrinn (github user: MarshallBrinn) on 05-01-2013 at 08:09_

**Comment by MarshallBrinn** [comment]
I have fixed this, tested and checked into the development branch.

That said, the second part of Aaron's note about the admin coming back is a mystery: I couldn't reproduce it.



_Trac comment by mbrinn (github user: MarshallBrinn) on 05-01-2013 at 09:41_

**Comment by seledwards** [comment]
I think this issue has reoccured.  We want to implement the rule: "If you are removed from a project, then you are removed from a slice."

_Trac comment by sedwards (github user: seledwards) on 05-14-2013 at 17:27_

**Comment by ahelsing** [comment]
This appears to be fixed. Tested in the following way with two accounts:
 1. A creates a project. B added to project as member.
 1. B creates a slice. B becomes slice lead (A is slice admin).
 1. A removes B from project.
 1. A is now slice lead.

_Trac comment by bujcich on 07-05-2013 at 09:53_
