### ISSUE TITLE
Auditor can see member info from slice page but not from project page

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#498]
There is an issue of privileges. 

An auditor in a project can click on the member of a project (on the project members section of the project page) and can see the list of slices to which the person belongs (and roles).

But on the slice page, clicking on a person in the slice member section gives an error "You can't see someone else's slices".

We should make this consistent.

 _Imported from trac ticket [#498](http://trac.gpolab.bbn.com/proto-ch/ticket/498),  created by mbrinn on 05-01-2013 at 07:35, last modified: 04-08-2014 at 09:25_

**Comment by MarshallBrinn** [comment]
Some commentary from emails

* The issue is that get_slices_for_member is guarded to only be called by the member. This is what we call from the slice page.
But from the project page, we call a combination of
   - $project_members = get_project_members($pa_url, $user, $project_id, null);
   - $slice_members = get_slice_members_for_project($sa_url, $user, $project_id, null);
   - $slices = lookup_slices($sa_url, $user, $project_id, null);

None of which is prohibited for auditors.

A few possible solutions:

- We get rid of these pages entirely. Perhaps they are no longer valuable.
- We allow auditors to see the slices to which another member belongs
- We put a similar guard on PA.get_slice_members_for_project as we have on SA.get_slices_for_member



_Trac comment by mbrinn (github user: MarshallBrinn) on 05-01-2013 at 07:46_

**Comment by ahelsing** [comment]
This is OBE - the PA/SA were rewritten, the guards changed, and we disabled the slice member page.

_Trac comment by ahelsing on 04-08-2014 at 09:25_
