### ISSUE TITLE
install scripts that portal operators run in /usr/local/bin on portals

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#499]
Install the following utilities from proto-ch/bin into `/usr/local/bin` (some other utilities, such as `geni-ops-report`, are already installed into `/usr/local/bin`):
```
geni-add-member-privilege
geni-add-project-member
geni-remove-project-member
```

 _Imported from trac ticket [#499](http://trac.gpolab.bbn.com/proto-ch/ticket/499),  created by chaos on 05-03-2013 at 11:46, last modified: 05-28-2013 at 15:02_

**Comment by ahelsing** [comment]
Rationale: since not all portal operators are necessarily developers, it's not ideal that portal operators need to check out the git tree to get consistent copies of CLI tools to use to do portal operations.  If operator utilities live in a consistent place on each portal/CH host, operators have the choice of configuring their certificates so they can run CLI commands from the portal host itself.

We can write consistent documentation for doing things that way, and everyone who does that is guaranteed to get the same version of the utilities which match the version installed on the portal/CH at that time.

This doesn't preclude people installing the tools on their own desktops, it just provides a consistent option for people who do portal operations infrequently and/or don't want to do extra setup.


_Trac comment by chaos on 05-03-2013 at 11:50_

**Comment by tcmitchell** [comment]
This is already part of the new install process that is under development. There will be an option to install executables in `/usr/local/[s]bin`.

_Trac comment by tmitchel (github user: tcmitchell) on 05-03-2013 at 12:21_

**Comment by tcmitchell** [comment]
This feature is complete and will be part of a future release.

_Trac comment by tmitchel (github user: tcmitchell) on 05-08-2013 at 13:05_

**Comment by tcmitchell** [comment]
Use `--bindir=/usr/local/bin --sbindir=/usr/local/sbin` args to configure script. Part of #354.

_Trac comment by tmitchel (github user: tcmitchell) on 05-28-2013 at 14:55_
