### ISSUE TITLE
Sliver status page is increasingly indenting the table rows

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#50]
_Imported from trac ticket [#50](http://trac.gpolab.bbn.com/proto-ch/ticket/50),  created by tmitchel on 05-23-2012 at 15:01, last modified: 05-25-2012 at 16:25_

**Comment by seledwards** [comment]
Yep.  There was an extra <td>. It's now removed.

Closing.

_Trac comment by sedwards (github user: seledwards) on 05-25-2012 at 16:25_
