### ISSUE TITLE
Add slice members public keys to omni-bundle.zip

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#508]
Now that we have slice membership, omni users may want to load the public keys of people on their project onto their slices.  To do this, the omni-bundle.zip will have to contain those keys.

 * Figure out how to handle the fact that users and their keys are slice specific (which is not currently supported by omni)

 _Imported from trac ticket [#508](http://trac.gpolab.bbn.com/proto-ch/ticket/508),  created by sedwards on 05-10-2013 at 15:35, last modified: 09-12-2013 at 11:12_
   CCing: nriga@...

**Comment by ahelsing** [comment]
We could add the entries for the all members of all slices that you are a member of, but not list those users in the `[users]` tag in the `omni_config`. But then experimenters would have to edit the `omni_config` depending on which slice they are using.

Is that too confusing?


_Trac comment by ahelsing on 09-12-2013 at 10:24_

**Comment by seledwards** [comment]
I think this should wait for the new common CH API which will provide a way to query for the users and public keys associated with a slice.  Then we can have omni make that call and add those users and public keys to the createsliver call.

_Trac comment by sedwards (github user: seledwards) on 09-12-2013 at 10:42_

**Comment by ahelsing** [comment]
Per Sarah, closing as won't fix

_Trac comment by ahelsing on 09-12-2013 at 11:12_
