### ISSUE TITLE
Add slice members public keys to omni template

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#509]
Add slice members to omni_config template that is downloadable from the profile page.

See also #508.

 _Imported from trac ticket [#509](http://trac.gpolab.bbn.com/proto-ch/ticket/509),  created by sedwards on 05-10-2013 at 15:36, last modified: 09-12-2013 at 11:13_
   CCing: nri@...

**Comment by ahelsing** [comment]
Per Sarah, closing as Won't Fix

_Trac comment by ahelsing on 09-12-2013 at 11:13_
