### ISSUE TITLE
Display and gray out buttons when people do not have appropriate permissions (instead of hiding the button)

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#51]
_Imported from trac ticket [#51](http://trac.gpolab.bbn.com/proto-ch/ticket/51),  created by tmitchel on 05-23-2012 at 15:02, last modified: 06-11-2012 at 14:25_

**Comment by MarshallBrinn** [comment]
I think this is done. I've put optional disabled buttons on all the functions I could see that needed them. I'll close this now but feel free to re-open if I've forgotten anything or gotten the logic wrong.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-11-2012 at 14:25_
