### ISSUE TITLE
Augment "Details" page with login info for multiple users

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#510]
1. Determine if IG manifests contain the login info for multiple users (if supplied). (EG currently doesn't support multiple users being loaded in the first place)
 2. Make sure "Details" page contains login info for these other users.

 _Imported from trac ticket [#510](http://trac.gpolab.bbn.com/proto-ch/ticket/510),  created by sedwards on 05-10-2013 at 15:39, last modified: 06-18-2013 at 17:01_
   CCing: nriga@...

**Comment by seledwards** [comment]
Niky and I tested and IG is only listing one login.  Niky emailed IG asking about it.

I checked in a change for the Details page which should make the code more robust to multiple logins.  Needs testing with an AM that reports multiple login info.

_Trac comment by sedwards (github user: seledwards) on 05-10-2013 at 17:21_

**Comment by ahelsing** [comment]
There is only 1 user's login in the base RSpec schema. There is an extension to support multiple, but I don't expect support for that until AM API v3.

http://groups.geni.net/geni/wiki/GAPI_AM_API_V3/CommonConcepts#Userlogininformation-ManifestRspecExtension


_Trac comment by ahelsing on 05-13-2013 at 10:24_

**Comment by ahelsing** [comment]
actually, you are allowed to include the login element multiple times in a manifest, but I don't think anyone does. Maybe GRAM.

_Trac comment by ahelsing on 05-13-2013 at 11:47_

**Comment by seledwards** [comment]
Aaron is going to request that InstaGENI add support to the AM API v2 implementation so that it includes login info for multiple users in the manifest.

If we can't get that, we'll need to call readyToLogin.py to get the login info.

_Trac comment by sedwards (github user: seledwards) on 05-13-2013 at 15:45_

**Comment by seledwards** [comment]
Aaron sent mail requesting this:

```
Aaron Helsinger <ahelsing@bbn.com>
To: ProtoGENI Developers <protogeni-dev@googlegroups.com>
[protogeni-dev] APIv2 and multiple user's login information

AM API v3 specifies an extension for showing multiple users and their
SSH keys in the manifest RSpec.

http://groups.geni.net/geni/wiki/GAPI_AM_API_V3/CommonConcepts#Userlogininformation-ManifestRspecExtension

Would it be possible for you to implement this extension as part of your
AM API v2 implementation? Or is this really hard?

We'd like this so that our tools can look in a single standard place for
the login information. Currently, we have to look at SliverStatus for PG
AMs, where other AMs or AM APIv3 PG will provide that information in the
manifest RSpec.
```

_Trac comment by sedwards (github user: seledwards) on 05-13-2013 at 16:56_

**Comment by seledwards** [comment]
Looks like we need to incorporate 'readyToLogin.py' in order to get this capability.

_Trac comment by sedwards (github user: seledwards) on 05-20-2013 at 13:24_

**Comment by seledwards** [comment]
This is important to get in as soon as feasible.

_Trac comment by sedwards (github user: seledwards) on 05-21-2013 at 16:49_

**Comment by seledwards** [comment]
This should be done ASAP.  

_Trac comment by sedwards (github user: seledwards) on 05-28-2013 at 15:13_

**Comment by seledwards** [comment]
I spoke with Niky and we decided that the existing code works except for the IG case (which needs to call SliverStatus to get the necessary info).

I'm working on adding an AJAX-ified SliverStatus call to the Details (manifest) page.  This means that page would render as it does now, but that for IG/PG AMs additional login info would fill in based on an additional SliverStatus call.

To do:
 * amstatus.php should fill in the additional login info from PG/IG AMs. (I made a php version of `getInfoFromSliverStatusPG` from the `readyToLogin.py` script which adds the info needed to generate the login to the existing return of `amstatus.php`.)
 * Add a little bit of AJAX to the Details page to call amstatus.php, pull out the login info and insert it next to the existing login info from the manifest
 * Figure out how to only call amstatus.php if there is a PG/IG AMs in the manifest?

The first item is basically done.  The second is in progress.  I have throughts about the third.

_Trac comment by sedwards (github user: seledwards) on 06-18-2013 at 09:56_

**Comment by seledwards** [comment]
Ok.  I did one and two above.  Tested in multi-node PG case.  Tested in multi-AM case (PG and a local gcf AM).  Currently it always queries all aggregate types regardless of whether PG/IG or EG or something else.

Login information from SliverStatus replaces login information from the manifest.

Closing.

_Trac comment by sedwards (github user: seledwards) on 06-18-2013 at 17:01_
