### ISSUE TITLE
Project Lead shown on home page (and project page?) is actually the project creator

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#512]
On the portal home page, Project Lead appears to really be the creator of the project?  The same appears to be true on the Project page.

Either change the displayed label or fix the DB table.

 _Imported from trac ticket [#512](http://trac.gpolab.bbn.com/proto-ch/ticket/512),  created by sedwards on 05-13-2013 at 17:47, last modified: 05-21-2013 at 10:31_
   CCing: nriga@...

**Comment by seledwards** [comment]
The `pa_project` table contains a field `lead_id`. How is this getting updated?

_Trac comment by sedwards (github user: seledwards) on 05-13-2013 at 17:47_

**Comment by ahelsing** [comment]
pa_controller's new modify_project_membership function is missing the update to the pa_project table when the lead ID is changing (see the UPDATE done in change_lead())

_Trac comment by ahelsing on 05-21-2013 at 10:18_
