### ISSUE TITLE
Create an omni page to display slice-specific info

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#52]
From feedback at demo 2:

Replace the "download slice credential" button with a link to an omni page that tells you how to use omni, allows download of slice cred, maybe generation of omni config file

 _Imported from trac ticket [#52](http://trac.gpolab.bbn.com/proto-ch/ticket/52),  created by tmitchel on 05-23-2012 at 15:10, last modified: 06-05-2012 at 14:23_

**Comment by ahelsing** [comment]
Use ticket #85 instead

_Trac comment by ahelsing on 06-05-2012 at 14:23_
