### ISSUE TITLE
Have raw manifest appear in a window

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#520]
Have the raw manifest appear in a separate window/tab/popup.

 _Imported from trac ticket [#520](http://trac.gpolab.bbn.com/proto-ch/ticket/520),  created by sedwards on 05-13-2013 at 18:04, last modified: 06-05-2013 at 15:02_
   CCing: nriga@...

**Comment by ahelsing** [comment]
Fixed for next release

_Trac comment by bujcich on 06-04-2013 at 14:18_

**Comment by ahelsing** [comment]
Done.

_Trac comment by bujcich on 06-05-2013 at 15:02_
