### ISSUE TITLE
Changes to profile should be recorded in a table

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#522]
Changes like requesting project lead or changing name should be recorded in a table.

Was #58.

 _Imported from trac ticket [#522](http://trac.gpolab.bbn.com/proto-ch/ticket/522),  created by sedwards on 05-14-2013 at 16:55, last modified: 03-30-2015 at 16:52_

**Comment by tcmitchell** [comment]
Recording project lead is covered on other tickets. User-driven changes to their own attributes are now recorded in the database. This is complete.
