### ISSUE TITLE
all action buttons on expired slices should be disabled

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#524]
Make sure all buttons are grayed out on the slice page for expired slices.

 _Imported from trac ticket [#524](http://trac.gpolab.bbn.com/proto-ch/ticket/524),  created by sedwards on 05-15-2013 at 08:57, last modified: 04-07-2014 at 13:47_

**Comment by ahelsing** [comment]
I believe this is done / OBE

_Trac comment by ahelsing on 04-07-2014 at 13:47_
