### ISSUE TITLE
Forward non-AM-API calls through proxy

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#53]
This is open to discussion.

Can the proxy am forward the non-AM-API calls on to the proxied aggregate? For instance, if an aggregate offers an extra operation, could the proxy AM recognize that it has received a non-AM-API call and just forward it along?

 _Imported from trac ticket [#53](http://trac.gpolab.bbn.com/proto-ch/ticket/53),  created by tmitchel on 05-23-2012 at 15:13, last modified: 11-21-2013 at 15:52_

**Comment by ahelsing** [comment]
We're not doing the proxy AM

_Trac comment by ahelsing on 11-21-2013 at 15:52_
