### ISSUE TITLE
Edit membership pages should exclude illegal options

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#536]
EG for the current user, do not show 'Remove from Project', if that is not allowed.

 _Imported from trac ticket [#536](http://trac.gpolab.bbn.com/proto-ch/ticket/536),  created by ahelsing on 05-15-2013 at 10:45, last modified: 05-15-2013 at 10:48_

**Comment by seledwards** [comment]
Duplicate of #525

_Trac comment by sedwards (github user: seledwards) on 05-15-2013 at 10:48_
