### ISSUE TITLE
Slice owner is not updated when Slice Lead is changed

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#537]
I changed the lead of a slice.
The owner of the slice did not change.

 _Imported from trac ticket [#537](http://trac.gpolab.bbn.com/proto-ch/ticket/537),  created by ahelsing on 05-15-2013 at 10:49, last modified: 05-21-2013 at 11:43_

**Comment by seledwards** [comment]
Can you say more?  Where are you seeing this?

_Trac comment by sedwards (github user: seledwards) on 05-15-2013 at 10:50_

**Comment by seledwards** [comment]
Is this a duplicate of #512?

_Trac comment by sedwards (github user: seledwards) on 05-15-2013 at 10:57_

**Comment by ahelsing** [comment]
Steps:
Create a project
Add someone to the project
2nd user: Create a slice
1st user: Delete the 2nd user ('Slice Owner' on slice.php) from the slice

Symptom: The Slice owner on slice.php still has the original name, even though they are no longer in the slice.

_Trac comment by ahelsing on 05-15-2013 at 11:10_
