### ISSUE TITLE
tools-admin.php is fake

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#539]
Symptom:
```
[Wed May 15 10:55:40 2013] [error] [client 128.89.81.32] PHP Notice:  Undefined offset: 0 in /var/www/secure/tools-admin.php on line 63, referer: https://illyrica.gpolab.bbn.com/secure/slice.php?slice_id=00e2f656-32c9-420e-b33f-cd838a6ec2e4
```

This appears to be because tools-admin has show_requested_accounts which uses a hard coded account_id.

This whole page may be bogus.

 _Imported from trac ticket [#539](http://trac.gpolab.bbn.com/proto-ch/ticket/539),  created by ahelsing on 05-15-2013 at 11:05, last modified: 06-17-2013 at 11:40_

**Comment by tcmitchell** [comment]
Delete the content on the admin tab and put up "This page intentionally left blank" or similar so operators realize that the page has no content.

_Trac comment by tmitchel (github user: tcmitchell) on 06-17-2013 at 10:43_

**Comment by ahelsing** [comment]
Fixed.

_Trac comment by bujcich on 06-17-2013 at 11:40_
