### ISSUE TITLE
Customize discovery service page

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#54]
See http://www.ncbi.nlm.nih.gov/sites/myncbi/; "Sign in via partner organization"; "If can't find organization, click here." Hint that organization contains "some US colleges and universities".

 _Imported from trac ticket [#54](http://trac.gpolab.bbn.com/proto-ch/ticket/54),  created by tmitchel on 05-23-2012 at 15:18, last modified: 06-08-2012 at 18:18_

**Comment by seledwards** [comment]
Tom says in email: 

The embedded discovery service is the web page that lets you choose an identity provider. The code is in the "shib" git repository at "sp/common/www/eds/".

The original URL is in the README, and I'm pretty sure there's an updated package available. It might be best to start from the latest. Let me know if I can be of assistance.

_Trac comment by sedwards (github user: seledwards) on 06-07-2012 at 14:39_

**Comment by seledwards** [comment]
Tom updated the code in the `shib` repo to the latest.

_Trac comment by sedwards (github user: seledwards) on 06-07-2012 at 14:58_

**Comment by seledwards** [comment]
Did a `get fetch` and `git merge` in my checkout of the `shib` repo.

Copied files to `sergyar`:
```
scp -r ./shib <target host>:~/.
```

These commands in `shib/sp/install-sp.sh` seem to be the only relevant commands to run on `sergyar` so trying them (as root): 
```
for d in common/www/*; do
  echo "Copying ${d} to /var/www"
  /bin/cp -R ${d} /var/www
done

# Restart the Shib Daemon and apache
service shibd restart
service apache2 restart
```

Which does .... well, it looks the same but nothing's broken which seems good.

Assuming this worked for the moment.

_Trac comment by sedwards (github user: seledwards) on 06-08-2012 at 16:01_

**Comment by seledwards** [comment]
Updated `index.html` to say "Please sign in via Partner Organization".

Updated 4 places in `idpselect_config.js` to say something like "Enter your college, university, or other organization's name".

Updated 2 places in `idpselect_config.js` to say "Get Help" and to link to the `login-help.php` page.

Updated `idpselect.css` to use padding (instead of a hardcode height which made some of the text overlap things it shouldn't).

In general we will need to make the style match the rest of the portal pages, but that's for another day.


_Trac comment by sedwards (github user: seledwards) on 06-08-2012 at 17:53_

**Comment by seledwards** [comment]
Sent instruction to gpo-sw-dev@geni.net with how to update.

Closing.

_Trac comment by sedwards (github user: seledwards) on 06-08-2012 at 18:15_

**Comment by seledwards** [comment]
Might as well include the text I put in the email: 

1) In your shib repo on your local machine (you should have this from when you first installed or you can checkout again) do:
  * git fetch
  * git merge origin/master
2) In the directory above shib do (or equivalent):
  * scp -r ./shib sergyar.gpolab.bbn.com:~/.
3) On your VM, run the following commands as root from the ~/shib/sp directory (these are the last bits of the install-sp.sh script in that directory):
  * for d in common/www/*; do   echo "Copying ${d} to /var/www";   /bin/cp -R ${d} /var/www; done
  * service shibd restart
  * service apache2 restart
4) Then log in.  (If you want, you can go in and delete all of your cookies set by your VM to see what it looks like as a new user, etc.)


_Trac comment by sedwards (github user: seledwards) on 06-08-2012 at 18:18_
