### ISSUE TITLE
Merge PA and SA

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#540]
We need to merge SA and PA to assure transactional integrity as we manage membership across SA and PA. Specifically, we want to make sure that if you remove someone from a project they will be removed from the slice, and that if you remove a slice lead, they are replaced with project lead.

Here's Sarah's summary of the semantics:

1. If remove a member from a project then remove member from all slices
2. Project lead is a member of all slices.
3. Project lead can't be removed.
4. If you add a project lead, then add the project lead to all slices.
5. Project lead must have the "create a project" permission.
Otherwise project and slice roles are orthogonal.

On May 14, 2013, at 4:38 PM, Aaron Helsinger <ahelsing@bbn.com> wrote:

- Project Auditor cannot create slices, but can be added to slices at
any role
- Change Project role to auditor does not require touching the SA
- Project Lead is always member of all slices in the project
- Must add lead to new slices
- Only people with create project privilege can be a project lead (PA
restricts this) ****
- Admins or Leads can call change_lead (for projects or slices)
- Remove from project implies remove from all slices
- Project lead cannot be removed from the project
- Change someone to be a project lead - then add that person as a member
of all slices
- But don't have to take someone else out

We also said:
- Starred item needed for tomorrow's release
- Then we will remove the PA.
- Change the PA URL in the SR
- Combine PA functions in sa_controller
- Rework pa_client to call the right functions in the sa_controller
(may be a no op)
- Then we will clean that up
- Remove all references to the PA and pa_client

 _Imported from trac ticket [#540](http://trac.gpolab.bbn.com/proto-ch/ticket/540),  created by mbrinn on 05-15-2013 at 12:49, last modified: 06-27-2013 at 22:52_

**Comment by ahelsing** [comment]
Fixed. The SA/PA merge has been merged into develop.

_Trac comment by bujcich on 06-20-2013 at 16:38_

**Comment by ahelsing** [comment]
Guards don't seem quite right. And we're seeing odd behavior when editing projects.

_Trac comment by ahelsing on 06-27-2013 at 11:49_

**Comment by ahelsing** [comment]
Added a bunch of guards
Restored some missing checks in create_project
Fixed up do-edit-project
did a bunch more testing


_Trac comment by ahelsing on 06-27-2013 at 22:52_
