### ISSUE TITLE
Add a "delete" ssh key button to Profile page

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#542]
On Profile page, there should be a "delete" button to delete an individual ssh key instead of having to click on the edit button first.

 _Imported from trac ticket [#542](http://trac.gpolab.bbn.com/proto-ch/ticket/542),  created by sedwards on 05-15-2013 at 14:48, last modified: 06-10-2013 at 16:27_
   CCing: nriga@...

**Comment by ahelsing** [comment]
Fixed.

_Trac comment by bujcich on 06-10-2013 at 16:27_
