### ISSUE TITLE
Allow the user to regenerate their cert

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#545]
The users should be able to re-generate the cert they can download. 

This is important for two reason:
  1) If they choose the wrong option the first time they created the cert, they should be able to fix that
   2) in case they want to change their cert. 

I am bringing this up again, since it came up recently when Regina wanted to change her cert because it was "compromised". She shared her cert with me to help her debug a GENI desktop problem and so she wants to create a new one. 

 _Imported from trac ticket [#545](http://trac.gpolab.bbn.com/proto-ch/ticket/545),  created by nriga on 05-16-2013 at 18:12, last modified: 05-15-2014 at 08:57_

**Comment by tcmitchell** [comment]
We'll need a way to regenerate certificates as they expire. The first user certificates will expire in October, I think.

Some comments on the use cases listed in the description:
 1. There's really no such thing as a wrong option the first time people create the certificate. All three methods generate equivalent certificates that can be used in exactly the same way. The methods differ only in where the private key lives.
 2. I'm not wild about letting users regenerate certificates whenever they want. I'd prefer that to be controlled in some way, like requesting a new certificate. It's fine to share certificates, but users should not be sharing their private key. A certificate is by definition a public document and shareable. Sharing the certificate doesn't compromise it in any way.


_Trac comment by tmitchel (github user: tcmitchell) on 05-16-2013 at 20:49_

**Comment by innnkkki** [comment]
Replying to [tmitchel](comment:1):
> We'll need a way to regenerate certificates as they expire. The first user certificates will expire in October, I think.
> 
> Some comments on the use cases listed in the description:
>  1. There's really no such thing as a wrong option the first time people create the certificate. All three methods generate equivalent certificates that can be used in exactly the same way. The methods differ only in where the private key lives.

On a high level you are right, but for naive users if they choose the second option, their life gets harder because now they have to keep track of their private key and using other tools gets tricky. So I can see people wanting to change their mind. This might also go the other way. A user chooses the first option, but later as he/she learns more about security they want to use the second option. 

>  2. I'm not wild about letting users regenerate certificates whenever they want. I'd prefer that to be controlled in some way, like requesting a new certificate. It's fine to share certificates, but users should not be sharing their private key. A certificate is by definition a public document and shareable. Sharing the certificate doesn't compromise it in any way.

You are right that users should not share their private keys, but the pem file comes with the private key. I am not saying this is wrong, I am just saying that this happened and whether this was the right or wrong way to debug, there should be a way to backtrack this when it happens. In general, I think I don't like one-time things that can not be changed later. The certificate is a user artifact and I think they should be able to manipulate it. 

_Trac comment by nriga (github user: innnkkki) on 05-17-2013 at 16:42_

**Comment by tcmitchell** [comment]
Resolved by #241.
See also #471, #232.

_Trac comment by tmitchel (github user: tcmitchell) on 05-15-2014 at 08:57_
