### ISSUE TITLE
Limit max-expiration in preparation for lockdown mode

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#548]
We need a 'pre-lockdown' mode for the portal/CH in which slices are not allowed to have expirations that go past a certain date (either at creation time or at renewal time).

 So that when we get to lockdown mode we only have slices whose expiration dates are soon and known.

 _Imported from trac ticket [#548](http://trac.gpolab.bbn.com/proto-ch/ticket/548),  created by mbrinn on 05-20-2013 at 08:59, last modified: 05-29-2013 at 11:46_

**Comment by MarshallBrinn** [comment]
I think fixing this will help fix Sarah's request as well about the SA providing messages explaining about the details of lock-down related falures.  The SA somehow needs to know about lockdown mode (which I'd been trying to avoid). So once we have that getting the SA to return a better explanatory message will be a piece of cake. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-20-2013 at 09:12_

**Comment by seledwards** [comment]
It would be nice to have this 3 weeks before June 17 which is May 27 (which is Memorial Day).

_Trac comment by sedwards (github user: seledwards) on 05-21-2013 at 16:51_

**Comment by MarshallBrinn** [comment]
This has been implemented and tested in the tkt547-lockdown branch.

Here's how it works. We have a mode called 'sundown mode' which has a max expiration time on slices.

Renew_slice and create_slice are bounded by this time when in sundown mode. rewew will give an error telling you the bound and telling you to go to the new CH. create will just compute the min of your requested time and the set time.

There are these scripts to manage this mode

enable/disable_sundown.sh : set up or clear sundown mode (enable takes a YYYY-mm-dd hh::mm::ss argument)
geni-manage-maintenance now takes --set-sundown message time and --clear-sundown arguments

We need to test this and then can move to panther and enable this mode.



_Trac comment by mbrinn (github user: MarshallBrinn) on 05-22-2013 at 13:35_
