### ISSUE TITLE
Add S/MIME encryption/decryption

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#55]
See functions in browser:lib/php/smime.php

 _Imported from trac ticket [#55](http://trac.gpolab.bbn.com/proto-ch/ticket/55),  created by tmitchel on 05-23-2012 at 15:25, last modified: 08-29-2013 at 12:36_

**Comment by ahelsing** [comment]
CH rewrite will make this OBE.

_Trac comment by ahelsing on 08-01-2013 at 15:31_
