### ISSUE TITLE
Update certificate creation instructions to match omni-configure

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#552]
The instructions for creating a CSR with a new key should be updated so that the generated key file matches the default key name that omni-configure.py will use. Get the new file name from Niky.

 _Imported from trac ticket [#552](http://trac.gpolab.bbn.com/proto-ch/ticket/552),  created by tmitchel on 05-21-2013 at 17:11, last modified: 05-28-2013 at 15:15_
   CCing: nriga@...

**Comment by seledwards** [comment]
The new file name is: `~/.ssl/geni_ssl_portal.key`

_Trac comment by sedwards (github user: seledwards) on 05-23-2013 at 17:34_

**Comment by seledwards** [comment]
Code is edited and on a branch.

_Trac comment by sedwards (github user: seledwards) on 05-24-2013 at 17:12_

**Comment by seledwards** [comment]
Merged onto develop (as part of merging `tkt567-clarify-uer-cert`). Closing.

_Trac comment by sedwards (github user: seledwards) on 05-28-2013 at 15:15_
