### ISSUE TITLE
Separate cert section

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#553]
The generate cert and download cert options might be better to be under 
a section titled "Manage my GENI cert" or something so that it is not tied to omni. 

 _Imported from trac ticket [#553](http://trac.gpolab.bbn.com/proto-ch/ticket/553),  created by nriga on 05-22-2013 at 13:49, last modified: 04-08-2014 at 09:49_

**Comment by ahelsing** [comment]
That section is now called 'SSL'.

_Trac comment by ahelsing on 04-08-2014 at 09:49_
