### ISSUE TITLE
List of project in download omni bundle should only include active projects

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#554]
Currently the drop down menu with projects when trying to download the omni config 
bundle has all the projects even the ones that are not active. 

It should probably have only the list of currently active projects. 

I am not sure which projects should be included in the omni-config that comes with the bundle though. 

 _Imported from trac ticket [#554](http://trac.gpolab.bbn.com/proto-ch/ticket/554),  created by nriga on 05-22-2013 at 13:52, last modified: 06-07-2013 at 12:25_

**Comment by ahelsing** [comment]
In portal/www/portal/omni-bundle.php
lookup_project_details returns a struct that includes the EXPIRED column. We could use that to adjust the num_projects field, and prune the list of projects we show in the loop around line 112


Then in lib/php/am_client.php around line 144, we need similar logic.

_Trac comment by ahelsing on 05-24-2013 at 15:00_

**Comment by ahelsing** [comment]
Fixed. This is part of the functionality provided in http://trac.gpolab.bbn.com/proto-ch/ticket/585

_Trac comment by bujcich on 06-07-2013 at 12:23_
