### ISSUE TITLE
Add definition of roles to portal interface

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#558]
Make sure the definition of roles is clear from the portal interface for both project lead/admin/member/auditor and slice lead/admin/member/auditor.

 _Imported from trac ticket [#558](http://trac.gpolab.bbn.com/proto-ch/ticket/558),  created by sedwards on 05-23-2013 at 11:19, last modified: 07-22-2014 at 13:32_
   CCing: nriga@...

**Comment by ahelsing** [comment]
I suggested this at the end of the gpo-tech meeting this morning, and Marshall didn't like it, but I wanted to suggest it one more time, and a little more clearly: I think it'd be valuable to use an adjective to differentiate these roles in the UI, i.e. have them show up in lists and tables and such as Project Lead, Project Admin, Project Member, and Project Auditor, and Slice Lead, Slice Admin, Slice Member, and Slice Auditor.

I do think it'd make it more visually obvious who's what, and reduce incidents of "oops, I meant to make this person an admin for my slice, and accidentally made them an admin for my project, because I was multitasking and didn't notice which page I was on" or whatever. If y'all don't like it, or if it's a pain to do, I don't think it's essential.

_Trac comment by jbs on 05-23-2013 at 11:23_

**Comment by seledwards** [comment]
Just noting that Hassam asked a question about this asking for documentation about what the roles mean and what it means about logins and key placement.


_Trac comment by sedwards (github user: seledwards) on 06-13-2013 at 18:12_

**Comment by ahelsing** [comment]
Role definitions could be put on the glossary. Theoretically they could be put on the pages where we change member roles, but I think that would make the pages too busy. I think those pages should instead have links to the glossary.

Here is some proposed text.

Project Lead: The person ultimately responsible for all resource reservations in the project. Project Leads and Admins are the only ones who can change the membership of a project and the roles of people in the project. There is only a single Lead in a project, but can be multiple Admins. The lead is like the professor for the class, where the admins are like TAs. The Lead can also create slices, as with project members. The lead of the project is automatically added to all slices created in the project.

Project Admin: Project Admins, along  with the Project Lead can change the membership of a project and the roles of people in the project. There is only a single Lead in a project, but can be multiple Admins. The lead is like the professor for the class, where the admins are like TAs. Admins can also create slices, as with project members.

Project Member: Members of a project can create slices (the creator of the slice becomes the Slice Lead).

Project Auditor: An auditor can be added to a slice, but cannot create new slices.

Note that all members of a project can see the other members of the project.

Slice Lead: The creator of the slice becomes the Slice Lead.

_Trac comment by ahelsing on 06-25-2013 at 20:38_

**Comment by ahelsing** [comment]
Continuing to work on text for this:

A Lead is like the professor of a class, where Admins are like teaching assistants. There is a single Lead of a Project or Slice, but can be many Admins. Admins and Leads generally have the same permissions.

Members have read-only permissions on a Project, but they can create slices. Members of a slice can reserve or delete resources, but cannot add other members to the slice.

Auditors have read only permissions on Projects and Slices - they can see the other members of the project or slice, list the resources reserved in the slice, but not reserve any resources themselves.

Under Project Lead, add: Current GENI Policy ... (see ticket #630)

Slice Lead The person responsible for all resource reservations in the slice. Leads and Admins can change slice membership, others cannot. There is a single lead of a slice. Leads and Admins have full control over the slice.

Slice Admin: Slice Admins can change slice membership, like a slice lead. Leads and Admins have full control over the slice.

Slice Member: A slice member can renew the slice, and reserve or delete resources. Slice members cannot change slice membership.

Slice Auditor: A slice auditor can see who is in the slice and list the resources reserved by the slice only.



_Trac comment by ahelsing on 06-26-2013 at 11:34_

**Comment by ahelsing** [comment]
Sarah & Niky: How important is this? Can you recommend some definitions / explanations, based on the text in the earlier comments?

_Trac comment by ahelsing on 08-01-2013 at 15:01_

**Comment by ahelsing** [comment]
The glossary is now a geni wiki page. Should these definitions go there, or on a portal internal page?

_Trac comment by ahelsing on 08-29-2013 at 11:51_

**Comment by seledwards** [comment]
I'll discuss this with Niky.

_Trac comment by sedwards (github user: seledwards) on 08-29-2013 at 11:58_

**Comment by seledwards** [comment]
We'd like be some sort of dialog/pop-up on the following pages:
 * Slice Member Management
 * Project Member Management
 * Bulk Upload

This could perhaps have a table and a link to the glossary.

Niky and I will come up with some text for this as well as text for the glossary.

_Trac comment by sedwards (github user: seledwards) on 08-29-2013 at 12:26_

**Comment by seledwards** [comment]
We did finally incorporate new words into the glossary:
 For Project roles: http://groups.geni.net/geni/wiki/GENIGlossary#Project
 For Slice roles: http://groups.geni.net/geni/wiki/GENIGlossary#Slice

_Trac comment by sedwards (github user: seledwards) on 05-23-2014 at 16:06_

**Comment by ahelsing** [comment]
Still waiting on text that you want and exactly where you want it in the portal.

_Trac comment by ahelsing on 07-15-2014 at 14:35_

**Comment by seledwards** [comment]
See comment:15 for wording.  

The text (or a link to the glossary) should go on the edit slice member page and the edit project member page.


_Trac comment by sedwards (github user: seledwards) on 07-15-2014 at 17:40_

**Comment by ahelsing** [comment]
Added links to the glossary on the 2 edit pages, bulk upload, and handling project join requests.

_Trac comment by ahelsing on 07-22-2014 at 13:32_
