### ISSUE TITLE
Add the ability to load Project Admins/Members onto slices by default

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#559]
In the following, it is assumed that the project lead will continue to always be added to a slice by default.

Make it possible to configure a project so that admins and/or members are automatically added to a slice when it is created.
	- Adding admins but not members supports the classroom use case (assuming TAs are admins and all of the students shouldn't be able to see each others work)
	- Adding all members supports the research group use case where everyone is involved in everything in the project  
	- We've talked about allowing admins to be added for awhile.  The case of adding members was suggested by one of the guys from NICTA (who's name I don't remember).
	- Niky thinks that we might want more granular control so that we can add some admins/members.  She's worried about the GEC tutorial use case where we have 100+ members and 10+ admins.

There are three options for doing this:
 1. _Super simple'' Always add all Admins to slices by default.
 1. ''Low granulariy'' Allow the lead to configure the project so that by default all slices in that project: have/don't have all of the project Admins as slice member; have/don't have all of the project Members as slice member. (This would probably be a toggle for each of the two cases.)
 2. ''High granularity'' Same as above except the project lead has the ability to determine which individuals are added to slices by default. (This might have some radio buttons so that each person can be set individually to be added to the project or not.)

The ''Super simple'' or the ''Low granularity'' option would be really useful. The ''High granularity_ option is nice to have.  

 _Imported from trac ticket [#559](http://trac.gpolab.bbn.com/proto-ch/ticket/559),  created by sedwards on 05-23-2013 at 11:22, last modified: 09-11-2013 at 12:02_
   CCing: nriga@..., vthomas@...

**Comment by ahelsing** [comment]
What's the relationship between Project Leads and Admins, and Slice Leads and Admins? If you create a slice, the is the Project Lead automatically a Slice Lead for that slice? Or a Slice Admin? What about Project Admins, are they automatically Slice Admins?

If you remove your Project Lead from your Slice, do their keys still get uploaded? (I'd assume not.)

_Trac comment by jbs on 05-23-2013 at 11:26_

**Comment by seledwards** [comment]
Project and Slice roles are largely orthogonal.

The Project Lead is added to the slice by default.  (But can be manually removed.)

I believe the person who created the slice is the Slice Lead.

Only people who belong in a Slice at the time a sliver is created will have their keys loaded.

_Trac comment by sedwards (github user: seledwards) on 05-23-2013 at 11:30_

**Comment by seledwards** [comment]
Niky mentioned this today.  She thinks we should do something here before the start of the school year.

We discussed it and the simplest thing to do is to have a toggle that allows the Project Lead to set whether Project Admins are automatically added to slices by default.  We think that teachers in a class will want this, but that tutorial instructors may not.

_Trac comment by sedwards (github user: seledwards) on 06-28-2013 at 08:31_

**Comment by ahelsing** [comment]
Niky/Sarah: Please tell us exactly what you want here.

_Trac comment by ahelsing on 08-01-2013 at 15:02_

**Comment by seledwards** [comment]
Aaron, I updated the description.

_Trac comment by sedwards (github user: seledwards) on 08-08-2013 at 21:41_

**Comment by ahelsing** [comment]
Doing option 1, making project admins be admins of all newly created slices.

_Trac comment by ahelsing on 09-11-2013 at 11:45_
