### ISSUE TITLE
Tie in GMOC pages

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#56]
When ready, tie in a few GMOC links or embeds:
 * GENI messages
 * AM status
 * Slice status

Relies on #181.

Also, add links to GMOC pages out outages and calendar, etc?

 _Imported from trac ticket [#56](http://trac.gpolab.bbn.com/proto-ch/ticket/56),  created by tmitchel on 05-23-2012 at 15:30, last modified: 04-07-2014 at 15:16_

**Comment by seledwards** [comment]
To do this properly relies on #181 which is that the CH SA should reporting monitoring data to GMOC.

_Trac comment by sedwards (github user: seledwards) on 07-19-2012 at 10:21_

**Comment by tcmitchell** [comment]
This creates a bit of a chicken-and-egg problem. The CH SA likely won't have anything to report to GMOC until very close to GEC 15 at the earliest, and then it will be a very limited set of data involving only the bravest of early adopters.

Is it possible to add some GMOC linkage without fulfilling issue #181? Even if that's a bit "improper"?

_Trac comment by tmitchel (github user: tcmitchell) on 07-19-2012 at 11:28_

**Comment by seledwards** [comment]
Maybe.

Just a question, is there any reason not to report unexciting/boring information?

We'd basically be reporting a list of slices and some basic info like operating org.

I think we can:
 1) get that info out of the CH now
 2) submit that info to GMOC now without harm

I'm proposing waiting until Sept to do it because GMOC may be updating their client side scripts and we should wait for those.

Is there some other consideration I'm missing?

_Trac comment by sedwards (github user: seledwards) on 07-19-2012 at 11:45_

**Comment by MarshallBrinn** [comment]
We have also talked about tying in the GMOC Map interface onto the portal page (replacing the static image on the current portal).

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 07:51_

**Comment by seledwards** [comment]
Not getting password-less login to GMOC UI before GEC15.  Moving away from GEC15 milestone.

_Trac comment by sedwards (github user: seledwards) on 10-18-2012 at 10:22_

**Comment by seledwards** [comment]
Add links to GMOC pages out outages and calendar, etc

_Trac comment by sedwards (github user: seledwards) on 10-25-2012 at 12:29_

**Comment by seledwards** [comment]
Some links: http://gmoc.grnoc.iu.edu/gmoc/index/support.html

_Trac comment by sedwards (github user: seledwards) on 10-25-2012 at 12:41_

**Comment by ahelsing** [comment]
Is this the right thing to do any more? Or are there newer monitoring pages that we should be tying in instead?

_Trac comment by ahelsing on 04-07-2014 at 10:45_

**Comment by ahelsing** [comment]
Close this as OBE, and wait for new monitoring.

_Trac comment by ahelsing on 04-07-2014 at 15:16_
