### ISSUE TITLE
Return a useful error for Omni when creating a slice for an expired project

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#562]
Currently if I try to create a slice for a project that has expired through Omni i get:

```
INFO:omni: ============================================================
geni@GENI-VM:~/gcf/src$ ./omni.py createslice testexp1 -r scaleTestSE
INFO:omni:Loading config file /home/geni/.gcf/omni_config
INFO:omni:Using control framework portal
ERROR:omni.pgch:Failed to create new PG slice urn:publicid:IDN+panther:scaleTestSE+slice+testexp1: Project scaleTestSE has expired. (code 4)
ERROR:omni:Create Slice Failed for slice name testexp1.
WARNING:omni:   Try re-running with --debug for more information.
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed createslice:

  Options as run:
		framework: portal
		project: scaleTestSE

  Args: createslice testexp1

  Result Summary: Create Slice Failed for slice name testexp1.
 
INFO:omni: ============================================================
```
Which can't help me identify what the problem is. Return something more useful

 _Imported from trac ticket [#562](http://trac.gpolab.bbn.com/proto-ch/ticket/562),  created by nriga on 05-23-2013 at 15:53, last modified: 06-06-2013 at 12:13_

**Comment by ahelsing** [comment]
This doesn't look like a 'project is expired' error.

It looks like your omni_config has a broken 'authority' field.

Your slice URN is
urn:publicid:IDN+:scaleTestSE+slice+testexp

Note there is no 'sergyar' before ':scaleTestSE'

_Trac comment by ahelsing on 05-23-2013 at 16:16_

**Comment by innnkkki** [comment]
Indeed after I fixed my omni_config the new error I get:
```
INFO:omni:Using control framework portal
ERROR:omni.pgch:Failed to create new PG slice urn:publicid:IDN+panther:scaleTestSE+slice+testexp1: Project scaleTestSE has expired. (code 4)
ERROR:omni:Create Slice Failed for slice name testexp1.

```
We should probably repeat it in the summary, like we when createsliver fails. 

_Trac comment by nriga (github user: innnkkki) on 05-23-2013 at 16:29_

**Comment by ahelsing** [comment]
This is an omni issue. Opened http://trac.gpolab.bbn.com/gcf/ticket/294

_Trac comment by ahelsing on 06-06-2013 at 12:13_
