### ISSUE TITLE
portal log_event calls should use $user

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#568]
A number of portal pages call log_event using the portal's keys as the signer. Shouldn't we use the user's keys?

 _Imported from trac ticket [#568](http://trac.gpolab.bbn.com/proto-ch/ticket/568),  created by ahelsing on 05-28-2013 at 22:37, last modified: 01-08-2014 at 11:39_

**Comment by tcmitchell** [comment]
This probably changes with speaks for.

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 11:53_

**Comment by ahelsing** [comment]
In fact, all calls to the log service should be using $user.
And similarly, do not pass $slice['owner_id'] as the user who is doing the action. Instead, the _client functions should get the user ID from out of the $signer and not take that argument.

However, currently the log service guards will break of the $signer is not the Portal. So fix that first.


_Trac comment by ahelsing on 12-16-2013 at 16:45_

**Comment by ahelsing** [comment]
see the branch logservice-as-user for code that starts to do this. Note this currently fails since the log service guard doesn't like it.

Also note that not all the needed calls have been updated on that branch - basically every call that uses Portal::getInstance() is suspect. Only a few calls at the beginning getting the user should be using Portal::getInstance()


_Trac comment by ahelsing on 12-17-2013 at 20:54_

**Comment by MarshallBrinn** [comment]
I did a fair amount of work on this and it is trickier that it appears.

Take the case of a project request. The code (rightly) wants to log an event with attributes for the requestor and the project. But the requestor isn't a member of the project so the current guards don't' allow the event to be created. If we were to make an exception (you're allowed to write a logging message if you have a pending request for a project) then we open a hole for anyone who made a request to log anything about a project to which they don't belong.

Some of the other cases of log_event (AM actions e.g.) are probably safer and more straight forward. Perhaps we need to go through all the cases (there are 10 or 11 in all) and decide which can be switched over to $user and which need to remain with Portal::getInstance().

Leaving this open until we review this at the next S/W group meeting.

- Marshall


_Trac comment by mbrinn (github user: MarshallBrinn) on 12-20-2013 at 12:36_

**Comment by ahelsing** [comment]
Ignoring cases where the KM or portal is looking up the user (kmactivate.php and user.php and do-register.php) I still see these cases:

```
./lib/php/am_client.php:55:    $result = log_event($log_url, Portal::getInstance(), $msg, $attributes, $user_id);
./portal/www/portal/renewsliver.php:207:  log_event($log_url, Portal::getInstance(),
./portal/www/portal/cancel-join-project.php:194:      log_event($log_url, Portal::getInstance(),
./portal/www/portal/cancel-join-project.php:210:    log_event($log_url, Portal::getInstance(),
./portal/www/portal/createsliver.php:127:log_event($log_url, Portal::getInstance(),
./portal/www/portal/deletesliver.php:169:  log_event($log_url, Portal::getInstance(),
./portal/www/portal/do-modify.php:207:  log_event($log_url, Portal::getInstance(), $msg, $member_attributes, $user->account_id);
./portal/www/portal/do-modify.php:212:  log_event($log_url, Portal::getInstance(), $msg, $member_attributes, $user->account_id);
./portal/www/portal/invite-to-project.php:150:  log_event($log_url, Portal::getInstance(), $msg, $attributes, $user->account_id);
./portal/www/portal/join-this-project.php:144:      error_log("Found no Log Service in SR!'", Portal::getInstance());
./portal/www/portal/join-this-project.php:150:    log_event($log_url, Portal::getInstance(),
```

Of those:
 * am_client, renewsliver, createsliver, deletesliver are slice operations where the user is a member of the slice. These should be changed.
 * cancel-join-project and join-this-project have the project as a context, but the user has no privilege for that project. So either you leave out the project context, or the portal has to be the caller.
 * do-modify is recording the user asking to change attributes - the only context is the user themselves. So I think this should work with the user as the caller
 * invite-to-project has a project as a context, but the caller is a member of the project, so this should work with the user being the caller

I suggest we leave cancel-join-project and join-this-project as is, but change the others. Comments?


_Trac comment by ahelsing on 01-08-2014 at 09:05_

**Comment by MarshallBrinn** [comment]
I agree:   
 * the AM calls should be changed
 * do-modify and invite-to-project should work with $user
 * The cancel-join-project and join-this-project should be portal

Sounds like the right plan.

- Marshall


_Trac comment by mbrinn (github user: MarshallBrinn) on 01-08-2014 at 09:07_
