### ISSUE TITLE
Update some links from portal-help to help

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#572]
Some links should point to help@geni.net and not portal-help. Particularly after we cut over [SignMeUp](http://groups.geni.net/geni/wiki/SignMeUp) to point new users to the portal and not to pgeni.
 - IdP select page where it says 'Need help'
 - idp/request.html
 - login-help.php
 - SignMeUpPortal
 - help.php - here we should add a link to help@geni.net and distinguish between them

 _Imported from trac ticket [#572](http://trac.gpolab.bbn.com/proto-ch/ticket/572),  created by ahelsing on 05-30-2013 at 11:43, last modified: 09-11-2013 at 15:42_
   CCing: nriga@...

**Comment by seledwards** [comment]
Updated the description to clarify the purpose of this ticket.

_Trac comment by sedwards (github user: seledwards) on 06-07-2013 at 13:17_

**Comment by seledwards** [comment]
The SignMeUp switchover is next week.  Should we do this soon?

_Trac comment by sedwards (github user: seledwards) on 06-14-2013 at 18:27_

**Comment by ahelsing** [comment]
yes, we should. Who has a handle on this and/or time?

_Trac comment by ahelsing on 06-14-2013 at 20:44_

**Comment by ahelsing** [comment]
Done.

Note
 - Shib module changed, in order to change the IdP select page
 - request.html change made, but must also be made in the new account request area


_Trac comment by ahelsing on 09-11-2013 at 11:11_

**Comment by tcmitchell** [comment]
change made in new account request area.

_Trac comment by tmitchel (github user: tcmitchell) on 09-11-2013 at 15:23_
