### ISSUE TITLE
Order of slices in portal

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#574]
It will be useful if slices that I am the lead appear first so that I can easily find them. 

This is especially important for the Lead of a project that is a member of all the slices on all his/her projects and it gets hard to locate slices. 

 _Imported from trac ticket [#574](http://trac.gpolab.bbn.com/proto-ch/ticket/574),  created by nriga on 05-30-2013 at 18:44, last modified: 09-09-2013 at 13:49_

**Comment by ahelsing** [comment]
see ticket #710

_Trac comment by ahelsing on 09-09-2013 at 13:49_
