### ISSUE TITLE
Errors in ch_error.log about /var/www/cainfo.html

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#578]
The new ch.geni.net ch_error.log shows:
`File does not exist: /var/www/cainfo.html`
This seems to come from PG AMs

This is because our new authority certs include this:
```
           Authority Information Access: 
                2.25.305821105408246119474742976030998643995 - URI:https://ch.geni.net/cainfo.html
```

Maybe putting an empty file at that location would quiet those messages?

 _Imported from trac ticket [#578](http://trac.gpolab.bbn.com/proto-ch/ticket/578),  created by ahelsing on 05-31-2013 at 19:54, last modified: 06-04-2013 at 11:15_

**Comment by tcmitchell** [comment]
Added.

_Trac comment by tmitchel (github user: tcmitchell) on 06-04-2013 at 11:15_
