### ISSUE TITLE
Construct join/invite pages for slices changes

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#58]
Mirror the project request pages for slices. Also for the initial membership request to use the request infrastructure.

 _Imported from trac ticket [#58](http://trac.gpolab.bbn.com/proto-ch/ticket/58),  created by ahelsing on 05-29-2012 at 14:42, last modified: 05-14-2013 at 16:56_

**Comment by ahelsing** [comment]
If we decide that the GEC demo needs to show the admin's perspective, then we need the request infrastructure for profile changes/account requests


_Trac comment by ahelsing on 05-29-2012 at 15:06_

**Comment by ahelsing** [comment]
For partners in a tutorial, we might need this.

Sarah notes that within a project there might no be privacy expectations, so a slice owner can see other project members and add them to the new slice. So we don't need 'invite'. We still need the request-to-join.

_Trac comment by ahelsing on 01-03-2013 at 14:13_

**Comment by seledwards** [comment]
Marshall is almost done with this.

_Trac comment by sedwards (github user: seledwards) on 05-10-2013 at 15:44_

**Comment by seledwards** [comment]
Sorry.  Marshall is doing the slice portion of this. 

_Trac comment by sedwards (github user: seledwards) on 05-13-2013 at 10:36_

**Comment by seledwards** [comment]
Moved Profile portion of this ticket to #522.  Removing from this ticket.

The slice portion is done.  Closing.

_Trac comment by sedwards (github user: seledwards) on 05-14-2013 at 16:56_
