### ISSUE TITLE
notify omni users to re-download after move

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#580]
After the portal moves to portal.geni.net, users who had downloaded an outside cert will have to do something.

We could put up a message on their home page reminding them of what they need to do

 _Imported from trac ticket [#580](http://trac.gpolab.bbn.com/proto-ch/ticket/580),  created by ahelsing on 06-03-2013 at 15:47, last modified: 06-20-2013 at 14:33_
   CCing: nriga@...

**Comment by ahelsing** [comment]
After the move, people who had an outside cert get a new attribute `panther_outside_cert` in `ma_member_attribute`. This attribute has value `no key` or `had key` as appropriate.

We could use this to decide who gets what message on the home page.
Then the page that lets you download our omni bundle or cert needs to set some other attribute to turn the message off.

Text should be something like:
```
Welcome to the new portal.geni.net
As part of the transition, your Omni configuration and SSL certificate
must change. To continue to use Omni you must
 - Upgrade to Omni 2.3 <link>
 - Update your Omni configuration <link to profile page>
 - Download your new certificate / Create a new certicate
```

Note that if we do this post transfer, the code also needs to check who now has an outside cert and remove those people from the set who get a message on the home page.


_Trac comment by ahelsing on 06-03-2013 at 15:50_

**Comment by seledwards** [comment]
I think we've decided not to do this. Closing as WONTFIX.

_Trac comment by sedwards (github user: seledwards) on 06-20-2013 at 14:33_
