### ISSUE TITLE
Stitching Allocate Resources Interface

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#581]
We need an interface to augment, replace or parallel the current allocate resources interface to support stitching. We've had some design discussions on how this might work and we need to start prototyping it after the transition to nye.

 _Imported from trac ticket [#581](http://trac.gpolab.bbn.com/proto-ch/ticket/581),  created by mbrinn on 06-03-2013 at 15:53, last modified: 07-29-2014 at 12:23_

**Comment by ahelsing** [comment]
This ticket fixes:
 * #228 (search RSpecs)
 * #412 (view RSpec button on 'Add Resources' page)
 * #467 (organize the list of RSpecs)

_Trac comment by bujcich on 07-29-2014 at 12:23_
