### ISSUE TITLE
Add project info to GEMINI data

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#585]
GEMINI would like a list of the experimenter's projects to be added to the data sent. Send an array of project names in the data blob.

 _Imported from trac ticket [#585](http://trac.gpolab.bbn.com/proto-ch/ticket/585),  created by tmitchel on 06-04-2013 at 12:09, last modified: 06-10-2013 at 15:39_

**Comment by tcmitchell** [comment]
Some tips:
 * Add this to [portal/www/portal/gemini.php](../tree/master/portal/www/portal/gemini.php)
 * Enable the gemini button for yourself (add an attribute in `ma_member_attribute` table)
 * Use key `project_names`, value is an array of strings.
 * Use `get_projects_for_member()`, and then probably `lookup_project_details()`
 * Do not include expired projects
 * See [portal/www/portal/omni-bundle.php](../tree/master/portal/www/portal/omni-bundle.php)


_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2013 at 14:16_

**Comment by ahelsing** [comment]
Fixed. Public/private SSH keys info to be sent to GEMINI should be opened up as a new ticket.

_Trac comment by bujcich on 06-10-2013 at 15:39_
