### ISSUE TITLE
OBE: Cache reserved resources

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#59]
Somewhere in the clearinghouse should be caching what resources are reserved in a slice. This would be used to summarize things on the slice page, plus for Resource Allocation Policy.
Be careful to keep the last update recent.
(Requests done through the portal or the proxy will be up to date anyhow.)

 _Imported from trac ticket [#59](http://trac.gpolab.bbn.com/proto-ch/ticket/59),  created by ahelsing on 05-29-2012 at 14:57, last modified: 12-05-2013 at 13:23_

**Comment by ahelsing** [comment]
note the new CHAPI has an api for a tool to report this. The portal should use it.

_Trac comment by ahelsing on 10-09-2013 at 13:00_

**Comment by MarshallBrinn** [comment]
The new CH will handle this.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-21-2013 at 15:19_
