### ISSUE TITLE
ch.geni.net apache config should block portal access

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#590]
If you go to https://ch.geni.net/secure/home.php you get a Server Error.
Instead, it should behave like going to nye.gpolab

Symptom was:

From the nye ch_error.log:
```
[Wed Jun 05 13:33:46 2013] [error] [client 198.110.3.189] PHP Warning:  require_once(util.php): failed to open stream: No such file or directory in /var/www/secure/db-util.php on line 26, referer: https://ch.geni.net/
[Wed Jun 05 13:33:46 2013] [error] [client 198.110.3.189] PHP Fatal error:  require_once(): Failed opening required 'util.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/secure/db-util.php on line 26, referer: https://ch.geni.net/
[Wed Jun 05 13:33:49 2013] [error] [client 198.110.3.189] PHP Warning:  require_once(util.php): failed to open stream: No such file or directory in /var/www/secure/db-util.php on line 26, referer: https://ch.geni.net/
[Wed Jun 05 13:33:49 2013] [error] [client 198.110.3.189] PHP Fatal error:  require_once(): Failed opening required 'util.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/secure/db-util.php on line 26, referer: https://ch.geni.net/
```

 _Imported from trac ticket [#590](http://trac.gpolab.bbn.com/proto-ch/ticket/590),  created by ahelsing on 06-05-2013 at 13:52, last modified: 06-20-2013 at 14:31_

**Comment by ahelsing** [comment]
FYI:
```
nye:/usr/share/geni-ch/lib/php/util.php
```
is present.  Maybe something isn't looking in the correct path?

_Trac comment by chaos on 06-05-2013 at 14:01_

**Comment by ahelsing** [comment]
Files are in /usr/share/geni-ch/lib/php
Is that where they're supposed to go instead?
But db-util.php is only in /var/www/secure. And the include path does not include /usr/share/geni-ch/lib/php. Maybe that is what is missing?

_Trac comment by ahelsing on 06-05-2013 at 14:06_

**Comment by ahelsing** [comment]
Chaos found it - if you try to access the portal at ch.geni.net you get this symptom

_Trac comment by ahelsing on 06-05-2013 at 14:10_

**Comment by ahelsing** [comment]
Per Aaron, we can roll this out during next week's maintenance, and don't need a hotfix or anything for it.

_Trac comment by chaos on 06-05-2013 at 14:22_

**Comment by seledwards** [comment]
Done as part of the 1.8 release. Closing.

_Trac comment by sedwards (github user: seledwards) on 06-20-2013 at 14:31_
