### ISSUE TITLE
"Member ... is already a member of project ..." error seen erroneously

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#591]
On portal.geni.net just now, i did the following:
 * As amcanary (brand new user), agree to the portal policies, but don't do anything else.
 * As chaos (admin on the project gpoamcanary):
   * Browse to project gpoamcanary
   * Click "Bulk Add New Members"
   * Browse for a CSV file, which contains:
```
$ cat gpoamcanary_csv 
amcanary@gpolab.bbn.com, Aggregate Manager Test User
```
   * Click "Upload"
   * Verify that the table correctly suggests adding candidate "Aggregate Manager Test User" with privilege "Member"
   * Click "Invite Selected Members"

When i did that:
 1. amcanary was correctly added to project gpoamcanary with privilege Member (good)
 2. As chaos, i saw the error screen:
```
Member ffea4a79-4dd6-477f-8d88-5ca91ee10175 is already a member of project 95548578-6918-4ebd-be6e-5a4432c264a1
```
 (not good)

 _Imported from trac ticket [#591](http://trac.gpolab.bbn.com/proto-ch/ticket/591),  created by chaos on 06-05-2013 at 13:55, last modified: 07-16-2014 at 10:24_

**Comment by seledwards** [comment]
I'm trying to reproduce this.  I verified that I was able to do a bulk upload and add an existing user (Aaron) and two different invited users (who's email didn't have accounts). That was fine.

Trying to add amcanary to a project now using Chaos' csv.

_Trac comment by sedwards (github user: seledwards) on 06-05-2013 at 15:38_

**Comment by seledwards** [comment]
I was able to add amcanary to the project without incident.

_Trac comment by sedwards (github user: seledwards) on 06-05-2013 at 15:55_
