### ISSUE TITLE
Call setClientCert with an array instead of a string

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#592]
In the flack HTML page, we currently pass the experimenter's certificate chain as a single string. The underlying SSL library wants this to be an array of certificates representing the chain. Split the single string into certificates and invoke `setClientCert()` with an array of strings, one certificate per array entry.

 _Imported from trac ticket [#592](http://trac.gpolab.bbn.com/proto-ch/ticket/592),  created by tmitchel on 06-05-2013 at 14:36, last modified: 06-10-2013 at 16:05_

**Comment by ahelsing** [comment]
Fixed (with Tom's JavaScript code).

_Trac comment by bujcich on 06-10-2013 at 16:05_
