### ISSUE TITLE
Update OpenId for portal.geni.net

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#594]
It looks like some of the OpenId implementation was hardcoded for panther. Fix that.

 _Imported from trac ticket [#594](http://trac.gpolab.bbn.com/proto-ch/ticket/594),  created by tmitchel on 06-06-2013 at 16:13, last modified: 06-10-2013 at 13:17_

**Comment by tcmitchell** [comment]
There are several occurrences of the panther hostname in the openid code:
```
$ find . -name '*.php' -exec grep -H panther {} \;
./lib/php/message_handler.php:  // the transition from panther.gpolab.bbn.com to
./openid/src/server-direct/config.php:$server_url = "https://panther.gpolab.bbn.com/server/server.php";
./openid/src/server-direct/config.php:$indirect_server_url = "https://panther.gpolab.bbn.com/secure/openid/server.php";
./openid/src/server-indirect/config.php:$server_url = "https://panther.gpolab.bbn.com/server/server.php";
```

_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2013 at 16:13_

**Comment by ahelsing** [comment]
Fixed.

_Trac comment by bujcich on 06-10-2013 at 13:17_
