### ISSUE TITLE
Restore installation of geni-ch-githash

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#598]
The automake installation dropped installation of geni-ch-githash. Restore it.

 _Imported from trac ticket [#598](http://trac.gpolab.bbn.com/proto-ch/ticket/598),  created by tmitchel on 06-06-2013 at 17:06, last modified: 06-20-2013 at 20:51_

**Comment by seledwards** [comment]
I think this is fixed or OBE.  Tom can you confirm?

_Trac comment by sedwards (github user: seledwards) on 06-20-2013 at 14:30_

**Comment by tcmitchell** [comment]
The file was never lost in the automake transition, it just moved from `/usr/local/etc/geni-ch-githash` to `/etc/geni-ch/geni-ch-githash`. The move is both to obey the configured Automake locations (`/etc`, not `/usr/local/etc`) and to locate this file with other portal/clearinghouse data.

_Trac comment by tmitchel (github user: tcmitchell) on 06-20-2013 at 20:51_
