### ISSUE TITLE
script to reset outside cert

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#601]
Write an operator script that deletes any outside cert for a given user

 _Imported from trac ticket [#601](http://trac.gpolab.bbn.com/proto-ch/ticket/601),  created by ahelsing on 06-07-2013 at 15:07, last modified: 06-12-2013 at 09:46_

**Comment by seledwards** [comment]
This script is called `geni-delete-outside-cert`.

_Trac comment by sedwards (github user: seledwards) on 06-12-2013 at 09:46_
