### ISSUE TITLE
Add GEMINI button(s) to home page

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#602]
Add a GEMINI button to each slice on the home page. This button should look the same and function the same as the button on the slice page.

GEMINI has also requested a general button as well that will transfer the user to GEMINI independent of which slice they are using.

Honor the gemini-user attribute for these just as is done on the slice page.

 _Imported from trac ticket [#602](http://trac.gpolab.bbn.com/proto-ch/ticket/602),  created by tmitchel on 06-07-2013 at 15:45, last modified: 06-10-2013 at 16:52_

**Comment by ahelsing** [comment]
Fixed.

_Trac comment by bujcich on 06-10-2013 at 15:53_

**Comment by tcmitchell** [comment]
We still need the GEMINI button on the home page that is not tied to a slice.

_Trac comment by tmitchel (github user: tcmitchell) on 06-10-2013 at 16:24_

**Comment by tcmitchell** [comment]
Top level button was added

_Trac comment by tmitchel (github user: tcmitchell) on 06-10-2013 at 16:52_
