### ISSUE TITLE
Revamp slice and sliver renewal

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#603]
Revamp how we do slice and sliver renewal on the slice page.

See also #323 and #361

 _Imported from trac ticket [#603](http://trac.gpolab.bbn.com/proto-ch/ticket/603),  created by sedwards on 06-08-2013 at 00:28, last modified: 06-11-2013 at 20:47_
   CCing: nriga@...

**Comment by seledwards** [comment]
Did a bunch of things:
 * Added a combined slice and sliver renewal option
 * AJAX-ified the sliver renewal operation
 * do-renew.php now handles three renew cases: slice only, slice and all slivers, single sliver
 * Display expiration times as text in UTC
 * sliver expiration times are handled appropriately if it hasn't been queried yet and if the AM is busy
 * all expiration times are printed in a consistent format (in UTC)
 * add datepickers (calendars) for both slice and sliver renewal
 * datepicker for slice renewal sets a min date of the current expiration and a max date of 21 days
 * datepicker for sliver renewal sets a min date of today and a max date of the slice expiration

Things to test: 
 * Basics (for all of the following note the windows you are given to select from): 
   - Renew just a slice 
   - Renew a slice and all slivers
   - Renew a single sliver
   - Get Status at AM with and without resource reservations
 * Max slice expiration is hardcoded to 21 days.  There should be a better way to do this.
 * Check the view of a slice from both Member and Auditor perspectives
 * Test against both IG and EG (can we do this on cascade now?)


_Trac comment by sedwards (github user: seledwards) on 06-08-2013 at 00:37_

**Comment by seledwards** [comment]
This code is on the `improverenew` branch.

_Trac comment by sedwards (github user: seledwards) on 06-08-2013 at 00:37_

**Comment by tcmitchell** [comment]
The SA has a setting for max expiration:
```
$sa_max_slice_renewal_days = 20;
```
At present, the portal has no way to access this information. Different SAs would have different values. There have been requests to increase this value as well, so we risk having the portal fall out of date.

Let's at least extract this value into the settings file so that it can be updated independent of the code.


_Trac comment by tmitchel (github user: tcmitchell) on 06-11-2013 at 12:48_

**Comment by ahelsing** [comment]
Is it too obvious to suggest that the tool (whether it's the Portal or Omni) can't know what the SA's max will be, unless it asks?

(Does it have a way to ask, other than by trying and failing?)

_Trac comment by jbs on 06-11-2013 at 12:53_

**Comment by tcmitchell** [comment]
I ran through most of the "Things to test" list:
 * ~~Basics (for all of the following note the windows you are given to select from):~~
  * ~~Renew just a slice~~
  * ~~Renew a slice and all slivers~~
  * ~~Renew a single sliver~~
 * ~~Get Status at AM with and without resource reservations~~
 * ~~Max slice expiration is hardcoded to 21 days. There should be a better way to do this.~~
 * ~~Check the view of a slice from both Member and Auditor perspectives~~
 * Test against both IG and EG (can we do this on cascade now?)

I reported an issue with the hardcoded 21 days: it shows up as limited to 9 days. Sarah is working on something and I caught an in-progress state.

We can test on cascade once Sarah is ready to do so. Cascade should have access to the NICTA ExoGENI rack.

_Trac comment by tmitchel (github user: tcmitchell) on 06-11-2013 at 14:18_

**Comment by seledwards** [comment]
Test ExoGENI NICTA and pgeni3 on cascade.  Fixed the EG geni_expires calculation.  Added renewsliver.php to the Makefile.

I think this is done.  Closing.

_Trac comment by sedwards (github user: seledwards) on 06-11-2013 at 20:47_
