### ISSUE TITLE
Create account for Joanne Achin

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#61]
Create an account so that Joanne Achin can log into the development portal VMs to help with user interface work.

Here email address is:
Joanne Achin <jachin@bbn.com>

So her username should probably match that.

 _Imported from trac ticket [#61](http://trac.gpolab.bbn.com/proto-ch/ticket/61),  created by sedwards on 05-29-2012 at 17:35, last modified: 05-30-2012 at 07:55_

**Comment by tcmitchell** [comment]
Done. Standard password.

_Trac comment by tmitchel (github user: tcmitchell) on 05-30-2012 at 07:55_
