### ISSUE TITLE
handle project request sends email to malformed address

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#611]
A user with email address `user@example.com` requests to join project "Foo". The lead of project "Foo" approves the request. An email is sent to `user@example_com`.

 _Imported from trac ticket [#611](http://trac.gpolab.bbn.com/proto-ch/ticket/611),  created by tmitchel on 06-12-2013 at 12:07, last modified: 06-13-2013 at 17:57_

**Comment by tcmitchell** [comment]
If the email address is first.last@example.edu, it gets translated to first_last@example_edu.

_Trac comment by tmitchel (github user: tcmitchell) on 06-12-2013 at 15:09_

**Comment by tcmitchell** [comment]
The HTML with the form shows the right email address in the name attribute of the select tag. But when it comes in via the post, the dots are replaced by underscores. The catch is that an email address can contain an underscore, which also comes in as an underscore. So we can't just translate underscores back to dots.

_Trac comment by tmitchel (github user: tcmitchell) on 06-12-2013 at 17:19_

**Comment by ahelsing** [comment]
just speculating - is this a quoting issue / html escape issue?

_Trac comment by ahelsing on 06-12-2013 at 20:40_

**Comment by tcmitchell** [comment]
Fixed by putting the email address in the comma-separated data instead of using the value of the name attribute.

_Trac comment by tmitchel (github user: tcmitchell) on 06-13-2013 at 17:57_
