### ISSUE TITLE
note on home.php and slice.php if there is imminent expiration of a slice (and slivers where possible)

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#613]
It'd be nice to indicate on the home page as well as on the slice page which slices (and slivers) are about to expire.

That way experimenters would be warned that they might need to renew them.

I think it would be hard to get the information about slivers expiring for the home page, but it could be done on the slice page.

Both pages already display the slice expiration date.

 _Imported from trac ticket [#613](http://trac.gpolab.bbn.com/proto-ch/ticket/613),  created by sedwards on 06-12-2013 at 13:45, last modified: 07-17-2014 at 11:24_
   CCing: dabideen@...

**Comment by ahelsing** [comment]
Note that the sliver_info table has some sliver expiration information now, so some of that data is available.

_Trac comment by ahelsing on 07-17-2014 at 11:24_

**Comment by ahelsing** [comment]
New dashboard provides this indication (not the slice page)

**Comment by tcmitchell** [comment]
Complete with new portal UI
