### ISSUE TITLE
slice expiration datepicker shouldn't let you pick a date past the project expiration

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#614]
On the slice page, the slice expiration datepicker currently limits you to a (configurable) maximum number of days from the present.  Ideally it should set the max to be `min(current date + max number of days to renew, project expiration)`.

This isn't critical because the SA won't let you renew past the project expiration, but it would be more user friendly if it didn't let you try.

 _Imported from trac ticket [#614](http://trac.gpolab.bbn.com/proto-ch/ticket/614),  created by sedwards on 06-12-2013 at 14:16, last modified: 07-10-2013 at 01:24_

**Comment by ahelsing** [comment]
Fixed and merged into `develop-gec17`. If a project expiration exists, the expiration and current date are compared to determine the number of days to expiration. Then the minimum is chosen between that and the maximum slice expiration in days (currently 185).

_Trac comment by bujcich on 07-05-2013 at 10:37_
