### ISSUE TITLE
gemini.php is issuing PHP warnings

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#619]
From the log file:
```

[Fri Jun 14 10:42:51 2013] [error] [client 128.89.81.42] PHP Notice:  Undefined variable: user_cert in /var/www/secure/gemini.php on line 122

[Fri Jun 14 10:42:51 2013] [error] [client 128.89.81.42] PHP Notice:  Undefined variable: warnings in /var/www/secure/gemini.php on line 185

```

 _Imported from trac ticket [#619](http://trac.gpolab.bbn.com/proto-ch/ticket/619),  created by tmitchel on 06-14-2013 at 13:00, last modified: 06-17-2013 at 15:34_

**Comment by tcmitchell** [comment]
The user_cert line can go away, the variable is no longer used.

The warnings array should get initialized before it is used.


_Trac comment by tmitchel (github user: tcmitchell) on 06-14-2013 at 13:01_

**Comment by ahelsing** [comment]
`user_cert` is commented out, and `warnings` is initialized before any references are made to it. (This may still require further testing by checking against the log file.)

_Trac comment by bujcich on 06-14-2013 at 13:24_

**Comment by ahelsing** [comment]
Tested by checking the error log (`/var/log/apache2/error.log`). Did not see any PHP notices.

_Trac comment by bujcich on 06-14-2013 at 16:39_
