### ISSUE TITLE
Review and repair permissions on project page

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#62]
The project page (project.php) is not properly checking privileges. It uses a general RESOURCE context to determine if the user can create a slice, but should be checking the project context instead. The "disable project" button has no privilege check at all. There may be other privilege checking issues as well.

 _Imported from trac ticket [#62](http://trac.gpolab.bbn.com/proto-ch/ticket/62),  created by tmitchel on 05-30-2012 at 11:16, last modified: 06-11-2012 at 14:23_

**Comment by MarshallBrinn** [comment]
I believe this is fixed - the calls to privAdmin and privSlice are replaced with proper calls to $user->isAllowed

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-11-2012 at 14:23_
