### ISSUE TITLE
Update GEMINI integration

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#623]
Update GEMINI integration to generally available:
 1. Send data to https://genidesktop.netlab.uky.edu/stable/logon/clearinghouse/logon_entry.php
 1. Make GENI Desktop buttons available to all users

 _Imported from trac ticket [#623](http://trac.gpolab.bbn.com/proto-ch/ticket/623),  created by tmitchel on 06-17-2013 at 10:23, last modified: 06-17-2013 at 11:30_

**Comment by ahelsing** [comment]
Fixed. Removed check of `if ($user->hasAttribute('gemini-user'))` from:
 * `portal/www/portal/slice.php`
 * `portal/www/portal/home-active.php`
 * `portal/www/portal/tool-slices.php`
Changed `dev` to `stable` in GEMINI URL in `portal/www/portal/gemini.php` and adjusted the redirection message to "Redirecting to GENI Desktop..."

_Trac comment by bujcich on 06-17-2013 at 11:30_
