### ISSUE TITLE
Conditionalize display of the generate ssh key button on uploadsshkey.php

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#625]
If a user already has a generated ssh key they should not be allowed to generate another. Remove the button and explanatory text from `uploadsshkey.html` and display the button in `uploadsshkey.php` only if the user does not have an ssh key already.

See `tools-user.php` for appropriate code to check for ssh keys.

 _Imported from trac ticket [#625](http://trac.gpolab.bbn.com/proto-ch/ticket/625),  created by tmitchel on 06-17-2013 at 12:24, last modified: 06-17-2013 at 15:34_

**Comment by ahelsing** [comment]
Fixed. The checking is done in `uploadsshkey.php` and the line was removed from `uploadsshkey.html`.

_Trac comment by bujcich on 06-17-2013 at 13:47_
