### ISSUE TITLE
"Join Project" request can lead to bounced messages

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#629]
If someone requests to join a project which is owned by a user with displayName "Lastname, Firstname" and e-mail address `valid@example.com`, this generates a join request e-mail with:
```
To: Lastname@gpolab.bbn.com, Firstname <valid@example.com>
```
The gpolab copy bounces.  I believe a correct join request e-mail should be addressed:
```
To: "Lastname, Firstname" <valid@example.com>
```

 _Imported from trac ticket [#629](http://trac.gpolab.bbn.com/proto-ch/ticket/629),  created by chaos on 06-18-2013 at 09:50, last modified: 06-30-2013 at 15:14_

**Comment by ahelsing** [comment]
See do-handle-project-request, do-modify, do-upload-project-members, invite-to-geni, invite-to-project, ask-for-project, and user

Then also sa_controller and ma_utils to be sure


_Trac comment by ahelsing on 06-25-2013 at 12:59_

**Comment by ahelsing** [comment]
join-this-project is the thing being complained about here.
invite-to-geni, invite-to-project and ask-for-project all take user input email addresses, so are a little suspect as well.

If the to has a comma, then quote it.


_Trac comment by ahelsing on 06-27-2013 at 23:05_

**Comment by tcmitchell** [comment]
Here is a proposed fix (untested):
```
diff --git a/portal/www/portal/join-this-project.php b/portal/www/portal/join-this-project.php
index 944a391.fc396b5 100644
--- a/portal/www/portal/join-this-project.php
+++ b/portal/www/portal/join-this-project.php
@@ -73,8 +73,8 @@ $admin_emails = array();
 if ($admins and count($admins) > 0) {
   foreach ($admins as $admin_res) {
     $admin = $user->fetchMember($admin_res[PA_PROJECT_MEMBER_TABLE_FIELDNAME::MEMBER_ID]);
-    $admin_emails[] = $admin->prettyName() . " <" . $admin->email() . ">";
-    //    error_log("Adding admin " . $admin->prettyName());
+    $admin_email[] = sprintf('"%s" <%s>', $admin->prettyName(),
+                             $admin->email());
   }
 }
 
@@ -152,7 +152,8 @@ Thank you,\n" . $user->prettyName() . "\n";
     $cc = ""; // FIXME: Include portal-dev-admin?
   }
   
-  mail($lead->prettyName() . "<" . $lead->email() . ">",
+  $lead_email = sprintf('"%s" <%s>', $lead->prettyName(), $lead->email());
+  mail($lead_email,
        "Join GENI project $project_name?",
        $message,
        "Reply-To: $email" . "\r\n" . $cc . "From: $name <$email>");
```

Other options:
 * stop including the `prettyName` in the email address altogether
 * Create a function on user for "prettyEmailAddress" that does the `sprintf` in the above diff
  * I think I prefer this to the above diff because it localizes the `sprintf` so there's a single location to fix/improve things.

_Trac comment by tmitchel (github user: tcmitchell) on 06-28-2013 at 12:25_
