### ISSUE TITLE
Add text next to the request to be a project lead button

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#630]
During summer camp, almost all students submitted a request to become project leads although the instructions clearly asked them not to. I think that we should add some text next to the button that indicates our general policy. 

 _Imported from trac ticket [#630](http://trac.gpolab.bbn.com/proto-ch/ticket/630),  created by nriga on 06-18-2013 at 10:17, last modified: 06-27-2013 at 23:12_

**Comment by seledwards** [comment]
This might be a problem as more people register for GEC.  Putting on the GEC17 milestone for consideration.

_Trac comment by sedwards (github user: seledwards) on 06-18-2013 at 18:14_

**Comment by ahelsing** [comment]
Niky suggests:
```
What about :
"Based on GENI's current policy only faculty and senior members of an organization
can be project leads (e.g. students *can not* be project leads)."

Another option would be to add the text in bold in the "Modify Account Page" there
we can also add more explanatory text if we need to. 
```


_Trac comment by ahelsing on 06-25-2013 at 13:34_

**Comment by ahelsing** [comment]
Put this text in modify.php.

This could go after the close form tag, or in between the 2 paragraphs just below the page header.

I suggested we use the text Niky suggests above.


_Trac comment by ahelsing on 06-25-2013 at 20:27_
