### ISSUE TITLE
Default slice expirations

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#636]
Josh suggests:

 * The default expiration for new slices should be one week.
 * The maximum expiration for renewslice should be six months.

And this should be configurable.

 _Imported from trac ticket [#636](http://trac.gpolab.bbn.com/proto-ch/ticket/636),  created by ahelsing on 06-20-2013 at 09:37, last modified: 06-28-2013 at 12:44_

**Comment by tcmitchell** [comment]
See browser:sa/php/sa_settings.php (which gets installed as `/usr/share/geni-ch/sa/php/sa_settings.php`.

Default expiration for new slices is held in `$sa_default_slice_expiration_hours`. One week would be `168` hours.

Max slice renewal is held in `$sa_max_slice_renewal_days`. Six months would be about `183` days.


_Trac comment by tmitchel (github user: tcmitchell) on 06-20-2013 at 21:11_

**Comment by seledwards** [comment]
If we change the CH we should also change the equivalent portal setting `proto-ch/portal/www/portal/settings.php` to say:
```
// set to match the current GENI CH SA
$portal_max_slice_renewal_days = 183;
```

_Trac comment by sedwards (github user: seledwards) on 06-21-2013 at 09:43_

**Comment by ahelsing** [comment]
Not a big deal either way, but 185 days might be a good pick, because six months will never be *longer* than that, which means that renew for "now + 6 months" would always work (whereas "now + 6 months" is 184 days for dates in March, May, July, and August).

_Trac comment by jbs on 06-26-2013 at 23:43_

**Comment by tcmitchell** [comment]
Updated the two constants in `sa_settings.php` and one constant in `portal/settings.php`.

_Trac comment by tmitchel (github user: tcmitchell) on 06-28-2013 at 12:44_
