### ISSUE TITLE
GENI User should be more restrictive

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#644]
We have a problem with user management in the portal

I can ask the MA for member data and and call user->init_from_member with that member's data and create that user (with their inside cert and key). I can then make calls to the MA AS that user.

Specifically, I can ask the MA for "MY" ssh keys (MA has a guard that only gives you your keys). But if I can change who "I" am in my call to lookup_ssh_keys, (from $user to some other GeniUser) then I can get their keys.

I propose two things.
 - We need to change GeniUser so that only "ME" can be created. This needs to be a more fundamental change so that no tool can go to the CH/MA pretending to be someone else.
 - We need to break up the lookup_ssh_keys to return only public keys.
 - And then have another function that returns private SSH keys only for you.

 _Imported from trac ticket [#644](http://trac.gpolab.bbn.com/proto-ch/ticket/644),  created by mbrinn on 06-21-2013 at 16:11, last modified: 07-02-2013 at 10:55_

**Comment by MarshallBrinn** [comment]
To be more specific about the first bullet, 
user.php has calls that use $this (the user being created) rather than Portal::getInstance() as the signer. That should be changed so that the portal is always speaking AS itself. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-24-2013 at 09:25_

**Comment by ahelsing** [comment]
even better would be if user.php used the user who is using the portal where that user is already known. In general, the portal should only speak as the portal long enough to get the cert/key for the current actual user.

_Trac comment by ahelsing on 06-24-2013 at 09:35_

**Comment by MarshallBrinn** [comment]
Fixed this. Several things done
1. Split lookup_ssh_keys into two calls: lookup_public_ssh_keys and lookup_private_ssh_keys
2. Make sure that only the current user can call lookup_private_ssh_keys for themselves (not portal, not another user). This is in addition to the protections done in the MA itself.
3. Fix a bug in sshkeyedit that didn't handle lists of keys (assumed only one).


_Trac comment by mbrinn (github user: MarshallBrinn) on 06-26-2013 at 08:35_
