### ISSUE TITLE
Login information is wrong in multi-user slices

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#645]
I created a slice with 3 members for one of my hosts (a raw host) the login information is wrong. I attach a screenshot. 

The AM is Utah Protogeni and the RSpec is the OpenFlow OVS Tutorial

 _Imported from trac ticket [#645](http://trac.gpolab.bbn.com/proto-ch/ticket/645),  created by nriga on 06-23-2013 at 10:50, last modified: 06-25-2013 at 09:39_

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [Screen Shot 2013-06-23 at 10.49.10 AM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/645/Screen Shot 2013-06-23 at 10.49.10 AM.png) on 06-23-2013 at 10:51_

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [tkt645.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/645/tkt645.png) on 06-24-2013 at 15:34_

**Comment by innnkkki** [comment]
I think the error is in the getInfoFromSliverStatusPG function where we set the login information outside the loop of children1, 
while it should be the last thing it happens at the end of each children2 iteration, i.e. within the children1 loop. 

This code:
```
  $loginInfo[ $client_id ] = array();
      foreach ($pgKeyList as $user => $keys) {	
            $loginInfo[ $client_id ][$user] = array('authentication' => 'ssh-keys', 
                              'hostname' => $hostname,
                              'client_id' =>  $client_id,
                              'port' => $port,
                              'username' => $user,
                              'keys'  =>  $keys,
                              'geni_status' => $geni_status,
                              'am_status' => $am_status
                             );

```

Should move to the exactly previous loop. 

_Trac comment by nriga (github user: innnkkki) on 06-23-2013 at 16:12_

**Comment by seledwards** [comment]
We need to be able to reproduce the problem (perhaps on cascade) and test the above fix.

We should be able to create a slice, reserve some resources, see the error.  Then add the fix and see that the error goes away. 


_Trac comment by sedwards (github user: seledwards) on 06-24-2013 at 15:29_

**Comment by seledwards** [comment]
We can do a hotfix on Tues 10-12 or Wed 1-3.

_Trac comment by sedwards (github user: seledwards) on 06-24-2013 at 15:31_

**Comment by seledwards** [comment]
I have a broken slice on portal1.gpolab.bbn.com in slice urn:publicid:IDN+ch1.gpolab.bbn.com:tutorial+slice+tkt645:
https://portal1.gpolab.bbn.com/secure/listresources.php?slice_id=7d30bd22-e4ed-4284-94fa-8c4aa4c631a4&am_id=19

_Trac comment by sedwards (github user: seledwards) on 06-24-2013 at 17:11_

**Comment by ahelsing** [comment]
Fixed via Niky's instructions.

_Trac comment by bujcich on 06-25-2013 at 09:39_
