### ISSUE TITLE
e-mail to identify users in bulk upload should not be case sensitive

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#646]
When you bulk load users into a project, it looks up users by email address in a case sensitive way.
They should be treated as case insensitive.

 _Imported from trac ticket [#646](http://trac.gpolab.bbn.com/proto-ch/ticket/646),  created by sedwards on 06-23-2013 at 22:13, last modified: 07-02-2013 at 10:47_

**Comment by ahelsing** [comment]
see upload-project-members line 234 and 238
Make these something like:
```
array_key_exists(strtolower($email), array_change_key_case($members_by_email)
```


_Trac comment by ahelsing on 07-01-2013 at 10:28_

**Comment by seledwards** [comment]
Also just do `$email = strtolower($email);`.

_Trac comment by sedwards (github user: seledwards) on 07-01-2013 at 12:52_

**Comment by seledwards** [comment]
Done.  Closing.

_Trac comment by sedwards (github user: seledwards) on 07-01-2013 at 12:56_
