### ISSUE TITLE
OBE: Differentiating MA Attributes

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#647]
The MA call get_member_info (called by various lookup_* calls) returns all the data from the ma_member_attributes table. 

There is no way to put different guards on different kinds of attributes and there should be. Otherwise we wind up with something that is either too restrictive or too lenient.

Here's a proposal:
  - We create two methods: lookup_public_member_info and lookup_protected_member_info.
  - The guard on lookup_public_member_info is open (i.e. anyone can get this info)
  - The guard on lookup_protected_member_info is very restrictive (i.e. only operators, authorities and the member themselves can see it).

The big question is which attributes go in which category?

I propose:
   - Public: Name (first, last, display) and Email
   - Protected: Everything else (eppn, affiliation, telephone) 

This ticket is intended as a forum to discuss the pros and cons of different guard stragegies on different MA attributes.

 _Imported from trac ticket [#647](http://trac.gpolab.bbn.com/proto-ch/ticket/647),  created by mbrinn on 06-24-2013 at 10:31, last modified: 12-05-2013 at 13:22_

**Comment by tcmitchell** [comment]
This should be OBE with the new CH.

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 12:06_
