### ISSUE TITLE
undefined variables in amstatus

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#648]
During the GREE tutorials just now, I see a bunch of warnings about undefined variables
 - undefined variable client_id in amstatus.php line 262 when called from sliverstatus.php or listresources.php
 - and line 266
 - undefined geni_status amstatus line 270 when called from sliverstatus or listresources.php
 - undefined am_status line 272
 - undefined client_id line 264
 - Undefined variable: am_id in /var/www/secure/listresources.php on line 140, referer: https://portal.geni.net/secure/project.php or home.php

 _Imported from trac ticket [#648](http://trac.gpolab.bbn.com/proto-ch/ticket/648),  created by ahelsing on 06-24-2013 at 14:33, last modified: 06-25-2013 at 11:21_

**Comment by seledwards** [comment]
All of these except for the am_id issue are due to #645.

_Trac comment by sedwards (github user: seledwards) on 06-24-2013 at 14:35_

**Comment by ahelsing** [comment]
Fixed. Most of the errors on the ticket were fixed with 645.

This fixes instances where am_id is undefined. If am_id was not specified as part of the URL, then $am_id was never defined when using the tool tool-lookupids.php. Now $am_id is initialized as an empty string prior to the include of tool-lookupids.php. That way if tool-lookupids.php does change $am_id, then it still works. If tool-lookupids.php doesn't change $am_id, then it stays as an initialized empty string.

_Trac comment by bujcich on 06-25-2013 at 11:21_
