### ISSUE TITLE
Delete on all AMs does not seem to work in parallel

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#652]
When I do delete resources on all the AMs, it usually gets stuck on Utah PG (makes sense
bigger AM) which makes me think that the calls are serialized. 

 _Imported from trac ticket [#652](http://trac.gpolab.bbn.com/proto-ch/ticket/652),  created by nriga on 06-24-2013 at 16:22, last modified: 04-07-2014 at 16:59_

**Comment by tcmitchell** [comment]
I don't think any promises are made about whether these requests are done serially or in parallel.

If a change to parallel is desired, we'll need to close the session earlier in the browser:portal/www/portal/deletesliver.php using [session-write-close()](http://php.net/manual/en/function.session-write-close.php). Don't close it until we're done with it though. See around line 77 where 'lasterror' is set.

_Trac comment by tmitchel (github user: tcmitchell) on 06-28-2013 at 13:50_

**Comment by ahelsing** [comment]
I believe that now that delete is AJAXified, this is OBE.

Note that individual Omni commands are not done in parallel, but instead the browser calls a separate PHP page for each AM.

_Trac comment by ahelsing on 04-07-2014 at 16:59_
