### ISSUE TITLE
update the privacy policy to cover sharing of data with operators via GMOC

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#654]
In order to make sure that the portal privacy covers the ways in which GMOC-collected data may be shared with operators, update the portal privacy policy:
```
portal/www/policy/privacy.html
```
changing the "Release of Information to Third Parties" section to read:
```
None of the information is shared with third parties, except operations staff involved in GENI support and event resolution.
```

 _Imported from trac ticket [#654](http://trac.gpolab.bbn.com/proto-ch/ticket/654),  created by chaos on 06-25-2013 at 13:06, last modified: 06-25-2013 at 13:48_

**Comment by tcmitchell** [comment]
Complete.

_Trac comment by tmitchel (github user: tcmitchell) on 06-25-2013 at 13:48_
