### ISSUE TITLE
Allow for download public SSH key

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#655]
We currently have a mechanism for downloading private SSH keys but no parallel mechanism for downloading public SSH keys. We should add this to the profile page.

 _Imported from trac ticket [#655](http://trac.gpolab.bbn.com/proto-ch/ticket/655),  created by mbrinn on 06-26-2013 at 08:36, last modified: 06-26-2013 at 09:47_

**Comment by ahelsing** [comment]
Fixed. A new file, downloadsshpublickey.php, takes care of retrieving the public ssh keys. It is a copy of downloadsshkey.php (used to download private keys) and it replaces instances of 'private' with 'public'. All of the user's public ssh keys (whether they were generated from the portal or not) are available for download. This fix was tested with having 1) a generated keypair and 2) a user-uploaded public key and 3) both.

_Trac comment by bujcich on 06-26-2013 at 09:47_
