### ISSUE TITLE
pa_project(project_id) should be declared unique

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#657]
The project_id column of pa_project is not declared as unique. 

Shouldn't it be?

And if we do so, then all uses of project_id within the PA (and now also SA) should add `REFERENCES pa_project (project_id)`

 _Imported from trac ticket [#657](http://trac.gpolab.bbn.com/proto-ch/ticket/657),  created by ahelsing on 06-26-2013 at 11:09, last modified: 07-25-2014 at 15:48_

**Comment by MarshallBrinn** [comment]
For that matter, none of the UUID fields (sa_slice.slice_id, ma_member.member_id etc.) are unique. We use these ID serial fields but then we join tables based on the UUID fields. That's wrong in general. Eitehr the real key is the ID or the real key is the UUID. - Marshall


_Trac comment by mbrinn (github user: MarshallBrinn) on 06-26-2013 at 11:29_

**Comment by ahelsing** [comment]
ma_member(member_id) is declared unique. So at least we did that much right. Your general point is a good one.

_Trac comment by ahelsing on 06-26-2013 at 11:36_

**Comment by ahelsing** [comment]
See ticket #943

_Trac comment by ahelsing on 07-25-2014 at 15:48_
