### ISSUE TITLE
Remove privSlice() and privAdmin() from user class

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#67]
These methods use outdated authorization. Replace calls to these methods with calls to User.isAllowed() using the appropriate contexts.

 _Imported from trac ticket [#67](http://trac.gpolab.bbn.com/proto-ch/ticket/67),  created by tmitchel on 05-31-2012 at 15:56, last modified: 06-11-2012 at 14:24_

**Comment by MarshallBrinn** [comment]
This is done - the calls are removed and the callers now call $user->isAllowed(...);

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-11-2012 at 14:24_
