### ISSUE TITLE
Clean up OpenID logging

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#670]
There are lots of printouts from openid stuff - mostly apparently debug stuff.

Clean these up.

Sample:
```
[Sun Jun 30 06:45:38 2013] [error] [client 60.241.64.49] OpenID-Direct: in server.php
[Sun Jun 30 06:45:38 2013] [error] [client 60.241.64.49] OpenID-Direct: loaded lib/actions.php
[Sun Jun 30 06:45:38 2013] [error] [client 60.241.64.49] OpenID-Direct: action = "action_default"
[Sun Jun 30 06:45:38 2013] [error] [client 60.241.64.49] OpenID-Direct: in action_default
[Sun Jun 30 06:45:40 2013] [error] [client 60.241.64.49] OpenID-Direct: in server.php
[Sun Jun 30 06:45:40 2013] [error] [client 60.241.64.49] OpenID-Direct: loaded lib/actions.php
[Sun Jun 30 06:45:40 2013] [error] [client 60.241.64.49] OpenID-Direct: action = "action_idpXrds"
[Sun Jun 30 06:45:41 2013] [error] [client 60.241.64.49] OpenID-Direct: in server.php
[Sun Jun 30 06:45:41 2013] [error] [client 60.241.64.49] OpenID-Direct: loaded lib/actions.php
[Sun Jun 30 06:45:41 2013] [error] [client 60.241.64.49] OpenID-Direct: action = "action_default"
[Sun Jun 30 06:45:41 2013] [error] [client 60.241.64.49] OpenID-Direct: in action_default
[Sun Jun 30 06:45:43 2013] [error] [client 60.241.64.49] OpenID-Direct mode = associate
[Sun Jun 30 06:45:47 2013] [error] [client 60.241.64.49] OpenID-Direct: in server.php, referer: http://localhost:400
0/resource/login/openid.html
[Sun Jun 30 06:45:47 2013] [error] [client 60.241.64.49] OpenID-Direct: loaded lib/actions.php, referer: http://loca
lhost:4000/resource/login/openid.html
[Sun Jun 30 06:45:47 2013] [error] [client 60.241.64.49] OpenID-Direct: action = "action_default", referer: http://l
ocalhost:4000/resource/login/openid.html
[Sun Jun 30 06:45:47 2013] [error] [client 60.241.64.49] OpenID-Direct: in action_default, referer: http://localhost
:4000/resource/login/openid.html
[Sun Jun 30 06:45:47 2013] [error] [client 60.241.64.49] OpenID-Direct mode = checkid_setup, referer: http://localho
st:4000/resource/login/openid.html
[Sun Jun 30 06:46:05 2013] [error] [client 60.241.64.49] PHP Notice:  Constant page_template already defined in /usr
/share/geni-ch/openid/src/server-indirect/lib/render.php on line 18, referer: https://shib-idp.geni.net:8444/idp/pro
file/SAML2/Redirect/SSO
[Sun Jun 30 06:46:05 2013] [error] [client 60.241.64.49] PHP Notice:  A session had already been started - ignoring 
session_start() in /usr/share/geni-ch/openid/src/server-indirect/lib/session.php on line 13, referer: https://shib-i
dp.geni.net:8444/idp/profile/SAML2/Redirect/SSO
[Sun Jun 30 06:46:05 2013] [error] [client 60.241.64.49] getServer server_url = https://portal.geni.net/server/serve
r.php, referer: https://shib-idp.geni.net:8444/idp/profile/SAML2/Redirect/SSO
[Sun Jun 30 06:46:05 2013] [error] [client 60.241.64.49] idURL server_url = https://portal.geni.net/server/server.ph
p, referer: https://shib-idp.geni.net:8444/idp/profile/SAML2/Redirect/SSO
```

 _Imported from trac ticket [#670](http://trac.gpolab.bbn.com/proto-ch/ticket/670),  created by ahelsing on 07-02-2013 at 10:30, last modified: 09-27-2013 at 07:17_

**Comment by ahelsing** [comment]
session_start: I see 2 calls in server_indirect:
./src/server-indirect/lib/session.php:    session_start();
./src/server-indirect/setup.php:session_start();


page_template: this is just a constant, defined in server.php and render.php. I think each is meant to be independent - renaming the constant in each page is likely the right thing.

The OpenID-Direct logs are here:
./src/server-direct/lib/actions.php:    error_log("OpenID-Direct: in action_default");
./src/server-direct/lib/actions.php:    error_log("OpenID-Direct mode = " . $request->mode);
./src/server-direct/lib/actions.php:        /* error_log("OpenID-Direct POST redirecting to $new_location"); */
./src/server-direct/server.php:error_log("OpenID-Direct: in server.php");
./src/server-direct/server.php:    error_log("OpenID-Direct: loaded lib/actions.php");
./src/server-direct/server.php:    error_log("OpenID-Direct: action = \"$action\"");


_Trac comment by ahelsing on 07-02-2013 at 10:39_

**Comment by tcmitchell** [comment]
While eliminating the debug printouts, we should also include relevant output like "OpenID authentication succeeded for %s to site %s".

Note that this is work in progress on a branch at origin.

_Trac comment by tmitchel (github user: tcmitchell) on 08-09-2013 at 16:50_

**Comment by tcmitchell** [comment]
Debug log messages have been removed. Session is checked before starting to avoid session_start error. `page_template` also fixed.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2013 at 07:17_
