### ISSUE TITLE
OBE: Put pgch behind apache

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#672]
We should consider moving PGCH behind apache.

See #650 for the pre-history of this ticket.

 _Imported from trac ticket [#672](http://trac.gpolab.bbn.com/proto-ch/ticket/672),  created by sedwards on 07-02-2013 at 13:38, last modified: 12-05-2013 at 13:20_

**Comment by ahelsing** [comment]
OBE with new CH.

_Trac comment by ahelsing on 08-01-2013 at 15:10_
