### ISSUE TITLE
Status on Expired Slice

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#675]
I went to an expired slice (from an expired slice) and hit 'Status' (Get All) and got lots of error messages and it never returned. There appears to be a bug in am_client.

 _Imported from trac ticket [#675](http://trac.gpolab.bbn.com/proto-ch/ticket/675),  created by mbrinn on 07-02-2013 at 16:59, last modified: 09-17-2013 at 10:08_

**Comment by ahelsing** [comment]
logs show:
```
[Tue Jul 02 16:35:44 2013] [error] [client 128.89.85.198] SCRIPT_NAME = /secure/amstatus.php, referer: https://portal1.gpolab.bbn.com/secure/slice.php?slice_id=a42f7b58-9b5e-4dd0-b1c2-be7d78e6cc1b
[Tue Jul 02 16:35:44 2013] [error] [client 128.89.85.198] ERROR.CODE 4, referer: https://portal1.gpolab.bbn.com/secure/slice.php?slice_id=a42f7b58-9b5e-4dd0-b1c2-be7d78e6cc1b
[Tue Jul 02 16:35:44 2013] [error] [client 128.89.85.198] ERROR.VALUE , referer: https://portal1.gpolab.bbn.com/secure/slice.php?slice_id=a42f7b58-9b5e-4dd0-b1c2-be7d78e6cc1b
[Tue Jul 02 16:35:44 2013] [error] [client 128.89.85.198] ERROR.OUTPUT Slice a42f7b58-9b5e-4dd0-b1c2-be7d78e6cc1b is expired., referer: https://portal1.gpolab.bbn.com/secure/slice.php?slice_id=a42f7b58-9b5e-4dd0-b1c2-be7d78e6cc1b

```


_Trac comment by ahelsing on 07-02-2013 at 17:02_

**Comment by ahelsing** [comment]
amstatus just needs to be robust to that error return trying to get the slice credential

_Trac comment by ahelsing on 08-01-2013 at 15:13_

**Comment by ahelsing** [comment]
I don't see error messages when I try this.  The status says "updating..." apparently indefinitely.  Maybe slice.php can gray out the button if the slice is expired?  Then it would never get to amstatus.js.  Or maybe amstatus.js can figure out that the slice is expired and return without attempting the query. Or both to be safe?

_Trac comment by phelinek on 09-16-2013 at 16:39_

**Comment by ahelsing** [comment]
Thinking about it graying out the button won't work, since this will only happen if you leave the browser open while a slice is expiring.  So the check will have to be in am_client.


_Trac comment by phelinek on 09-16-2013 at 16:49_

**Comment by ahelsing** [comment]
I found the error messages - they're in portal_error.log (I was looking in ch_error.log)


_Trac comment by phelinek on 09-16-2013 at 17:33_

**Comment by ahelsing** [comment]
Added a check to see if the slice is expired before making the JSON query.  The JSON query was hanging and never returning. Now there are no error messages in the log, and the status comes up as "error". If we want a different status, I can set it to GENI_FAILED, which would come up as red FAILED as it does when the query for a non-expired slice fails.  I thought it might be better to have the expired status look different from the non-expired status.

_Trac comment by phelinek on 09-17-2013 at 10:08_
