### ISSUE TITLE
Undefined variable in tool-expired-projects

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#687]
```
[Wed Jul 03 11:54:11 2013] [error] [client 128.89.73.121] PHP Notice:  Undefined variable: project_request_map in /var/www/secure/tool-expired-projects.php on line 52, referer: https://portal.geni.net/secure/wimax-enable.php
[Wed Jul 03 11:54:11 2013] [error] [client 128.89.73.121] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/secure/tool-expired-projects.php on line 52, referer: https://portal.geni.net/secure/wimax-enable.php
```

 _Imported from trac ticket [#687](http://trac.gpolab.bbn.com/proto-ch/ticket/687),  created by ahelsing on 07-03-2013 at 12:01, last modified: 07-10-2013 at 01:25_

**Comment by ahelsing** [comment]
I believe the problem is that in tool-projects, project_request_map is defined inside an if block (line 158). If instead it is defined before the if block this probably works.

To test this you must be a project lead or admin for at least one project that has a pending join request.
Then expire that project
Then load the projects tab




_Trac comment by ahelsing on 07-03-2013 at 12:06_

**Comment by seledwards** [comment]
To reproduce you must be a member of only expired projects.

_Trac comment by sedwards (github user: seledwards) on 07-03-2013 at 16:52_
