### ISSUE TITLE
write a standalone script to determine which people in a provided list have portal accounts

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#700]
For tutorials (especially at GEC), it would be very handy to have a script which takes in:
```
email, first_name, last_name
```
or realistically we probably get:
```
email, name
```
And looks through everyone who has a portal account and produces a list like:
```
email, first_name, last_name, has_account
```
or
```
email, name, has_account
```

 _Imported from trac ticket [#700](http://trac.gpolab.bbn.com/proto-ch/ticket/700),  created by sedwards on 07-10-2013 at 14:38, last modified: 07-31-2013 at 17:09_

**Comment by seledwards** [comment]
The following existing script will provide a list of everyone who has an account:
```
$ /usr/local/bin/geni-ops-report -u portal -p portal -g
contact_urn,contact_email,contact_lastname,contact_givenname,owner_id
urn:publicid:IDN+ch-se.gpolab.bbn.com+user+sedwards,sedwards@geni.net,Edwards,Sarah,XXXXXXXXXXX
```

_Trac comment by sedwards (github user: seledwards) on 07-10-2013 at 14:40_

**Comment by seledwards** [comment]
Or better: 
```
sudo -u www-data /usr/local/bin/geni-ops-report -u portal -P /usr/sysadmin/etc/portal_password -g
```

_Trac comment by sedwards (github user: seledwards) on 07-10-2013 at 14:45_

**Comment by seledwards** [comment]
I have a complete version of this (probably could use some fine tuning) in proto-ch/bin/check_existence_of_accounts on branch tkt700-lookup-list-of-accounts.

_Trac comment by sedwards (github user: seledwards) on 07-15-2013 at 20:19_

**Comment by seledwards** [comment]
This is checked in on a branch in the proto-ch repo.  It's probably ready to be merged in.  It's pretty much a standalone script.  If we think it belongs elsewhere then we shouldn't merge but instead move it.

_Trac comment by sedwards (github user: seledwards) on 07-31-2013 at 16:22_

**Comment by tcmitchell** [comment]
Merged with no changes.

_Trac comment by tmitchel (github user: tcmitchell) on 07-31-2013 at 17:09_
