### ISSUE TITLE
Cert generation and download links outside of Omni

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#708]
Certificate generation and use is more general than Omni. Have the links for doing this outside of the Omni section.

Maybe a new section under 'My Stuff' for the certificates

 _Imported from trac ticket [#708](http://trac.gpolab.bbn.com/proto-ch/ticket/708),  created by ahelsing on 07-11-2013 at 15:47, last modified: 10-08-2013 at 11:33_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
Added an "SSL tab" to the profile page.  It has a button that opens the `kmcert.php` page to allow you to generate or download your SSL cert.


_Trac comment by sedwards (github user: seledwards) on 10-07-2013 at 17:02_
