### ISSUE TITLE
Re organize profile page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#709]
Maybe the SSH keys part of of the profile page should be with 'My Stuff'

Or maybe a new section for certs and keys

 _Imported from trac ticket [#709](http://trac.gpolab.bbn.com/proto-ch/ticket/709),  created by ahelsing on 07-11-2013 at 15:50, last modified: 08-29-2013 at 12:12_

**Comment by tcmitchell** [comment]
OBE with the new tabbed profile page.

_Trac comment by tmitchel (github user: tcmitchell) on 08-29-2013 at 12:12_
