### ISSUE TITLE
Project member page: Hide slice roles when empty

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#71]
On the project-member page:
Hide the Slice Roles table when the project member is not in any slices.

This seems to work sometimes, but not always. I believe there are slice attributes but no slices in the project?

 _Imported from trac ticket [#71](http://trac.gpolab.bbn.com/proto-ch/ticket/71),  created by ahelsing on 06-04-2012 at 15:56, last modified: 06-15-2012 at 15:02_

**Comment by MarshallBrinn** [comment]
I believe this is fixed with the recent changes to the membership coming from PA_PROJECT_MEMBER, not CS_ASSERTION. I've tested this in a  number of configurations and can no longer reproduce the behavior.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-15-2012 at 15:02_
