### ISSUE TITLE
Add Renew button to the per slice row

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#711]
In the tables that list slices, all the actions are there, except Renew. Can we add a button or link on the per slice row so people can see how to renew your slice.

A link to the slice page?

Move renew to a new page so you have a button both there and on the slice page to take you there?

 _Imported from trac ticket [#711](http://trac.gpolab.bbn.com/proto-ch/ticket/711),  created by ahelsing on 07-11-2013 at 15:56, last modified: 07-11-2013 at 15:56_

**Comment by ahelsing** [comment]
the new dashboard slice card has a renew action option

**Comment by tcmitchell** [comment]
Complete with the new portal UI.
