### ISSUE TITLE
Lack of component_manager_id causes manifests to not be displayed for ExoSM

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#712]
The ExoSM does not have a `component_manager_id` and so no nodes or links are displayed for it.

Fix this.  

Test both the manifest after adding resources or doing listresources (via the Details page).

 _Imported from trac ticket [#712](http://trac.gpolab.bbn.com/proto-ch/ticket/712),  created by sedwards on 07-15-2013 at 09:56, last modified: 09-12-2013 at 10:35_
   CCing: nriga@...

**Comment by seledwards** [comment]
ExoGENI has been playing around with what they want to do here.  It's possible we will need to filter the manifest based on the authority in the `sliver_id` instead of by filtering on the `component_manager_id`.

_Trac comment by sedwards (github user: seledwards) on 07-19-2013 at 09:34_

**Comment by ahelsing** [comment]
Waiting for ExoSM to be fixed to really fix this - Likely the next maintenance window in a couple weeks.

We could in the meantime start using the sliver_id instead of the component_manager_id.


_Trac comment by ahelsing on 08-01-2013 at 15:16_

**Comment by seledwards** [comment]
Replying to [ahelsing](comment:2):
> Waiting for ExoSM to be fixed to really fix this - Likely the next maintenance window in a couple weeks.
> 
> We could in the meantime start using the sliver_id instead of the component_manager_id.

That sounds right to me.

_Trac comment by sedwards (github user: seledwards) on 08-01-2013 at 16:26_

**Comment by ahelsing** [comment]
It appears ExoGENI has done as promised: the component_manager_id and component_id reflect the rack where the resources are located, and the sliver_id reflects the AM.

_Trac comment by ahelsing on 09-09-2013 at 12:51_

**Comment by ahelsing** [comment]
The fix is in portal/www/portal/print-text-helper.php around line 111

```
diff --git a/portal/www/portal/print-text-helpers.php b/portal/www/portal/print-
index 78d482a.18d8e5f 100644
--- a/portal/www/portal/print-text-helpers.php
+++ b/portal/www/portal/print-text-helpers.php
@@ -66,6 +66,26 @@ function get_name_from_urn( $urn ){
   return $name;
 }
 
+function get_auth_from_urn( $urn ){
+  if (! isset($urn) or $urn == "") {
+    return $urn;
+  }
+  if (strpos($urn, "urn:publicid:IDN+") < 0) {
+    return $urn;
+  }
+  // Exclude the usual prefix with trailing +
+  $temp = substr($urn, strlen("urn:publicid:IDN+"));
+  if (! $temp or $temp == "") {
+    return $urn;
+  }
+  // grap all up to the next +
+  $auth = substr($temp, 0, strpos("+"));
+  if (! $auth or $auth == "") {
+    return $urn;
+  }
+  return $auth;
+}
+
 function print_rspec_pretty( $xml, $manifestOnly=True, $filterToAM=False, $comp
   $err_str = "<p><i>Resource Specification returned was not valid XML.</i></p>"
   try {
@@ -109,7 +129,14 @@ function print_rspec_pretty( $xml, $manifestOnly=True, $fil
     $comp_id = $node['component_id'];
     $comp_mgr_id = $node['component_manager_id'];
     if ($filterToAM and ($comp_mgr_id!=$componentMgrURN)){
+      $sliver_id = $node['sliver_id'];
+      $sliver_auth = get_auth_from_urn($urn);
+      $compMgrAuth = get_auth_from_urn($componentMgrURN);
+      if ($sliver_auth == $compMgrAuth) {
+       error_log("Component " . $comp_id . " is part of desired AM " . $compone
+      } else {
        continue;
+      }
     }
     $node_num = $node_num+1;
     $comp_name = get_name_from_urn($comp_id);
```


_Trac comment by ahelsing on 09-09-2013 at 13:21_

**Comment by ahelsing** [comment]
Also around line 230 there's a similar fix:
```
    if ($filterToAM and ($componentMgrName!=$componentMgrURN)){
      $sliver_id = $link['sliver_id'];
      $sliver_auth = get_auth_from_urn($urn);
      $compMgrAuth = get_auth_from_urn($componentMgrURN);
      if ($sliver_auth == $compMgrAuth) {
	error_log("Component " . $comp_id . " is part of desired AM " . $componentMgrURN . " based on sliver_id " . $sliver_id);
      } else {
	continue;
      }
    }
```


_Trac comment by ahelsing on 09-09-2013 at 13:25_

**Comment by ahelsing** [comment]
fix is on a branch on origin, and works in the base (non ExoGENI) case.

Waiting for EG maintenance to be complete for other testing

_Trac comment by ahelsing on 09-11-2013 at 11:22_
