### ISSUE TITLE
Create Project results in duplicate rows in cs_assertion

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#72]
After Create Project, cs_assertion table has 2 duplicate rows (same context_id, principal ID, attribute type)

 _Imported from trac ticket [#72](http://trac.gpolab.bbn.com/proto-ch/ticket/72),  created by ahelsing on 06-04-2012 at 15:57, last modified: 06-04-2012 at 16:51_

**Comment by MarshallBrinn** [comment]
This is fixed - it was, indeed, doing everything twice...

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-04-2012 at 16:51_
