### ISSUE TITLE
RSpec upload page not robust to bad RSpecs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#720]
RSpec upload error from the nye logs:
```
[Fri Jul 19 04:38:32 2013] [error] [client 203.143.166.187] PHP Warning:  DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in /var/www/secure/rspecupload.php on line 49, referer: https://portal.geni.net/secure/rspecupload.php
[Fri Jul 19 04:38:32 2013] [error] [client 203.143.166.187] PHP Notice:  Trying to get property of non-object in /var/www/secure/rspecupload.php on line 56, referer: https://portal.geni.net/secure/rspecupload.php
[Fri Jul 19 04:38:32 2013] [error] [client 203.143.166.187] PHP Warning:  Invalid argument supplied for foreach() in /var/www/secure/rspecupload.php on line 56, referer: https://portal.geni.net/secure/rspecupload.php
```

 _Imported from trac ticket [#720](http://trac.gpolab.bbn.com/proto-ch/ticket/720),  created by ahelsing on 07-19-2013 at 05:40, last modified: 08-16-2013 at 12:54_

**Comment by ahelsing** [comment]
looks like the script should
  - check for errors
  - print the start of the bad XML for debugging
  - fail gracefully


_Trac comment by ahelsing on 07-19-2013 at 07:32_

**Comment by ahelsing** [comment]
does the bad RSpec end up in the DB?

_Trac comment by ahelsing on 08-01-2013 at 15:24_

**Comment by tcmitchell** [comment]
The bad RSpecs did end up in the database.

The fix verifies that the uploaded file is an XML file. If an error occurs in parsing, the file upload is halted and the user is shown the parser error along with the line and column number where the parse stopped.

_Trac comment by tmitchel (github user: tcmitchell) on 08-16-2013 at 12:54_
