### ISSUE TITLE
Some users are confused by the URL requirement on the account registration page

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#723]
The account registration page annotates the URL field to be HTML 5 type "url". Implementation of this type varies by browser. Firefox enforces this restriction with a parser that does not accept a URL like "www.geni.net", but will accept "x:www.geni.net", for instance.

Make this field more flexible by removing the `type="url"` attribute, allowing users to type any string into this field.

The page in question is https://portal.geni.net/idp/request.html

 _Imported from trac ticket [#723](http://trac.gpolab.bbn.com/proto-ch/ticket/723),  created by tmitchel on 07-21-2013 at 12:47, last modified: 10-03-2013 at 17:18_

**Comment by seledwards** [comment]
As an alternative, perhaps we could have default text of "http://".

_Trac comment by sedwards (github user: seledwards) on 09-30-2013 at 15:36_

**Comment by tcmitchell** [comment]
This was fixed in the account request software. The account requests are no longer part of the portal software.

_Trac comment by tmitchel (github user: tcmitchell) on 10-03-2013 at 17:18_
