### ISSUE TITLE
non project member can load project page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#727]
You can load the project page for a project that you are not a member of.

Josh noticed that Nick can load a project that Josh is the only member for.

https://portal.geni.net/secure/project.php?project_id=a45a13ea-9480-478e-bb21-6d5043ecb192

 _Imported from trac ticket [#727](http://trac.gpolab.bbn.com/proto-ch/ticket/727),  created by ahelsing on 07-22-2013 at 16:09, last modified: 08-12-2013 at 11:30_

**Comment by tcmitchell** [comment]
Added check for project membership. Non-members are redirected to home page with a 'no privileges' message.

_Trac comment by tmitchel (github user: tcmitchell) on 08-12-2013 at 11:30_
