### ISSUE TITLE
remove Add Note function on slice and project pages

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#728]
No one uses the Add Note function on slices and projects.

It is also currently unprotected.

Rather than try to invent a way to protect it, remove these buttons and pages.

 _Imported from trac ticket [#728](http://trac.gpolab.bbn.com/proto-ch/ticket/728),  created by ahelsing on 07-22-2013 at 16:23, last modified: 10-01-2013 at 13:18_

**Comment by ahelsing** [comment]
notes are done as log events.
The logging service has no guards.

So this probably needs to be done in the portal add-project-note and add-slice-note pages. We want to require USE permissions on the project and WRITE permissions on the slice.  We could add an add_note cs_action to add these two rules and then check those rules in the portal pages.


_Trac comment by ahelsing on 08-13-2013 at 11:40_

**Comment by ahelsing** [comment]
No one uses this functionality, and the new federation APIs don't have a logging service anyhow.

Kill this functionality

_Trac comment by ahelsing on 09-27-2013 at 10:27_

**Comment by tcmitchell** [comment]
Removed.

_Trac comment by tmitchel (github user: tcmitchell) on 10-01-2013 at 13:18_
