### ISSUE TITLE
Project member page: don't use get_attributes

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#73]
The Project member page (and probably the slice member page) should not use the CS functions directly.

 _Imported from trac ticket [#73](http://trac.gpolab.bbn.com/proto-ch/ticket/73),  created by ahelsing on 06-04-2012 at 15:59, last modified: 06-05-2012 at 14:18_

**Comment by MarshallBrinn** [comment]
All fixed - uses get_project_members, get_slice_members and get_slice_members_for_project instead

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-05-2012 at 14:18_
