### ISSUE TITLE
Reserving resources does not work in IE 8

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#730]
Reserving resources via `slice-add-resources.php` does not work in IE 8. The error returned is "Object doesn't support this property or method" on line 7, character 3.

To test IE without using Windows as a host, download a VM with any recent IE version and recent Windows operating system: http://www.modern.ie/en-us/virtualization-tools

 _Imported from trac ticket [#730](http://trac.gpolab.bbn.com/proto-ch/ticket/730),  created by bujcich on 07-30-2013 at 14:01, last modified: 08-01-2013 at 14:29_

**Comment by ahelsing** [comment]
If Google Analytics shows IE8 users, then we should do this.

_Trac comment by ahelsing on 08-01-2013 at 14:29_

**Comment by tcmitchell** [comment]
According to Google analytics, 64 of 59,187 sessions used IE 8 from August 1, 2013 (when this ticket was opened) and August 1, 2015. That's 0.1% of sessions. This is not worth working on.
