### ISSUE TITLE
home page: map overlaps the red box for no projects

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#74]
On the home page, the map overlaps the red text box saying you have no projects

 _Imported from trac ticket [#74](http://trac.gpolab.bbn.com/proto-ch/ticket/74),  created by ahelsing on 06-04-2012 at 16:00, last modified: 06-08-2012 at 09:28_

**Comment by tcmitchell** [comment]
I was there, so I fixed it. I put the text inside a span with class instruction, which shrinks the red box to the size of the text instead of the width of the page.

_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2012 at 09:00_

**Comment by seledwards** [comment]
If the browser is narrow the outline of the box on the span overlaps itself in an ugly way.

_Trac comment by sedwards (github user: seledwards) on 06-07-2012 at 14:20_

**Comment by tcmitchell** [comment]
I tried various combinations of `span`, `p`, and `div` tags and found nothing better than what we have, but lots that are worse. Some quite a bit worse. What we've got displays poorly in a very narrow browser, or a combination of a magnified font and narrow window. But it displays nicely in most circumstances.

_Trac comment by tmitchel (github user: tcmitchell) on 06-08-2012 at 09:28_
