### ISSUE TITLE
Parse "mail" attribute properly

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#740]
The mail attribute can have multiple values. We've seen a single case of that so far. Find out what the format really is, and thus how to properly parse it.

 _Imported from trac ticket [#740](http://trac.gpolab.bbn.com/proto-ch/ticket/740),  created by tmitchel on 08-05-2013 at 17:11, last modified: 02-03-2015 at 10:15_

**Comment by tcmitchell** [comment]
Multiple values in attributes are separated by a semicolon, per the [Shibboleth documentation](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAddAttribute).

We should be parsing the "mail" attribute using a semicolon as a separator. But how to store and use multiple email addresses? That's an interesting question. It may simply mean storing the attribute as it arrives, similar to affiliation, and then parsing that when we need it, which is not too often. A standard routine could turn these multi-valued attributes into an array. When we need a single email address, as is the case for a certificate, we can choose the first one, When we send email, we could send to all asserted email addresses.

_Trac comment by tmitchel (github user: tcmitchell) on 08-06-2013 at 10:47_

**Comment by tcmitchell** [comment]
Another occurrence of this happened:
```
member_id: UUID
eppn: FLast@example.edu
first_name: First
last_name: Last
displayName: First Last
email_address: First.Last@example.eduFirstLast@example.edu
username: FOO
urn: urn:publicid:IDN+ch.geni.net+user+FOO
```

I fixed up the database entry to be "First.Last@example.edu".


_Trac comment by tmitchel (github user: tcmitchell) on 09-05-2013 at 18:09_

**Comment by ahelsing** [comment]
Replaced by chapi ticket 175

_Trac comment by ahelsing on 12-11-2013 at 09:53_

**Comment by tcmitchell** [comment]
Reopening because this one properly belongs in the portal because the clearinghouse doesn't and shouldn't know about Shibboleth.

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2015 at 10:43_

**Comment by tcmitchell** [comment]
The [InCommon Federation Attribute Summary](https://www.incommon.org/federation/attributesummary.html) lists which attributes can be multi-valued and which cannot. Most can have multiple values. 

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2015 at 10:44_

**Comment by tcmitchell** [comment]
The chapi ticket (http://trac.gpolab.bbn.com/chapi/ticket/175) has been closed.

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2015 at 10:46_

**Comment by tcmitchell** [comment]
The following files are possibly or likely related:
 * [do-register.php](browser:portal/www/portal/do-register.php)
 * [do-modify.php](browser:portal/www/portal/do-modify.php)
 * [error-text.php](browser:portal/www/portal/error-text.php)
 * [modify.php](browser:portal/www/portal/modify.php)


_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2015 at 10:53_

**Comment by tcmitchell** [comment]
The file error-text.php does not need updating or modification. It sends email, and is fine with the raw values including semi-colons.

The account modification files (modify.php, do-modify.php) require a bit of an overhaul, but it's for the better. It helps us towards two other open issues:
 * #299 "Remove "account" and "identity" tables"
 * #273 "Profile: Make modify real, request project lead"


_Trac comment by tmitchel (github user: tcmitchell) on 01-30-2015 at 17:25_

**Comment by tcmitchell** [comment]
This depends on http://trac.gpolab.bbn.com/chapi/ticket/346

Account modification has been overhauled. Task complete.

_Trac comment by tmitchel (github user: tcmitchell) on 02-03-2015 at 10:15_
