### ISSUE TITLE
clean up example admin address used in etc/settings.php

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#741]
The `etc/settings.php` file contains the e-mail address:
```
$portal_admin_email = 'portal-dev-admin@gpolab.bbn.com';
```
This should be an example address, rather than a BBN-centric one.

 _Imported from trac ticket [#741](http://trac.gpolab.bbn.com/proto-ch/ticket/741),  created by chaos on 08-05-2013 at 17:11, last modified: 08-05-2013 at 18:08_

**Comment by tcmitchell** [comment]
`settings.php` was obsolete. It has been removed. While there, the documentation in `example-settings.php` was improved.

_Trac comment by tmitchel (github user: tcmitchell) on 08-05-2013 at 18:08_
