### ISSUE TITLE
Revise handling of Google Analytics

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#742]
Currently, Google Analytics uses two variables (`$portal_enable_analytics` and `$portal_analytics_string`) in two settings files. This setup makes it difficult to quickly disable Google Analytics without going through a complete software update. To fix this:
 * Remove `$portal_enable_analytics` from `portal/www/portal/settings.php`.
 * Set up the values of `$portal_enable_analytics` and `$portal_analytics_string` in `/etc/geni-ch/settings.php` on a per-machine basis.
 * Revise `header.php` to check if `$portal_enable_analytics` exists. 
   * If it exists, include the relevant GA code.
   * If it doesn't exist, don't enable GA.

To disable Google Analytics when needed, just comment out the Analytics string line in `/etc/geni-ch/settings.php`.

 _Imported from trac ticket [#742](http://trac.gpolab.bbn.com/proto-ch/ticket/742),  created by bujcich on 08-06-2013 at 13:38, last modified: 09-10-2013 at 16:26_

**Comment by ahelsing** [comment]
Any reason not to just move `$portal_enable_analytics` to `/etc/geni-ch/settings.php`?  I don't see any big downside to having two variables in that file, and it seems like it would require less logic for y'all.

_Trac comment by chaos on 08-06-2013 at 13:40_

**Comment by ahelsing** [comment]
Good idea. I fixed the description to reflect this. We can do that since it would only require replacing a line or two of code in `header.php` to check whether `$portal_enable_analytics` is set.

_Trac comment by bujcich on 08-06-2013 at 13:51_

**Comment by ahelsing** [comment]
Fixed. I changed several things:
 1. Removed `$portal_enable_analytics` from the local `settings.php` file. That way there's no confusion about which variable enables it.
 1. Opened syseng ticket http://groups.geni.net/syseng/ticket/5328 to add `$portal_analytics_enable` to the configuration by Puppet.
 1. Changed references in `header.php` to refer to `$portal_analytics_enable`.
 1. Added a check in `header.php` to see if `$portal_analytics_enable` is set. I noticed during testing that it was giving me a lot of warnings about the variable not being set since it hadn't been added to `/etc/geni-ch/settings.php` yet. By default, the behavior will be to skip over the GA portion of code in `header.php` if nothing about GA has been set.

_Trac comment by bujcich on 09-01-2013 at 14:29_

**Comment by tcmitchell** [comment]
This isn't working with the config file update.

_Trac comment by tmitchel (github user: tcmitchell) on 09-10-2013 at 11:13_

**Comment by tcmitchell** [comment]
The `global` definition in `header.php` did not get updated.

_Trac comment by tmitchel (github user: tcmitchell) on 09-10-2013 at 11:13_

**Comment by tcmitchell** [comment]
Fixed.

_Trac comment by tmitchel (github user: tcmitchell) on 09-10-2013 at 16:26_
