### ISSUE TITLE
geni-pgch service does not start

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#746]
On a portal/CH node loaded with the latest develop code:
```
$ cat /etc/geni-ch/geni-ch-githash 
[fe596731a2897b7c23821e7f0b0e8693977f3f23](https://github.com/GENI-NSF/geni-portal/commit/fe596731a2897b7c23821e7f0b0e8693977f3f23)
```
the geni-pgch service fails at startup:
```
$ sudo /etc/init.d/geni-pgch start
 * Starting GENI Flack service  geni-pgch
   ...fail!
```
The log message contains the error:
```
Traceback (most recent call last):
  File "/usr/share/geni-ch/portal/gcf/src/gcf-pgch.py", line 45, in <module>
    from geni.pgch import PGClearinghouse
  File "/usr/share/geni-ch/portal/gcf-2.2.1/src/geni/pgch.py", line 39, in <module>
    from SecureThreadedXMLRPCServer import SecureThreadedXMLRPCRequestHandler
ImportError: No module named SecureThreadedXMLRPCServer
```

 _Imported from trac ticket [#746](http://trac.gpolab.bbn.com/proto-ch/ticket/746),  created by chaos on 08-07-2013 at 14:52, last modified: 08-07-2013 at 15:54_

**Comment by tcmitchell** [comment]
The version of gcf was switched from 2.2.1 to 2.2.1-threaded-ticket313. browser:prep-ch.sh still uses gcf-2.2.1, so that needs to be updated.

_Trac comment by tmitchel (github user: tcmitchell) on 08-07-2013 at 15:42_

**Comment by tcmitchell** [comment]
This fix has been committed.

_Trac comment by tmitchel (github user: tcmitchell) on 08-07-2013 at 15:54_
