### ISSUE TITLE
downloading omni-bundle in safari result in directory not zip file being downloaded

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#748]
Using Version 6.0.5 (7536.30.1) download my omni-bundle.zip and found that the zip file is automatically unzipped by the safari.

The user finds a "omni-bundle" directory rather than an omni-bundle.zip.  Also this will create a scenario that does not match our instructions which rely on the bundle being a zip file.

This is not a major problem, but I am capturing it so we have a record of this.

 _Imported from trac ticket [#748](http://trac.gpolab.bbn.com/proto-ch/ticket/748),  created by lnevers on 08-08-2013 at 13:44, last modified: 12-18-2013 at 13:01_
   CCing: nriga@..., vthomas@...

**Comment by ahelsing** [comment]
This is a safari configuration issue

_Trac comment by ahelsing on 12-18-2013 at 13:01_
