### ISSUE TITLE
allow re-download SSH private key

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#75]
Allow a user to re-download their generated SSH private key

 _Imported from trac ticket [#75](http://trac.gpolab.bbn.com/proto-ch/ticket/75),  created by ahelsing on 06-04-2012 at 16:01, last modified: 06-05-2012 at 11:26_

**Comment by tcmitchell** [comment]
Added a download button to the ssh key table for this purpose.

_Trac comment by tmitchel (github user: tcmitchell) on 06-05-2012 at 11:26_
