### ISSUE TITLE
On Chrome, the buttons look funny

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#750]
With the updated look and feel of the portal, when we increase the size of the page on Chrome, the shadows around the buttons don't also increase in size.  (That is Ben's description of the problem.)

 _Imported from trac ticket [#750](http://trac.gpolab.bbn.com/proto-ch/ticket/750),  created by sedwards on 08-08-2013 at 21:46, last modified: 08-12-2013 at 13:49_
   CCing: nriga@..., vthomas@...

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [Screen Shot 2013-08-08 at 9.45.37 PM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/750/Screen Shot 2013-08-08 at 9.45.37 PM.png) on 08-08-2013 at 21:47_

**Comment by ahelsing** [comment]
I was able to reproduce this on the Mac version of Chrome (using version 28.0.1500.95) but not on the Linux version. It appears that the shadow surrounding the button will scale but the button itself will not. It likely comes down to how the Mac version renders the `box-shadow` attribute and/or how it renders buttons. Both are things that we can't fix from our end.

_Trac comment by bujcich on 08-09-2013 at 09:58_

**Comment by ahelsing** [comment]
Closing as wontfix unless I can a solution for it.

_Trac comment by bujcich on 08-09-2013 at 13:20_
