### ISSUE TITLE
Reconcile the use of "omni-bundle"

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#752]
We are inconsistent about the use of the phrase "omni-bundle".

In particular: 
 * [Configure omni](https://portal.geni.net/secure/profile.php?project_id=&slice_id=&member_id=#omni) uses the phrase "customized configuration data" but does not use the phrase "omni bundle", but
 * [omni-bundle.php](https://portal.geni.net/secure/omni-bundle.php) refers to the "omni bundle" multiple times including in the header and the breadcrumb but does not use the phrase "customized configuration data"

In tutorials we've been refering to the omni bundle, but that phrasing doesn't appear on the top page but does on the second page.

We need to reconcile the two pages with each other and with tutorial usage.

 _Imported from trac ticket [#752](http://trac.gpolab.bbn.com/proto-ch/ticket/752),  created by sedwards on 08-08-2013 at 21:53, last modified: 07-15-2014 at 17:41_
   CCing: nriga@..., vthomas@...

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [Screen Shot 2013-09-20 at 8.12.25 PM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/752/Screen Shot 2013-09-20 at 8.12.25 PM.png) on 09-20-2013 at 20:16_

**Comment by seledwards** [comment]
Dramatically simplified the text on the omni-bundle page so that it didn't repeat what was on the Profile page.

A screenshot is attached. See #753 for screenshots of the Profile page.  

Both the Profile page and the omni-bundle page both say "omni configuration data" everywhere except one spot. I left the one reference to omni-bundle (on the Profile page it's a reference to the default place the file is downloaded to; on the omni-bundle.php page it's in the breadcrumb).  I think that's fine because I think folks will say "omni-bundle" when speaking because that is what the file itself is called.

Merging and closing.  Reopen if anyone has issues with this.

_Trac comment by sedwards (github user: seledwards) on 09-20-2013 at 20:20_

**Comment by seledwards** [comment]
Added a sentence on the omni-bundle page providing a link back to the instructions for configuring omni on the profile page.

Also, considering merging the content of the omni-bundle page into the omni configuration instructions on the profile page.  So reopening.

_Trac comment by sedwards (github user: seledwards) on 09-24-2013 at 10:58_

**Comment by ahelsing** [comment]
Sarah: What remains to do on this ticket?

_Trac comment by ahelsing on 07-15-2014 at 14:46_

**Comment by seledwards** [comment]
I think it's done. Closing.

_Trac comment by sedwards (github user: seledwards) on 07-15-2014 at 17:41_
