### ISSUE TITLE
Send email when a project is about to expire

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#754]
It would be nice to send email to a project when the project is going to expire.

 _Imported from trac ticket [#754](http://trac.gpolab.bbn.com/proto-ch/ticket/754),  created by sedwards on 08-08-2013 at 22:00, last modified: 04-08-2014 at 09:29_
   CCing: nriga@..., vthomas@...

**Comment by ahelsing** [comment]
Replaced by chapi ticket 264.

_Trac comment by ahelsing on 04-08-2014 at 09:29_
