### ISSUE TITLE
undefined HTTP_HOST in map-small.html

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#755]
From the nye logs:
```
[Sun Aug 11 18:19:34 2013] [error] [client 50.19.71.188] PHP Notice:  Undefined index: HTTP_HOST in /var/www/common/map/map-small.html on line 1
[Sun Aug 11 18:19:34 2013] [error] [client 50.19.71.188] PHP Notice:  Undefined index: HTTP_HOST in /var/www/common/map/map-small.html on line 69
```

 _Imported from trac ticket [#755](http://trac.gpolab.bbn.com/proto-ch/ticket/755),  created by ahelsing on 08-12-2013 at 11:15, last modified: 08-12-2013 at 12:33_

**Comment by tcmitchell** [comment]
Removed unnecessary reference to HTTP_HOST.

_Trac comment by tmitchel (github user: tcmitchell) on 08-12-2013 at 12:33_
