### ISSUE TITLE
Send an email to experimenter when they request a GPO IdP account

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#759]
When an experimenter requests a GPO IdP account, immediately send them an email acknowledging the receipt of the request and informing them that it might be a couple of business days for them to get a response.

```
To: <EXPERIMENTER EMAIL>
From: GENI Identity Provider <www-data@shib-idp.geni.net>
Subject: Your GENI IdP account request has been received

Dear <EXPERIMENTER NAME>,
We have received your request for an account at the GENI Identity
Provider.  We are processing your request and you should hear from us
in 3-4 business days.

If you have any questions about your account request or about using
GENI in general, please email help@geni.net.

Thank you for your interest in GENI!

Sincerely,

GENI Experimenter Support
help@geni.net
```

 _Imported from trac ticket [#759](http://trac.gpolab.bbn.com/proto-ch/ticket/759),  created by sedwards on 08-15-2013 at 16:03, last modified: 10-03-2013 at 17:26_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
I will come up with a draft email and add it to this ticket.

_Trac comment by sedwards (github user: seledwards) on 08-15-2013 at 16:05_

**Comment by seledwards** [comment]
Updated text.  Need to decide on what the From email should be.

_Trac comment by sedwards (github user: seledwards) on 08-19-2013 at 14:31_

**Comment by seledwards** [comment]
I discussed this with Chaos and we think this email should be from "GENI Identity Provider <www-data@shib-idp.geni.net>" (or the equivalent on development machines).

I think this means this ticket is ready to go back to the software group. Reassigning to Tom so he can find it a new owner.

_Trac comment by sedwards (github user: seledwards) on 08-22-2013 at 16:20_

**Comment by seledwards** [comment]
And fixing the linebreaks.

_Trac comment by sedwards (github user: seledwards) on 08-22-2013 at 16:22_

**Comment by ahelsing** [comment]
If there is a way to set the reply-to field, pl. set it to help@geni.net.  Thanks!

_Trac comment by vthomas on 08-22-2013 at 16:37_

**Comment by ahelsing** [comment]
This was fixed in the account request software. The account requests are no longer part of the portal software.

_Trac comment by phelinek on 10-03-2013 at 17:26_
