### ISSUE TITLE
after download SSH key, somehow show it is done

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#76]
Currently after you download your SSH private key, you get no visual indication that you've handled the SSH keys bit of the new user checklist.
Use javascript to rewrite the page? Have download be on a different page than the generation?

 _Imported from trac ticket [#76](http://trac.gpolab.bbn.com/proto-ch/ticket/76),  created by ahelsing on 06-04-2012 at 16:02, last modified: 06-05-2012 at 11:27_

**Comment by tcmitchell** [comment]
The ssh key generation page no longer handles download. Download is handled via a button on the ssh key table. This problem goes away with the arrival of the download button.

_Trac comment by tmitchel (github user: tcmitchell) on 06-05-2012 at 11:27_
