### ISSUE TITLE
Send an email to experimenter when they request to be a project lead

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#760]
When an experimenter requests to be a project lead, immediately send them an email acknowledging the receipt of the request and informing them that it might be a couple of business days for them to get a response.

```
To: <EXPERIMENTER EMAIL>
From: GENI Portal <www-data@portal.geni.net>
Subject: Your GENI Project Lead request has been received

Dear <EXPERIMENTER NAME>,

We have received your request to be a GENI Project Lead.  We are
processing your request and you should hear from us in 3-4 business
days.

If you have any questions about your request or about using GENI in
general, please email help@geni.net.

Thank you for your interest in GENI!

Sincerely,

GENI Experimenter Support
help@geni.net
```

 _Imported from trac ticket [#760](http://trac.gpolab.bbn.com/proto-ch/ticket/760),  created by sedwards on 08-15-2013 at 16:05, last modified: 09-11-2013 at 15:43_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
I will come up with a draft email and add it to this ticket.

_Trac comment by sedwards (github user: seledwards) on 08-15-2013 at 16:05_

**Comment by seledwards** [comment]
Updated text.  Need to decide on what the From email should be.

```
To: <EXPERIMENTER EMAIL>
From: portal-help@geni.net????
Subject: Your GENI Project Lead request has been received

Dear <EXPERIMENTER NAME>,

We have received your request to be a GENI Project Lead.  We are processing your request and you should hear from us in 3-4 business days.   

If you have any questions about your request or about using GENI in general, please email help@geni.net.

Thank you for your interest in GENI!

Sincerely,

GENI Experimenter Support
help@geni.net
```

_Trac comment by sedwards (github user: seledwards) on 08-19-2013 at 14:32_

**Comment by seledwards** [comment]
Discussed this with Chaos and we think the from should be "GENI Portal <www-data@portal.geni.net>".

_Trac comment by sedwards (github user: seledwards) on 08-22-2013 at 16:24_

**Comment by seledwards** [comment]
Experimenter group is done with this.  Reassigning to Tom to find it a home.

_Trac comment by sedwards (github user: seledwards) on 08-22-2013 at 16:25_

**Comment by ahelsing** [comment]
If there is a way to set the reply-to field, pl. set it to help@geni.net.  Thanks!

_Trac comment by vthomas on 08-22-2013 at 16:38_
