### ISSUE TITLE
Alphabetize RSpecs and label public and private RSpecs

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#761]
Make it easier to find specific RSpecs:
 * label the portions of the list that are public vs private
 * alphabetize the RSpecs by name in each of the public and private sections

 _Imported from trac ticket [#761](http://trac.gpolab.bbn.com/proto-ch/ticket/761),  created by sedwards on 08-15-2013 at 16:11, last modified: 09-24-2013 at 12:56_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
_ahelsing attached [Screen Shot 2013-09-24 at 10.12.59 AM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/761/Screen Shot 2013-09-24 at 10.12.59 AM.png) on 09-24-2013 at 10:13_

**Comment by ahelsing** [comment]
See #467

_Trac comment by ahelsing on 09-17-2013 at 17:07_

**Comment by ahelsing** [comment]
The list of public RSpecs seems to still not be alphabetical. Am I missing something?

Looking at the code in rspecs.php, it appears that public_rspecs is not being sorted

In addition, the dropdown of RSpec names on slice-add-resources.php should be sorted the same way.

To do this, we should fix db-util.php fetchRSpecMetaData to make each of the 2 queries do "order by name"

_Trac comment by ahelsing on 09-24-2013 at 10:20_

**Comment by ahelsing** [comment]
No, sorry, I guess I misunderstood the ticket. I divided the top list into private and public and alphabetized each of those.  I can easily alphabetize the bottom list also. And I didn't realize there was a second list on slice-add-resources.  I sorted the arrays, but I can do the sort inside the query if you think that's better.

_Trac comment by phelinek on 09-24-2013 at 10:34_

**Comment by ahelsing** [comment]
Now that I see the dropdown list of rspecs I think maybe I misunderstood the ticket even more.  Is that the part that is supposed to be divided into private and public, rather than subdividing the private rspecs into private and public?  

_Trac comment by phelinek on 09-24-2013 at 11:04_

**Comment by tcmitchell** [comment]
I think the goal is to have a single dropdown box on the slice-add-resources page, with a (non-selectable) marker for private RSpecs, then all the private RSpecs in alphabetical order, then a (non-selectable) marker for public RSpecs, then all the public RSpecs in alphabetical order.

_Trac comment by tmitchel (github user: tcmitchell) on 09-24-2013 at 11:12_

**Comment by ahelsing** [comment]
I just clarified with Sarah, and that's what she meant.  So I'll work on that.  Meanwhile, I've made three alphabetized lists on the Manage RSpecs page.  I can leave them like that, or back out that change.  Sarah didn't care because she doesn't think people use that page often.

_Trac comment by phelinek on 09-24-2013 at 11:25_

**Comment by tcmitchell** [comment]
I like the separation of RSpecs into 3 lists on rspecs.php (my private, my public, public). The last category, public, should be sorted alphabetically by name. It doesn't appear to be at present.

_Trac comment by tmitchel (github user: tcmitchell) on 09-24-2013 at 11:33_

**Comment by ahelsing** [comment]
Yes that was actually a cut and paste error.  Now the three lists are alphabetized.  

The drop-down list on the select resources page is now divided into private and public sections and alphabetized.

Note that names starting with capital letters appear in the sort first, then names starting with lower case letters.  If that's a problem can make the sort case-insensitive. I'm closing this, but if we want a case-insensitive sort I can re-open again.

_Trac comment by phelinek on 09-24-2013 at 11:51_

**Comment by ahelsing** [comment]
Could you please make this sort case-insensitive?  Thanks!

_Trac comment by vthomas on 09-24-2013 at 12:42_

**Comment by ahelsing** [comment]
The sort is now case-insensitive

_Trac comment by phelinek on 09-24-2013 at 12:56_
