### ISSUE TITLE
Would be nice if I could tell the portal where I had resources

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#762]
It's annoying even now (and unnecessary load on the aggregates) to poll 10 aggregates when I only have resources at 1 or 2 of them.  When there are 50 aggregates in that list it's going to be even worse.

It would be nice if I could ask for resource status at a given aggregate, or even just tell the portal where to look when I do slice-wide operations.

 _Imported from trac ticket [#762](http://trac.gpolab.bbn.com/proto-ch/ticket/762),  created by nick.bastin on 08-16-2013 at 04:07, last modified: 06-02-2014 at 16:07_

**Comment by tcmitchell** [comment]
You can ask for resource status at a given aggregate with the "Get Status" button that appears to the left of each aggregate on the slice page. There is currently no way to limit slice-wide operations to a set of aggregates.

_Trac comment by tmitchel (github user: tcmitchell) on 08-16-2013 at 08:58_

**Comment by ahelsing** [comment]
See ticket #339

_Trac comment by ahelsing on 08-16-2013 at 09:37_

**Comment by ahelsing** [comment]
This will be tied in with use of sliver_info and a re-org of the slice page.

_Trac comment by ahelsing on 04-08-2014 at 09:17_

**Comment by ahelsing** [comment]
I pushed a branch that has code that puts a variable of slice_ams on the slice.php page for Keith to integrate into the boxes.

_Trac comment by rrhain on 05-30-2014 at 13:40_
