### ISSUE TITLE
WiMAX: Support multiple wimax sites

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#773]
The WiMAX code currently hard-codes a single WiMAX site. Support multiple sites that can individually be enabled? Or always enable all? But then what happens if a new site comes on line?

 _Imported from trac ticket [#773](http://trac.gpolab.bbn.com/proto-ch/ticket/773),  created by ahelsing on 08-26-2013 at 13:33, last modified: 05-13-2015 at 10:33_

**Comment by ahelsing** [comment]
_ahelsing attached [witest-logo-white.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/773/witest-logo-white.png) on 10-24-2014 at 09:31_

**Comment by ahelsing** [comment]
Manu says multiple sites is post GEC18

_Trac comment by ahelsing on 09-23-2013 at 15:19_

**Comment by ahelsing** [comment]
Manu says that some time post GEC20, they will want to support multiple WiMAX sites. Each site will have its own LDAP database. So we need to create the wimax account individually at each site - and therefore probably support different usernames at each site. The project can be the same across all sites, or could be different. Whatever is easier.



_Trac comment by ahelsing on 05-12-2014 at 14:25_

**Comment by ahelsing** [comment]
At the GEC we suggested that all sites would use the same users and groups. But what if one gives an error?

_Trac comment by ahelsing on 06-24-2014 at 08:50_

**Comment by ahelsing** [comment]
Current design plan is that the portal talks only to Orbit. Orbit in turn talks to other sites.

However:
 - we want to show users links to all the other wimax sites
 - error messages should indicate if account creation failed at some wimax sites and which ones
 - sync function should indicate which sites the user has a wimax account at. We'll want to be able to show that


_Trac comment by ahelsing on 07-17-2014 at 16:11_

**Comment by ahelsing** [comment]
waiting on the Orbit folks to start building out their piece.

_Trac comment by ahelsing on 08-13-2014 at 13:17_

**Comment by ahelsing** [comment]
Multi site sync to Poly is working.

Manu says people have asked to have their own logos show up in the portal. Ivan says they can push to the portal in some way what sites to show.

We'll need to start gathering logos, etc.


_Trac comment by ahelsing on 10-22-2014 at 12:18_

**Comment by ahelsing** [comment]
For NYU Poly, use:
URL is http://witestlab.poly.edu
pretty name is WITest.
Icon is attached.


_Trac comment by ahelsing on 10-24-2014 at 09:30_

**Comment by ahelsing** [comment]
Formatting sites with a table, and adding WITest explicitly. 

_Trac comment by ahelsing on 11-05-2014 at 14:00_

**Comment by MarshallBrinn** [comment]
This is handled by fixes to #1392.
