### ISSUE TITLE
Update Map RSpec data for new RSpecs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#780]
Once we add the FOAM aggregates next week (assuming that happens) we should update the data used for the maps to reflect the new aggregates. And make sure the FOAM aggregates appear.

 _Imported from trac ticket [#780](http://trac.gpolab.bbn.com/proto-ch/ticket/780),  created by ahelsing on 08-30-2013 at 10:03, last modified: 09-05-2013 at 18:44_

**Comment by tcmitchell** [comment]
Files have been updated.

Additionally:
 * Update advertisement filenames to those generated by `omni.py -o listresources`
 * Install `map.php` so it is easy to run anywhere
 * Install advertisements to support `map.php`


_Trac comment by tmitchel (github user: tcmitchell) on 09-05-2013 at 18:43_
