### ISSUE TITLE
Portal allows re-uploading an existing Rspec name and description.

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#784]
In a scenario where an RSPec is uploaded with these characteristics:

 - Shortname: compute-ig-gatech
 - Description: Compute IG GATech

and the same operation is repeated later, there is no notification that the information is duplicate. This results in multiple entries with the same name and description.

Should the user be prevented from duplicating an RSpec name entry? 

Or, should there be a warning about re-using the "Shortname" and then allowing the user to choose to overwrite the previous RSpec?

Or should there be a warning about re-using the "Shortname" and then suggest that they delete the existing one or try a new name?

 _Imported from trac ticket [#784](http://trac.gpolab.bbn.com/proto-ch/ticket/784),  created by lnevers on 09-03-2013 at 16:32, last modified: 09-23-2014 at 12:33_

**Comment by ahelsing** [comment]
see `rspecupload.php` around line  161
```
    // Look at the supplied name and description. If those (both? either?) already exist, then refuse
    // Well, if the requested visibility is public, then if they exist anywhere, complain
    // If requested visibility is private, then if they exist as public or as private to this user, then complain
    // $name = $_POST["name"];
    // $description = $_POST["description"];
    // $visibility = $_POST["group1"];
```


_Trac comment by ahelsing on 09-11-2013 at 15:17_

**Comment by tcmitchell** [comment]
For private rspecs, the name must be unique for the given owner but can be the same as a public rspec or as a private rspec owned by another user. Public rspecs must have a unique name.

_Trac comment by tmitchel (github user: tcmitchell) on 09-15-2014 at 16:19_

**Comment by ahelsing** [comment]
Now you cannot edit the description of an RSpec. It appears to be in the same category and have the same name as an existing RSpec.

_Trac comment by ahelsing on 09-23-2014 at 12:05_

**Comment by tcmitchell** [comment]
Fixed. Use the rspec_id that is set when updating an rspec. Detect name conflicts with rspecs other than the one being updated.

_Trac comment by tmitchel (github user: tcmitchell) on 09-23-2014 at 12:33_
