### ISSUE TITLE
portal should allow user selection of aggregate where to execute  operations

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#785]
Current state: 17 aggregates are in portal (list will grow).

All delete, status an details operations are executed on all aggregates. User should be able to select a subset of aggregates where the commands should be run (as it is possible in Flack now).

The current approach also makes some scenarios more tedious. For example, if a 4 site OpenFlow experiment is created (4 foam aggregates slivers, 4 compute aggregate sliver and core slivers). User may want to delete sliver at one aggregate (may to request more nodes, or maybe because they decided not to use one of the aggregates).  Currently the only option is to delete all slivers and to have to recreate each of the slivers. 

In addition, this adds delay to the command responses in the portal interface, if user only cares about 4 aggregates, why have them wait for responses from 17 aggregate?

 _Imported from trac ticket [#785](http://trac.gpolab.bbn.com/proto-ch/ticket/785),  created by lnevers on 09-04-2013 at 09:50, last modified: 09-04-2013 at 10:48_

**Comment by ahelsing** [comment]
All operations can be done on a single aggregate - in the table of aggregates, just hit the relevant button in that row.

Beyond that, see tickets #166 and #339

_Trac comment by ahelsing on 09-04-2013 at 10:12_

**Comment by luisanevers** [comment]
Replying to [ahelsing](comment:1):
> All operations can be done on a single aggregate - in the table of aggregates, just hit the relevant button in that row.

What table of aggregates? The one in Flack?  


_Trac comment by lnevers (github user: luisanevers) on 09-04-2013 at 10:25_

**Comment by ahelsing** [comment]
The table on the slice page. Scroll down and there is a list of all the aggregates, with buttons for 'Add Resources', 'Get Status', 'Renew', 'Details', etc.

_Trac comment by ahelsing on 09-04-2013 at 10:37_

**Comment by luisanevers** [comment]
Thank you, I had been focusing on the top level pages and mostly on the "Slices" page.


_Trac comment by lnevers (github user: luisanevers) on 09-04-2013 at 10:48_
