### ISSUE TITLE
Portal does not always list all aggregates for operation results on all aggregates

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#786]
In a scenario where a slice has resources at 3 aggregates and a renew is issues for "slice & all resources" the results show:
```
Renewing Slice and Resources on: GPF-T1
Renewed slice until: 2013-09-11 00:00:00 UTC

Issued renew resources at 17 of 17 aggregate.
Renewed resources at:

    GPO InstaGENI
    GPO OpenFlow
    GPO InstaGENI OpenFlow

No resources renewed at:

    GPO ExoGENI
    ExoGENI ExoSM
    Northwestern InstaGENI OpenFlow
    Georgia Tech InstaGENI OpenFlow
    UtahDDC InstaGENI OpenFlow
```
In the output above only 5 aggregates are listed as not having resources, while there is actually 14 that do not have resources.
Should all be listed in this output?

The same occurs for a delete resource at all aggregates:
```
Deleting resources on slice: GPF-T1
Issued delete resources at 17 of 17 aggregate.

Deleted resources at:

    GPO InstaGENI
    GPO OpenFlow
    GPO InstaGENI OpenFlow

No resources deleted at:

    GPO ExoGENI
    ExoGENI ExoSM
    Georgia Tech InstaGENI OpenFlow
    UtahDDC InstaGENI OpenFlow
    Northwestern InstaGENI OpenFlow
```

 _Imported from trac ticket [#786](http://trac.gpolab.bbn.com/proto-ch/ticket/786),  created by lnevers on 09-04-2013 at 11:02, last modified: 09-04-2013 at 12:23_

**Comment by tcmitchell** [comment]
The aggregates that do not appear in the lists do not trust the staging clearinghouse. Communications cannot occur in this situation, hence the displayed behavior.

_Trac comment by tmitchel (github user: tcmitchell) on 09-04-2013 at 12:23_
