### ISSUE TITLE
There is no version information in the GENI portal

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#789]
Could not fine any version information in the portal. Version information should be added  

As I was looking as some tickets which describe expected resolution version, I could not tell how those versions related to the current portal version because there is no version in the portal.

 _Imported from trac ticket [#789](http://trac.gpolab.bbn.com/proto-ch/ticket/789),  created by lnevers on 09-09-2013 at 12:54, last modified: 09-12-2013 at 16:08_

**Comment by ahelsing** [comment]
It would make sense to put this in the footer

_Trac comment by ahelsing on 09-09-2013 at 13:46_

**Comment by ahelsing** [comment]
Fixed. I added a new variable `$portal_version` in `portal/www/portal/settings.php`. If it is set, it displays the version number in the footer. Otherwise, it defaults back to what the footer currently looks like on the production portal.

Should the updating of this variable be a step somewhere in the update process?

_Trac comment by bujcich on 09-12-2013 at 15:28_

**Comment by luisanevers** [comment]
Just took a pick and I think the font for the Portal version is somewhat small.  

All other information in the bottom banner is the same size font (plus some bold).  Why not make the portal version the same font size as the rest of the bottom banner?


_Trac comment by lnevers (github user: luisanevers) on 09-12-2013 at 15:48_

**Comment by ahelsing** [comment]
Sure. I'm also going to move it to the top of the footer.

_Trac comment by ahelsing on 09-12-2013 at 15:54_

**Comment by ahelsing** [comment]
Should that line ("GENI Portal Version...") also be bold to differentiate it from the copyright lines?

_Trac comment by bujcich on 09-12-2013 at 15:58_

**Comment by luisanevers** [comment]
Looks good without the bolding at the top of the footer. My opinion, :-)

_Trac comment by lnevers (github user: luisanevers) on 09-12-2013 at 16:01_

**Comment by ahelsing** [comment]
Now looking at it, I agree. Thanks!

_Trac comment by bujcich on 09-12-2013 at 16:08_
