### ISSUE TITLE
drop nicknames from omni_config

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#792]
Once people are using omni2.4 we should stop including nicknames in the generated omni_config files

 _Imported from trac ticket [#792](http://trac.gpolab.bbn.com/proto-ch/ticket/792),  created by ahelsing on 09-12-2013 at 14:16, last modified: 04-08-2014 at 09:39_

**Comment by innnkkki** [comment]
We should leave a few as examples. 

_Trac comment by nriga (github user: innnkkki) on 09-26-2013 at 17:38_

**Comment by ahelsing** [comment]
nicknames have gone away

_Trac comment by ahelsing on 04-08-2014 at 09:39_
