### ISSUE TITLE
GENI Portal has incorrect company name in copyright label

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-portal#793]
The GENI Portal has the following copyright label:

"Copyright © 2013 BBN Technologies"

The label should be:

 "Copyright © 2013 Raytheon BBN Technologies"

 _Imported from trac ticket [#793](http://trac.gpolab.bbn.com/proto-ch/ticket/793),  created by lnevers on 09-12-2013 at 15:55, last modified: 09-12-2013 at 16:07_

**Comment by ahelsing** [comment]
I originally modeled this off of http://www.geni.net -- should that be changed on there as well?

_Trac comment by bujcich on 09-12-2013 at 16:02_

**Comment by luisanevers** [comment]
Replying to [bujcich](comment:1):
> I originally modeled this off of http://www.geni.net -- should that be changed on there as well?

Probably historical, because site was set up before we were bought out by Raytheon. 

Both geni.net and portal.geni.net should use a Copyright statement should use the current company names.

_Trac comment by lnevers (github user: luisanevers) on 09-12-2013 at 16:07_
