### ISSUE TITLE
Make GENI username more visible

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#797]
Users are frequently confused about what username to use for sshing into nodes. Currently the GENI username matches what all but one existing AM use for their ssh logins (the one exception is PlanetLab).  So perhaps it would help users if we made their GENI username more prominent.

Two simple thoughts:
 (1) In the header change "Logged in as John Doe" to "Logged in as John Doe (jdoe)"
 (2) On the Profile page, make two changes:
     a) Make the "Account Summary" tab be the first (and default tab)
     b) Change "GENI Username" to be the first entry on the "Account Summary" table.

I'm happy to make this change if it would help.

 _Imported from trac ticket [#797](http://trac.gpolab.bbn.com/proto-ch/ticket/797),  created by sedwards on 09-16-2013 at 17:45, last modified: 09-24-2013 at 10:57_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Option 1, sure

Option 2a: Maybe. I want to be conservative in changing tab orders, big UI things. I think the argument at one point was that there is usually nothing you have to do here. The only reason to go there is to get your username, no? Does that merit putting it first? Are there other changes to ordering we want while we are here?

Option 2b: Maybe. Or maybe 3rd, just after email?



_Trac comment by ahelsing on 09-17-2013 at 09:26_

**Comment by seledwards** [comment]
Option 2b: I like moving username after email.  But if we do that I want to bring URN up to be after username as well.

_Trac comment by sedwards (github user: seledwards) on 09-20-2013 at 20:43_

**Comment by seledwards** [comment]
Option 1 and Option 2b are done and merged into develop.

Closing.

_Trac comment by sedwards (github user: seledwards) on 09-24-2013 at 10:57_
