### ISSUE TITLE
Sliver Status page: Omni output below table

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#80]
Move the Omni output text below the table of status output

 _Imported from trac ticket [#80](http://trac.gpolab.bbn.com/proto-ch/ticket/80),  created by ahelsing on 06-04-2012 at 16:06, last modified: 06-04-2012 at 22:22_

**Comment by seledwards** [comment]
Done.
Closing.

_Trac comment by sedwards (github user: seledwards) on 06-04-2012 at 22:22_
