### ISSUE TITLE
WiMAX: Support openid

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#809]
Provide our side of support for openid integration with WiMAX.

In particular, be sure to send the value of `wimax_username` in `ma_member_attribute` as the username under which the user is trying to log in to wimax.

 _Imported from trac ticket [#809](http://trac.gpolab.bbn.com/proto-ch/ticket/809),  created by ahelsing on 09-24-2013 at 12:16, last modified: 10-01-2013 at 12:41_

**Comment by tcmitchell** [comment]
Added wimax_username to OpenID AX with URI `http://geni.net/wimax/username`.

_Trac comment by tmitchel (github user: tcmitchell) on 10-01-2013 at 12:41_
