### ISSUE TITLE
Rspecs in user Profile

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#810]
Now that the user profile is nice and tabbed:-) I think there is no reason for a separate page since under that Rspec tab there is only one button 

 _Imported from trac ticket [#810](http://trac.gpolab.bbn.com/proto-ch/ticket/810),  created by nriga on 09-24-2013 at 15:37, last modified: 10-08-2013 at 13:43_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
The fix here is the make the rspecs div include a new tools-rspecs.php - which may be nearly exactly the current rspecs.php

So refactor rspecs.php to match that, and fix slice-add-resources.php to point to profile.php#rspecs which should be the rspecs tab - if we can do that


_Trac comment by ahelsing on 09-30-2013 at 08:42_

**Comment by ahelsing** [comment]
Renamed rspecs.php to tool-rspecs.php and removed the exit()
Changed references from rspecs.php to tool-rspecs.php
Removed button and extra header information from profile rspecs tab
For lockdown mode, doesn't display rspec list, just headers (used to gray out the button)


_Trac comment by phelinek on 10-04-2013 at 11:47_

**Comment by ahelsing** [comment]
Fixed an incorrect include statement, cleaned up extra include statements, added rspecs.php to get to tool-rspecs from slice-add-resources

_Trac comment by phelinek on 10-04-2013 at 15:29_
