### ISSUE TITLE
Alphabetize members in Project

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#811]
Violet R. Syrotiyk from ASU is teaching a class this semester and send us the following suggestion for the portal:
```
 It would be nice to be able to sort the members 
of my project (or just have them displayed in sorted 
order by surname by default). I want to only let people from my 
class in and so having it sorted would save me a linear search. 
```

 _Imported from trac ticket [#811](http://trac.gpolab.bbn.com/proto-ch/ticket/811),  created by nriga on 09-24-2013 at 15:41, last modified: 10-01-2013 at 15:39_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
probably also in slice

_Trac comment by ahelsing on 09-24-2013 at 15:53_

**Comment by ahelsing** [comment]
Alphabetized by lastname by role for both project and slice

_Trac comment by phelinek on 09-30-2013 at 10:39_
