### ISSUE TITLE
Rationalize the Profile tabs

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#812]
The tabs on the Profile page could use some rationalization.

Some suggestions:
 1) Rename "Other" tab to be called "Tools".
 2) Move "Authorize or De-authorize Tools" from the "Account Details" tab to the "Tools" tab
 3) Move "Modify user supplied accounts details" to "Account Summary"
 4) Remove the (now empty) "Account Details" tab
 5) "Account Summary" tab should include the user specified info (eg phone number) from the "Modify user supplied accounts details" button
 6) Change order of tabs to something like: Account Summary, SSH Keys, Configure omni, RSpecs, Tools, Outstanding Requests
 7) Add SSL cert creation/download button somewhere besides just in the body of the omni tab.  Perhaps this is it's own tab?  Perhaps it belongs linked from the Account Details tab? see #708
 8) Have the RSpec tab contain the contents of the RSpec management page instead of just being a link. See #810.

 _Imported from trac ticket [#812](http://trac.gpolab.bbn.com/proto-ch/ticket/812),  created by sedwards on 09-24-2013 at 15:50, last modified: 10-08-2013 at 13:43_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
1-6 are done.  In the case of #6, the telephone number is displayed only when present.  In most cases, it isn't present.  7 and 8 are covered in other tickets.

_Trac comment by phelinek on 10-03-2013 at 16:21_
