### ISSUE TITLE
Renew fails when exceeding max renew time of AM

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#814]
I am trying to renew my Utah IG VMs and I keep failing, probably because I ask for too long of a time, there is no suggestion as to what might succeed and the fact that it failed is not too obvious (maybe change the color to red)

 _Imported from trac ticket [#814](http://trac.gpolab.bbn.com/proto-ch/ticket/814),  created by nriga on 09-25-2013 at 11:55, last modified: 07-16-2014 at 14:28_

**Comment by innnkkki** [comment]
I just succeeded in renewing the sliver and I noticed that the difference between success and fail is very subtle. One says:
"Renewed resources at:" and the other "No resources renewed at:"
This can be easily missed. 

_Trac comment by nriga (github user: innnkkki) on 09-25-2013 at 12:04_

**Comment by ahelsing** [comment]
See #969 - is this OBE?

_Trac comment by ahelsing on 02-20-2014 at 14:05_
