### ISSUE TITLE
Modify listresources.php to have a link to a page which contains a single RSpec which is a raw unformatted XML file

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#82]
The page which shows rspecs (listresources.php) has a link to the raw rspec.  

Do two things:
 (1) Make the raw rspec page just be the raw xml file containing the rspec for a single aggregate
 (2) Adjust the format of listresources.php to have a separate button for each possible raw rspec.

 _Imported from trac ticket [#82](http://trac.gpolab.bbn.com/proto-ch/ticket/82),  created by sedwards on 06-05-2012 at 09:47, last modified: 04-07-2014 at 15:32_

**Comment by seledwards** [comment]
This will be easier if we do #81 first.

_Trac comment by sedwards (github user: seledwards) on 06-05-2012 at 09:48_

**Comment by ahelsing** [comment]
I think this is OBE

_Trac comment by ahelsing on 04-07-2014 at 15:32_
