### ISSUE TITLE
Add slice name instructions in the create slice page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#821]
We should have good practices for naming slices in the create slice page. 
We do have something similar for projects. 

 _Imported from trac ticket [#821](http://trac.gpolab.bbn.com/proto-ch/ticket/821),  created by nriga on 09-27-2013 at 15:28, last modified: 10-01-2013 at 15:40_

**Comment by ahelsing** [comment]
We should say:
"Use only alphanumeric plus hyphen (no leading hyphen), and at most 19 characters"

We should also note that slice names must be unique across the GENI Clearinghouse (note that this is an ugly fact of life because of PG....)


_Trac comment by ahelsing on 09-27-2013 at 16:44_
