### ISSUE TITLE
Make "Generate SSL cert" button open in a new tab

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#822]
It appears that the SSL cert generation page no longer opens in a new tab which means the "close" button doesn't work.

This means that if you generate your SSL cert that you can't get back to the main part of the portal.

To test:
 * SSL cert generation page opens in new tab
 * Close button on that new tab works

 _Imported from trac ticket [#822](http://trac.gpolab.bbn.com/proto-ch/ticket/822),  created by sedwards on 09-27-2013 at 16:29, last modified: 10-01-2013 at 13:19_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Issue is on tools-user.php where it has links to kmcert.php - it needs ` target="_blank"` inside the `<a>` tag. See line 314.

Since this is now a `<button>` element, the right fix may be to replace `window.location` with `window.open`


_Trac comment by ahelsing on 09-27-2013 at 16:40_

**Comment by ahelsing** [comment]
Not quite related but -- note that the changes in v2.2 also got rid of the link to download your cert, once you have generated it. Now the only way to do that is by going to the manual omni config instructions. That seems wrong.


_Trac comment by ahelsing on 09-30-2013 at 08:50_

**Comment by seledwards** [comment]
Agreed that seems wrong. Perhaps this belongs as part of #812 "Rationalize the Profile tabs".

Also sounds like we might be able to close #751 "Don't offer experimenters to 'download cert' immediately after creating their SSL cert" then?



_Trac comment by sedwards (github user: seledwards) on 09-30-2013 at 10:45_

**Comment by seledwards** [comment]
Done.  

_Trac comment by sedwards (github user: seledwards) on 09-30-2013 at 14:31_
