### ISSUE TITLE
Different details view for EG and IG

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#823]
The way that the multiple logins appear on the details page of the portal is different. 

In IG all the logins are lumped together in one cell, in EG each login is a separate row. 

I attach screenshots for both cases. The difference probably comes from the fact that login info comes from listresources in EG and sliverstatus in IG. I think these two should be consistent and I personally vote for the IG look: more compact, in EG it is hard to see the details of all your slice. 

 _Imported from trac ticket [#823](http://trac.gpolab.bbn.com/proto-ch/ticket/823),  created by nriga on 09-30-2013 at 09:55, last modified: 10-01-2013 at 15:40_
   CCing: gpo-expt-support@...

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [details-ig-login.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/823/details-ig-login.png) on 09-30-2013 at 09:55_

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [details-eg-login.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/823/details-eg-login.png) on 09-30-2013 at 09:55_

**Comment by ahelsing** [comment]
See print-text-helpers starting at line 186 - this is the version with a separate table row for each login. To fix this, it would have to simply track if it has printed any logins yet. If so, print `<br/>` and then the `<a>`.
See amstatus.js the function add_one_login starting at line 337. This is the version we like, and whose HTML we want to mimic.

Proposed new code for print-text-helpers.php:
```
    echo "</tr>\n";
    $hadLogins = False;
    foreach ($logins as $login) {
      $ssh_user = $login['username'];
      $ssh_host = $login['hostname'];
      $ssh_port = $login['port'];
      $ssh_url = "ssh://$ssh_user@$ssh_host";
      if ($ssh_port and $ssh_port != 22) {
        $ssh_url .= ":$ssh_port";
      }

      if (! $hadLogins) {
	$hadLogins = True;
	echo "<tr>\n";    
	echo "<th colspan='2'>Login</th>\n";
	echo "<td colspan='3' class='login' id='login_".$client_id."'>";
      } else {
	echo "<br/>\n";
      }
      echo "<a href='$ssh_url' target='_blank'>";
      echo "ssh ", $login['username'],"@",$login['hostname'];
      if ($ssh_port and $ssh_port != 22) {
	echo " -p ", $login['port'];
      }
      echo "</a>\n";
      if (!$manifestOnly){
      	 echo "<span class='status_msg'><i>Querying for more login information... </i></span>\n";      
      }
    } // end of loop over logins
    if ($hadLogins) {
      echo "</td>\n";
      echo "</tr>\n";
    }
```


_Trac comment by ahelsing on 09-30-2013 at 10:36_
