### ISSUE TITLE
Fix the ExoGENI sample rspecs

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#824]
Since ExoGENI added support for multiple users, the old EG images do not work. 
We should update the EG rspecs we have in the portal to either have the latest image:
http://geni.renci.org:12080/registry/images.jsp

Or just leave the image empty since now there is a default image for EG as well. 

 _Imported from trac ticket [#824](http://trac.gpolab.bbn.com/proto-ch/ticket/824),  created by nriga on 09-30-2013 at 10:21, last modified: 07-31-2014 at 13:06_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
I vote for not specifying an image if the expt does not require a certain version of OS.  In general, I think, the rspecs we publish should be as underspecified as possible.   

_Trac comment by vthomas on 09-30-2013 at 11:18_

**Comment by ahelsing** [comment]
And perhaps add comments in the rspec documents if there are assumptions such as "this assumes the default image is a Debian image".

_Trac comment by vthomas on 09-30-2013 at 11:31_

**Comment by tcmitchell** [comment]
Please upload new RSpecs for ExoGENI and we will delete the existing ones. Make sure when you upload them that they are public.

Let us know which RSpecs you want deleted, we would be happy to remove obsolete RSpecs.


_Trac comment by tmitchel (github user: tcmitchell) on 10-04-2013 at 10:25_

**Comment by seledwards** [comment]
I'm working on this as part of the great RSpec cleanup of June 2014.

I've uploaded an ExoSmall image.  I'm working on a raw PC and a intra-EG stitched rspec.

_Trac comment by sedwards (github user: seledwards) on 06-04-2014 at 17:42_

**Comment by seledwards** [comment]
I added an intra-EG stitched rspec.

Short name: 3 ExoSmall VMs, linear topology: GPO-FIU-RENCI (ExoSM only)	

Description: Use at ExoSM to get three ExoGENI VMs in a linear topology (GPO EG - FIU EG - RENCI EG). Size of VMs is ExoSmall. Link approx 100kbps.

_Trac comment by sedwards (github user: seledwards) on 06-04-2014 at 18:05_

**Comment by ahelsing** [comment]
Is this done?

_Trac comment by ahelsing on 07-15-2014 at 14:58_

**Comment by seledwards** [comment]
I still had one to fix but it couldn't be tested at the time.  I'll put it back on my to do list.

_Trac comment by sedwards (github user: seledwards) on 07-15-2014 at 17:42_

**Comment by seledwards** [comment]
I did the last EG Raw PC RSpec. Closing.

_Trac comment by sedwards (github user: seledwards) on 07-31-2014 at 13:06_
