### ISSUE TITLE
download ssl cert/key page redirect

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#84]
The Download SSL cert/key page leaves you on the same page when you are done.

Maybe redirect to another page to do the actual download?

 _Imported from trac ticket [#84](http://trac.gpolab.bbn.com/proto-ch/ticket/84),  created by ahelsing on 06-05-2012 at 12:53, last modified: 06-18-2012 at 15:21_

**Comment by tcmitchell** [comment]
SSL cert/key generation now redirects to profile page instead of downloading. There was already a download button on the ssl cert/key table, so use that for download. No more dead end.

_Trac comment by tmitchel (github user: tcmitchell) on 06-18-2012 at 15:21_
