### ISSUE TITLE
Add a way to determine how you created your SSL cert

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#840]
There are two different ways to generate an SSL cert for use with the portal (the difference being whether you did a CSR or the CH generated the cert/key for you).  However, once you've generated your cert, you can't easily tell how you generated it.

Add an indication to the profile page indicating how the cert was generated (basically whether or not it includes the private key).

Could say:
 * "Portal Generated" vs "Portal Signed"

 _Imported from trac ticket [#840](http://trac.gpolab.bbn.com/proto-ch/ticket/840),  created by sedwards on 10-04-2013 at 13:16, last modified: 12-11-2013 at 21:01_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
We can tell this by  whether the column private_key is null. If so, then this is "GENI Signed". If not (there is a private key) then this is "GENI Generated".

_Trac comment by ahelsing on 12-10-2013 at 13:26_
