### ISSUE TITLE
Download slice credential page and link

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#85]
Make the Download Slice Credential button say something about Omni and external tools.

Make the page itself let you download the credential, cert/key, omni_config, all in one

 _Imported from trac ticket [#85](http://trac.gpolab.bbn.com/proto-ch/ticket/85),  created by ahelsing on 06-05-2012 at 12:57, last modified: 11-27-2012 at 16:08_

**Comment by ahelsing** [comment]
I put Omni in the label on the slice page

_Trac comment by ahelsing on 06-07-2012 at 12:41_

**Comment by tcmitchell** [comment]
Deferring until after GEC 14.

Downloading the cert/key and omni_config are operations an experimenter would do once. Slice credentials, on the other hand, are slice specific, so you have to do that for each slice. I don't understand the idea of tying these together in a bundle. There's also currently no page for this. Does this ticket suggest a new page? Or just a link/button to get the bundle? I think it would be confusing to experimenters if they keep getting the same cert/key and omni_config over and over. This needs to be thought out more.

_Trac comment by tmitchel (github user: tcmitchell) on 06-18-2012 at 15:36_

**Comment by ahelsing** [comment]
downloading is currently broken. I disabled the button on the slice page


_Trac comment by ahelsing on 10-02-2012 at 16:17_

**Comment by seledwards** [comment]
Updated the omni_config generated by the current version of this page per #314.

_Trac comment by sedwards (github user: seledwards) on 11-09-2012 at 22:36_

**Comment by seledwards** [comment]
Remove "slice credential" button and replace with a "use omni" button.

_Trac comment by sedwards (github user: seledwards) on 11-27-2012 at 16:08_
