### ISSUE TITLE
Allow adding known people to projects/slices

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#86]
If I am a project/slice admin, then I can see members of that project/slice.
Given that, I should be able to add those people to a new project/slice directly, without having to first invite them.

 _Imported from trac ticket [#86](http://trac.gpolab.bbn.com/proto-ch/ticket/86),  created by ahelsing on 06-05-2012 at 13:03, last modified: 05-14-2013 at 17:05_

**Comment by ahelsing** [comment]
build a list of all members of projects or slices for which I am lead or admin.
Then provide a multi-select drop-down to add those people to the current project/slice from the project/slice page.
Email the people when they've been added


_Trac comment by ahelsing on 06-05-2012 at 13:04_

**Comment by seledwards** [comment]
Taken care of by bulk add #171.  Closing.

_Trac comment by sedwards (github user: seledwards) on 05-14-2013 at 17:05_
