### ISSUE TITLE
Allow to launch flack without a public key

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#860]
I tried to launch flack from a new account but I couldn't because I didn't have any SSH public key, I think after the warning the user should still have the option of launching flack with no SSH keys. 

 _Imported from trac ticket [#860](http://trac.gpolab.bbn.com/proto-ch/ticket/860),  created by nriga on 10-17-2013 at 18:19, last modified: 10-21-2013 at 12:22_
   CCing: gpo-expt-support@...

**Comment by tcmitchell** [comment]
Duplicate of issue #694.

_Trac comment by tmitchel (github user: tcmitchell) on 10-21-2013 at 12:22_
