### ISSUE TITLE
Change omni configuration instructions to say `omni` not `omni.py` etc

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#862]
The addition of a windows executable and a mac app mean that not everyone is running omni as `omni.py` anymore.  

We've updated the instructions for the UNIX version to tell people to include an alias for `omni` to `omni.py` (and the same for `omni-configure` etc)

We should update the instructions in the portal to say `omni`, `omni-configure` etc where relevant.

 _Imported from trac ticket [#862](http://trac.gpolab.bbn.com/proto-ch/ticket/862),  created by sedwards on 10-18-2013 at 18:16, last modified: 11-05-2013 at 15:26_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
see `tool-omniconfig` and `tools-user`

_Trac comment by ahelsing on 11-05-2013 at 14:45_
