### ISSUE TITLE
Go back to RSpecs tab after an rspec action

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#865]
Currently after I upload/delete an rspec i automatically get back to the main profile page, it makes more sense to go back to the rspecs page where I started this action from. 

 _Imported from trac ticket [#865](http://trac.gpolab.bbn.com/proto-ch/ticket/865),  created by nriga on 10-23-2013 at 01:34, last modified: 09-30-2014 at 16:40_

**Comment by seledwards** [comment]
It would be nice to see similar behavior for actions on other tabs (like the Omni Configuration tab).

_Trac comment by sedwards (github user: seledwards) on 10-23-2013 at 12:33_

**Comment by ahelsing** [comment]
I think this has been fixed.

_Trac comment by ahelsing on 09-30-2014 at 16:40_
