### ISSUE TITLE
Two public rspecs should not have the same short name

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#866]
I accidentally uploaded the same rspec twice with the exact same information. 

Probably the short description should be unique at least for public rspecs, and probably for the private rspecs of each user. 

I have to delete the second rspec since I have to share it with other people, but I took a snapshot, just in case there is a shuttle different that I can't see; look 4XenVMs-star-PubIP

 _Imported from trac ticket [#866](http://trac.gpolab.bbn.com/proto-ch/ticket/866),  created by nriga on 10-23-2013 at 01:39, last modified: 10-24-2013 at 09:49_

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [Screen Shot 2013-10-23 at 1.38.46 AM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/866/Screen Shot 2013-10-23 at 1.38.46 AM.png) on 10-23-2013 at 01:40_

**Comment by ahelsing** [comment]
See ticket #784

_Trac comment by ahelsing on 10-24-2013 at 09:49_
