### ISSUE TITLE
OBE: /etc/init.d/geni-pgch should set a umask

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#868]
The init script for geni-pgch does not set a umask.  As a result, things like the geni-pgch PID file (and possibly other things) are created world-writable.  A umask which simply prevents group and world write permissions should be sufficient, i.e. the init script could say, early on:
```
umask 022
```

 _Imported from trac ticket [#868](http://trac.gpolab.bbn.com/proto-ch/ticket/868),  created by chaos on 10-23-2013 at 10:49, last modified: 12-05-2013 at 13:21_

**Comment by tcmitchell** [comment]
Look at other init.d scripts on Ubuntu 10.04 and follow their lead.

_Trac comment by tmitchel (github user: tcmitchell) on 10-23-2013 at 16:43_
