### ISSUE TITLE
Revamp the "Modify Account page"

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#877]
In the modify account page, the request project lead checkbox should be accompanied by appropriate language so that it is clear what the responsibilities of a project lead are. 

 _Imported from trac ticket [#877](http://trac.gpolab.bbn.com/proto-ch/ticket/877),  created by nriga on 11-04-2013 at 15:47, last modified: 11-06-2013 at 08:45_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
The checkbox currently says 'Make me a project lead who can create projects.'

How about: 'Make me a project lead. I am a professor or senior technical staff (as indicated by my profile page supplied above). I want the ability to create projects, and I agree to take full responsibility for all GENI resource reservations by members of my projects, and understand what it means to be a project lead.' 


_Trac comment by ahelsing on 11-05-2013 at 15:13_

**Comment by ahelsing** [comment]
I have this wording queued up in a branch, waiting to apply. Anyone want to comment on the wording before I merge it in?

_Trac comment by ahelsing on 11-05-2013 at 16:07_

**Comment by seledwards** [comment]
I like the new improved wording.  

_Trac comment by sedwards (github user: seledwards) on 11-05-2013 at 16:11_

**Comment by ahelsing** [comment]
The wording is fine.   Question: By profile page supplied above, are we asking for a web page that lists them as faculty/staff?  Technical staff from many companies often don't have their own web pages or company pages listing them and their titles.


_Trac comment by vthomas on 11-05-2013 at 17:22_
