### ISSUE TITLE
CHAPI *_client code doesn't handle exceptions

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#883]
The chapidev client code (see chapi.php) assumes all returns are the GENI triple. This code does not handle connection problems, HTTP Error codes, XMLRPC error codes, etc.

Add logic to handle those cases and treat as errors, logging appropriately.

 _Imported from trac ticket [#883](http://trac.gpolab.bbn.com/proto-ch/ticket/883),  created by ahelsing on 11-12-2013 at 11:50, last modified: 12-05-2013 at 13:11_

**Comment by MarshallBrinn** [comment]
Fixed tested and checked in (git revision [a84476a06225425c593ec1640bc4e3a5f917b5aa](https://github.com/GENI-NSF/geni-portal/commit/a84476a06225425c593ec1640bc4e3a5f917b5aa)). 

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-21-2013 at 12:36_
