### ISSUE TITLE
Install ca-gpolab.crt in the service_registry

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#884]
In order for Flack to speak to the portal, we need to pass Flack the cert that signed the apache certs. This is located in:

/etc/ssl/certs/ca-gpolab.cert

A change should be made to the install_db script to insert this cert into the service_registry using a SQL expression like:

insert into service_registry (service_url, service_type, service_cert) values ('', 7, '/etc/ssl/certs/ca-gpolab.crt');

 _Imported from trac ticket [#884](http://trac.gpolab.bbn.com/proto-ch/ticket/884),  created by mbrinn on 11-13-2013 at 11:40, last modified: 12-05-2013 at 13:12_

**Comment by tcmitchell** [comment]
This will be done in chapi (see http://trac.gpolab.bbn.com/chapi/ticket/34).

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2013 at 11:47_
