### ISSUE TITLE
CHAPI result_handler should trim error string

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#889]
When the error string being passed to error-text.php is too long, the server refuses to show the page because the URL is too long.

Trim the error string so the full URL is < 2040 bytes

 _Imported from trac ticket [#889](http://trac.gpolab.bbn.com/proto-ch/ticket/889),  created by ahelsing on 11-14-2013 at 14:31, last modified: 12-05-2013 at 13:12_

**Comment by tcmitchell** [comment]
Trimmed to 1500. The trim length is a constant, so easily adjusted. 1500 chars should be plenty.

_Trac comment by tmitchel (github user: tcmitchell) on 11-21-2013 at 16:52_
