### ISSUE TITLE
newch: do-upload-project-members fails

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#900]
I tried to bulk upload project members.

portal_error log shows:

  [Wed Nov 27 06:37:26 2013] [error] [client 128.89.254.59] PHP Fatal error:  Call to undefined function put_message() in /usr/share/geni-ch/lib/php/pa_client.php on line 460, referer: https://portal-ah.gpolab.bbn.com/secure/upload-project-members.php?project_id=ab328cc1-4a4e-4b58-abe2-bbd9e08e6448

 _Imported from trac ticket [#900](http://trac.gpolab.bbn.com/proto-ch/ticket/900),  created by ahelsing on 11-27-2013 at 06:39, last modified: 12-05-2013 at 13:11_

**Comment by ahelsing** [comment]
See pa_client.php:
460:  $result = put_message($sa_url, $invite_member_message, 
472:  $result = put_message($sa_url, $accept_invitation_message, 
491:  $results = put_message($sa_url, $lookup_project_attributes_message, 


_Trac comment by ahelsing on 12-02-2013 at 12:07_

**Comment by MarshallBrinn** [comment]
Fixed - the invite_member/accept_invitation methods are supported in pa_client.php and in CHAPI. 

There is still an issue that the flow of invite member does not use this code (it is only joined in the bulk upload for members not in GENI). I think this is not correct and will open a separate proto-ch ticket about this.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-03-2013 at 08:51_
