### ISSUE TITLE
upload-project-members warning

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#901]
I did a bulk upload of project members, and got in the portal_error log:

  [Wed Nov 27 06:37:20 2013] [error] [client 128.89.254.59] PHP Notice:  Undefined index: ahelsing@geni.net in /usr/share/geni-ch/lib/php/ma_client.php on line 654, referer: https://portal-ah.gpolab.bbn.com/secure/upload-project-members.php?project_id=ab328cc1-4a4e-4b58-abe2-bbd9e08e6448

 _Imported from trac ticket [#901](http://trac.gpolab.bbn.com/proto-ch/ticket/901),  created by ahelsing on 11-27-2013 at 06:40, last modified: 12-05-2013 at 13:13_

**Comment by MarshallBrinn** [comment]
This is fixed and checked in.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-03-2013 at 10:57_
