### ISSUE TITLE
Certificate error in Flack from emulab.net

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#905]
Flack gets an error when it tries to call GetVersion at ProtoGENI Utah:

  Task encountered a fault: tlsError: Certificate keyUsage or basicConstraints conflict or indicate that the certificate is not a CA. If the certificate is the only one in the chain or isn't the first then the certificate must be a valid CA.

 _Imported from trac ticket [#905](http://trac.gpolab.bbn.com/proto-ch/ticket/905),  created by tmitchel on 12-02-2013 at 10:12, last modified: 12-02-2013 at 10:40_

**Comment by tcmitchell** [comment]
It looks like www.emulab.net got a new SSL server certificate last week. It is now signed by "InCommon Server CA", and no longer by Thawte. We'll need to update the service registry with the right intermediate CA so that Flack will trust the new www.emulab.net SSL server certificate.

_Trac comment by tmitchel (github user: tcmitchell) on 12-02-2013 at 10:19_

**Comment by ahelsing** [comment]
I'm curious if this is something that monitoring could have detected by having one of the AM API type checks do the same call that flack uses.  Is this more like "run `omni SomeCommand` to reproduce the same effect" or more like a complicated setup that only exists in the specific case of flack via the CH?

_Trac comment by chaos on 12-02-2013 at 10:23_

**Comment by tcmitchell** [comment]
* I added the InCommon Server CA to the set of SR certificates
 * I updated browser:sr/Makefile.am to remove the old intermediate CA and add the new one
 * I updated browser:bin/add_utah_am with the new intermediate CA
 * I manually update the service registry table to point to the new intermediate CA
 * I manually removed the old intermediate CA from nye

Flack can speak to emulab.net again.


_Trac comment by tmitchel (github user: tcmitchell) on 12-02-2013 at 10:40_

**Comment by tcmitchell** [comment]
Replying to [chaos](comment:2):
> I'm curious if this is something that monitoring could have detected by having one of the AM API type checks do the same call that flack uses.  Is this more like "run `omni SomeCommand` to reproduce the same effect" or more like a complicated setup that only exists in the specific case of flack via the CH?

This is specific to Flack.


_Trac comment by tmitchel (github user: tcmitchell) on 12-02-2013 at 10:40_
