### ISSUE TITLE
Invite/Accept/Join project membership flow confusing

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#908]
We have several different mechanisms for inviting people to join project. I can ask to join a project, you can ask me to join my project, I can 'bulk upload' project members which automatically add people (if they are known in GENI) or uses the invite_member/accept_invitation mechanism.

We have two different tables and sets of methods; PA_PROJECT_MEMBER_INVITATION and PA_PROJECT_MEMBER_REQUEST and it isn't clear which flow and circumstance uses which. I think this needs a redesign for clarity.

 _Imported from trac ticket [#908](http://trac.gpolab.bbn.com/proto-ch/ticket/908),  created by mbrinn on 12-03-2013 at 08:55, last modified: 07-15-2014 at 15:03_

**Comment by ahelsing** [comment]
no one is complaining

_Trac comment by ahelsing on 07-15-2014 at 15:03_
