### ISSUE TITLE
Rename SSH key delete

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#91]
Delete on the table of SSH keys looks prominent and common.
Rename it? Somehow indicate it is rare.

Additionally, add a confirmation before deleting an ssh key, and explain on that page what it means to delete an ssh key from the system.

 _Imported from trac ticket [#91](http://trac.gpolab.bbn.com/proto-ch/ticket/91),  created by ahelsing on 06-05-2012 at 13:52, last modified: 06-13-2012 at 18:25_

**Comment by tcmitchell** [comment]
I added a confirm dialog before deleting.

This ticket probably points toward an edit page that allows changing the name and description, and allows deleting (with a confirmation).

_Trac comment by tmitchel (github user: tcmitchell) on 06-08-2012 at 16:18_

**Comment by tcmitchell** [comment]
Added an edit page for ssh keys. Delete button is on that page instead of on the profile page.

_Trac comment by tmitchel (github user: tcmitchell) on 06-13-2012 at 18:25_
