### ISSUE TITLE
optimize CH queries

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#912]
Look for ways to optimize CH API invocations for performance
 - look for cases where the portal does not want expired projects/slices, but is retrieving them
 - look for cases where the portal wants only 3 columns but retrieves 10

 _Imported from trac ticket [#912](http://trac.gpolab.bbn.com/proto-ch/ticket/912),  created by ahelsing on 12-05-2013 at 08:34, last modified: 01-13-2014 at 15:56_

**Comment by ahelsing** [comment]
focus on user, header, tool-lookupids,
  tool-breadcrumbs, home, slice, amclient,
  tool-slices, tool-projects
  Or look at the lookup_public/private/identifying, sr_client,
  lookup_slices, lookup_projects (anything doing a list)

_Trac comment by ahelsing on 12-12-2013 at 09:21_

**Comment by MarshallBrinn** [comment]
I've done a fair amount of optimizing there, adding some custom CHAPI calls and eliminating or consolidating redundant calls. I think we're down to a  pretty reasonable level. The number of CHAPI calls for normal operations is considerably smaller and the times (admittedly standalone) are reduced by about half.

The changes are in the proto-ch branch tkt912_perforrmance and the chap branch tkt132_performance

We should check these out and test them when we reconvene after New years.

- Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-19-2013 at 13:59_
