### ISSUE TITLE
error-text should have a mailto link for help

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#921]
The error-text page should have a link "Need help? Report a problem?" or something like that. This can pop up a mailto link (not a web page in case the problem is really bad).

This email should be pre populated with
 * Datetime
 * email
 * eppn
 * error text
 * http_referer or other indication of where they came from
 * A prompt for the user to say what they were trying to do, and what problem they are having or question they have

 _Imported from trac ticket [#921](http://trac.gpolab.bbn.com/proto-ch/ticket/921),  created by ahelsing on 12-08-2013 at 06:50, last modified: 02-11-2014 at 11:52_

**Comment by tcmitchell** [comment]
browser:portal/www/portal/error-text.php does not currently have the user information, but it can in many circumstances. The mailto link will need to be conditionalized to populate the user info if it is available, omitting it if not.

There are two calls to `show_header`. The one with the third argument of zero is the case where user information is not available. The other case has access to user information (`show_header` called with just 2 arguments). So in that block (the else block), it is safe to add a call to `geni_loadUser`:
```
$user = geni_loadUser();
```

From there you can get the user's email and eppn.

If no user info is available (if you're in the 3 argument part of the `if`) don't include the user's info, but include as much as possible of the other information.

_Trac comment by tmitchel (github user: tcmitchell) on 01-28-2014 at 10:40_

**Comment by ahelsing** [comment]
added mailto link, resulting email looks like this:

2014-02-04 18:58
Project Name may not contain spaces.
HTTP REFERER: https://portal-ph.gpolab.bbn.com/secure/edit-project.php

User email: phelinek@bbn.com
User eppn: phelinek@gpolab.bbn.com

User questions or comments (please add):

_Trac comment by phelinek on 02-04-2014 at 14:03_
