### ISSUE TITLE
Change omni bundle to be called `omni.bundle`

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#929]
Some users and browser have trouble with the zip extension on the omni bundle.  Change the bundle to be called `omni.bundle` instead.

[matching gcf ticket](http://trac.gpolab.bbn.com/gcf/ticket/454)

 _Imported from trac ticket [#929](http://trac.gpolab.bbn.com/proto-ch/ticket/929),  created by sedwards on 12-11-2013 at 11:58, last modified: 06-03-2014 at 11:45_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Note that this cannot be done until a GCF release with the fix to that GCF ticket.

_Trac comment by ahelsing on 12-11-2013 at 12:05_

**Comment by seledwards** [comment]
gcf 2.5.3 fixes the dependency for this ticket.

_Trac comment by sedwards (github user: seledwards) on 05-29-2014 at 16:42_

**Comment by seledwards** [comment]
Added a pull down menu to select the version of omni you are using.

_Trac comment by sedwards (github user: seledwards) on 06-02-2014 at 16:06_

**Comment by seledwards** [comment]
Also made some minor changes to wording.  Closing.

_Trac comment by sedwards (github user: seledwards) on 06-02-2014 at 16:57_
