### ISSUE TITLE
Pass irods username and zone in Labwiki OpenID payload

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#937]
Currently Labwiki uses the GENI portal username to derive the iRODS username.
This does not work in all cases.  We should have been getting the username and
zone from the Portal in the OpenID payload.  Could we get these items added
to the payload?

If the user does not yet have an iRODS account created via the portal, these can
be left out of the payload and Labwiki will detect and handle this appropriately.

If possible, it would be great to have this additional feature sometime in January.

 _Imported from trac ticket [#937](http://trac.gpolab.bbn.com/proto-ch/ticket/937),  created by johren on 12-12-2013 at 20:03, last modified: 01-03-2014 at 16:15_

**Comment by tcmitchell** [comment]
The iRODS zone is available in browser:lib/php/irods_utils.php. The iRODS username is available as a member attribute. Send these via OpenID Attribute Exchange.

_Trac comment by tmitchel (github user: tcmitchell) on 01-03-2014 at 14:58_

**Comment by tcmitchell** [comment]
The iRODS zone and username are returned via OpenID Attribute Exchange.
 * To receive iRODS username ask for http://geni.net/irods/username
 * To receive iRODS zone ask for http://geni.net/irods/zone


_Trac comment by tmitchel (github user: tcmitchell) on 01-03-2014 at 16:15_
