### ISSUE TITLE
incommon error redirect should do portal logout

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#939]
When we get insufficient attributes from an identity provider, also log the user out from the portal - so they have an opportunity to select a different identity provider that might work better

 _Imported from trac ticket [#939](http://trac.gpolab.bbn.com/proto-ch/ticket/939),  created by ahelsing on 12-13-2013 at 09:30, last modified: 01-31-2014 at 11:24_

**Comment by tcmitchell** [comment]
The redirect through our logout handler on insufficient attributes seems to redirect to the identity provider logout page if the identity provider has a SingleLogoutService configured. For these cases the identity may not honor the "return" parameter and the user does not get notified that they have insufficient attributes for access to the portal. One university notified us that when they try to access the portal they get redirected to their logout page. They didn't know that they weren't properly releasing attributes to the portal.

Remove this fix and always redirect to the federated error handler. Experimenters who want to try a different identity provider will have to manually logout from their identity provider.

_Trac comment by tmitchel (github user: tcmitchell) on 01-30-2014 at 10:32_

**Comment by tcmitchell** [comment]
The logout code has been undone. Insufficient attributes causes a redirect to the InCommon federated error handling service without any other cleanup. Clearing the PHP session does nothing useful in this case so it is not done. This update will give all users with insufficient attributes positive notification of the problem via the InCommon service.

_Trac comment by tmitchel (github user: tcmitchell) on 01-31-2014 at 11:24_
