### ISSUE TITLE
Can't renew slice to max allowed time

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#946]
I'm trying to renew this slice: 	`urn:publicid:IDN+ch.geni.net:tutorial+slice+monitor`

The portal let's me attempt to renew it to July 11, 2014, but when I try, I get an error:
`[SERVER] SERVER_ERROR (global name 'user_email' is not defined)`

I am able to renew until May 31, 2014, but all of the dates I tried in June and July gave me the above error.

If it matters, this slice is a slice I've had a long time.

 _Imported from trac ticket [#946](http://trac.gpolab.bbn.com/proto-ch/ticket/946),  created by sedwards on 01-07-2014 at 11:19, last modified: 01-07-2014 at 11:32_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
See http://trac.gpolab.bbn.com/chapi/ticket/201

Is this critical to fix now?

_Trac comment by ahelsing on 01-07-2014 at 11:29_

**Comment by seledwards** [comment]
Nope.  Just reporting it while I noticed it.

_Trac comment by sedwards (github user: seledwards) on 01-07-2014 at 11:32_
