### ISSUE TITLE
Slice and project expiration times

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#953]
When trying to renew a slice, I run into a problem where the portal wouldn't let me renew my slice up to the project expiration date (see attached file). 

 * OS Version: Mac OS X 10.7.5
 * Browser: Chrome Version 31.0.1650.63

Also I noticed the the default project and slice expiration do not match, i.e. the project is at 00:00:00 on the date while the slice is on 23:59:59. It would be nice if those two match and if you are changing them it would be nice if the are made equal to the latest time for that data (i think this should be 23:59:59 SST, but I might be wrong) so that there is no surprise when things expires

 _Imported from trac ticket [#953](http://trac.gpolab.bbn.com/proto-ch/ticket/953),  created by nriga on 01-14-2014 at 10:56, last modified: 01-15-2014 at 10:10_

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [Screen Shot 2014-01-13 at 7.29.04 PM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/953/Screen Shot 2014-01-13 at 7.29.04 PM.png) on 01-14-2014 at 10:56_

**Comment by ahelsing** [comment]
I can see how the javascript on the slice page might do the wrong thing. Actually I can't be sure why it always works for me.

It is already true that if you don't specify a time in your new slice expiration and there is a project expiration and your new slice expiration is the same day, then the slice should be expiring at the same time. I will change projects to expire at the end of the day if you don't specify.


_Trac comment by ahelsing on 01-14-2014 at 16:51_
