### ISSUE TITLE
Update flack.php to use new loading mechanism

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#955]
Flack can now be loaded with a new mechanism that will allow easier testing of development releases. Update flack.php accordingly.

 _Imported from trac ticket [#955](http://trac.gpolab.bbn.com/proto-ch/ticket/955),  created by tmitchel on 01-14-2014 at 17:07, last modified: 01-16-2014 at 16:18_

**Comment by tcmitchell** [comment]
_tmitchel (tcmitchell) attached [flackportal-sample.html](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/955/flackportal-sample.html) on 01-14-2014 at 17:08_

**Comment by tcmitchell** [comment]
Description of desired changes (from email thread):

** GET Parameters **

First of all, the place where Flack and the js code is fetched is determined by a 'source' GET parameter. And portal mode is enabled by a 'portal' GET parameter. The source defaults to the stable tree and the portal defaults to off.

Possible sources are:

'local' -- fetches from http://localhost:8080
'devel' -- fetches from http://www.emulab.net/protogeni/flack-devel/
'stable' -- fetches from http://www.emulab.net/protogeni/flack-stable/
'none' -- fetches from the current directory (uses relative names).

When testing a new version of Flack, say, you will want to use:

flack.html?portal=1&source=devel

Otherwise you will probably want to leave it off to default to stable:

flack.html?portal=1


** HTML File Generation **

Now let's look inside the flackportal-sample.html. You will notice that this is a much simpler file because all of the code has been pulled out into its own JS file. When generating it, you will fill in your parameters by putting them in the given script tags using PHP.

Since the certificates are placed directly inside of plaintext script tags, you no longer need to escape carriage returns at the end of them.

You also do not need to urlencode the URNs/URLs that are parameters (though there should be no extra spaces inside those <script> tags).


** Deployment **

You have several options for deployment. At the very least, you need to host your own flack.css which you can get from:

https://www.emulab.net/protogeni/flack-stable/flack.css

And you will also need to generate an appropriate html source file yourself. If you just want to use the flack-stable version by default, this is all you need to do.

On the other hand, if you want to have full control over everything, you can host it all yourself and use 'source=none' by default. You might want to do this on a development server if you are testing things yourself. But some sites, like ARL, might want to do this in production. ARL will need to go one step further and host their own loader.js as well, of course.


** Stable vs. Devel **

Whenever I push an update to Flack from now on, I will first deploy it up to the devel tree. We can test it on development servers and also in place on the flack portal by adding a 'source=devel' parameter by hand to the Portal or Desktop URL.

When we are confident that the new patch should be released, probably a few days later, I will deploy it to the stable tree. Now ordinary users will start seeing it.

There will only ever be two variations of the code running at a time, the one running on devel and the one running on stable.


** Conclusion **

Please let me know if you have any issues integrating this or other questions or concerns.

_Trac comment by tmitchel (github user: tcmitchell) on 01-14-2014 at 17:13_

**Comment by ahelsing** [comment]
By my read:
 - The new loading stuff does look simpler
 - We must be careful: no carriage returns in certs
 - Also, no urlencoding of URL/URNs
 - We need to host our own flack.css
 - We'll have to generate the new HTML
 - make flack.php take a "source" param so you can readily switch to devel
 - We'll want to somehow allow a local loader.js readily
  - that is, an arg to the php that causes a change to use a different loader.js, so supporting ARL is easier
 - Our flack.php takes a GET of the source and in turn generates a flack.html with GET of ?portal=1&source=stable or some such. Is that flack.php doing a relative redirect?


_Trac comment by ahelsing on 01-15-2014 at 09:26_

**Comment by ahelsing** [comment]
Jon says:
```
To run in portal mode you pass a 'portal=1' GET parameter. If you want to set it in code, you can add a <script>isPortal=1;</script> tag after the inclusion of loader.js
```
That seems like something we might want to do from the portal, since it will just break if you try anything else I think.

_Trac comment by ahelsing on 01-16-2014 at 11:35_

**Comment by tcmitchell** [comment]
Additional info about the portal variable from Jon:

 To run in portal mode you pass a 'portal=1' GET parameter. If you want to set it in code, you can add a <script>isPortal=1;</script> tag after the inclusion of loader.js.

_Trac comment by tmitchel (github user: tcmitchell) on 01-16-2014 at 11:42_

**Comment by tcmitchell** [comment]
The `source` parameter does not seem to be working. Hussam reports the same problem. I posted a sample page on nye (`flacknew.php`) so that Jon can test within the portal environment.

_Trac comment by tmitchel (github user: tcmitchell) on 01-16-2014 at 13:28_

**Comment by tcmitchell** [comment]
Jon fixed the problem, and a couple others, and it's working now.

A bunch of files get deleted with this change, so there is a manual step of removing those from the installed directory. These are documented on the ticket for the next upgrade.

The new flack page is available at https://portal.geni.net/secure/flacknew.php until the next portal upgrade. That will allow Jon and/or the experimenter support group to test a new version of Flack before the next portal upgrade. This file will be deleted at the next portal upgrade.

_Trac comment by tmitchel (github user: tcmitchell) on 01-16-2014 at 16:18_
