### ISSUE TITLE
RSpecs: allow paste from file

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#956]
Allow pasting the RSpec to use for an allocation into the browser.

This would be a textarea of some kind. It would appear on the Add Resources page AND on the page for uploading a new RSpec.

In particular, on the Add Resources page it might not be actually saved to the DB.

 _Imported from trac ticket [#956](http://trac.gpolab.bbn.com/proto-ch/ticket/956),  created by ahelsing on 01-15-2014 at 09:52, last modified: 02-07-2014 at 12:29_

**Comment by MarshallBrinn** [comment]
Rather than allowing pasting from the browser, we have added a feature to import an RSpec file from your local disk. See #957.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-07-2014 at 12:29_
