### ISSUE TITLE
RSpecs: Allow anonymous rspecs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#957]
Allow experimenters to specify an RSpec without explicitly putting it in the DB. For example, when an experimenter is developing their RSpec they may go through multiple iterations. Having to upload the RSpec, then delete it when it doesn't work, seems a pain.

Ideally on the Add Resources page you could specify an RSpec from a local file or by pasting into a browser window (see ticket #956), and that RSpec would be used for the allocation. To implement this, we might under the covers put the RSpec in the DB. But if we do, it should be easy to update that RSpec in place or replace it, etc. Or maybe it is removed from the DB when we are done.

 _Imported from trac ticket [#957](http://trac.gpolab.bbn.com/proto-ch/ticket/957),  created by ahelsing on 01-15-2014 at 09:55, last modified: 02-11-2014 at 11:53_
   CCing: gpo-expt-support@...

**Comment by MarshallBrinn** [comment]
Added a new option to "Add Resources" to allow for taking an rspec from the local disk and using it for a single reservation (no uploading into the portal database). Tested, demo-ed to Niky and checked in.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-07-2014 at 12:30_
