### ISSUE TITLE
Shorten slice expiration

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#96]
Slices appear to be getting a 30 day expiration. Make that:
 * configurable, and
 * shorter

 _Imported from trac ticket [#96](http://trac.gpolab.bbn.com/proto-ch/ticket/96),  created by ahelsing on 06-05-2012 at 14:02, last modified: 06-08-2012 at 11:12_

**Comment by tcmitchell** [comment]
Added $sa_default_slice_expiration_hours to sa_settings.php, and used it in sa_controller. Units are hours as the name suggests. Current setting is 8.

_Trac comment by tmitchel (github user: tcmitchell) on 06-08-2012 at 11:12_
