### ISSUE TITLE
map html files should use SERVER_NAME, not HTTP_HOST

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#962]
The various map.html files should use SERVER_NAME and not HTTP_HOST to find the name of the server for constructing URLs. SERVER_NAME is more reliably present.

Fix at these spots:
```
./portal/www/common/map/1080display/map-big.html:1:<script type="text/javascript" src=<?php echo '"https://'; echo $_SERVER['HTTP_HOST']; echo "/common/map/OpenLayers-2.13/OpenLayers.js\"";?>></script>
./portal/www/common/map/1080display/map-big.html:69:          url: <?php echo '"https://'; echo $_SERVER['HTTP_HOST']; echo "/common/map/current.json\""; ?>,
./portal/www/common/map/map-small.html:71:          url: <?php echo '"https://'; echo $_SERVER['HTTP_HOST']; echo "/common/map/current.json\""; ?>,
./portal/www/portal/map.html:1:<script type="text/javascript" src=<?php echo '"https://'; echo $_SERVER['HTTP_HOST']; echo "/common/map/OpenLayers-2.13/OpenLayers.js\"";?>></script>
./portal/www/portal/map.html:70:          url: <?php echo '"https://'; echo $_SERVER['HTTP_HOST']; echo "/common/map/current.json\""; ?>,
```

Change HTTP_HOST to SERVER_NAME

 _Imported from trac ticket [#962](http://trac.gpolab.bbn.com/proto-ch/ticket/962),  created by ahelsing on 01-22-2014 at 10:33, last modified: 01-27-2014 at 11:52_

**Comment by tcmitchell** [comment]
Instead of HTTP_HOST or SERVER_NAME these could all be relative URLs eliminating the need for either variable.

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2014 at 11:52_
