### ISSUE TITLE
add operator helper scripts

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#964]
There are a number of helper scripts that would be useful. Several times now I've been asked to provide an email address for an experimenter based on logs at the SCS or an aggregate. And now there's an example of an aggregate seeing a sliver behaving badly. We have a slice HRN and Rob also found a user email address. We want the user's name, but also other people on the slice who could shut down the badly behaving resources.

Some useful scripts would be:

 - given an email address, get the member username and name
 - given a username, get the member email address and name
 - given a slice urn, get the slice lead (name&email) and admins, and the project lead
 - given a username, get the non-expired slices and projects they are a member of (noting if they are the lead of any of the slices/projects)

 _Imported from trac ticket [#964](http://trac.gpolab.bbn.com/proto-ch/ticket/964),  created by ahelsing on 01-28-2014 at 13:39, last modified: 03-31-2015 at 10:19_

**Comment by ahelsing** [comment]
omni listslicemembers and listslices and listprojects covers some of these. Note the first two.

_Trac comment by ahelsing on 09-30-2014 at 16:38_

**Comment by MarshallBrinn** [comment]
This will be handled by Charlie's new admin page.

**Comment by ahelsing** [comment]
Charlie's admin page lets you do those searches.
