### ISSUE TITLE
New account registration does not honor maintenance outage

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#965]
A new user can register during a maintenance outage. After registration they get cut off because of the maintenance outage. New user registration should honor the maintenance outage.

 _Imported from trac ticket [#965](http://trac.gpolab.bbn.com/proto-ch/ticket/965),  created by tmitchel on 01-29-2014 at 10:35, last modified: 05-27-2014 at 11:44_

**Comment by MarshallBrinn** [comment]
Fixed in kmactivbate.py which checked for "lockdown_mode" but not for "maintenance_mode".

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-27-2014 at 11:44_
