### ISSUE TITLE
Portal am_client renew calls should use --alap flag

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#969]
am_client renew calls from the portal should use the --alap flag to omni (as late as possible).

 _Imported from trac ticket [#969](http://trac.gpolab.bbn.com/proto-ch/ticket/969),  created by mbrinn on 02-04-2014 at 16:21, last modified: 02-20-2014 at 12:04_

**Comment by MarshallBrinn** [comment]
Added the flag, need to test it on cascade.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-06-2014 at 13:04_

**Comment by ahelsing** [comment]
tested on cascade with both IG and EG AMs. It at least did no harm.

_Trac comment by ahelsing on 02-20-2014 at 12:04_
