### ISSUE TITLE
sliver status: indicate when it is an error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#97]
When Sliver Status returns an error, show text up top showing clearly that you got an error and this is debug information

 _Imported from trac ticket [#97](http://trac.gpolab.bbn.com/proto-ch/ticket/97),  created by ahelsing on 06-05-2012 at 14:03, last modified: 06-21-2012 at 21:34_

**Comment by seledwards** [comment]
Hum... I'm choosing to interpret this ticket as "edit text to clearly indicate if there has been an error".

The text we are currently using is returned by omni, so I'll see about parsing it and reformatting it a bit.


_Trac comment by sedwards (github user: seledwards) on 06-21-2012 at 11:43_

**Comment by seledwards** [comment]
Added some text and a table to the SliverStatus page which says this:
```
Errors seen by 2 aggregates:
Aggregate	Error Message
Local gcf AM	[Errno 111] Connection refused
pgeni3	No slice or aggregate here
```

Closing.

_Trac comment by sedwards (github user: seledwards) on 06-21-2012 at 21:34_
