### ISSUE TITLE
Editing an ssh key results in odd success message

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#973]
When an SSH key is edited the success message says `"Updated SSH keypair ()"`. That's an odd message. The intent is to put a status message inside the parens, but the ma_client does not return any value, so no status message is available.

Instead:
 * Return TRUE on success from `ma_client.update_ssh_key` or raise an exception if an error is returned from the MA

 _AND_
 * Wrap the call in `sshkeyedit.php` in a try/catch block to handle success or error properly

 _Imported from trac ticket [#973](http://trac.gpolab.bbn.com/proto-ch/ticket/973),  created by tmitchel on 02-12-2014 at 16:50, last modified: 11-07-2014 at 14:20_

**Comment by ahelsing** [comment]
Returning a real success and real error in ma_client, catching exceptions, and printing a better message when there is an error or it succeeds

_Trac comment by ahelsing on 11-07-2014 at 14:20_

**Comment by ahelsing** [comment]
Test with various descriptions: none, short, > 15 characters

_Trac comment by ahelsing on 11-07-2014 at 14:20_
