### ISSUE TITLE
Tell experimenters to use Omni 2.5 and chapi framework

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#975]
Change the omni_config we generate for experimenters to use the `chapi` framework, and change the wording on the portal to tell people to use Omni 2.5 as necessary.

Note this depends on Omni 2.5 being released.

 _Imported from trac ticket [#975](http://trac.gpolab.bbn.com/proto-ch/ticket/975),  created by ahelsing on 02-19-2014 at 15:37, last modified: 02-25-2014 at 12:28_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
Sarah & Vic suggest we provide 2 omni_config files in the download bundle. The 2nd "new" one uses the chapi framework. Only omni-configure from omni 2.5 knows to look at that file, so you only end up using the chapi framework if you have new Omni.


_Trac comment by ahelsing on 02-19-2014 at 20:25_

**Comment by seledwards** [comment]
Added omni_config_chapi file to the omni-bundle.zip.  Updated the template for manually configuring your omni_config.

Tested omni 2.5 with both version of the downloaded template.

Tested omni 2.5 omni-configure.py with omni-bundle both using and not using the --not-use-chapi flag.

_Trac comment by sedwards (github user: seledwards) on 02-23-2014 at 22:15_

**Comment by tcmitchell** [comment]
On `tool-omniconfig.php` the omni-config link for older omni (pre 2.5) does not get updated when the default project changes.

The two download links use the same "id" but only the first gets updated because elements cannot share the same id on a page.


_Trac comment by tmitchel (github user: tcmitchell) on 02-25-2014 at 12:22_

**Comment by tcmitchell** [comment]
The secondary download link now has a unique id and the javascript code that updates the link href now updates both ids.

_Trac comment by tmitchel (github user: tcmitchell) on 02-25-2014 at 12:28_
