### ISSUE TITLE
Cleanup passphrase temp files

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#979]
In kmtool/www/kmtool/km_utils.php need to uncomment code to delete (unlink) the passphrase in/out/text files.

 _Imported from trac ticket [#979](http://trac.gpolab.bbn.com/proto-ch/ticket/979),  created by mbrinn on 02-25-2014 at 15:51, last modified: 04-10-2014 at 17:21_

**Comment by tcmitchell** [comment]
Fixed.

_Trac comment by tmitchel (github user: tcmitchell) on 04-10-2014 at 17:21_
