### ISSUE TITLE
flack.php sometimes missing a value

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#987]
A couple people report sometimes when loading Flack they get a popup: 

`ERROR: Could not find saurl/saurn/churl/sliceurn tags`

This is an error from Flack: https://www.emulab.net/protogeni/flack-stable/main.js

When this happens we see no error logs. The implication is that flack.php set one of those values to an empty string or something that evaluates to false. Based on the code, the value is set, just set to something that javascript evaluates as false.

 _Imported from trac ticket [#987](http://trac.gpolab.bbn.com/proto-ch/ticket/987),  created by ahelsing on 04-01-2014 at 15:44, last modified: 04-02-2014 at 11:05_
   CCing: johren@..., nriga@...

**Comment by ahelsing** [comment]
_johren attached [pagesourceTicket987.html](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/987/pagesourceTicket987.html) on 04-01-2014 at 15:54_

**Comment by ahelsing** [comment]
I have reproduced the problem and attached the page source.  The URL is below with the slice_id.
The slice name is joGEMINI01

view-[https](../tree/master/https)://portal.geni.net/secure/flack.php?slice_id=a5c97587-e54b-47d2-8f82-0421ae2eaddd

_Trac comment by johren on 04-01-2014 at 15:56_

**Comment by ahelsing** [comment]
Unfortunately, all 4 of the fields that flack says are missing appear to be present in the page source. And their values look reasonable, and correct. Hmmm.

_Trac comment by ahelsing on 04-01-2014 at 16:15_

**Comment by tcmitchell** [comment]
It's possible that this is a timing issue. If the launcher code is loaded and executed before the variable settings are evaluated we could see this kind of error. It all matches the non-deterministic nature of the error. I'll take a look at the HTML and JavaScript and seek Jon's advice if needed.

_Trac comment by tmitchel (github user: tcmitchell) on 04-02-2014 at 09:53_

**Comment by tcmitchell** [comment]
The HTML page has the Flack loader sript in a tag _before_ setting the various variables. It appears that [JavaScript loads these tags sequentially](http://docstore.mik.ua/orelly/webprog/jscript/ch12_03.htm). If that's really the case I'm surprised that this ever works, or works as often as it does. I have written to Jon to ask his thoughts, and also suggested that instead of the loader executing the load function automatically it could simply define the function and leave the invocation to the HTML page in which it is embedded, presumable in the `onload` event.

_Trac comment by tmitchel (github user: tcmitchell) on 04-02-2014 at 10:13_

**Comment by tcmitchell** [comment]
Adding Niky, as the original reporter of this issue.

_Trac comment by tmitchel (github user: tcmitchell) on 04-02-2014 at 10:14_

**Comment by tcmitchell** [comment]
Jon suggests that we rearrange the script tags for now. He'll add a jquery construct in a future version of the Flack loader to ensure that the loading happens after all other JavaScript is loaded.

_Trac comment by tmitchel (github user: tcmitchell) on 04-02-2014 at 10:55_

**Comment by tcmitchell** [comment]
Done. The flack loader has been moved to the bottom of the HTML.

_Trac comment by tmitchel (github user: tcmitchell) on 04-02-2014 at 11:05_
