### ISSUE TITLE
Malformed 'From' field in join related emails

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#988]
We got a bounce today with the error "Missing purported responsible address". A little googling reveals that we are sending a malformed 'From' header. We send:
  From: experimenter (via the GENI Portal) <www-data@gpolab.bbn.com>
But we should send:
  From: "experimenter (via the GENI Portal)" <www-data@gpolab.bbn.com>
The particular email that bounced had an email address where the examples above say "experimenter" because we do not have name information on them.

To find all the occurrences, try something like this:
```
$ find . -name '*.php' -exec grep -H 'via the GENI Portal' {} \;
./portal/www/portal/ask-for-project.php:  $headers .= "Reply-To: $email" . "\r\n" . "From: $name (via the GENI Portal) <www-data@gpolab.bbn.com>";  
./portal/www/portal/do-upload-project-members.php:    $headers .= "Reply-To: $userEmail" . "\r\n" . "From: $name (via the GENI Portal) <www-data@gpolab.bbn.com>";
./portal/www/portal/invite-to-geni.php:  $headers .= "Reply-To: $email" . "\r\n" . "From: $name (via the GENI Portal) <www-data@gpolab.bbn.com>"; 
./portal/www/portal/invite-to-project.php:  $headers .= "Reply-To: $email" . "\r\n" . "From: $name (via the GENI Portal) <www-data@gpolab.bbn.com>"; 
./portal/www/portal/join-this-project.php:  $headers .= "Reply-To: $email" . "\r\n" . $cc . "From: $name (via the GENI Portal) <www-data@gpolab.bbn.com>"; 
```

 _Imported from trac ticket [#988](http://trac.gpolab.bbn.com/proto-ch/ticket/988),  created by tmitchel on 04-03-2014 at 11:00, last modified: 04-10-2014 at 12:18_

**Comment by ahelsing** [comment]
Added \" characters in the appropriate places.   Tested it as best as I knew how - 
deleted displayName, first_name, and last_name in the db and then tried to call
the php files that were modified.   

_Trac comment by rrhain on 04-08-2014 at 15:56_
