### ISSUE TITLE
ExoGENI detects certificate/credential mismatch

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#993]
We get "No credential was found with appropriate privileges or valid dates" from ExoGENI when the portal is authorized via speaks-for. The problem is that the portal uses speaks-for to get a slice credential from the SA. The SA uses the experimenter's outside certificate inside the slice credential. Then the portal uses the inside certificate to talk to an ExoGENI aggregate (non-speaks-for) and ExoGENI notices that the certificate on the wire (inside) does not match the certificate in the credential (outside).

It may be easier to move forward on passing speaks-for to ExoGENI instead of working around this issue. InstaGENI does not detect the mismatch. We don't know if FOAM will or if SFA-based aggregates will.

 _Imported from trac ticket [#993](http://trac.gpolab.bbn.com/proto-ch/ticket/993),  created by tmitchel on 04-08-2014 at 16:41, last modified: 06-30-2014 at 15:39_

**Comment by tcmitchell** [comment]
This is probably a case where `user->certificate()` and `user->privateKey()` are used in the wrong context.

_Trac comment by tmitchel (github user: tcmitchell) on 04-08-2014 at 16:43_

**Comment by tcmitchell** [comment]
The code does not confuse the certificate/privateKey with the inside cert/key. Both the SF invocation and the non-SF invocation appear to use identical arguments and the `--speaks-for` case is not used. There are no significant differences between the slice credentials used in the SF and non-SF cases either. This is a repeatable and reproducible bug. Further investigation is required.

Things to try:
 - hold all the artifacts form the omni call (certs, creds, etc.) and examine them for differences
 - Use `--debug` and `--verbose-ssl` options to omni to look for differences in the invocations
 - Ask EG what the real underlying error is on their side to help figure out where the difference lies.

_Trac comment by tmitchel (github user: tcmitchell) on 04-09-2014 at 11:37_

**Comment by tcmitchell** [comment]
This turned out to be a mismatch between the certificate on the wire (inside) and the certificate in the credential (outside). Further discussion is in the updated description.

_Trac comment by tmitchel (github user: tcmitchell) on 04-11-2014 at 16:07_

**Comment by tcmitchell** [comment]
ExoGENI fails with a parser error when presented with a speaks-for credential signed via the xml-signer. ExoGENI is able to parse speaks-for credentials signed by the gcf command line tool. ExoGENI reports that the issue is with the expiration field.

The command line tool puts in an expiration like:
```
<expires>2015-05-15T18:29:06Z</expires>
```
xml-signer uses an expiration like:
```
<expires>2014-06-14T17:04:11.646Z</expires>
```
The difference is the sub-second resolution on the latter. ExoGENI says they can update their parser.

_Trac comment by tmitchel (github user: tcmitchell) on 05-21-2014 at 16:30_

**Comment by tcmitchell** [comment]
Anirban and ExoGENI says a fix is ready and will be installed as part of the June 9, 2014 ExoGENI maintenance.

_Trac comment by tmitchel (github user: tcmitchell) on 05-30-2014 at 12:35_

**Comment by tcmitchell** [comment]
Anirban's fix works, and ExoGENI now handles speaks-for.

Rather than fix the odd case of speaks-for at the portal but not to the aggregates, we should press forward and either use speaks-for at both (by adding the appropriate service attributes) or continue with inside certificate at both. No hybrid solution of speaks-for at portal but inside cert at aggregate (unless necessary because the aggregate does not support speaks-for).

_Trac comment by tmitchel (github user: tcmitchell) on 06-18-2014 at 16:49_

**Comment by ahelsing** [comment]
We won't fix the hybrid mode where you try to talk speaks for to an EG AM that doesn't talk speaks for.

_Trac comment by ahelsing on 06-30-2014 at 15:39_
