### ISSUE TITLE
Add new link to the portal landing page

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#994]
Add a link under the "Find out more about using GENI" section. 

The first link should be:
 * New to GENI? links to: http://groups.geni.net/geni/wiki/GeniNewcomersWelcome

 _Imported from trac ticket [#994](http://trac.gpolab.bbn.com/proto-ch/ticket/994),  created by nriga on 04-08-2014 at 19:43, last modified: 05-16-2014 at 12:11_
   CCing: gpo-expt-support@...

**Comment by tcmitchell** [comment]
Added.

_Trac comment by tmitchel (github user: tcmitchell) on 05-16-2014 at 12:11_
